begin;
create table public.crm_project_templates(id uuid primary key default gen_random_uuid(),board_id uuid not null references public.crm_boards,name text not null check(length(trim(name)) between 1 and 160),active boolean not null default true,version integer not null default 1);
create table public.crm_template_versions(id uuid primary key default gen_random_uuid(),template_id uuid not null references public.crm_project_templates,revision integer not null,parameters jsonb not null,tasks jsonb not null,author_id uuid not null references public.profiles,created_at timestamptz not null default now(),unique(template_id,revision));
create table public.crm_sales(id uuid primary key default gen_random_uuid(),deal_id uuid not null unique references public.crm_deals,publication_id uuid not null unique references public.crm_quote_publications,company_id uuid not null references public.companies,project_id uuid unique references public.projects,contract_id uuid unique references public.contracts,invoice_id uuid not null unique references public.invoices,owner_id uuid not null references public.profiles,total numeric(14,2) not null,currency text not null,payment_terms jsonb not null,planned_budget jsonb not null,created_by uuid not null references public.profiles,won_at timestamptz not null default now());
create table public.crm_project_workstreams(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.crm_sales,project_id uuid not null references public.projects,product_line_id uuid not null unique references public.crm_product_lines,template_version_id uuid not null references public.crm_template_versions,parameters jsonb not null,plan jsonb not null);
create table public.crm_task_plans(task_id uuid primary key references public.tasks on delete cascade,workstream_id uuid not null references public.crm_project_workstreams,task_key text not null,phase integer not null check(phase between 0 and 5),process text not null,step text not null,unit text not null,quantity numeric not null,duration_minutes numeric not null,crew integer not null,crew_role text not null,tools text not null,preconditions text not null,dependencies uuid[] not null default '{}',unique(workstream_id,task_key));
alter table public.projects add column manager_id uuid references public.profiles;
create function portal_private.template_access() returns boolean language sql stable security definer set search_path='' as $$select public.is_admin() or portal_private.sales_user() or portal_private.crm_permission('project.own');$$;
revoke all on function portal_private.template_access() from public,anon;grant execute on function portal_private.template_access() to authenticated;
do $$declare t text;begin foreach t in array array['crm_project_templates','crm_template_versions','crm_sales','crm_project_workstreams','crm_task_plans'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;
create policy template_read on public.crm_project_templates for select to authenticated using(portal_private.template_access());
create policy template_version_read on public.crm_template_versions for select to authenticated using(portal_private.template_access());
create policy sale_read on public.crm_sales for select to authenticated using(portal_private.deal_access(deal_id) or (project_id is not null and portal_private.crm_permission('project.own') and portal_private.project_assigned(project_id)));
create policy workstream_read on public.crm_project_workstreams for select to authenticated using(public.is_staff() and public.can_project(project_id));
create policy task_plan_read on public.crm_task_plans for select to authenticated using(public.is_admin() or portal_private.task_assigned(task_id));
create trigger config_audit after insert or update or delete on public.crm_project_templates for each row execute function portal_private.crm_config_audit();
create index crm_templates_board on public.crm_project_templates(board_id);
create index crm_workstreams_project on public.crm_project_workstreams(project_id);
create index crm_workstreams_sale on public.crm_project_workstreams(sale_id);
create index crm_task_plans_stream on public.crm_task_plans(workstream_id);

create function public.save_crm_project_template(p_id uuid,p_version integer,p_board uuid,p_name text,p_active boolean,p_parameters jsonb,p_tasks jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare template public.crm_project_templates;parameter jsonb;task jsonb;keys text[]:='{}';task_keys text[]:='{}';key text;previous_phase integer:=-1;begin
if not public.is_admin() then raise exception 'Administrator configures templates';end if;
if not exists(select 1 from public.crm_boards where id=p_board and outcome<>'Contract') then raise exception 'Project product board required';end if;
if jsonb_typeof(p_parameters) is distinct from 'array' or jsonb_array_length(p_parameters)>30 or jsonb_typeof(p_tasks) is distinct from 'array' or jsonb_array_length(p_tasks) not between 1 and 100 then raise exception 'Use up to 30 parameters and 1–100 tasks';end if;
for parameter in select value from jsonb_array_elements(p_parameters) loop
key:=parameter->>'key';if key is null or key !~ '^[a-z][a-z0-9_]{0,39}$' or key=any(keys) or length(trim(coalesce(parameter->>'label',''))) not between 1 and 100 or not ((parameter->>'min')::numeric between 0 and 100000 and (parameter->>'max')::numeric between 0 and 100000 and (parameter->>'default')::numeric between (parameter->>'min')::numeric and (parameter->>'max')::numeric) or (parameter->>'min') is null or (parameter->>'max') is null or (parameter->>'default') is null then raise exception 'Invalid or duplicate template parameter';end if;keys:=keys||key;end loop;
for task in select value from jsonb_array_elements(p_tasks) loop
key:=task->>'key';if key is null or key !~ '^[a-z][a-z0-9_]{0,39}$' or key=any(task_keys) or (task->>'phase')::integer not between 0 and 5 or (task->>'phase')::integer<previous_phase or length(trim(coalesce(task->>'title',''))) not between 1 and 200 or length(coalesce(task->>'unit','')) not between 1 and 30 or length(coalesce(task->>'crew_role','')) not between 1 and 100 or not ((task->>'minutes')::numeric between 0 and 100000 and (task->>'fixed_minutes')::numeric between 0 and 100000 and (task->>'fixed_quantity')::numeric between 0 and 100000 and (task->>'crew')::integer between 1 and 100) or (task->>'phase') is null or (task->>'minutes') is null or (task->>'fixed_minutes') is null or (task->>'fixed_quantity') is null or (task->>'crew') is null then raise exception 'Invalid template task or phase order';end if;
if jsonb_typeof(task->'quantity_parameters') is distinct from 'array' or exists(select 1 from jsonb_array_elements_text(task->'quantity_parameters') v where not v=any(keys)) or (coalesce(task->>'factor_parameter','')<>'' and not task->>'factor_parameter'=any(keys)) or (coalesce(task->>'condition_parameter','')<>'' and not task->>'condition_parameter'=any(keys)) or jsonb_typeof(task->'depends_on') is distinct from 'array' or exists(select 1 from jsonb_array_elements_text(task->'depends_on') v where not v=any(task_keys)) or jsonb_typeof(task->'checklist') is distinct from 'array' or jsonb_array_length(task->'checklist')>30 or exists(select 1 from jsonb_array_elements_text(task->'checklist') v where length(trim(v)) not between 1 and 200) or length(coalesce(task->>'tools',''))>2000 or length(coalesce(task->>'preconditions',''))>2000 then raise exception 'Invalid task formula, checklist or predecessor';end if;
previous_phase:=(task->>'phase')::integer;task_keys:=task_keys||key;end loop;
if p_id is null then insert into public.crm_project_templates(board_id,name,active) values(p_board,trim(p_name),p_active) returning * into template;
else select * into template from public.crm_project_templates where id=p_id for update;if not found or template.version is distinct from p_version or template.board_id<>p_board then raise exception 'Template changed or product cannot change';end if;update public.crm_project_templates set name=trim(p_name),active=p_active,version=version+1 where id=p_id returning * into template;end if;
insert into public.crm_template_versions(template_id,revision,parameters,tasks,author_id) values(template.id,template.version,p_parameters,p_tasks,auth.uid());return template.id;end$$;

create function portal_private.build_project_plan(p_version uuid,p_values jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$declare template public.crm_template_versions;parameter jsonb;task jsonb;parameter_values jsonb:='{}';tasks jsonb:='[]';quantity numeric;factor numeric;minutes numeric;value numeric;key text;total numeric:=0;begin
select * into template from public.crm_template_versions where id=p_version;if not found or jsonb_typeof(p_values) is distinct from 'object' then raise exception 'Template version and parameter object required';end if;
if exists(select 1 from jsonb_object_keys(p_values) v where not exists(select 1 from jsonb_array_elements(template.parameters) p where p->>'key'=v)) then raise exception 'Unknown project parameter';end if;
for parameter in select v from jsonb_array_elements(template.parameters) v loop key:=parameter->>'key';value:=coalesce((p_values->>key)::numeric,(parameter->>'default')::numeric);if value is null or not(value between (parameter->>'min')::numeric and (parameter->>'max')::numeric) then raise exception 'Project parameter outside allowed range: %',key;end if;parameter_values:=parameter_values||jsonb_build_object(key,value);end loop;
for task in select v from jsonb_array_elements(template.tasks) v loop
if coalesce(task->>'condition_parameter','')<>'' and (parameter_values->>(task->>'condition_parameter'))::numeric<=0 then continue;end if;
quantity:=(task->>'fixed_quantity')::numeric;for key in select v from jsonb_array_elements_text(task->'quantity_parameters') v loop quantity:=quantity+(parameter_values->>key)::numeric;end loop;
if quantity=0 then continue;end if;
factor:=case when coalesce(task->>'factor_parameter','')='' then 1 else (parameter_values->>(task->>'factor_parameter'))::numeric end;
minutes:=round(((task->>'fixed_minutes')::numeric+quantity*(task->>'minutes')::numeric)*factor,2);
if quantity>100000 or minutes<=0 or minutes>1000000 then raise exception 'Task quantity or duration is outside planning limits';end if;
total:=total+minutes*(task->>'crew')::integer;
tasks:=tasks||jsonb_build_array(task||jsonb_build_object('quantity',quantity,'duration_minutes',minutes,'man_hours',round(minutes*(task->>'crew')::integer/60,2)));
end loop;if jsonb_array_length(tasks)=0 then raise exception 'Parameters produce no tasks';end if;
if exists(select 1 from jsonb_array_elements(tasks) t cross join lateral jsonb_array_elements_text(t->'depends_on') dependency where not exists(select 1 from jsonb_array_elements(tasks) p where p->>'key'=dependency)) then raise exception 'A required predecessor was excluded by the parameters';end if;
return jsonb_build_object('template_version',template.id,'revision',template.revision,'parameters',parameter_values,'tasks',tasks,'man_hours',round(total/60,2),'man_days',round(total/480,2));end$$;
revoke all on function portal_private.build_project_plan(uuid,jsonb) from public,anon,authenticated;
create function public.preview_crm_project_plan(p_version uuid,p_values jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not portal_private.template_access() then raise exception 'Project planning access required';end if;return portal_private.build_project_plan(p_version,p_values);end$$;
create function public.crm_project_managers() returns table(id uuid,name text) language plpgsql stable security definer set search_path='' as $$begin if not portal_private.template_access() then raise exception 'Project planning access required';end if;return query select p.id,p.name from public.profiles p where p.active and (p.role='admin' or p.role='team' and portal_private.crm_user_permission(p.id,'project.own')) order by p.name;end$$;

create function public.convert_crm_won(p_deal uuid,p_version integer,p_publication uuid,p_manager uuid,p_start date,p_workstreams jsonb,p_payment jsonb,p_contract jsonb default null) returns uuid language plpgsql security definer set search_path='' as $$declare deal public.crm_deals;publication public.crm_quote_publications;sale public.crm_sales;line record;selection jsonb;plan jsonb;plans jsonb:='[]';task jsonb;task_id uuid;project uuid;contract uuid;invoice uuid;stream uuid;phase integer;milestone uuid;milestones jsonb:='{}';task_ids jsonb:='{}';task_end date;predecessor text;dependencies uuid[];percent numeric;invoice_total numeric;invoice_net numeric;invoice_tax numeric;invoice_taxable numeric;pra_rate numeric;budget jsonb;latest uuid;begin
if not portal_private.deal_edit(p_deal) then raise exception 'Sales conversion access required';end if;
select * into deal from public.crm_deals where id=p_deal for update;
select * into sale from public.crm_sales where deal_id=p_deal;if found then if sale.publication_id=p_publication then return sale.id;else raise exception 'Deal already converted from another quotation';end if;end if;
if deal.version is distinct from p_version or deal.stage in ('won','lost') then raise exception 'Deal changed or is terminal';end if;
select * into publication from public.crm_quote_publications where id=p_publication for update;
if not found or publication.deal_id<>p_deal or publication.status<>'Accepted' or publication.company_id is distinct from deal.company_id then raise exception 'Accepted quotation for this customer required';end if;
select snapshot into budget from public.crm_quote_budgets where publication_id=publication.id for update;if not found then raise exception 'Accepted budget snapshot unavailable';end if;
if jsonb_typeof(p_workstreams) is distinct from 'array' or jsonb_array_length(p_workstreams)>6 or p_start is null or p_start<(now() at time zone 'Asia/Karachi')::date-365 or p_start>(now() at time zone 'Asia/Karachi')::date+730 then raise exception 'Valid start date and workstream selections required';end if;
if jsonb_typeof(p_payment) is distinct from 'object' or p_payment->>'kind' not in ('Full','Advance','Milestones','Monthly') then raise exception 'Supported payment terms required';end if;
percent:=(p_payment->>'first_percent')::numeric;if percent is null or not(percent>0 and percent<=100) or (p_payment->>'kind'='Full' and percent<>100) then raise exception 'Valid first invoice percentage required';end if;
if p_payment->>'kind'='Monthly' and ((p_payment->>'months') is null or not((p_payment->>'months')::integer between 1 and 120) or abs(percent-100/(p_payment->>'months')::numeric)>0.01) then raise exception 'Monthly percentage must match contract periods';end if;
if p_payment->>'kind'='Milestones' and (jsonb_typeof(p_payment->'schedule') is distinct from 'array' or jsonb_array_length(p_payment->'schedule') not between 1 and 20 or exists(select 1 from jsonb_array_elements(p_payment->'schedule') p where length(trim(coalesce(p->>'title',''))) not between 1 and 100 or (p->>'percent') is null or not((p->>'percent')::numeric>0 and (p->>'percent')::numeric<=100)) or (select sum((p->>'percent')::numeric) from jsonb_array_elements(p_payment->'schedule') p)<>100 or percent is distinct from (p_payment->'schedule'->0->>'percent')::numeric) then raise exception 'Milestone percentages must total 100 and match the first invoice';end if;
for line in select l.*,b.outcome,b.name from public.crm_product_lines l join public.crm_boards b on b.id=l.board_id where l.deal_id=p_deal and l.status='Active' order by b.code loop
if line.outcome='Contract' then
if p_contract is null or not public.valid_sla_targets(p_contract->'targets') or (p_contract->>'end_date')::date<p_start or (p_contract->>'end_date') is null or length(trim(coalesce(p_contract->>'services',''))) not between 1 and 10000 then raise exception 'Contract dates, services and SLA targets required';end if;
else
if not exists(select 1 from public.profiles where id=p_manager and active and role in ('admin','team') and (role='admin' or portal_private.crm_user_permission(id,'project.own'))) then raise exception 'Active project manager with project department access required';end if;
select v into selection from jsonb_array_elements(p_workstreams) v where v->>'product_line_id'=line.id::text;
if selection is null or (select count(*) from jsonb_array_elements(p_workstreams) v where v->>'product_line_id'=line.id::text)<>1 then raise exception 'Choose one template per active project product';end if;
select v.id into latest from public.crm_project_templates t join public.crm_template_versions v on v.template_id=t.id and v.revision=t.version where v.id=(selection->>'template_version_id')::uuid and t.board_id=line.board_id and t.active;
if latest is null then raise exception 'Choose the current active template version for this product';end if;
plan:=portal_private.build_project_plan(latest,selection->'parameters');plans:=plans||jsonb_build_array(jsonb_build_object('product_line_id',line.id,'plan',plan));
end if;end loop;
if jsonb_array_length(p_workstreams)<>jsonb_array_length(plans) then raise exception 'Unexpected or duplicate product template selection';end if;
if jsonb_array_length(plans)>0 then
insert into public.projects(company_id,title,description,manager_id,start_date) values(deal.company_id,deal.title,'Created from accepted quotation '||publication.number||' v'||publication.revision,p_manager,p_start) returning id into project;
if exists(select 1 from public.profiles where id=p_manager and role='team') then insert into public.project_assignments(project_id,technician_id) values(project,p_manager);end if;
for phase in 0..5 loop insert into public.milestones(project_id,title) values(project,'Phase '||phase||' · '||(array['Mobilization','Civil & containment','Cable deployment','Termination & installation','Testing & commissioning','QA-QC & handover'])[phase+1]) returning id into milestone;milestones:=milestones||jsonb_build_object(phase::text,milestone);end loop;
end if;
if exists(select 1 from public.crm_product_lines l join public.crm_boards b on b.id=l.board_id where l.deal_id=p_deal and l.status='Active' and b.outcome='Contract') then insert into public.contracts(company_id,title,start_date,end_date,renewal_date,services,targets) values(deal.company_id,deal.title||' · Support SLA',p_start,(p_contract->>'end_date')::date,(p_contract->>'end_date')::date-30,p_contract->>'services',p_contract->'targets') returning id into contract;end if;
invoice_total:=round(publication.total*percent/100,2);invoice_tax:=round(publication.tax_total*percent/100,2);invoice_net:=invoice_total-invoice_tax;if invoice_total<=0 then raise exception 'First invoice must be positive';end if;
insert into public.invoices(company_id,company_name,currency,due_on,notes,subtotal,tax_total,total) values(deal.company_id,publication.company_name,publication.currency,current_date+30,'Draft from '||publication.number||' v'||publication.revision||' · '||(p_payment->>'kind')||' · '||percent||'%',invoice_net,invoice_tax,invoice_total) returning id into invoice;
invoice_taxable:=round((budget->'quote'->>'service_tax_base')::numeric*percent/100,2);pra_rate:=(budget->'quote'->>'pra_percent')::numeric;
if invoice_net>invoice_taxable then insert into public.invoice_items(invoice_id,description,quantity,unit_price,tax_percent,net,tax,position) values(invoice,'Accepted quotation '||publication.number||' v'||publication.revision||' — first payment',1,invoice_net-invoice_taxable,0,invoice_net-invoice_taxable,0,0);end if;
if invoice_taxable>0 then insert into public.invoice_items(invoice_id,description,quantity,unit_price,tax_percent,net,tax,position) values(invoice,'Taxable services — first payment',1,invoice_taxable,pra_rate,invoice_taxable,invoice_tax,1);end if;
insert into public.crm_sales(deal_id,publication_id,company_id,project_id,contract_id,invoice_id,owner_id,total,currency,payment_terms,planned_budget,created_by) select deal.id,publication.id,deal.company_id,project,contract,invoice,deal.owner_id,publication.total,publication.currency,p_payment,b.snapshot,auth.uid() from public.crm_quote_budgets b where b.publication_id=publication.id returning * into sale;
if sale.id is null then raise exception 'Accepted budget snapshot unavailable';end if;
for selection in select v from jsonb_array_elements(plans) v loop
plan:=selection->'plan';insert into public.crm_project_workstreams(sale_id,project_id,product_line_id,template_version_id,parameters,plan) values(sale.id,project,(selection->>'product_line_id')::uuid,(plan->>'template_version')::uuid,plan->'parameters',plan) returning id into stream;
task_ids:='{}';task_end:=p_start;
for task in select v from jsonb_array_elements(plan->'tasks') v loop
dependencies:='{}';for predecessor in select v from jsonb_array_elements_text(task->'depends_on') v loop dependencies:=dependencies||(task_ids->>predecessor)::uuid;end loop;
insert into public.tasks(project_id,title,internal,start_date,deadline,milestone_id,assignee) values(project,task->>'title',true,task_end,task_end+greatest(0,ceil((task->>'duration_minutes')::numeric/480)::integer-1),(milestones->>(task->>'phase'))::uuid,p_manager) returning id into task_id;
insert into public.crm_task_plans(task_id,workstream_id,task_key,phase,process,step,unit,quantity,duration_minutes,crew,crew_role,tools,preconditions,dependencies) values(task_id,stream,task->>'key',(task->>'phase')::integer,coalesce(task->>'process',''),coalesce(task->>'step',''),task->>'unit',(task->>'quantity')::numeric,(task->>'duration_minutes')::numeric,(task->>'crew')::integer,task->>'crew_role',coalesce(task->>'tools',''),coalesce(task->>'preconditions',''),dependencies);
insert into public.task_items(task_id,title) select task_id,v from jsonb_array_elements_text(task->'checklist') v;
task_ids:=task_ids||jsonb_build_object(task->>'key',task_id);task_end:=task_end+greatest(1,ceil((task->>'duration_minutes')::numeric/480)::integer);
end loop;end loop;
if project is not null then update public.projects set deadline=(select max(deadline) from public.tasks where project_id=project) where id=project;update public.milestones m set deadline=(select max(t.deadline) from public.tasks t where t.milestone_id=m.id) where m.project_id=project;end if;
update public.crm_deals set stage='won',estimated_value=publication.total,next_followup=null,version=version+1,stage_changed_at=now() where id=p_deal;
insert into public.crm_sales_activity(lead_id,deal_id,kind,body,actor_id) values(deal.lead_id,deal.id,'Stage','Won: sale, accepted budget and first invoice draft created',auth.uid());
insert into public.billing_events(invoice_id,action,detail) values(invoice,'Draft created','Accepted CRM quotation');
if project is not null then insert into public.portal_reminders(user_id,event_key,title,view,project_id) select p_manager,'crm-sale:'||sale.id,'New project: '||deal.title,'projects',project where coalesce((select enabled from public.portal_reminder_preferences where user_id=p_manager),true) on conflict do nothing;end if;
return sale.id;end$$;
-- Converted deals stay Won. Further products require a change order.
do $$declare definition text;begin definition:=pg_get_functiondef('public.save_crm_deal(uuid,integer,text,numeric,date,timestamptz,text,text,date)'::regprocedure);definition:=replace(definition,'select * into old from public.crm_deals where id=p_id for update;','select * into old from public.crm_deals where id=p_id for update;if exists(select 1 from public.crm_sales where deal_id=p_id) then raise exception ''Converted sale is locked; use a change order'';end if;');execute definition;end$$;
do $$declare f regprocedure;begin for f in select oid::regprocedure from pg_proc where pronamespace='public'::regnamespace and proname in ('save_crm_project_template','preview_crm_project_plan','crm_project_managers','convert_crm_won') loop execute format('revoke all on function %s from public,anon',f);execute format('grant execute on function %s to authenticated',f);end loop;end$$;
commit;
