begin;
create table public.crm_nodes(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects,workstream_id uuid references public.crm_project_workstreams,task_id uuid references public.tasks,device_id text not null check(length(device_id) between 1 and 80),floor text not null default '' check(length(floor)<=100),location text not null default '' check(length(location)<=300),route text not null default '' check(length(route)<=300),cable_id text not null default '' check(length(cable_id)<=100),cable_length numeric(12,2) not null default 0 check(cable_length between 0 and 100000),discipline text not null check(discipline in ('CCTV','Data','PA','WLAN','Voice','Civil','Other')),version integer not null default 1,unique(project_id,device_id));
create table public.crm_node_checks(node_id uuid not null references public.crm_nodes,step text not null check(step in ('route','labelled','termination','mounted','continuity','functional')),phase integer not null check(phase between 1 and 4),result text not null default 'Pending' check(result in ('Pending','Pass','Fail')),status text not null default 'Draft' check(status in ('Draft','Submitted','Published')),note text not null default '' check(length(note)<=2000),evidence uuid[] not null default '{}' check(cardinality(evidence)<=20),checked_by uuid references public.profiles,checked_at timestamptz,reviewed_by uuid references public.profiles,reviewed_at timestamptz,version integer not null default 1,primary key(node_id,step));
create table public.crm_node_imports(id uuid primary key,project_id uuid not null references public.projects,actor_id uuid not null references public.profiles,payload jsonb not null,count integer not null);
create table public.crm_phases(project_id uuid not null references public.projects,phase integer not null check(phase between 0 and 5),status text not null default 'Draft' check(status in ('Draft','Submitted','Published')),summary text not null default '' check(length(summary)<=4000),evidence uuid[] not null default '{}' check(cardinality(evidence)<=20),version integer not null default 1,reviewed_by uuid references public.profiles,reviewed_at timestamptz,primary key(project_id,phase));
create table public.crm_punch_items(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects,node_id uuid references public.crm_nodes,task_id uuid references public.tasks,title text not null check(length(trim(title)) between 1 and 200),location text not null default '' check(length(location)<=300),discipline text not null check(discipline in ('CCTV','Data','PA','WLAN','Voice','Civil','Other')),priority text not null check(priority in ('H','M','L')),status text not null default 'Open' check(status in ('Open','Submitted','Closed')),published boolean not null default false,note text not null default '' check(length(note)<=2000),evidence uuid[] not null default '{}' check(cardinality(evidence)<=20),created_by uuid not null references public.profiles,closed_by uuid references public.profiles,closed_at timestamptz,version integer not null default 1);
create table public.crm_execution_history(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects,node_id uuid references public.crm_nodes,kind text not null,record_id text not null,action text not null,snapshot jsonb not null,actor_id uuid not null references public.profiles,created_at timestamptz not null default now());
create index crm_nodes_project on public.crm_nodes(project_id);
create index crm_punch_project on public.crm_punch_items(project_id);
create index crm_execution_history_project on public.crm_execution_history(project_id);
alter table public.crm_node_checks add column id uuid not null unique default gen_random_uuid();
alter table public.crm_node_checks add column checked_name text not null default '',add column reviewed_name text not null default '';
alter table public.crm_phases add column id uuid not null unique default gen_random_uuid();
create function portal_private.execution_manager(p_project uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_admin() or (portal_private.crm_permission('project.own') and portal_private.project_assigned(p_project));$$;
create function portal_private.node_worker(p_node uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_admin() or exists(select 1 from public.crm_nodes n where n.id=p_node and public.is_staff() and (portal_private.project_assigned(n.project_id) or portal_private.task_assigned(n.task_id)));$$;
create function portal_private.node_visible(p_node uuid) returns boolean language sql stable security definer set search_path='' as $$select portal_private.node_worker(p_node) or exists(select 1 from public.crm_nodes n where n.id=p_node and exists(select 1 from public.profiles where id=auth.uid() and active and role='client') and public.can_project(n.project_id) and exists(select 1 from public.crm_node_checks c where c.node_id=n.id and c.status='Published'));$$;
create function portal_private.execution_evidence(p_project uuid,p_files uuid[]) returns boolean language sql stable security definer set search_path='' as $$select p_files is not null and cardinality(p_files)<=20 and not exists(select 1 from unnest(p_files) f where f is null or not exists(select 1 from public.files where id=f and project_id=p_project));$$;
do $$declare t text;begin foreach t in array array['crm_nodes','crm_node_checks','crm_node_imports','crm_phases','crm_punch_items','crm_execution_history'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);end loop;end$$;
grant select on public.crm_nodes,public.crm_node_checks,public.crm_phases,public.crm_punch_items,public.crm_execution_history to authenticated;
create policy node_read on public.crm_nodes for select to authenticated using(portal_private.node_visible(id));
create policy node_check_read on public.crm_node_checks for select to authenticated using(portal_private.node_worker(node_id) or (status='Published' and portal_private.node_visible(node_id)));
create policy phase_read on public.crm_phases for select to authenticated using(public.can_project(project_id) and (public.is_staff() or status='Published'));
create policy punch_read on public.crm_punch_items for select to authenticated using(public.is_admin() or (public.is_staff() and (portal_private.project_assigned(project_id) or portal_private.task_assigned(task_id) or portal_private.node_worker(node_id))) or (published and exists(select 1 from public.profiles where id=auth.uid() and active and role='client') and public.can_project(project_id)));
create policy execution_history_read on public.crm_execution_history for select to authenticated using(public.is_admin() or (public.is_staff() and case when node_id is not null then portal_private.node_worker(node_id) else portal_private.project_assigned(project_id) end));
revoke all on function portal_private.execution_manager(uuid),portal_private.node_worker(uuid),portal_private.node_visible(uuid),portal_private.execution_evidence(uuid,uuid[]) from public,anon;
grant execute on function portal_private.execution_manager(uuid),portal_private.node_worker(uuid),portal_private.node_visible(uuid) to authenticated;

create function public.save_crm_node(p_id uuid,p_version integer,p_project uuid,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare node public.crm_nodes;stream uuid:=nullif(p_data->>'workstream_id','')::uuid;task uuid:=nullif(p_data->>'task_id','')::uuid;begin
perform 1 from public.projects where id=p_project and status<>'Completed' for update;if not found or not portal_private.execution_manager(p_project) then raise exception 'Active project manager access required';end if;
if exists(select 1 from public.crm_phases where project_id=p_project and status<>'Draft') then raise exception 'Node register locks when phase review starts';end if;
if stream is not null and not exists(select 1 from public.crm_project_workstreams where id=stream and project_id=p_project) then raise exception 'Workstream belongs to another project';end if;
if task is not null and not exists(select 1 from public.tasks where id=task and project_id=p_project) then raise exception 'Task belongs to another project';end if;
if p_id is null then insert into public.crm_nodes(project_id,device_id,discipline) values(p_project,upper(trim(p_data->>'device_id')),p_data->>'discipline') returning * into node;
else select * into node from public.crm_nodes where id=p_id for update;if not found or node.project_id<>p_project or node.version is distinct from p_version then raise exception 'Node changed. Refresh first.';end if;end if;
update public.crm_nodes set device_id=upper(trim(p_data->>'device_id')),workstream_id=stream,task_id=task,floor=coalesce(p_data->>'floor',''),location=coalesce(p_data->>'location',''),route=coalesce(p_data->>'route',''),cable_id=coalesce(p_data->>'cable_id',''),cable_length=coalesce(nullif(p_data->>'cable_length','')::numeric,0),discipline=p_data->>'discipline',version=case when p_id is null then version else version+1 end where id=node.id;
insert into public.crm_node_checks(node_id,step,phase) select node.id,step,phase from (values('route',1),('labelled',2),('termination',3),('mounted',3),('continuity',4),('functional',4)) steps(step,phase) on conflict do nothing;
insert into public.crm_phases(project_id,phase) select p_project,n from generate_series(0,5) n on conflict do nothing;
insert into public.crm_execution_history(project_id,node_id,kind,record_id,action,snapshot,actor_id) select p_project,id,'Node',id::text,'Saved',to_jsonb(n),auth.uid() from public.crm_nodes n where id=node.id;return node.id;end$$;
create function public.import_crm_nodes(p_batch uuid,p_project uuid,p_rows jsonb) returns integer language plpgsql security definer set search_path='' as $$declare previous public.crm_node_imports;row jsonb;n integer:=0;begin
if p_batch is null or not portal_private.execution_manager(p_project) or jsonb_typeof(p_rows) is distinct from 'array' or jsonb_array_length(p_rows) not between 1 and 500 then raise exception 'Manager and 1–500 node rows required';end if;
perform pg_advisory_xact_lock(hashtext(p_batch::text));select * into previous from public.crm_node_imports where id=p_batch;if found then if previous.actor_id=auth.uid() and previous.project_id=p_project and previous.payload=p_rows then return previous.count;else raise exception 'Import identifier already used';end if;end if;
for row in select value from jsonb_array_elements(p_rows) loop perform public.save_crm_node(null,null,p_project,row);n:=n+1;end loop;insert into public.crm_node_imports values(p_batch,p_project,auth.uid(),p_rows,n);return n;end$$;
create function public.save_crm_node_check(p_node uuid,p_step text,p_version integer,p_result text,p_note text,p_evidence uuid[]) returns void language plpgsql security definer set search_path='' as $$declare node public.crm_nodes;check_row public.crm_node_checks;begin
select * into node from public.crm_nodes where id=p_node;perform 1 from public.projects where id=node.project_id and status<>'Completed' for update;
if not found or not portal_private.node_worker(p_node) then raise exception 'Assigned node required';end if;
select * into check_row from public.crm_node_checks where node_id=p_node and step=p_step for update;
if not found or check_row.version is distinct from p_version or check_row.status<>'Draft' or exists(select 1 from public.crm_phases where project_id=node.project_id and phase=check_row.phase and status<>'Draft') then raise exception 'Check changed or locked by review';end if;
if p_result not in ('Pass','Fail') or p_result is null or (p_result='Fail' and length(trim(coalesce(p_note,'')))<3) or not portal_private.execution_evidence(node.project_id,p_evidence) then raise exception 'Valid result, failure note and project evidence required';end if;
update public.crm_node_checks set result=p_result,note=p_note,evidence=p_evidence,checked_by=auth.uid(),checked_name=(select name from public.profiles where id=auth.uid()),checked_at=now(),version=version+1 where node_id=p_node and step=p_step;
insert into public.crm_execution_history(project_id,node_id,kind,record_id,action,snapshot,actor_id) select node.project_id,p_node,'Check',p_step,'Saved',to_jsonb(c),auth.uid() from public.crm_node_checks c where node_id=p_node and step=p_step;end$$;
create function public.crm_node_check_action(p_node uuid,p_step text,p_version integer,p_action text,p_note text default '') returns void language plpgsql security definer set search_path='' as $$declare node public.crm_nodes;check_row public.crm_node_checks;begin
select * into node from public.crm_nodes where id=p_node;perform 1 from public.projects where id=node.project_id and status<>'Completed' for update;
if not found or not portal_private.node_worker(p_node) then raise exception 'Assigned node required';end if;
select * into check_row from public.crm_node_checks where node_id=p_node and step=p_step for update;if not found or check_row.version is distinct from p_version then raise exception 'Check changed';end if;
if p_action='Submit' and check_row.status='Draft' and check_row.result in ('Pass','Fail') then update public.crm_node_checks set status='Submitted',version=version+1 where node_id=p_node and step=p_step;
elsif p_action='Publish' and public.is_admin() and check_row.status='Submitted' then update public.crm_node_checks set status='Published',reviewed_by=auth.uid(),reviewed_name=(select name from public.profiles where id=auth.uid()),reviewed_at=now(),version=version+1 where node_id=p_node and step=p_step;update public.files set published=true where id=any(check_row.evidence);
elsif p_action='Return' and public.is_admin() and check_row.status='Submitted' and length(trim(coalesce(p_note,'')))>=3 and length(p_note)<=2000 then update public.crm_node_checks set status='Draft',note=p_note,version=version+1 where node_id=p_node and step=p_step;
else raise exception 'Check review action unavailable';end if;
insert into public.crm_execution_history(project_id,node_id,kind,record_id,action,snapshot,actor_id) select node.project_id,p_node,'Check',p_step,p_action,to_jsonb(c),auth.uid() from public.crm_node_checks c where node_id=p_node and step=p_step;end$$;

create function public.save_crm_punch_item(p_project uuid,p_node uuid,p_task uuid,p_title text,p_location text,p_discipline text,p_priority text) returns uuid language plpgsql security definer set search_path='' as $$declare item uuid;begin
perform 1 from public.projects where id=p_project and status<>'Completed' for update;
if not found or not (portal_private.execution_manager(p_project) or (p_node is not null and portal_private.node_worker(p_node)) or (p_task is not null and portal_private.task_assigned(p_task))) then raise exception 'Assigned work required';end if;
if p_node is not null and not exists(select 1 from public.crm_nodes where id=p_node and project_id=p_project) or p_task is not null and not exists(select 1 from public.tasks where id=p_task and project_id=p_project) then raise exception 'Related node and task must belong to project';end if;
if exists(select 1 from public.crm_phases where project_id=p_project and phase=5 and status<>'Draft') then raise exception 'Final phase review locks new punch items';end if;
insert into public.crm_punch_items(project_id,node_id,task_id,title,location,discipline,priority,created_by) values(p_project,p_node,p_task,trim(p_title),p_location,p_discipline,p_priority,auth.uid()) returning id into item;
insert into public.crm_execution_history(project_id,node_id,kind,record_id,action,snapshot,actor_id) select p_project,p_node,'Punch',id::text,'Created',to_jsonb(p),auth.uid() from public.crm_punch_items p where id=item;return item;end$$;
create function public.crm_punch_action(p_id uuid,p_version integer,p_action text,p_note text,p_evidence uuid[]) returns void language plpgsql security definer set search_path='' as $$declare item public.crm_punch_items;begin
select * into item from public.crm_punch_items where id=p_id;perform 1 from public.projects where id=item.project_id and status<>'Completed' for update;
if not found or not (portal_private.execution_manager(item.project_id) or portal_private.node_worker(item.node_id) or portal_private.task_assigned(item.task_id)) then raise exception 'Assigned punch item required';end if;
select * into item from public.crm_punch_items where id=p_id for update;if item.version is distinct from p_version or not portal_private.execution_evidence(item.project_id,p_evidence) or length(coalesce(p_note,''))>2000 then raise exception 'Punch changed or evidence invalid';end if;
if p_action='Submit closure' and item.status='Open' and length(trim(coalesce(p_note,'')))>=3 then update public.crm_punch_items set status='Submitted',published=false,note=p_note,evidence=p_evidence,version=version+1 where id=p_id;
elsif p_action='Close' and public.is_admin() and item.status='Submitted' then update public.crm_punch_items set status='Closed',published=true,closed_by=auth.uid(),closed_at=now(),version=version+1 where id=p_id;update public.files set published=true where id=any(item.evidence);
elsif p_action='Publish' and public.is_admin() and item.status='Open' then update public.crm_punch_items set published=true,version=version+1 where id=p_id;
elsif p_action='Return' and public.is_admin() and item.status='Submitted' and length(trim(coalesce(p_note,'')))>=3 then update public.crm_punch_items set status='Open',published=false,note=p_note,version=version+1 where id=p_id;
else raise exception 'Punch review action unavailable';end if;
insert into public.crm_execution_history(project_id,node_id,kind,record_id,action,snapshot,actor_id) select item.project_id,item.node_id,'Punch',id::text,p_action,to_jsonb(p),auth.uid() from public.crm_punch_items p where id=p_id;end$$;

create function public.crm_phase_action(p_project uuid,p_phase integer,p_version integer,p_action text,p_summary text,p_evidence uuid[]) returns void language plpgsql security definer set search_path='' as $$declare phase_row public.crm_phases;begin
perform 1 from public.projects where id=p_project and status<>'Completed' for update;if not found or not portal_private.execution_manager(p_project) then raise exception 'Project manager access required';end if;
insert into public.crm_phases(project_id,phase) select p_project,n from generate_series(0,5) n on conflict do nothing;
select * into phase_row from public.crm_phases where project_id=p_project and phase=p_phase for update;if not found or phase_row.version is distinct from p_version then raise exception 'Phase changed. Refresh first.';end if;
if not portal_private.execution_evidence(p_project,p_evidence) or p_summary is null or length(p_summary)>4000 then raise exception 'Project evidence and summary required';end if;
if p_action in ('Submit','Publish') then
if p_phase>0 and not exists(select 1 from public.crm_phases where project_id=p_project and phase=p_phase-1 and status='Published') then raise exception 'Previous phase must be published first';end if;
if exists(select 1 from public.crm_node_checks c join public.crm_nodes n on n.id=c.node_id where n.project_id=p_project and c.phase=p_phase and (c.result<>'Pass' or c.status<>'Published')) then raise exception 'All phase node checks must be reviewed Pass';end if;
if exists(select 1 from public.crm_task_plans p join public.tasks t on t.id=p.task_id where t.project_id=p_project and p.phase=p_phase and (t.status<>'Done' or not exists(select 1 from public.task_completions c where c.task_id=t.id and c.status in ('Published','Confirmed')))) then raise exception 'Phase tasks require approved completion';end if;
if p_phase=5 and exists(select 1 from public.crm_punch_items where project_id=p_project and status<>'Closed') then raise exception 'Close all punch items before final phase';end if;
end if;
if p_action='Submit' and phase_row.status='Draft' and length(trim(p_summary))>=3 and cardinality(p_evidence)>0 then update public.crm_phases set status='Submitted',summary=p_summary,evidence=p_evidence,version=version+1 where project_id=p_project and phase=p_phase;
elsif p_action='Publish' and public.is_admin() and phase_row.status='Submitted' then update public.crm_phases set status='Published',reviewed_by=auth.uid(),reviewed_at=now(),version=version+1 where project_id=p_project and phase=p_phase;update public.files set published=true where id=any(phase_row.evidence);
elsif p_action='Return' and public.is_admin() and phase_row.status='Submitted' and length(trim(p_summary))>=3 then update public.crm_phases set status='Draft',summary=p_summary,version=version+1 where project_id=p_project and phase=p_phase;
else raise exception 'Phase review action unavailable';end if;
insert into public.crm_execution_history(project_id,kind,record_id,action,snapshot,actor_id) select p_project,'Phase',p_phase::text,p_action,to_jsonb(p),auth.uid() from public.crm_phases p where project_id=p_project and phase=p_phase;end$$;
create function public.crm_execution_progress(p_project uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare result jsonb;begin
if not public.can_project(p_project) then raise exception 'Project access required';end if;
select jsonb_agg(jsonb_build_object('phase',phase,'expected',expected,'passed',passed,'percent',case when expected=0 then null else round(passed*100.0/expected,1) end) order by phase) into result from (select p.phase,count(c.node_id) expected,count(c.node_id) filter(where c.result='Pass' and c.status='Published') passed from generate_series(0,5) p(phase) left join (public.crm_node_checks c join public.crm_nodes n on n.id=c.node_id) on c.phase=p.phase and n.project_id=p_project and (public.is_admin() or portal_private.node_worker(n.id) or (c.status='Published' and exists(select 1 from public.profiles where id=auth.uid() and active and role='client'))) group by p.phase) s;return coalesce(result,'[]');end$$;

-- Internal completion approval keeps its evidence private.
do $$declare definition text;begin definition:=pg_get_functiondef('public.task_completion_action(uuid,integer,text,text)'::regprocedure);
definition:=replace(definition,$gate$elsif p_action='Publish' and public.is_admin() and c.status='Submitted' then
 if t.internal then raise exception 'Internal tasks cannot be published to clients';end if;
 update public.files set published=true where id=any(c.evidence);$gate$,$gate$elsif p_action in ('Publish','Approve') and public.is_admin() and c.status='Submitted' then
 if t.internal and p_action='Publish' then raise exception 'Internal tasks cannot be published to clients';end if;
 if not t.internal and p_action='Approve' then raise exception 'Publish shared task results instead';end if;
 if p_action='Publish' then update public.files set published=true where id=any(c.evidence);end if;$gate$);execute definition;end$$;
do $$declare f regprocedure;begin for f in select oid::regprocedure from pg_proc where pronamespace='public'::regnamespace and proname in ('save_crm_node','import_crm_nodes','save_crm_node_check','crm_node_check_action','save_crm_punch_item','crm_punch_action','crm_phase_action','crm_execution_progress') loop execute format('revoke all on function %s from public,anon',f);execute format('grant execute on function %s to authenticated',f);end loop;end$$;
commit;
