begin;
create table public.crm_handovers(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects,revision integer not null,status text not null default 'Awaiting signatures' check(status in ('Awaiting signatures','Signed','Changes requested','Cancelled','Closed')),summary text not null check(length(trim(summary)) between 3 and 4000),feedback text not null default '',contractor_id uuid not null references public.profiles,consultant_id uuid not null references public.profiles,client_id uuid not null references public.profiles,snapshot jsonb not null,snapshot_hash text not null,version integer not null default 1,created_by uuid not null references public.profiles,created_at timestamptz not null default now(),closed_at timestamptz,unique(project_id,revision),check(contractor_id<>consultant_id and contractor_id<>client_id and consultant_id<>client_id));
create unique index crm_handover_active on public.crm_handovers(project_id) where status in ('Awaiting signatures','Signed','Closed');
create table public.crm_handover_signatures(id uuid primary key default gen_random_uuid(),handover_id uuid not null references public.crm_handovers,party text not null check(party in ('Contractor','Consultant','Client')),signer_id uuid not null references public.profiles,account_name text not null,signed_name text not null check(length(trim(signed_name)) between 2 and 150),consent text not null,snapshot_hash text not null,signed_at timestamptz not null default now(),unique(handover_id,party),unique(handover_id,signer_id));
create table public.crm_handover_documents(id uuid primary key default gen_random_uuid(),handover_id uuid not null unique references public.crm_handovers,pdf bytea not null check(octet_length(pdf) between 100 and 5242880),sha256 text not null,archived_by uuid not null references public.profiles,archived_at timestamptz not null default now());
alter table public.projects add column handover_id uuid references public.crm_handovers,add column closed_at timestamptz;
create function portal_private.handover_signer_eligible(p_project uuid,p_signer uuid,p_party text) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles u join public.projects p on p.id=p_project where u.id=p_signer and u.active and case when p_party='Client' then u.role='client' and u.company_id=p.company_id when p_party='Contractor' then u.role='admin' or u.role='team' and exists(select 1 from public.project_assignments a where a.project_id=p.id and a.technician_id=u.id) when p_party='Consultant' then u.role='client' and u.company_id=p.company_id or u.role='admin' or u.role='team' and exists(select 1 from public.project_assignments a where a.project_id=p.id and a.technician_id=u.id) else false end);$$;
create function portal_private.handover_read(p_handover uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.crm_handovers h where h.id=p_handover and (portal_private.execution_manager(h.project_id) or public.can_project(h.project_id) and exists(select 1 from public.profiles u where u.id=auth.uid() and u.active and (u.role='client' or u.id in (h.contractor_id,h.consultant_id,h.client_id)))));$$;
do $$declare t text;begin foreach t in array array['crm_handovers','crm_handover_signatures','crm_handover_documents'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);end loop;end$$;
grant select on public.crm_handovers,public.crm_handover_signatures to authenticated;
create policy handover_read on public.crm_handovers for select to authenticated using(portal_private.handover_read(id));
create policy handover_signature_read on public.crm_handover_signatures for select to authenticated using(portal_private.handover_read(handover_id));
-- PDF bytes are returned only through the checked download function.
revoke all on function portal_private.handover_signer_eligible(uuid,uuid,text),portal_private.handover_read(uuid) from public,anon;
grant execute on function portal_private.handover_read(uuid) to authenticated;
create function portal_private.handover_ready(p_project uuid) returns void language plpgsql security definer set search_path='' as $$begin
if (select count(*) from public.crm_phases where project_id=p_project and status='Published')<>6 then raise exception 'All six phases must be published';end if;
if exists(select 1 from public.crm_node_checks c join public.crm_nodes n on n.id=c.node_id where n.project_id=p_project and (c.status<>'Published' or c.result<>'Pass')) then raise exception 'All device checks must be reviewed Pass';end if;
if exists(select 1 from public.crm_punch_items where project_id=p_project and status<>'Closed') then raise exception 'Close every punch finding first';end if;
if exists(select 1 from public.crm_task_plans tp join public.tasks t on t.id=tp.task_id where t.project_id=p_project and (t.status<>'Done' or not exists(select 1 from public.task_completions c where c.task_id=t.id and c.status in ('Published','Confirmed')) or exists(select 1 from public.task_items i where i.task_id=t.id and not i.done))) then raise exception 'Planned tasks and checklists must be approved';end if;
end$$;
create function public.crm_handover_signers(p_project uuid) returns table(id uuid,name text,role text) language plpgsql stable security definer set search_path='' as $$begin
if not portal_private.execution_manager(p_project) then raise exception 'Project manager access required';end if;
return query select u.id,u.name,u.role from public.profiles u where portal_private.handover_signer_eligible(p_project,u.id,'Consultant') order by u.name;end$$;
create function public.create_crm_handover(p_project uuid,p_summary text,p_contractor uuid,p_consultant uuid,p_client uuid) returns uuid language plpgsql security definer set search_path='' as $$declare p public.projects;h uuid;payload jsonb;rev integer;begin
if not public.is_admin() then raise exception 'Administrator release required';end if;
select * into p from public.projects where id=p_project for update;if not found or p.status='Completed' then raise exception 'Active project required';end if;
perform portal_private.handover_ready(p_project);
if not portal_private.handover_signer_eligible(p_project,p_contractor,'Contractor') or not portal_private.handover_signer_eligible(p_project,p_consultant,'Consultant') or not portal_private.handover_signer_eligible(p_project,p_client,'Client') then raise exception 'Choose eligible active project signers';end if;
select coalesce(max(revision),0)+1 into rev from public.crm_handovers where project_id=p_project;
payload:=jsonb_build_object('project_id',p.id,'project',p.title,'company',(select name from public.companies where id=p.company_id),'summary',trim(p_summary),'revision',rev,'phases',coalesce((select jsonb_agg(jsonb_build_object('phase',phase,'summary',summary,'reviewed_at',reviewed_at,'evidence',evidence) order by phase) from public.crm_phases where project_id=p.id),'[]'::jsonb),'nodes',coalesce((select jsonb_agg(jsonb_build_object('device',n.device_id,'discipline',n.discipline,'location',n.location,'checks',(select jsonb_agg(jsonb_build_object('step',c.step,'result',c.result,'checked_by',c.checked_name,'reviewed_by',c.reviewed_name,'reviewed_at',c.reviewed_at) order by c.step) from public.crm_node_checks c where c.node_id=n.id)) order by n.device_id) from public.crm_nodes n where n.project_id=p.id),'[]'::jsonb),'punch',coalesce((select jsonb_agg(jsonb_build_object('title',title,'location',location,'priority',priority,'closed_at',closed_at) order by id) from public.crm_punch_items where project_id=p.id),'[]'::jsonb));
insert into public.crm_handovers(project_id,revision,summary,contractor_id,consultant_id,client_id,snapshot,snapshot_hash,created_by) values(p.id,rev,trim(p_summary),p_contractor,p_consultant,p_client,payload,encode(sha256(convert_to(payload::text,'UTF8')),'hex'),auth.uid()) returning id into h;
insert into public.crm_execution_history(project_id,kind,record_id,action,snapshot,actor_id) values(p.id,'Handover',h::text,'Released',payload,auth.uid());
insert into public.portal_reminders(user_id,event_key,title,view,project_id) select u,'handover:'||h::text,'Handover signature requested: '||p.title,'handover',p.id from unnest(array[p_contractor,p_consultant,p_client]) u where coalesce((select enabled from public.portal_reminder_preferences where user_id=u),true) on conflict do nothing;
return h;end$$;
create function public.crm_handover_action(p_id uuid,p_version integer,p_action text,p_party text,p_name text,p_consent boolean,p_note text default '') returns void language plpgsql security definer set search_path='' as $$declare h public.crm_handovers;target uuid;begin
select * into h from public.crm_handovers where id=p_id;perform 1 from public.projects where id=h.project_id and status<>'Completed' for update;
select * into h from public.crm_handovers where id=p_id for update;if not found or h.version is distinct from p_version or not portal_private.handover_read(p_id) then raise exception 'Handover changed or unavailable';end if;
target:=case p_party when 'Contractor' then h.contractor_id when 'Consultant' then h.consultant_id when 'Client' then h.client_id end;
if p_action='Sign' and h.status='Awaiting signatures' and target=auth.uid() and p_consent is true and portal_private.handover_signer_eligible(h.project_id,auth.uid(),p_party) then
insert into public.crm_handover_signatures(handover_id,party,signer_id,account_name,signed_name,consent,snapshot_hash) select h.id,p_party,auth.uid(),name,trim(p_name),'I approve this handover revision and consent to recording my electronic sign-off.',h.snapshot_hash from public.profiles where id=auth.uid();
update public.crm_handovers set status=case when (select count(*) from public.crm_handover_signatures where handover_id=h.id)=3 then 'Signed' else status end,version=version+1 where id=h.id;
elsif p_action='Request changes' and h.status='Awaiting signatures' and target=auth.uid() and portal_private.handover_signer_eligible(h.project_id,auth.uid(),p_party) and length(trim(coalesce(p_note,''))) between 3 and 2000 then update public.crm_handovers set status='Changes requested',feedback=trim(p_note),version=version+1 where id=h.id;
elsif p_action='Cancel' and public.is_admin() and h.status in ('Awaiting signatures','Signed','Changes requested') and length(trim(coalesce(p_note,''))) between 3 and 2000 then update public.crm_handovers set status='Cancelled',feedback=trim(p_note),version=version+1 where id=h.id;
else raise exception 'Handover action unavailable';end if;
insert into public.crm_execution_history(project_id,kind,record_id,action,snapshot,actor_id) values(h.project_id,'Handover',h.id::text,p_action,jsonb_build_object('party',p_party,'note',p_note),auth.uid());end$$;
create function public.close_crm_handover(p_id uuid,p_version integer,p_pdf_base64 text) returns uuid language plpgsql security definer set search_path='' as $$declare h public.crm_handovers;bytes bytea;doc uuid;c public.contracts;today date:=(now() at time zone 'Asia/Karachi')::date;begin
if not public.is_admin() then raise exception 'Administrator archive required';end if;
select * into h from public.crm_handovers where id=p_id;perform 1 from public.projects where id=h.project_id for update;select * into h from public.crm_handovers where id=p_id for update;
if not found or h.version is distinct from p_version or h.status not in ('Signed','Closed') then raise exception 'All signatures and current revision required';end if;
if h.status='Closed' then return (select id from public.crm_handover_documents where handover_id=h.id);end if;
perform portal_private.handover_ready(h.project_id);
if (select count(*) from public.crm_handover_signatures where handover_id=h.id and snapshot_hash=h.snapshot_hash)<>3 or not portal_private.handover_signer_eligible(h.project_id,h.contractor_id,'Contractor') or not portal_private.handover_signer_eligible(h.project_id,h.consultant_id,'Consultant') or not portal_private.handover_signer_eligible(h.project_id,h.client_id,'Client') then raise exception 'Three valid project signatures required';end if;
if p_pdf_base64 is null or length(p_pdf_base64)>7000000 then raise exception 'PDF maximum size is 5 MB';end if;bytes:=decode(p_pdf_base64,'base64');
if octet_length(bytes) not between 100 and 5242880 or substring(bytes from 1 for 5)<>convert_to('%PDF-','UTF8') or position(convert_to('%%EOF','UTF8') in bytes)=0 then raise exception 'Valid generated PDF required';end if;
if position(convert_to('IMAN-HANDOVER:'||h.id::text||':'||h.snapshot_hash||':v'||h.version::text,'UTF8') in bytes)=0 then raise exception 'PDF must identify the current signed handover revision';end if;
insert into public.crm_handover_documents(handover_id,pdf,sha256,archived_by) values(h.id,bytes,encode(sha256(bytes),'hex'),auth.uid()) returning id into doc;
update public.crm_handovers set status='Closed',closed_at=now(),version=version+1 where id=h.id;
update public.projects set status='Completed',handover_id=h.id,closed_at=now() where id=h.project_id;
select c0.* into c from public.contracts c0 join public.crm_sales s on s.contract_id=c0.id where s.project_id=h.project_id and c0.status='Draft' for update of c0;
if found then update public.contracts set status='Active',start_date=today,end_date=today+(c.end_date-c.start_date),renewal_date=today+(c.end_date-c.start_date)-30 where id=c.id;update public.projects set contract_id=c.id where id=h.project_id;end if;
insert into public.crm_execution_history(project_id,kind,record_id,action,snapshot,actor_id) values(h.project_id,'Handover',h.id::text,'Closed',jsonb_build_object('document',doc,'pdf_sha256',encode(sha256(bytes),'hex')),auth.uid());return doc;end$$;
create function public.download_crm_handover(p_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare d public.crm_handover_documents;begin
if not portal_private.handover_read(p_id) then raise exception 'Handover access required';end if;select * into d from public.crm_handover_documents where handover_id=p_id;if not found then raise exception 'Signed PDF is not archived yet';end if;return jsonb_build_object('base64',encode(d.pdf,'base64'),'sha256',d.sha256,'archived_at',d.archived_at);end$$;
create function portal_private.handover_project_guard() returns trigger language plpgsql security definer set search_path='' as $$begin
if (new.handover_id is distinct from old.handover_id or new.closed_at is distinct from old.closed_at) and not exists(select 1 from public.crm_handovers h join public.crm_handover_documents d on d.handover_id=h.id where h.id=new.handover_id and h.project_id=old.id and h.status='Closed' and new.status='Completed') then raise exception 'Closure fields require archived handover';end if;
if old.handover_id is not null and (new.status is distinct from old.status or new.handover_id is distinct from old.handover_id or new.closed_at is distinct from old.closed_at) then raise exception 'Signed closure is immutable';end if;
if new.status='Completed' and old.status<>'Completed' and (exists(select 1 from public.crm_phases where project_id=old.id) or exists(select 1 from public.crm_project_workstreams where project_id=old.id)) and not exists(select 1 from public.crm_handovers h join public.crm_handover_documents d on d.handover_id=h.id where h.id=new.handover_id and h.project_id=old.id and h.status='Closed') then raise exception 'Archive signed handover before completing project';end if;
if (new.company_id is distinct from old.company_id or new.title is distinct from old.title) and exists(select 1 from public.crm_handovers where project_id=old.id and status in ('Awaiting signatures','Signed','Closed')) then raise exception 'Released handover fixes project identity';end if;return new;end$$;
create trigger handover_project_guard before update on public.projects for each row execute function portal_private.handover_project_guard();
create function portal_private.handover_work_guard() returns trigger language plpgsql security definer set search_path='' as $$declare row_data jsonb:=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;pid uuid;begin
if tg_table_name in ('tasks','task_completions','crm_nodes','crm_phases','crm_punch_items') then pid:=(row_data->>'project_id')::uuid;
elsif tg_table_name='task_items' then select project_id into pid from public.tasks where id=(row_data->>'task_id')::uuid;
elsif tg_table_name='crm_node_checks' then select project_id into pid from public.crm_nodes where id=(row_data->>'node_id')::uuid;end if;
if exists(select 1 from public.crm_handovers where project_id=pid and status in ('Awaiting signatures','Signed','Closed')) then raise exception 'Released handover locks execution; cancel the revision before changes';end if;
if tg_op='DELETE' then return old;end if;return new;end$$;
do $$declare t text;begin foreach t in array array['tasks','task_items','task_completions','crm_nodes','crm_node_checks','crm_phases','crm_punch_items'] loop execute format('create trigger handover_work_guard before insert or update or delete on public.%I for each row execute function portal_private.handover_work_guard()',t);end loop;end$$;
revoke all on function portal_private.handover_work_guard() from public,anon,authenticated;
revoke all on function portal_private.handover_ready(uuid),portal_private.handover_project_guard() from public,anon,authenticated;
revoke all on function public.crm_handover_signers(uuid),public.create_crm_handover(uuid,text,uuid,uuid,uuid),public.crm_handover_action(uuid,integer,text,text,text,boolean,text),public.close_crm_handover(uuid,integer,text),public.download_crm_handover(uuid) from public,anon;
grant execute on function public.crm_handover_signers(uuid),public.create_crm_handover(uuid,text,uuid,uuid,uuid),public.crm_handover_action(uuid,integer,text,text,text,boolean,text),public.close_crm_handover(uuid,integer,text),public.download_crm_handover(uuid) to authenticated;
commit;
