begin;
create sequence public.sc_numbers;
revoke all on sequence public.sc_numbers from public,anon,authenticated;
create table public.sc_vendors(id uuid primary key default gen_random_uuid(),name text not null unique check(length(trim(name)) between 1 and 160),contact text not null default '' check(length(contact)<=300),assessment text not null default '' check(length(assessment)<=2000),rating integer not null default 0 check(rating between 0 and 5),status text not null default 'Pending' check(status in ('Pending','Approved','Suspended')),version integer not null default 1,created_by uuid not null references public.profiles);
create table public.sc_locations(id uuid primary key default gen_random_uuid(),name text not null unique check(length(trim(name)) between 1 and 160),kind text not null check(kind in ('Office','Vehicle','Site','RMA')),active boolean not null default true);
alter table public.crm_catalog add column description text not null default '',add column barcode text not null default '',add column tracking text not null default 'Quantity' check(tracking in ('Quantity','Serial','Returnable')),add column preferred_vendor uuid references public.sc_vendors,add column safety_stock numeric(12,3) not null default 0 check(safety_stock between 0 and 100000),add column reorder_level numeric(12,3) not null default 0 check(reorder_level between 0 and 100000);
insert into public.crm_settings(id,label,value) values('supply_controls','Supply chain controls','{"min_quotes":2,"pr_admin_above":0,"po_admin_above":0,"issue_admin_above":0,"price_jump_percent":10}');
create table public.sc_requests(id uuid primary key default gen_random_uuid(),number text not null unique default ('MR-'||lpad(nextval('public.sc_numbers')::text,6,'0')),project_id uuid references public.projects,task_id uuid references public.tasks,purpose text not null check(length(trim(purpose)) between 3 and 2000),site text not null check(length(trim(site)) between 1 and 300),required_by date not null,status text not null default 'Requested' check(status in ('Requested','Reserved / Sourcing','Approved','Ordered','Received','Issued','Delivered','Closed','Cancelled')),source text not null default 'Manual',created_by uuid not null references public.profiles,created_at timestamptz not null default now(),version integer not null default 1);
create unique index sc_one_boq_request on public.sc_requests(project_id) where source='Accepted BOQ';
create table public.sc_request_lines(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.sc_requests,item_id uuid not null references public.crm_catalog,item_name text not null,unit text not null,quantity numeric(12,3) not null check(quantity>0 and quantity<=100000),reserved numeric(12,3) not null default 0,ordered numeric(12,3) not null default 0,received numeric(12,3) not null default 0,issued numeric(12,3) not null default 0,delivered numeric(12,3) not null default 0,returned numeric(12,3) not null default 0,unique(request_id,item_id),check(reserved>=0 and ordered>=0 and received>=0 and issued>=0 and delivered>=0 and returned>=0 and issued<=quantity and delivered<=issued and returned<=delivered));
create table public.sc_reservations(id uuid primary key default gen_random_uuid(),line_id uuid not null references public.sc_request_lines,location_id uuid not null references public.sc_locations,quantity numeric(12,3) not null check(quantity>=0),unique(line_id,location_id));
create table public.sc_requisitions(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.sc_requests,line_id uuid not null unique references public.sc_request_lines,number text not null unique default ('PR-'||lpad(nextval('public.sc_numbers')::text,6,'0')),rfq_number text not null unique default ('RFQ-'||lpad(nextval('public.sc_numbers')::text,6,'0')),quantity numeric(12,3) not null check(quantity>0),estimated_rate numeric(14,2) not null,estimated_total numeric(14,2) not null,status text not null default 'Pending' check(status in ('Pending','Approved')),manager_approved_by uuid references public.profiles,approved_by uuid references public.profiles,approved_at timestamptz,over_budget boolean not null default false,version integer not null default 1);
create table public.sc_request_approvals(id uuid primary key default gen_random_uuid(),request_id uuid not null unique references public.sc_requests,estimated_total numeric(14,2) not null,over_budget boolean not null,manager_approved_by uuid references public.profiles,approved_by uuid references public.profiles);
create table public.sc_quotes(id uuid primary key default gen_random_uuid(),requisition_id uuid not null references public.sc_requisitions,vendor_id uuid not null references public.sc_vendors,rate numeric(14,2) not null check(rate>0 and rate<100000000),delivery_date date not null,warranty text not null check(length(warranty)<=500),payment_terms text not null check(length(trim(payment_terms)) between 1 and 500),created_by uuid not null references public.profiles,created_at timestamptz not null default now(),unique(requisition_id,vendor_id));
alter table public.sc_quotes add column vendor_snapshot jsonb not null default '{}';
create table public.sc_orders(id uuid primary key default gen_random_uuid(),number text not null unique default ('PO-'||lpad(nextval('public.sc_numbers')::text,6,'0')),request_id uuid not null references public.sc_requests,requisition_id uuid not null references public.sc_requisitions,line_id uuid not null references public.sc_request_lines,quote_id uuid not null references public.sc_quotes,vendor_id uuid not null references public.sc_vendors,quantity numeric(12,3) not null check(quantity>0 and quantity<=100000),rate numeric(14,2) not null check(rate>0 and rate<100000000),total numeric(14,2) not null,status text not null default 'Pending approval' check(status in ('Pending approval','Approved','In transit','Part received','Received','Cancelled')),received numeric(12,3) not null default 0 check(received>=0 and received<=quantity),rejected numeric(12,3) not null default 0,reason text not null check(length(reason)<=2000),due_date date not null,created_by uuid not null references public.profiles,approved_by uuid references public.profiles,manager_approved_by uuid references public.profiles,over_budget boolean not null default false,approved_at timestamptz,created_at timestamptz not null default now(),version integer not null default 1);
alter table public.sc_orders add column vendor_snapshot jsonb not null default '{}';
create table public.sc_receipts(id uuid primary key default gen_random_uuid(),number text not null unique default ('GRN-'||lpad(nextval('public.sc_numbers')::text,6,'0')),gate_number text not null unique default ('IGP-'||lpad(nextval('public.sc_numbers')::text,6,'0')),inspection_number text not null unique default ('QC-'||lpad(nextval('public.sc_numbers')::text,6,'0')),order_id uuid not null references public.sc_orders,request_id uuid not null references public.sc_requests,line_id uuid not null references public.sc_request_lines,location_id uuid not null references public.sc_locations,arrived numeric(12,3) not null check(arrived>0),accepted numeric(12,3) not null check(accepted>=0),rejected numeric(12,3) not null check(rejected>=0),rate numeric(14,2) not null,note text not null check(length(trim(note)) between 3 and 2000),created_by uuid not null references public.profiles,created_at timestamptz not null default now(),check(arrived=accepted+rejected));
create table public.sc_issues(id uuid primary key default gen_random_uuid(),number text not null unique default ('MIN-'||lpad(nextval('public.sc_numbers')::text,6,'0')),request_id uuid not null references public.sc_requests,line_id uuid not null references public.sc_request_lines,location_id uuid not null references public.sc_locations,quantity numeric(12,3) not null check(quantity>0),rate numeric(14,4) not null,total numeric(14,2) not null,recipient_id uuid references public.profiles,return_due date,status text not null default 'Pending approval' check(status in ('Pending approval','Approved','Posted','In transit','Delivered','Cancelled')),approved_by uuid references public.profiles,created_by uuid not null references public.profiles,posted_at timestamptz,delivered_at timestamptz,receiver_id uuid references public.profiles,receiver_name text,delivery_note text not null default '',challan_number text unique,outward_number text unique,serials text[] not null default '{}',version integer not null default 1);
create table public.sc_returns(id uuid primary key default gen_random_uuid(),number text not null unique,request_id uuid not null references public.sc_requests,line_id uuid not null references public.sc_request_lines,issue_id uuid references public.sc_issues,receipt_id uuid references public.sc_receipts,location_id uuid not null references public.sc_locations,quantity numeric(12,3) not null check(quantity>0),rate numeric(14,4) not null,kind text not null check(kind in ('Site return','Vendor return')),note text not null check(length(trim(note)) between 3 and 2000),created_by uuid not null references public.profiles,created_at timestamptz not null default now(),check((issue_id is null)<>(receipt_id is null)));
create table public.sc_adjustments(id uuid primary key default gen_random_uuid(),number text not null unique default ('ADJ-'||lpad(nextval('public.sc_numbers')::text,6,'0')),item_id uuid not null references public.crm_catalog,location_id uuid not null references public.sc_locations,expected numeric(12,3) not null,counted numeric(12,3) not null check(counted>=0 and counted<=100000),rate numeric(14,4) not null check(rate>=0 and rate<100000000),note text not null check(length(trim(note)) between 3 and 2000),status text not null default 'Pending' check(status in ('Pending','Posted')),created_by uuid not null references public.profiles,approved_by uuid references public.profiles,created_at timestamptz not null default now());
create table public.sc_stock_ledger(id uuid primary key default gen_random_uuid(),item_id uuid not null references public.crm_catalog,location_id uuid not null references public.sc_locations,quantity numeric(12,3) not null check(quantity<>0),rate numeric(14,4) not null check(rate>=0 and rate<100000000),project_id uuid references public.projects,request_id uuid references public.sc_requests,document_id uuid not null,kind text not null,actor_id uuid not null references public.profiles,created_at timestamptz not null default now());
create table public.sc_serials(id uuid primary key default gen_random_uuid(),item_id uuid not null references public.crm_catalog,serial text not null check(length(trim(serial)) between 1 and 120),location_id uuid not null references public.sc_locations,receipt_id uuid not null references public.sc_receipts,issue_id uuid references public.sc_issues,status text not null default 'In stock' check(status in ('In stock','Issued','Returned to vendor')),unique(item_id,serial));
create table public.sc_history(id uuid primary key default gen_random_uuid(),request_id uuid references public.sc_requests,kind text not null,document_id uuid not null,action text not null,note text not null default '',actor_id uuid not null references public.profiles,created_at timestamptz not null default now());
create index sc_request_project on public.sc_requests(project_id);
create index sc_line_request on public.sc_request_lines(request_id);
create index sc_ledger_item_location on public.sc_stock_ledger(item_id,location_id);
create index sc_order_request on public.sc_orders(request_id);
create function portal_private.supply_department() returns boolean language sql stable security definer set search_path='' as $$select public.is_admin() or portal_private.crm_permission('stock.manage') or portal_private.crm_permission('purchase.manage') or portal_private.crm_permission('logistics.manage') or portal_private.crm_permission('finance.manage');$$;
create function portal_private.supply_request_access(p_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.sc_requests r where r.id=p_id and (portal_private.supply_department() or public.is_staff() and r.project_id is null and r.created_by=auth.uid() or public.is_staff() and public.can_project(r.project_id) and (portal_private.execution_manager(r.project_id) or (r.task_id is null and portal_private.project_assigned(r.project_id) or portal_private.task_assigned(r.task_id)))));$$;
create function portal_private.supply_cost_access(p_id uuid) returns boolean language sql stable security definer set search_path='' as $$select portal_private.supply_department() or exists(select 1 from public.sc_requests r where r.id=p_id and portal_private.execution_manager(r.project_id));$$;
create function portal_private.supply_control(p_key text) returns numeric language sql stable security definer set search_path='' as $$select (value->>p_key)::numeric from public.crm_settings where id='supply_controls';$$;
create function portal_private.supply_balance(p_item uuid,p_location uuid) returns table(on_hand numeric,stock_value numeric,reserved numeric,average_rate numeric) language sql stable security definer set search_path='' as $$with l as (select coalesce(sum(quantity),0) qty,coalesce(sum(quantity*rate),0) value from public.sc_stock_ledger where item_id=p_item and location_id=p_location),r as (select coalesce(sum(r.quantity),0) qty from public.sc_reservations r join public.sc_request_lines x on x.id=r.line_id where x.item_id=p_item and r.location_id=p_location) select l.qty,l.value,r.qty,case when l.qty>0 then round(l.value/l.qty,4) else 0 end from l,r;$$;
create function portal_private.supply_active_request(p_id uuid) returns public.sc_requests language plpgsql security definer set search_path='' as $$declare r public.sc_requests;begin select * into r from public.sc_requests where id=p_id for update;if not found or r.status='Cancelled' then raise exception 'Active material request required';end if;if r.project_id is not null then perform 1 from public.projects where id=r.project_id and status<>'Completed' for update;if not found then raise exception 'Active project required';end if;end if;return r;end$$;
create function portal_private.supply_audit(p_request uuid,p_kind text,p_doc uuid,p_action text,p_note text default '') returns void language sql security definer set search_path='' as $$insert into public.sc_history(request_id,kind,document_id,action,note,actor_id) values(p_request,p_kind,p_doc,p_action,p_note,auth.uid());$$;
do $$declare t text;begin foreach t in array array['sc_vendors','sc_locations','sc_requests','sc_request_lines','sc_reservations','sc_requisitions','sc_request_approvals','sc_quotes','sc_orders','sc_receipts','sc_issues','sc_returns','sc_adjustments','sc_stock_ledger','sc_serials','sc_history'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;
create policy supply_request_read on public.sc_requests for select to authenticated using(portal_private.supply_request_access(id));
create policy supply_line_read on public.sc_request_lines for select to authenticated using(portal_private.supply_request_access(request_id));
create policy supply_issue_read on public.sc_issues for select to authenticated using(portal_private.supply_cost_access(request_id));
-- Cost-bearing documents stay private to departments and assigned project managers.
do $$declare t text;begin foreach t in array array['sc_request_approvals','sc_requisitions','sc_orders','sc_receipts','sc_returns'] loop execute format('create policy supply_cost_read on public.%I for select to authenticated using(portal_private.supply_cost_access(request_id))',t);end loop;end$$;
create policy supply_quote_read on public.sc_quotes for select to authenticated using(exists(select 1 from public.sc_requisitions r where r.id=requisition_id and portal_private.supply_cost_access(r.request_id)));
create policy supply_reservation_read on public.sc_reservations for select to authenticated using(portal_private.supply_department());
do $$declare t text;begin foreach t in array array['sc_vendors','sc_locations','sc_adjustments','sc_stock_ledger','sc_serials'] loop execute format('create policy supply_department_read on public.%I for select to authenticated using(portal_private.supply_department())',t);end loop;end$$;
create policy supply_history_read on public.sc_history for select to authenticated using(portal_private.supply_cost_access(request_id));
create policy supply_catalog_read on public.crm_catalog for select to authenticated using(portal_private.supply_department());
create policy supply_settings_read on public.crm_settings for select to authenticated using(id='supply_controls' and portal_private.supply_department());
revoke all on function portal_private.supply_department(),portal_private.supply_request_access(uuid),portal_private.supply_cost_access(uuid),portal_private.supply_control(text),portal_private.supply_balance(uuid,uuid),portal_private.supply_active_request(uuid),portal_private.supply_audit(uuid,text,uuid,text,text) from public,anon,authenticated;
grant execute on function portal_private.supply_department(),portal_private.supply_request_access(uuid),portal_private.supply_cost_access(uuid) to authenticated;

create function public.save_supply_controls(p_version integer,p_data jsonb) returns void language plpgsql security definer set search_path='' as $$declare key text;n numeric;begin
if not public.is_admin() then raise exception 'Administrator required';end if;if jsonb_typeof(p_data) is distinct from 'object' or (select count(*) from jsonb_object_keys(p_data))<>5 then raise exception 'Five supply control values required';end if;
foreach key in array array['min_quotes','pr_admin_above','po_admin_above','issue_admin_above','price_jump_percent'] loop n:=(p_data->>key)::numeric;if n is null or n<0 or n>=100000000 or (key='min_quotes' and (n not between 1 and 20 or n<>trunc(n))) or (key='price_jump_percent' and n>100) then raise exception 'Invalid approval control';end if;end loop;
update public.crm_settings set value=p_data,version=version+1,updated_by=auth.uid(),updated_at=now() where id='supply_controls' and version=p_version;if not found then raise exception 'Controls changed. Refresh first';end if;end$$;
create function public.save_supply_master(p_kind text,p_id uuid,p_version integer,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare result uuid;begin
if p_kind='Vendor' and portal_private.crm_permission('purchase.manage') then
if p_id is null then insert into public.sc_vendors(name,contact,created_by) values(trim(p_data->>'name'),coalesce(p_data->>'contact',''),auth.uid()) returning id into result;
else if (exists(select 1 from public.sc_orders where vendor_id=p_id) or exists(select 1 from public.sc_quotes where vendor_id=p_id)) and exists(select 1 from public.sc_vendors where id=p_id and name<>trim(p_data->>'name')) then raise exception 'Vendor identity used on a PO is fixed; create a new assessed vendor';end if;update public.sc_vendors set name=trim(p_data->>'name'),contact=coalesce(p_data->>'contact',''),assessment=coalesce(p_data->>'assessment',''),rating=(p_data->>'rating')::integer,status=case when public.is_admin() then p_data->>'status' when name<>trim(p_data->>'name') then 'Pending' else status end,version=version+1 where id=p_id and version=p_version returning id into result;if public.is_admin() and p_data->>'status'='Approved' and length(trim(coalesce(p_data->>'assessment','')))<3 then raise exception 'Vendor assessment required';end if;end if;
elsif p_kind='Location' and portal_private.crm_permission('stock.manage') then if p_id is not null then raise exception 'Locations are fixed; create a new location';end if;insert into public.sc_locations(name,kind) values(trim(p_data->>'name'),p_data->>'kind') returning id into result;
elsif p_kind='Item' and (portal_private.crm_permission('stock.manage') or portal_private.crm_permission('purchase.manage')) then
if p_id is null then insert into public.crm_catalog(name,unit) values(trim(p_data->>'name'),coalesce(nullif(p_data->>'unit',''),'each')) returning id into result;else select id into result from public.crm_catalog where id=p_id and version=p_version for update;end if;
if result is not null then
if (exists(select 1 from public.sc_stock_ledger where item_id=result) or exists(select 1 from public.sc_request_lines where item_id=result)) and exists(select 1 from public.crm_catalog where id=result and (tracking is distinct from p_data->>'tracking' or unit is distinct from p_data->>'unit')) then raise exception 'Used item unit and tracking type are fixed';end if;
update public.crm_catalog set name=trim(p_data->>'name'),category=coalesce(p_data->>'category',''),unit=coalesce(nullif(p_data->>'unit',''),'each'),tracking=p_data->>'tracking',barcode=coalesce(p_data->>'barcode',''),description=coalesce(p_data->>'description',''),preferred_vendor=nullif(p_data->>'preferred_vendor','')::uuid,reorder_level=coalesce((p_data->>'reorder_level')::numeric,0),safety_stock=coalesce((p_data->>'safety_stock')::numeric,0),version=case when p_id is null then version else version+1 end where id=result;end if;
else raise exception 'Supply department permission required';end if;
if result is null then raise exception 'Master record changed';end if;perform portal_private.supply_audit(null,p_kind,result,'Saved');return result;end$$;
create function portal_private.supply_item_guard() returns trigger language plpgsql security definer set search_path='' as $$begin
if (new.unit is distinct from old.unit or new.tracking is distinct from old.tracking) and (exists(select 1 from public.sc_stock_ledger where item_id=old.id) or exists(select 1 from public.sc_request_lines where item_id=old.id)) then raise exception 'Used catalogue unit and tracking type are fixed';end if;return new;end$$;
create trigger supply_item_guard before update on public.crm_catalog for each row execute function portal_private.supply_item_guard();
revoke all on function portal_private.supply_item_guard() from public,anon,authenticated;
create function public.supply_request_items() returns table(id uuid,name text,unit text,tracking text) language plpgsql stable security definer set search_path='' as $$begin if not public.is_staff() then raise exception 'Active staff required';end if;return query select c.id,c.name,c.unit,c.tracking from public.crm_catalog c where c.active order by c.name;end$$;
create function public.supply_staff() returns table(id uuid,name text,role text,active boolean) language plpgsql stable security definer set search_path='' as $$begin if not portal_private.supply_department() then raise exception 'Supply department required';end if;return query select u.id,u.name,u.role,u.active from public.profiles u where u.active and u.role in ('admin','team') order by u.name;end$$;
create function public.create_supply_request(p_project uuid,p_task uuid,p_purpose text,p_site text,p_required_by date,p_lines jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare req uuid;row jsonb;item public.crm_catalog;qty numeric;begin
if not public.is_staff() or (p_project is null and not portal_private.supply_department() and not portal_private.crm_permission('project.own')) then raise exception 'Staff request access required';end if;
if p_project is not null then perform 1 from public.projects where id=p_project and status<>'Completed' for update;if not found or not (public.is_admin() or portal_private.execution_manager(p_project) or (p_task is not null and portal_private.task_assigned(p_task)) or portal_private.project_assigned(p_project)) then raise exception 'Assigned active project required';end if;end if;
if p_project is not null and exists(select 1 from public.crm_sales where project_id=p_project and currency<>'PKR') then raise exception 'Supply valuation currently requires PKR project budget';end if;
if p_task is not null and not exists(select 1 from public.tasks where id=p_task and project_id=p_project) then raise exception 'Task must belong to request project';end if;
if p_required_by is null or jsonb_typeof(p_lines) is distinct from 'array' or jsonb_array_length(p_lines) not between 1 and 100 then raise exception 'Required date and 1–100 item lines required';end if;
insert into public.sc_requests(project_id,task_id,purpose,site,required_by,created_by) values(p_project,p_task,trim(p_purpose),trim(p_site),p_required_by,auth.uid()) returning id into req;
for row in select value from jsonb_array_elements(p_lines) order by value->>'item_id' loop select * into item from public.crm_catalog where id=(row->>'item_id')::uuid and active for share;if not found then raise exception 'Active catalogue item required';end if;qty:=(row->>'quantity')::numeric;if item.tracking in ('Serial','Returnable') and qty<>trunc(qty) then raise exception 'Whole units required for tracked items';end if;insert into public.sc_request_lines(request_id,item_id,item_name,unit,quantity) values(req,item.id,item.name,item.unit,qty);end loop;
perform portal_private.supply_audit(req,'MR',req,'Requested');return req;end$$;
create function public.supply_stock_report() returns table(id text,item_id uuid,item text,tracking text,location_id uuid,location text,on_hand numeric,reserved numeric,available numeric,average_rate numeric,stock_value numeric,reorder_level numeric) language plpgsql stable security definer set search_path='' as $$begin if not portal_private.supply_department() then raise exception 'Supply department required';end if;return query select c.id::text||':'||l.id::text,c.id,c.name,c.tracking,l.id,l.name,b.on_hand,b.reserved,b.on_hand-b.reserved,b.average_rate,round(b.stock_value,2),c.reorder_level from public.crm_catalog c cross join public.sc_locations l cross join lateral portal_private.supply_balance(c.id,l.id) b where c.active and l.active order by c.name,l.name;end$$;
create function public.check_supply_stock(p_request uuid,p_version integer,p_location uuid) returns void language plpgsql security definer set search_path='' as $$declare req public.sc_requests;line public.sc_request_lines;b record;take numeric;shortfall numeric;rate numeric;begin
if not portal_private.crm_permission('stock.manage') then raise exception 'Store permission required';end if;req:=portal_private.supply_active_request(p_request);if req.version is distinct from p_version or req.status<>'Requested' then raise exception 'Request changed or already checked';end if;
if not exists(select 1 from public.sc_locations where id=p_location and active) then raise exception 'Active stock location required';end if;
for line in select * from public.sc_request_lines where request_id=p_request order by item_id for update loop select last_rate into rate from public.crm_catalog where id=line.item_id for update;select * into b from portal_private.supply_balance(line.item_id,p_location);take:=least(line.quantity,greatest(0,b.on_hand-b.reserved));shortfall:=line.quantity-take;
if take>0 then insert into public.sc_reservations(line_id,location_id,quantity) values(line.id,p_location,take);end if;
update public.sc_request_lines set reserved=take where id=line.id;
if shortfall>0 then insert into public.sc_requisitions(request_id,line_id,quantity,estimated_rate,estimated_total) values(p_request,line.id,shortfall,rate,round(shortfall*rate,2));end if;end loop;
update public.sc_requests set status='Reserved / Sourcing',version=version+1 where id=p_request;perform portal_private.supply_audit(p_request,'MR',p_request,'Stock checked');end$$;
create function public.approve_supply_request(p_request uuid,p_version integer,p_note text default '') returns void language plpgsql security definer set search_path='' as $$declare req public.sc_requests;cost numeric;budget numeric;committed numeric;overrun boolean;first_approver uuid;begin
req:=portal_private.supply_active_request(p_request);if req.version is distinct from p_version or req.status<>'Reserved / Sourcing' or req.created_by=auth.uid() then raise exception 'Separate approver and current stock check required';end if;
select coalesce(sum(x.quantity*c.last_rate),0) into cost from public.sc_request_lines x join public.crm_catalog c on c.id=x.item_id where x.request_id=p_request;
select coalesce(sum((x->>'quantity')::numeric*(x->>'unit_cost')::numeric),0) into budget from public.crm_sales s cross join lateral jsonb_array_elements(s.planned_budget->'lines') x where s.project_id=req.project_id and x->>'block'='Material';
select coalesce(sum(q.estimated_total),0) into committed from public.sc_request_approvals q join public.sc_requests r on r.id=q.request_id where r.project_id=req.project_id and q.approved_by is not null and r.status<>'Cancelled' and r.id<>p_request;
overrun:=req.project_id is not null and cost+committed>budget;
if not public.is_admin() and (req.project_id is null or not portal_private.execution_manager(req.project_id) or cost>portal_private.supply_control('pr_admin_above')) and not (overrun and portal_private.execution_manager(req.project_id)) then raise exception 'Approval matrix requires administrator';end if;
insert into public.sc_request_approvals(request_id,estimated_total,over_budget) values(req.id,cost,overrun) on conflict(request_id) do update set estimated_total=excluded.estimated_total,over_budget=excluded.over_budget;
if overrun then
if length(trim(coalesce(p_note,'')))<3 then raise exception 'Budget overrun reason required';end if;
select manager_approved_by into first_approver from public.sc_request_approvals where request_id=p_request;
if first_approver is null then if not portal_private.execution_manager(req.project_id) then raise exception 'Assigned project manager first approval required';end if;update public.sc_request_approvals set manager_approved_by=auth.uid() where request_id=p_request;update public.sc_requisitions set manager_approved_by=auth.uid(),over_budget=true,version=version+1 where request_id=p_request;update public.sc_requests set version=version+1 where id=p_request;perform portal_private.supply_audit(p_request,'PR',p_request,'Overrun PM approval',p_note);return;
elsif not public.is_admin() or first_approver=auth.uid() then raise exception 'Distinct administrator overrun approval required';end if;end if;
update public.sc_request_approvals set approved_by=auth.uid() where request_id=p_request;
update public.sc_requisitions set status='Approved',approved_by=auth.uid(),approved_at=now(),over_budget=overrun,version=version+1 where request_id=p_request;
update public.sc_requests set status='Approved',version=version+1 where id=p_request;perform portal_private.supply_audit(p_request,'PR',p_request,'Approved',p_note);end$$;
create function public.add_supply_quote(p_requisition uuid,p_vendor uuid,p_rate numeric,p_due date,p_warranty text,p_terms text) returns uuid language plpgsql security definer set search_path='' as $$declare pr public.sc_requisitions;doc uuid;begin
if not portal_private.crm_permission('purchase.manage') then raise exception 'Procurement required';end if;select * into pr from public.sc_requisitions where id=p_requisition;perform portal_private.supply_active_request(pr.request_id);if pr.status<>'Approved' then raise exception 'Approved requisition required';end if;
if not exists(select 1 from public.sc_vendors where id=p_vendor and status='Approved') then raise exception 'Assessed approved vendor required';end if;
insert into public.sc_quotes(requisition_id,vendor_id,rate,delivery_date,warranty,payment_terms,created_by,vendor_snapshot) values(p_requisition,p_vendor,p_rate,p_due,p_warranty,p_terms,auth.uid(),(select to_jsonb(v) from public.sc_vendors v where id=p_vendor)) returning id into doc;perform portal_private.supply_audit(pr.request_id,'RFQ',doc,'Vendor quotation recorded');return doc;end$$;
create function public.create_supply_order(p_quote uuid,p_quantity numeric,p_reason text) returns uuid language plpgsql security definer set search_path='' as $$declare quote public.sc_quotes;pr public.sc_requisitions;req public.sc_requests;item public.crm_catalog;remaining numeric;doc uuid;begin
if not portal_private.crm_permission('purchase.manage') then raise exception 'Purchase permission required';end if;select * into quote from public.sc_quotes where id=p_quote;select * into pr from public.sc_requisitions where id=quote.requisition_id;req:=portal_private.supply_active_request(pr.request_id);select * into pr from public.sc_requisitions where id=pr.id for update;
if pr.status<>'Approved' or not exists(select 1 from public.sc_vendors where id=quote.vendor_id and status='Approved') then raise exception 'Approved PR and vendor required';end if;
if (select count(distinct q.vendor_id) from public.sc_quotes q join public.sc_vendors v on v.id=q.vendor_id and v.status='Approved' where q.requisition_id=pr.id)<portal_private.supply_control('min_quotes') then raise exception 'Minimum vendor quotations not met';end if;
select * into item from public.crm_catalog where id=(select item_id from public.sc_request_lines where id=pr.line_id);
if (quote.rate>coalesce((select min(rate) from public.sc_quotes where requisition_id=pr.id),quote.rate) or item.last_rate>0 and quote.rate>item.last_rate*(1+portal_private.supply_control('price_jump_percent')/100)) and length(trim(coalesce(p_reason,'')))<3 then raise exception 'Higher price selection needs a reason';end if;
select pr.quantity-coalesce(sum(quantity),0) into remaining from public.sc_orders where requisition_id=pr.id and status<>'Cancelled';if p_quantity is null or p_quantity<=0 or p_quantity>remaining or item.tracking<>'Quantity' and p_quantity<>trunc(p_quantity) then raise exception 'Order quantity exceeds remaining shortfall';end if;
insert into public.sc_orders(request_id,requisition_id,line_id,quote_id,vendor_id,quantity,rate,total,reason,due_date,created_by,vendor_snapshot) values(req.id,pr.id,pr.line_id,quote.id,quote.vendor_id,p_quantity,quote.rate,round(p_quantity*quote.rate,2),coalesce(p_reason,''),quote.delivery_date,auth.uid(),(select to_jsonb(v) from public.sc_vendors v where id=quote.vendor_id)) returning id into doc;perform portal_private.supply_audit(req.id,'PO',doc,'Raised',p_reason);return doc;end$$;
create function public.supply_order_action(p_order uuid,p_version integer,p_action text,p_note text default '') returns void language plpgsql security definer set search_path='' as $$declare po public.sc_orders;req public.sc_requests;budget numeric;committed numeric;overrun boolean;begin
select * into po from public.sc_orders where id=p_order;req:=portal_private.supply_active_request(po.request_id);select * into po from public.sc_orders where id=p_order for update;if po.version is distinct from p_version then raise exception 'Order changed';end if;
if p_action='Approve' and po.status='Pending approval' and auth.uid()<>po.created_by then
if not exists(select 1 from public.sc_vendors where id=po.vendor_id and status='Approved') then raise exception 'Vendor approval must remain active before PO approval';end if;
select coalesce(sum((x->>'quantity')::numeric*(x->>'unit_cost')::numeric),0) into budget from public.crm_sales ss cross join lateral jsonb_array_elements(ss.planned_budget->'lines') x where ss.project_id=req.project_id and x->>'block'='Material';
select coalesce(sum(a.estimated_total),0) into committed from public.sc_request_approvals a join public.sc_requests r on r.id=a.request_id where r.project_id=req.project_id and a.approved_by is not null and r.status<>'Cancelled';
committed:=committed+coalesce((select sum(o.quantity*(o.rate-r.estimated_rate)) from public.sc_orders o join public.sc_requisitions r on r.id=o.requisition_id join public.sc_requests mr on mr.id=o.request_id where mr.project_id=req.project_id and o.status in ('Approved','In transit','Part received','Received')),0)+po.quantity*(po.rate-(select estimated_rate from public.sc_requisitions where id=po.requisition_id));
overrun:=req.project_id is not null and committed>budget;
if overrun and po.manager_approved_by is null then if not portal_private.execution_manager(req.project_id) or length(trim(coalesce(p_note,'')))<3 then raise exception 'Budget overrun needs project manager approval and reason';end if;update public.sc_orders set manager_approved_by=auth.uid(),over_budget=true,version=version+1 where id=po.id;perform portal_private.supply_audit(req.id,'PO',po.id,'Overrun PM approval',p_note);return;
elsif overrun and (not public.is_admin() or po.manager_approved_by=auth.uid()) then raise exception 'Distinct administrator must approve PO budget overrun';
elsif not overrun and not (public.is_admin() or portal_private.execution_manager(req.project_id) and po.total<=portal_private.supply_control('po_admin_above')) then raise exception 'PO approval threshold requires administrator';end if;
update public.sc_orders set status='Approved',approved_by=auth.uid(),approved_at=now(),version=version+1 where id=p_order;update public.sc_request_lines set ordered=ordered+po.quantity where id=po.line_id;update public.sc_requests set status='Ordered',version=version+1 where id=req.id;
elsif p_action='Dispatch' and po.status='Approved' and portal_private.crm_permission('logistics.manage') then update public.sc_orders set status='In transit',version=version+1 where id=p_order;
elsif p_action='Cancel' and po.status='Pending approval' and portal_private.crm_permission('purchase.manage') and length(trim(coalesce(p_note,'')))>=3 then update public.sc_orders set status='Cancelled',version=version+1 where id=p_order;
else raise exception 'Order approval or action unavailable';end if;perform portal_private.supply_audit(req.id,'PO',p_order,p_action,p_note);end$$;
create function public.receive_supply_order(p_order uuid,p_version integer,p_location uuid,p_arrived numeric,p_accepted numeric,p_note text,p_serials text[]) returns uuid language plpgsql security definer set search_path='' as $$declare po public.sc_orders;req public.sc_requests;line public.sc_request_lines;item public.crm_catalog;doc uuid;begin
if not portal_private.crm_permission('stock.manage') then raise exception 'Store goods receipt permission required';end if;select * into po from public.sc_orders where id=p_order;req:=portal_private.supply_active_request(po.request_id);select * into po from public.sc_orders where id=p_order for update;
if po.version is distinct from p_version or po.status not in ('Approved','In transit','Part received') or po.created_by=auth.uid() then raise exception 'Separate receipt operator and approved current PO required';end if;
select * into line from public.sc_request_lines where id=po.line_id for update;select * into item from public.crm_catalog where id=line.item_id for update;
if not exists(select 1 from public.sc_locations where id=p_location and active) or p_arrived is null or p_accepted is null or p_arrived<=0 or p_accepted<0 or p_accepted>p_arrived or p_arrived>po.quantity-po.received or item.tracking<>'Quantity' and (p_arrived<>trunc(p_arrived) or p_accepted<>trunc(p_accepted)) then raise exception 'Valid arrival and accepted quantities within outstanding PO required';end if;
if p_serials is null or item.tracking='Serial' and (cardinality(p_serials)<>p_accepted or (select count(distinct s) from unnest(p_serials) s)<>cardinality(p_serials)) or item.tracking<>'Serial' and cardinality(p_serials)<>0 then raise exception 'One unique serial per accepted serialised unit required';end if;
insert into public.sc_receipts(order_id,request_id,line_id,location_id,arrived,accepted,rejected,rate,note,created_by) values(po.id,req.id,line.id,p_location,p_arrived,p_accepted,p_arrived-p_accepted,po.rate,trim(p_note),auth.uid()) returning id into doc;
if p_accepted>0 then insert into public.sc_stock_ledger(item_id,location_id,quantity,rate,document_id,kind,actor_id,request_id) values(item.id,p_location,p_accepted,po.rate,doc,'GRN',auth.uid(),req.id);insert into public.sc_reservations(line_id,location_id,quantity) values(line.id,p_location,p_accepted) on conflict(line_id,location_id) do update set quantity=sc_reservations.quantity+excluded.quantity;update public.sc_request_lines set received=received+p_accepted,reserved=reserved+p_accepted where id=line.id;update public.crm_catalog set last_rate=po.rate where id=item.id;end if;
insert into public.sc_serials(item_id,serial,location_id,receipt_id) select item.id,trim(s),p_location,doc from unnest(p_serials) s;
update public.sc_orders set received=received+p_accepted,rejected=rejected+p_arrived-p_accepted,status=case when received+p_accepted=quantity then 'Received' else 'Part received' end,version=version+1 where id=po.id;
update public.sc_requests set status='Received',version=version+1 where id=req.id;perform portal_private.supply_audit(req.id,'GRN',doc,'Inspected and received',p_note);return doc;end$$;
create table public.sc_transfers(id uuid primary key default gen_random_uuid(),number text not null unique default ('TRF-'||lpad(nextval('public.sc_numbers')::text,6,'0')),item_id uuid not null references public.crm_catalog,from_location uuid not null references public.sc_locations,to_location uuid not null references public.sc_locations,quantity numeric(12,3) not null check(quantity>0 and quantity<=100000),rate numeric(14,4) not null,note text not null check(length(trim(note)) between 3 and 2000),created_by uuid not null references public.profiles,created_at timestamptz not null default now(),check(from_location<>to_location));
alter table public.sc_transfers enable row level security;revoke all on public.sc_transfers from public,anon,authenticated;grant select on public.sc_transfers to authenticated;create policy supply_transfer_read on public.sc_transfers for select to authenticated using(portal_private.supply_department());
create function public.transfer_supply_stock(p_item uuid,p_from uuid,p_to uuid,p_quantity numeric,p_note text,p_serials text[]) returns uuid language plpgsql security definer set search_path='' as $$declare item public.crm_catalog;b record;doc uuid;begin
if not portal_private.crm_permission('stock.manage') then raise exception 'Store permission required';end if;select * into item from public.crm_catalog where id=p_item and active for update;select * into b from portal_private.supply_balance(p_item,p_from);
if not found or p_from is not distinct from p_to or (select count(*) from public.sc_locations where id in (p_from,p_to) and active)<>2 or p_quantity is null or p_quantity<=0 or p_quantity>b.on_hand-b.reserved or item.tracking<>'Quantity' and p_quantity<>trunc(p_quantity) then raise exception 'Transfer requires available unreserved stock and distinct active locations';end if;
if p_serials is null or item.tracking='Serial' and (cardinality(p_serials)<>p_quantity or (select count(distinct s) from unnest(p_serials) s)<>cardinality(p_serials) or exists(select 1 from unnest(p_serials) s where not exists(select 1 from public.sc_serials where item_id=p_item and serial=s and status='In stock' and location_id=p_from))) or item.tracking<>'Serial' and cardinality(p_serials)<>0 then raise exception 'Matching available transfer serials required';end if;
insert into public.sc_transfers(item_id,from_location,to_location,quantity,rate,note,created_by) values(p_item,p_from,p_to,p_quantity,b.average_rate,trim(p_note),auth.uid()) returning id into doc;
insert into public.sc_stock_ledger(item_id,location_id,quantity,rate,document_id,kind,actor_id) values(p_item,p_from,-p_quantity,b.average_rate,doc,'Transfer out',auth.uid()),(p_item,p_to,p_quantity,b.average_rate,doc,'Transfer in',auth.uid());update public.sc_serials set location_id=p_to where item_id=p_item and serial=any(p_serials);perform portal_private.supply_audit(null,'TRF',doc,'Transferred',p_note);return doc;end$$;
create function public.create_supply_adjustment(p_item uuid,p_location uuid,p_counted numeric,p_rate numeric,p_note text) returns uuid language plpgsql security definer set search_path='' as $$declare b record;doc uuid;begin
if not portal_private.crm_permission('stock.manage') then raise exception 'Store permission required';end if;
if not exists(select 1 from public.crm_catalog where id=p_item and active and tracking='Quantity') or not exists(select 1 from public.sc_locations where id=p_location and active) then raise exception 'Quantity-only item and active location required; serial stock enters through GRN';end if;
select * into b from portal_private.supply_balance(p_item,p_location);insert into public.sc_adjustments(item_id,location_id,expected,counted,rate,note,created_by) values(p_item,p_location,b.on_hand,p_counted,p_rate,trim(p_note),auth.uid()) returning id into doc;perform portal_private.supply_audit(null,'ADJ',doc,'Count submitted',p_note);return doc;end$$;
create function public.post_supply_adjustment(p_id uuid) returns void language plpgsql security definer set search_path='' as $$declare a public.sc_adjustments;b record;qty numeric;rate numeric;begin
if not public.is_admin() then raise exception 'Administrator stock variance approval required';end if;select * into a from public.sc_adjustments where id=p_id for update;if not found or a.status<>'Pending' or a.created_by=auth.uid() then raise exception 'Separate approver required';end if;perform 1 from public.crm_catalog where id=a.item_id for update;select * into b from portal_private.supply_balance(a.item_id,a.location_id);if b.on_hand<>a.expected or a.counted<b.reserved then raise exception 'Stock changed or count is below reservations';end if;qty:=a.counted-b.on_hand;rate:=case when qty<0 then b.average_rate else a.rate end;
if qty<>0 then insert into public.sc_stock_ledger(item_id,location_id,quantity,rate,document_id,kind,actor_id) values(a.item_id,a.location_id,qty,rate,a.id,'Adjustment',auth.uid());end if;if qty>0 then update public.crm_catalog set last_rate=a.rate where id=a.item_id and last_rate=0;end if;update public.sc_adjustments set status='Posted',approved_by=auth.uid() where id=a.id;perform portal_private.supply_audit(null,'ADJ',a.id,'Approved and posted',a.note);end$$;
create function public.create_supply_issue(p_line uuid,p_location uuid,p_quantity numeric,p_recipient uuid,p_due date,p_serials text[]) returns uuid language plpgsql security definer set search_path='' as $$declare line public.sc_request_lines;req public.sc_requests;item public.crm_catalog;b record;held numeric;booked numeric;doc uuid;begin
if not portal_private.crm_permission('stock.manage') then raise exception 'Store issue permission required';end if;select * into line from public.sc_request_lines where id=p_line;req:=portal_private.supply_active_request(line.request_id);select * into line from public.sc_request_lines where id=p_line for update;select * into item from public.crm_catalog where id=line.item_id for update;
if req.status in ('Requested','Reserved / Sourcing','Cancelled') then raise exception 'Approved material request required';end if;
select quantity into held from public.sc_reservations where line_id=line.id and location_id=p_location;select coalesce(sum(quantity),0) into booked from public.sc_issues where line_id=line.id and location_id=p_location and status in ('Pending approval','Approved');select * into b from portal_private.supply_balance(item.id,p_location);
if p_quantity is null or p_quantity<=0 or p_quantity>coalesce(held,0)-booked or p_quantity>b.on_hand or item.tracking<>'Quantity' and p_quantity<>trunc(p_quantity) then raise exception 'Quantity exceeds unissued reservation';end if;
if item.tracking='Returnable' and (p_recipient is null or p_due is null) then raise exception 'Returnable tool needs accountable recipient and return date';end if;
if p_recipient is not null and not exists(select 1 from public.profiles u where u.id=p_recipient and u.active and (u.role='admin' or u.role='team' and (req.project_id is null or exists(select 1 from public.project_assignments a where a.project_id=req.project_id and a.technician_id=u.id) or exists(select 1 from public.tasks t where t.id=req.task_id and (t.assignee=u.id or u.id=any(t.collaborators)))))) then raise exception 'Active assigned recipient required';end if;
if p_serials is null or item.tracking='Serial' and (cardinality(p_serials)<>p_quantity or (select count(distinct s) from unnest(p_serials) s)<>cardinality(p_serials) or exists(select 1 from unnest(p_serials) s where not exists(select 1 from public.sc_serials where serial=s and item_id=item.id and location_id=p_location and status='In stock'))) or item.tracking<>'Serial' and cardinality(p_serials)<>0 then raise exception 'Select available serials matching issued quantity';end if;
insert into public.sc_issues(request_id,line_id,location_id,quantity,rate,total,recipient_id,return_due,serials,created_by) values(req.id,line.id,p_location,p_quantity,b.average_rate,round(p_quantity*b.average_rate,2),p_recipient,p_due,p_serials,auth.uid()) returning id into doc;perform portal_private.supply_audit(req.id,'MIN',doc,'Prepared');return doc;end$$;
create function public.supply_issue_action(p_issue uuid,p_version integer,p_action text,p_name text default '',p_consent boolean default false) returns void language plpgsql security definer set search_path='' as $$declare i public.sc_issues;req public.sc_requests;line public.sc_request_lines;b record;held numeric;begin
select * into i from public.sc_issues where id=p_issue;req:=portal_private.supply_active_request(i.request_id);select * into i from public.sc_issues where id=p_issue for update;if not found or i.version is distinct from p_version then raise exception 'Issue changed';end if;select * into line from public.sc_request_lines where id=i.line_id for update;
if p_action='Cancel' and i.status in ('Pending approval','Approved') and portal_private.crm_permission('stock.manage') and length(trim(coalesce(p_name,'')))>=3 then update public.sc_issues set status='Cancelled',version=version+1 where id=i.id;
elsif p_action='Approve' and i.status='Pending approval' and auth.uid()<>i.created_by and (public.is_admin() or portal_private.execution_manager(req.project_id) and i.total<=portal_private.supply_control('issue_admin_above')) then update public.sc_issues set status='Approved',approved_by=auth.uid(),version=version+1 where id=i.id;
elsif p_action='Post' and i.status='Approved' and portal_private.crm_permission('stock.manage') then
perform 1 from public.crm_catalog where id=line.item_id for update;select * into b from portal_private.supply_balance(line.item_id,i.location_id);select quantity into held from public.sc_reservations where line_id=line.id and location_id=i.location_id for update;
if coalesce(held,0)<i.quantity or b.on_hand<i.quantity or b.average_rate is distinct from i.rate then raise exception 'Reservation or stock valuation changed; prepare a new issue';end if;
if exists(select 1 from unnest(i.serials) s where not exists(select 1 from public.sc_serials where serial=s and item_id=line.item_id and location_id=i.location_id and status='In stock')) then raise exception 'Serials no longer available';end if;
insert into public.sc_stock_ledger(item_id,location_id,quantity,rate,project_id,request_id,document_id,kind,actor_id) values(line.item_id,i.location_id,-i.quantity,i.rate,req.project_id,req.id,i.id,'Issue',auth.uid());update public.sc_reservations set quantity=quantity-i.quantity where line_id=line.id and location_id=i.location_id;update public.sc_request_lines set reserved=reserved-i.quantity,issued=issued+i.quantity where id=line.id;update public.sc_serials set status='Issued',issue_id=i.id where item_id=line.item_id and serial=any(i.serials);update public.sc_issues set status='Posted',posted_at=now(),version=version+1 where id=i.id;update public.sc_requests set status='Issued',version=version+1 where id=req.id;
elsif p_action='Dispatch' and i.status='Posted' and portal_private.crm_permission('logistics.manage') then update public.sc_issues set status='In transit',challan_number='DC-'||lpad(nextval('public.sc_numbers')::text,6,'0'),outward_number='OGP-'||lpad(nextval('public.sc_numbers')::text,6,'0'),version=version+1 where id=i.id;
elsif p_action='Confirm delivery' and i.status='In transit' and public.is_staff() and (public.is_admin() or portal_private.execution_manager(req.project_id) or req.task_id is not null and portal_private.task_assigned(req.task_id) or portal_private.project_assigned(req.project_id) or i.recipient_id=auth.uid()) and p_consent is true and length(trim(coalesce(p_name,''))) between 2 and 150 then
update public.sc_issues set status='Delivered',receiver_id=auth.uid(),receiver_name=trim(p_name),delivered_at=now(),delivery_note='Received at site; consent recorded',version=version+1 where id=i.id;update public.sc_request_lines set delivered=delivered+i.quantity where id=line.id;update public.sc_requests set status=case when not exists(select 1 from public.sc_request_lines where request_id=req.id and delivered<quantity) then 'Closed' else 'Delivered' end,version=version+1 where id=req.id;
else raise exception 'Issue approval, posting or delivery action unavailable';end if;perform portal_private.supply_audit(req.id,'MIN',i.id,p_action);end$$;
-- The field receiving view contains no purchase rates or stock valuation.
create function public.supply_deliveries(p_request uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not portal_private.supply_request_access(p_request) then raise exception 'Assigned request required';end if;return coalesce((select jsonb_agg(jsonb_build_object('id',id,'number',number,'line_id',line_id,'quantity',quantity,'status',status,'version',version,'challan_number',challan_number,'outward_number',outward_number,'receiver_name',receiver_name,'delivered_at',delivered_at) order by number) from public.sc_issues where request_id=p_request),'[]'::jsonb);end$$;
create function public.return_supply_material(p_issue uuid,p_receipt uuid,p_location uuid,p_quantity numeric,p_note text,p_serials text[]) returns uuid language plpgsql security definer set search_path='' as $$declare i public.sc_issues;g public.sc_receipts;req public.sc_requests;line public.sc_request_lines;item public.crm_catalog;prior numeric;b record;rate numeric;doc uuid;kind text;begin
if not portal_private.crm_permission('stock.manage') or (p_issue is null)=(p_receipt is null) then raise exception 'Store and one source document required';end if;
if p_issue is not null then select * into i from public.sc_issues where id=p_issue;select * into req from public.sc_requests where id=i.request_id for update;select * into line from public.sc_request_lines where id=i.line_id for update;select coalesce(sum(quantity),0) into prior from public.sc_returns where issue_id=i.id;if i.status<>'Delivered' or p_quantity>i.quantity-prior then raise exception 'Return exceeds delivered issue';end if;rate:=i.rate;kind:='Site return';
else select * into g from public.sc_receipts where id=p_receipt;select * into req from public.sc_requests where id=g.request_id for update;select * into line from public.sc_request_lines where id=g.line_id for update;select coalesce(sum(quantity),0) into prior from public.sc_returns where receipt_id=g.id;if p_quantity>g.accepted-prior or p_location<>g.location_id then raise exception 'Return exceeds accepted source receipt';end if;kind:='Vendor return';end if;
select * into item from public.crm_catalog where id=line.item_id for update;if not found or p_quantity is null or p_quantity<=0 or p_quantity>100000 or item.tracking<>'Quantity' and p_quantity<>trunc(p_quantity) or not exists(select 1 from public.sc_locations where id=p_location and active) then raise exception 'Valid source and positive return quantity required';end if;
if kind='Vendor return' then select * into b from portal_private.supply_balance(item.id,p_location);if p_quantity>b.on_hand-b.reserved then raise exception 'Cannot return stock reserved for a request';end if;rate:=b.average_rate;end if;
if p_serials is null or item.tracking='Serial' and (cardinality(p_serials)<>p_quantity or (select count(distinct s) from unnest(p_serials) s)<>cardinality(p_serials) or exists(select 1 from unnest(p_serials) s where not exists(select 1 from public.sc_serials x where x.serial=s and x.item_id=item.id and case when kind='Site return' then x.issue_id=i.id and x.status='Issued' else x.receipt_id=g.id and x.status='In stock' and x.location_id=p_location end))) or item.tracking<>'Serial' and cardinality(p_serials)<>0 then raise exception 'Serials must match original source and return quantity';end if;
insert into public.sc_returns(number,request_id,line_id,issue_id,receipt_id,location_id,quantity,rate,kind,note,created_by) values((case when kind='Site return' then 'SRN-' else 'RTV-' end)||lpad(nextval('public.sc_numbers')::text,6,'0'),req.id,line.id,i.id,g.id,p_location,p_quantity,rate,kind,trim(p_note),auth.uid()) returning id into doc;
insert into public.sc_stock_ledger(item_id,location_id,quantity,rate,project_id,request_id,document_id,kind,actor_id) values(item.id,p_location,case when kind='Site return' then p_quantity else -p_quantity end,rate,case when kind='Site return' then req.project_id else null end,req.id,doc,kind,auth.uid());
if kind='Site return' then update public.sc_request_lines set returned=returned+p_quantity where id=line.id;update public.sc_serials set status='In stock',issue_id=null,location_id=p_location where item_id=item.id and serial=any(p_serials);else update public.sc_serials set status='Returned to vendor' where item_id=item.id and serial=any(p_serials);end if;
perform portal_private.supply_audit(req.id,case when kind='Site return' then 'SRN' else 'RTV' end,doc,'Posted',p_note);return doc;end$$;
create function public.cancel_supply_request(p_id uuid,p_version integer,p_note text) returns void language plpgsql security definer set search_path='' as $$declare req public.sc_requests;begin
req:=portal_private.supply_active_request(p_id);if req.version is distinct from p_version or req.status not in ('Requested','Reserved / Sourcing','Approved') or not (public.is_admin() or req.created_by=auth.uid() and portal_private.supply_request_access(p_id)) or length(trim(coalesce(p_note,'')))<3 or exists(select 1 from public.sc_orders where request_id=p_id and status<>'Cancelled') or exists(select 1 from public.sc_issues where request_id=p_id and status<>'Cancelled') then raise exception 'Cancellation unavailable; active documents must be resolved first';end if;
perform 1 from public.crm_catalog where id in (select item_id from public.sc_request_lines where request_id=p_id) order by id for update;
update public.sc_reservations set quantity=0 where line_id in (select id from public.sc_request_lines where request_id=p_id);update public.sc_request_lines set reserved=0 where request_id=p_id;update public.sc_requests set status='Cancelled',version=version+1 where id=p_id;perform portal_private.supply_audit(p_id,'MR',p_id,'Cancelled',p_note);end$$;
create function public.request_supply_boq(p_project uuid,p_site text,p_required_by date) returns uuid language plpgsql security definer set search_path='' as $$declare sale public.crm_sales;rows jsonb;doc uuid;begin
if not portal_private.execution_manager(p_project) then raise exception 'Assigned project manager required';end if;perform 1 from public.projects where id=p_project and status<>'Completed' for update;if not found then raise exception 'Active project required';end if;select id into doc from public.sc_requests where project_id=p_project and source='Accepted BOQ';if found then return doc;end if;select * into sale from public.crm_sales where project_id=p_project;if not found then raise exception 'Accepted sale budget required';end if;
if exists(select 1 from jsonb_array_elements(sale.planned_budget->'lines') x where x->>'block'='Material' and (nullif(x->>'catalog_id','') is null or not exists(select 1 from public.crm_catalog where id=(x->>'catalog_id')::uuid and active))) then raise exception 'Map all accepted material BOQ lines to active catalogue items before creating MR';end if;
select jsonb_agg(jsonb_build_object('item_id',item,'quantity',qty)) into rows from (select x->>'catalog_id' item,sum((x->>'quantity')::numeric) qty from jsonb_array_elements(sale.planned_budget->'lines') x where x->>'block'='Material' group by x->>'catalog_id') grouped;
doc:=public.create_supply_request(p_project,null,'Accepted BOQ material plan',p_site,p_required_by,rows);update public.sc_requests set source='Accepted BOQ' where id=doc;return doc;end$$;
-- Project closure waits for material custody and deliveries too.
create function portal_private.supply_close_guard() returns trigger language plpgsql security definer set search_path='' as $$begin
if new.status='Completed' and old.status<>'Completed' and (exists(select 1 from public.sc_requests where project_id=old.id and status not in ('Closed','Cancelled')) or exists(select 1 from public.sc_issues i join public.sc_request_lines l on l.id=i.line_id join public.crm_catalog c on c.id=l.item_id where i.request_id in (select id from public.sc_requests where project_id=old.id) and c.tracking='Returnable' and i.quantity>(select coalesce(sum(quantity),0) from public.sc_returns r where r.issue_id=i.id))) then raise exception 'Close material requests and check in returnable tools before project closure';end if;return new;end$$;
create trigger supply_close_guard before update on public.projects for each row execute function portal_private.supply_close_guard();
revoke all on function portal_private.supply_close_guard() from public,anon,authenticated;
do $$declare f record;begin for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('supply_staff','save_supply_controls','save_supply_master','supply_request_items','create_supply_request','supply_stock_report','check_supply_stock','approve_supply_request','add_supply_quote','create_supply_order','supply_order_action','receive_supply_order','create_supply_adjustment','post_supply_adjustment','create_supply_issue','supply_issue_action','supply_deliveries','transfer_supply_stock','return_supply_material','cancel_supply_request','request_supply_boq') loop execute format('revoke all on function %s from public,anon',f.sig);execute format('grant execute on function %s to authenticated',f.sig);end loop;end$$;
commit;
