begin;
insert into public.crm_settings(id,label,value) values('expense_categories','Expense categories','["Materials","Labor/Salaries","Subcontractor","Equipment","TADA","Software & Licenses","Insurance","Admin & Overhead","Rent & Utilities","Marketing & Bidding","Taxes & Fees","Other"]') on conflict(id) do nothing;
create table public.fin_expenses(id uuid primary key default gen_random_uuid(),number text not null unique default ('EXP-'||lpad(nextval('public.sc_numbers')::text,6,'0')),project_id uuid references public.projects,task_id uuid references public.tasks,category text not null check(length(trim(category)) between 1 and 100),description text not null check(length(trim(description)) between 3 and 2000),payee text not null check(length(trim(payee)) between 1 and 160),vendor_id uuid references public.sc_vendors,voucher text not null check(length(trim(voucher)) between 1 and 160),incurred_on date not null,due_on date not null check(due_on>=incurred_on),amount numeric(14,2) not null check(amount>0 and amount<100000000),evidence text not null check(length(trim(evidence)) between 3 and 2000),status text not null default 'Draft' check(status in ('Draft','Submitted','Approved','Rejected','Cancelled')),created_by uuid not null references public.profiles,approved_by uuid references public.profiles,approved_at timestamptz,created_at timestamptz not null default now(),version integer not null default 1,check(task_id is null or project_id is not null));
create unique index fin_expense_voucher on public.fin_expenses(lower(trim(payee)),lower(trim(voucher)));
create index fin_expense_project on public.fin_expenses(project_id);
create table public.fin_loans(id uuid primary key default gen_random_uuid(),number text not null unique default ('ADV-'||lpad(nextval('public.sc_numbers')::text,6,'0')),kind text not null check(kind in ('Loan','Staff advance')),direction text not null check(direction in ('Given','Taken')),counterparty text not null check(length(trim(counterparty)) between 1 and 160),staff_id uuid references public.profiles,project_id uuid references public.projects,agreement text not null unique check(length(trim(agreement)) between 1 and 160),principal numeric(14,2) not null check(principal>0 and principal<100000000),agreed_on date not null,due_on date not null check(due_on>=agreed_on),terms text not null check(length(trim(terms)) between 3 and 2000),evidence text not null check(length(trim(evidence)) between 3 and 2000),status text not null default 'Draft' check(status in ('Draft','Submitted','Approved','Rejected','Cancelled')),created_by uuid not null references public.profiles,approved_by uuid references public.profiles,approved_at timestamptz,created_at timestamptz not null default now(),version integer not null default 1,check((kind='Staff advance' and direction='Given' and staff_id is not null) or (kind='Loan' and staff_id is null)));
create unique index fin_agreement_normalized on public.fin_loans(lower(trim(agreement)));
create table public.fin_cash_entries(id uuid primary key default gen_random_uuid(),number text not null unique default ('FCASH-'||lpad(nextval('public.sc_numbers')::text,6,'0')),expense_id uuid references public.fin_expenses,loan_id uuid references public.fin_loans,kind text not null check(kind in ('Expense payment','Disbursement','Repayment')),direction text not null check(direction in ('In','Out')),amount numeric(14,2) not null check(amount>0 and amount<100000000),paid_on date not null,method text not null check(method in ('Cash','Bank transfer','Cheque','Mobile wallet')),reference text not null check(length(trim(reference)) between 1 and 160),evidence text not null check(length(trim(evidence)) between 3 and 2000),created_by uuid not null references public.profiles,created_at timestamptz not null default now(),reversed_by uuid references public.profiles,reversed_at timestamptz,reversal_reason text check(length(trim(reversal_reason)) between 3 and 2000),check((expense_id is null)<>(loan_id is null)),check((kind='Expense payment' and expense_id is not null and direction='Out') or (kind in ('Disbursement','Repayment') and loan_id is not null)),check((reversed_by is null)=(reversed_at is null)),check((reversed_by is null)=(reversal_reason is null)));
create unique index fin_cash_reference on public.fin_cash_entries(coalesce(expense_id,loan_id),kind,method,lower(trim(reference)));
create index fin_cash_loan on public.fin_cash_entries(loan_id);
create index fin_cash_expense on public.fin_cash_entries(expense_id);
create table public.fin_history(id uuid primary key default gen_random_uuid(),expense_id uuid references public.fin_expenses,loan_id uuid references public.fin_loans,action text not null,note text not null,actor_id uuid not null references public.profiles,created_at timestamptz not null default now(),check((expense_id is null)<>(loan_id is null)));
create table public.fin_invoice_projects(id uuid primary key references public.invoices,project_id uuid not null references public.projects,linked_by uuid not null references public.profiles,linked_at timestamptz not null default now());
create index fin_invoice_project on public.fin_invoice_projects(project_id);
create function portal_private.expense_scope(p_project uuid,p_task uuid) returns boolean language sql stable security definer set search_path='' as $$select portal_private.payables_access() or public.is_staff() and p_project is not null and public.can_project(p_project) and (portal_private.execution_manager(p_project) or (p_task is null and portal_private.project_assigned(p_project)) or (p_task is not null and portal_private.task_assigned(p_task) and exists(select 1 from public.tasks where id=p_task and project_id=p_project)));$$;
create function portal_private.expense_read(p_expense uuid) returns boolean language sql stable security definer set search_path='' as $$select portal_private.payables_access() or exists(select 1 from public.fin_expenses e where e.id=p_expense and (portal_private.execution_manager(e.project_id) or e.created_by=auth.uid() and portal_private.expense_scope(e.project_id,e.task_id)));$$;
create function portal_private.finance_audit(p_expense uuid,p_loan uuid,p_action text,p_note text) returns void language sql security definer set search_path='' as $$insert into public.fin_history(expense_id,loan_id,action,note,actor_id) values(p_expense,p_loan,p_action,p_note,auth.uid());$$;
create function portal_private.finance_project_currency(p_project uuid) returns text language sql stable security definer set search_path='' as $$select coalesce((select currency from public.crm_sales where project_id=p_project),(select currency from public.client_orders where project_id=p_project order by created_at limit 1),'PKR');$$;
create function portal_private.finance_project_check(p_project uuid) returns void language plpgsql security definer set search_path='' as $$begin if p_project is not null then perform 1 from public.projects where id=p_project for share;if not found or portal_private.finance_project_currency(p_project)<>'PKR' then raise exception 'Existing PKR project required';end if;end if;end$$;
create function portal_private.finance_lock(p_kind text,p_id uuid,p_version integer) returns void language plpgsql security definer set search_path='' as $$declare v integer;begin if p_kind='Expense' then select version into v from public.fin_expenses where id=p_id for update;elsif p_kind='Loan' then select version into v from public.fin_loans where id=p_id for update;else raise exception 'Unsupported ledger';end if;if v is null or v is distinct from p_version then raise exception 'Record changed or unavailable. Refresh first';end if;end$$;
do $$declare t text;begin foreach t in array array['fin_expenses','fin_loans','fin_cash_entries','fin_history','fin_invoice_projects'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;
create policy expense_read on public.fin_expenses for select to authenticated using(portal_private.expense_read(id));
create policy loan_read on public.fin_loans for select to authenticated using(portal_private.payables_access());
create policy finance_cash_read on public.fin_cash_entries for select to authenticated using(portal_private.payables_access());
create policy finance_history_read on public.fin_history for select to authenticated using(portal_private.payables_access() or expense_id is not null and portal_private.expense_read(expense_id));
create policy invoice_project_read on public.fin_invoice_projects for select to authenticated using(portal_private.payables_access() or portal_private.execution_manager(project_id));
create policy finance_category_read on public.crm_settings for select to authenticated using(id='expense_categories' and public.is_staff());
revoke all on function portal_private.expense_scope(uuid,uuid),portal_private.expense_read(uuid),portal_private.finance_audit(uuid,uuid,text,text),portal_private.finance_project_check(uuid),portal_private.finance_project_currency(uuid),portal_private.finance_lock(text,uuid,integer) from public,anon,authenticated;
grant execute on function portal_private.expense_read(uuid) to authenticated;

create function public.save_finance_expense(p_id uuid,p_version integer,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare e public.fin_expenses;project uuid:=nullif(p_data->>'project_id','')::uuid;task uuid:=nullif(p_data->>'task_id','')::uuid;vendor uuid:=nullif(p_data->>'vendor_id','')::uuid;n numeric:=(p_data->>'amount')::numeric;doc uuid;begin
 if not portal_private.expense_scope(project,task) then raise exception 'Accounts or assigned work access required';end if;
 if p_id is not null then perform portal_private.finance_lock('Expense',p_id,p_version);select * into e from public.fin_expenses where id=p_id;if e.status not in ('Draft','Rejected') or not portal_private.expense_read(p_id) or (e.created_by<>auth.uid() and not portal_private.payables_access()) or e.project_id is distinct from project or e.task_id is distinct from task then raise exception 'Only your draft/rejected expense on the original work scope can be revised';end if;end if;
 perform portal_private.finance_project_check(project);
 if task is not null and not exists(select 1 from public.tasks where id=task and project_id=project) then raise exception 'Task must belong to selected project';end if;
 if n is null or n<=0 or n>=100000000 or n<>round(n,2) or not exists(select 1 from public.crm_settings s cross join lateral jsonb_array_elements_text(s.value) cat where s.id='expense_categories' and cat=p_data->>'category') then raise exception 'Positive two-decimal amount and configured expense category required';end if;
 if (p_data->>'incurred_on')::date is null or not isfinite((p_data->>'incurred_on')::date) or (p_data->>'incurred_on')::date>(now() at time zone 'Asia/Karachi')::date or (p_data->>'due_on')::date is null or not isfinite((p_data->>'due_on')::date) then raise exception 'Valid dates required; expense cannot be future dated';end if;
 if vendor is not null and not portal_private.payables_access() then raise exception 'Accounts chooses vendor-linked expense records';end if;
 if vendor is not null then perform 1 from public.sc_vendors where id=vendor for update;end if;
 if vendor is not null and (not exists(select 1 from public.sc_vendors where id=vendor) or exists(select 1 from public.sc_bills where vendor_id=vendor and lower(trim(vendor_invoice))=lower(trim(p_data->>'voucher')))) then raise exception 'Vendor unavailable or invoice already recorded in purchase bills';end if;
 if p_id is null then insert into public.fin_expenses(project_id,task_id,category,description,payee,vendor_id,voucher,incurred_on,due_on,amount,evidence,created_by) values(project,task,p_data->>'category',trim(p_data->>'description'),trim(p_data->>'payee'),vendor,trim(p_data->>'voucher'),(p_data->>'incurred_on')::date,(p_data->>'due_on')::date,n,trim(p_data->>'evidence'),auth.uid()) returning id into doc;
 else update public.fin_expenses set category=p_data->>'category',description=trim(p_data->>'description'),payee=trim(p_data->>'payee'),vendor_id=vendor,voucher=trim(p_data->>'voucher'),incurred_on=(p_data->>'incurred_on')::date,due_on=(p_data->>'due_on')::date,amount=n,evidence=trim(p_data->>'evidence'),status='Draft',version=version+1 where id=e.id returning id into doc;end if;
 perform portal_private.finance_audit(doc,null,case when p_id is null then 'Created' else 'Revised' end,trim(p_data->>'description'));return doc;end$$;
-- Serialize vendor invoice duplicate checks across expense and purchasing entry points.
create function portal_private.finance_bill_duplicate_guard() returns trigger language plpgsql security definer set search_path='' as $$begin
 perform 1 from public.sc_vendors where id=new.vendor_id for update;
 if exists(select 1 from public.fin_expenses where vendor_id=new.vendor_id and lower(trim(voucher))=lower(trim(new.vendor_invoice)) and status<>'Cancelled') then raise exception 'Vendor invoice already recorded as an expense; cancel unpaid expense before purchase billing';end if;return new;end$$;
create trigger finance_bill_duplicate_guard before insert or update of vendor_invoice,vendor_id on public.sc_bills for each row execute function portal_private.finance_bill_duplicate_guard();
revoke all on function portal_private.finance_bill_duplicate_guard() from public,anon,authenticated;
create function public.save_finance_loan(p_id uuid,p_version integer,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare l public.fin_loans;project uuid:=nullif(p_data->>'project_id','')::uuid;staff uuid:=nullif(p_data->>'staff_id','')::uuid;n numeric:=(p_data->>'principal')::numeric;doc uuid;name text;begin
 if not portal_private.payables_access() then raise exception 'Accounts access required';end if;
 if p_id is not null then perform portal_private.finance_lock('Loan',p_id,p_version);select * into l from public.fin_loans where id=p_id;if l.status not in ('Draft','Rejected') or l.project_id is distinct from project then raise exception 'Only draft/rejected agreement on original project can be revised';end if;end if;
 perform portal_private.finance_project_check(project);
 if n is null or n<=0 or n>=100000000 or n<>round(n,2) or (p_data->>'agreed_on')::date is null or not isfinite((p_data->>'agreed_on')::date) or (p_data->>'agreed_on')::date>(now() at time zone 'Asia/Karachi')::date or (p_data->>'due_on')::date is null or not isfinite((p_data->>'due_on')::date) then raise exception 'Valid positive principal and agreement dates required';end if;
 if p_data->>'kind'='Staff advance' then select p.name into name from public.profiles p where p.id=staff and p.active and p.role in ('admin','team');if not found then raise exception 'Active staff recipient required';end if;else name:=trim(p_data->>'counterparty');end if;
 if p_id is null then insert into public.fin_loans(kind,direction,counterparty,staff_id,project_id,agreement,principal,agreed_on,due_on,terms,evidence,created_by) values(p_data->>'kind',p_data->>'direction',name,staff,project,trim(p_data->>'agreement'),n,(p_data->>'agreed_on')::date,(p_data->>'due_on')::date,trim(p_data->>'terms'),trim(p_data->>'evidence'),auth.uid()) returning id into doc;
 else update public.fin_loans set kind=p_data->>'kind',direction=p_data->>'direction',counterparty=name,staff_id=staff,agreement=trim(p_data->>'agreement'),principal=n,agreed_on=(p_data->>'agreed_on')::date,due_on=(p_data->>'due_on')::date,terms=trim(p_data->>'terms'),evidence=trim(p_data->>'evidence'),status='Draft',version=version+1 where id=l.id returning id into doc;end if;
 perform portal_private.finance_audit(null,doc,case when p_id is null then 'Created' else 'Revised' end,trim(p_data->>'agreement'));return doc;end$$;
create function public.finance_ledger_action(p_kind text,p_id uuid,p_version integer,p_action text,p_note text default '') returns void language plpgsql security definer set search_path='' as $$declare s text;creator uuid;begin
 if p_kind='Expense' then if not portal_private.expense_read(p_id) then raise exception 'Expense access required';end if;else if not portal_private.payables_access() then raise exception 'Accounts access required';end if;end if;
 perform portal_private.finance_lock(p_kind,p_id,p_version);
 if p_kind='Expense' then select status,created_by into s,creator from public.fin_expenses where id=p_id;else select status,created_by into s,creator from public.fin_loans where id=p_id;end if;
 if p_action='Submit' then if s not in ('Draft','Rejected') or (creator<>auth.uid() and not portal_private.payables_access()) then raise exception 'Draft/rejected record required';end if;s:='Submitted';
 elsif p_action in ('Approve','Reject') then if not public.is_admin() or s<>'Submitted' or creator=auth.uid() or length(trim(coalesce(p_note,'')))<3 then raise exception 'Separate administrator, submitted record and reason required';end if;s:=case when p_action='Approve' then 'Approved' else 'Rejected' end;
 elsif p_action='Cancel' then if s='Cancelled' or length(trim(coalesce(p_note,'')))<3 or (s='Approved' and not public.is_admin()) or (creator<>auth.uid() and not portal_private.payables_access()) or exists(select 1 from public.fin_cash_entries where (expense_id=p_id or loan_id=p_id) and reversed_by is null) then raise exception 'Authorized unpaid/undisbursed record and reason required';end if;s:='Cancelled';
 else raise exception 'Unsupported ledger action';end if;
 if p_kind='Expense' then update public.fin_expenses set status=s,approved_by=case when s='Approved' then auth.uid() else null end,approved_at=case when s='Approved' then now() else null end,version=version+1 where id=p_id;else update public.fin_loans set status=s,approved_by=case when s='Approved' then auth.uid() else null end,approved_at=case when s='Approved' then now() else null end,version=version+1 where id=p_id;end if;
 perform portal_private.finance_audit(case when p_kind='Expense' then p_id end,case when p_kind='Loan' then p_id end,p_action,coalesce(p_note,''));end$$;

create function public.record_finance_cash(p_kind text,p_id uuid,p_version integer,p_action text,p_amount numeric,p_date date,p_method text,p_reference text,p_evidence text) returns uuid language plpgsql security definer set search_path='' as $$declare e public.fin_expenses;l public.fin_loans;disbursed numeric;repaid numeric;paid numeric;direction text;doc uuid;begin
 if not portal_private.payables_access() then raise exception 'Accounts access required';end if;perform portal_private.finance_lock(p_kind,p_id,p_version);
 if p_amount is null or p_amount<=0 or p_amount>=100000000 or p_amount<>round(p_amount,2) or p_date is null or not isfinite(p_date) or p_date>(now() at time zone 'Asia/Karachi')::date then raise exception 'Valid positive two-decimal amount and cash date required';end if;
 if p_kind='Expense' then
 select * into e from public.fin_expenses where id=p_id;if e.status<>'Approved' or e.approved_by is null or e.approved_by=auth.uid() or p_action<>'Expense payment' or p_date<e.incurred_on then raise exception 'Separately approved expense and valid payment action/date required';end if;
 select coalesce(sum(amount),0) into paid from public.fin_cash_entries where expense_id=e.id and reversed_by is null;if p_amount>e.amount-paid then raise exception 'Payment exceeds expense outstanding';end if;direction:='Out';
 else
 select * into l from public.fin_loans where id=p_id;if l.status<>'Approved' or l.approved_by is null or l.approved_by=auth.uid() or p_action not in ('Disbursement','Repayment') or p_date<l.agreed_on or p_date<coalesce((select max(paid_on) from public.fin_cash_entries where loan_id=l.id and reversed_by is null),l.agreed_on) then raise exception 'Separately approved agreement and chronological cash date required';end if;
 select coalesce(sum(amount) filter(where kind='Disbursement'),0),coalesce(sum(amount) filter(where kind='Repayment'),0) into disbursed,repaid from public.fin_cash_entries where loan_id=l.id and reversed_by is null;
 if p_action='Disbursement' and p_amount>l.principal-disbursed or p_action='Repayment' and p_amount>disbursed-repaid then raise exception 'Movement exceeds remaining principal or outstanding balance';end if;
 direction:=case when (l.direction='Given' and p_action='Disbursement') or (l.direction='Taken' and p_action='Repayment') then 'Out' else 'In' end;
 end if;
 insert into public.fin_cash_entries(expense_id,loan_id,kind,direction,amount,paid_on,method,reference,evidence,created_by) values(e.id,l.id,p_action,direction,p_amount,p_date,p_method,trim(p_reference),trim(p_evidence),auth.uid()) returning id into doc;
 if p_kind='Expense' then update public.fin_expenses set version=version+1 where id=e.id;else update public.fin_loans set version=version+1 where id=l.id;end if;perform portal_private.finance_audit(e.id,l.id,p_action,p_amount::text||' PKR · '||direction||' · '||trim(p_reference));return doc;end$$;
create function public.reverse_finance_cash(p_id uuid,p_version integer,p_reason text) returns void language plpgsql security definer set search_path='' as $$declare c public.fin_cash_entries;disbursed numeric;repaid numeric;begin
 if not public.is_admin() then raise exception 'Administrator required';end if;select * into c from public.fin_cash_entries where id=p_id;if not found then raise exception 'Cash record unavailable';end if;perform portal_private.finance_lock(case when c.expense_id is not null then 'Expense' else 'Loan' end,coalesce(c.expense_id,c.loan_id),p_version);
 select * into c from public.fin_cash_entries where id=p_id for update;if c.reversed_by is not null or c.created_by=auth.uid() or length(trim(coalesce(p_reason,'')))<3 then raise exception 'Separate administrator and reversal reason required';end if;
 if c.loan_id is not null then select coalesce(sum(amount) filter(where kind='Disbursement'),0),coalesce(sum(amount) filter(where kind='Repayment'),0) into disbursed,repaid from public.fin_cash_entries where loan_id=c.loan_id and reversed_by is null and id<>c.id;if repaid>disbursed or exists(select 1 from (select sum(case when kind='Disbursement' then amount else -amount end) over(order by paid_on,number) running from public.fin_cash_entries where loan_id=c.loan_id and reversed_by is null and id<>c.id) balances where running<0) then raise exception 'Reverse repayments before reversing their disbursement';end if;end if;
 update public.fin_cash_entries set reversed_by=auth.uid(),reversed_at=now(),reversal_reason=trim(p_reason) where id=c.id;
 if c.expense_id is not null then update public.fin_expenses set version=version+1 where id=c.expense_id;else update public.fin_loans set version=version+1 where id=c.loan_id;end if;perform portal_private.finance_audit(c.expense_id,c.loan_id,'Cash reversed',c.number||' · '||trim(p_reason));end$$;
create function public.finance_projects() returns table(id uuid,title text,company text,currency text) language plpgsql stable security definer set search_path='' as $$begin if not public.is_staff() then raise exception 'Staff access required';end if;return query select p.id,p.title,c.name,portal_private.finance_project_currency(p.id) from public.projects p join public.companies c on c.id=p.company_id left join public.crm_sales s on s.project_id=p.id where portal_private.payables_access() or public.can_project(p.id) order by p.title;end$$;
create function public.finance_staff() returns table(id uuid,name text) language plpgsql stable security definer set search_path='' as $$begin if not portal_private.payables_access() then raise exception 'Accounts access required';end if;return query select p.id,p.name from public.profiles p where p.active and p.role in ('admin','team') order by p.name;end$$;
create function public.finance_ledger_report(p_kind text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare result jsonb;begin
 if not public.is_staff() or p_kind not in ('Expense','Loan') or p_kind='Loan' and not portal_private.payables_access() then raise exception 'Ledger access required';end if;
 if p_kind='Expense' then select coalesce(jsonb_agg(to_jsonb(e)||jsonb_build_object('project',coalesce(p.title,'Office'),'paid',coalesce(c.paid,0),'balance',case when e.status='Approved' then e.amount-coalesce(c.paid,0) else 0 end,'payment_status',case when e.status<>'Approved' then e.status when e.amount=coalesce(c.paid,0) then 'Paid' when coalesce(c.paid,0)>0 then 'Partially paid' else 'Unpaid' end,'days_overdue',case when e.status='Approved' and e.amount>coalesce(c.paid,0) then greatest(0,(now() at time zone 'Asia/Karachi')::date-e.due_on) else 0 end) order by e.due_on,e.number),'[]') into result from public.fin_expenses e left join public.projects p on p.id=e.project_id left join lateral(select sum(amount) paid from public.fin_cash_entries where expense_id=e.id and reversed_by is null)c on true where portal_private.expense_read(e.id);
 else select coalesce(jsonb_agg(to_jsonb(l)||jsonb_build_object('project',coalesce(p.title,'Office'),'disbursed',coalesce(c.disbursed,0),'repaid',coalesce(c.repaid,0),'balance',coalesce(c.disbursed,0)-coalesce(c.repaid,0),'undisbursed',case when l.status='Approved' then l.principal-coalesce(c.disbursed,0) else 0 end,'days_overdue',case when l.status='Approved' and coalesce(c.disbursed,0)>coalesce(c.repaid,0) then greatest(0,(now() at time zone 'Asia/Karachi')::date-l.due_on) else 0 end) order by l.due_on,l.number),'[]') into result from public.fin_loans l left join public.projects p on p.id=l.project_id left join lateral(select sum(amount) filter(where kind='Disbursement') disbursed,sum(amount) filter(where kind='Repayment') repaid from public.fin_cash_entries where loan_id=l.id and reversed_by is null)c on true;end if;return result;end$$;
create function portal_private.finance_invoice_links() returns table(invoice_id uuid,project_id uuid) language sql stable security definer set search_path='' as $$with links as(select id invoice_id,project_id from public.fin_invoice_projects union select invoice_id,project_id from public.crm_sales where project_id is not null union select invoice_id,project_id from public.client_orders where project_id is not null and invoice_id is not null) select * from links union select r.invoice_id,l.project_id from public.invoice_schedule_runs r join public.invoice_schedules s on s.id=r.schedule_id join links l on l.invoice_id=s.source_invoice;$$;
revoke all on function portal_private.finance_invoice_links() from public,anon,authenticated;
create function public.link_finance_invoice(p_invoice uuid,p_project uuid) returns void language plpgsql security definer set search_path='' as $$declare company uuid;begin
 if not portal_private.payables_access() then raise exception 'Accounts access required';end if;perform 1 from public.invoices where id=p_invoice for update;if not found then raise exception 'Invoice unavailable';end if;
 select company_id into company from public.projects where id=p_project;if not found or not exists(select 1 from public.invoices where id=p_invoice and company_id=company and currency=portal_private.finance_project_currency(p_project)) then raise exception 'Invoice must belong to the project customer and currency';end if;
 if exists(select 1 from portal_private.finance_invoice_links() where invoice_id=p_invoice and project_id<>p_project) then raise exception 'Invoice already linked to another project';end if;
 insert into public.fin_invoice_projects(id,project_id,linked_by) values(p_invoice,p_project,auth.uid()) on conflict(id) do nothing;end$$;
create function public.finance_invoices() returns table(id uuid,number text,company text,currency text,status text,total numeric,project_id uuid) language plpgsql stable security definer set search_path='' as $$begin if not portal_private.payables_access() then raise exception 'Accounts access required';end if;return query select i.id,i.number,i.company_name,i.currency,i.status,i.total,l.project_id from public.invoices i left join portal_private.finance_invoice_links() l on l.invoice_id=i.id order by i.issued_on desc,i.number;end$$;

create function public.project_financials(p_project uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare p public.projects;s public.crm_sales;planned numeric;contract_net numeric;material numeric;expenses numeric;recorded numeric;purchased numeric;billed numeric;paid_vendor numeric;paid_expense numeric;loan_out numeric;loan_in numeric;invoiced numeric;received numeric;credited numeric;outstanding numeric;categories jsonb;begin
 if p_project is null or not (portal_private.payables_access() or portal_private.execution_manager(p_project)) then raise exception 'Accounts or assigned project manager required';end if;
 select * into p from public.projects where id=p_project;if not found then raise exception 'Project unavailable';end if;select * into s from public.crm_sales where project_id=p.id;
 if portal_private.finance_project_currency(p.id)<>'PKR' then raise exception 'PKR project financials only; foreign-currency costs need separate reporting';end if;
 planned:=coalesce((s.planned_budget->'calculation'->>'cost')::numeric,(select sum(round((x->>'quantity')::numeric*(x->>'unit_cost')::numeric,2)) from jsonb_array_elements(s.planned_budget->'lines') x));
 contract_net:=coalesce((s.planned_budget->'calculation'->>'subtotal')::numeric,(select subtotal from public.crm_quote_publications where id=s.publication_id));
 select round(coalesce(sum(-l.quantity*l.rate),0),2) into material from public.sc_stock_ledger l join public.crm_catalog c on c.id=l.item_id where l.project_id=p.id and l.kind in ('Issue','Site return') and c.tracking<>'Returnable';
 select coalesce(sum(amount),0) into expenses from public.fin_expenses where project_id=p.id and status='Approved';recorded:=material+expenses;
 select coalesce(sum(o.total),0) into purchased from public.sc_orders o join public.sc_requests r on r.id=o.request_id where r.project_id=p.id and o.approved_by is not null and o.status<>'Cancelled';
 select coalesce(sum(total),0) into billed from public.sc_bills where project_id=p.id and status='Approved';
 select coalesce(sum(v.amount),0) into paid_vendor from public.sc_vendor_payments v join public.sc_bills b on b.id=v.bill_id where b.project_id=p.id and v.reversed_by is null;
 select coalesce(sum(c.amount),0) into paid_expense from public.fin_cash_entries c join public.fin_expenses e on e.id=c.expense_id where e.project_id=p.id and c.reversed_by is null;
 select coalesce(sum(c.amount) filter(where c.direction='Out'),0),coalesce(sum(c.amount) filter(where c.direction='In'),0) into loan_out,loan_in from public.fin_cash_entries c join public.fin_loans l on l.id=c.loan_id where l.project_id=p.id and c.reversed_by is null;
 select coalesce(sum(i.total),0),coalesce(sum(c.paid),0),coalesce(sum(c.credit),0),coalesce(sum(greatest(0,i.total-coalesce(c.paid,0)-coalesce(c.credit,0))),0) into invoiced,received,credited,outstanding from public.invoices i join portal_private.finance_invoice_links() links on links.invoice_id=i.id left join lateral(select (select coalesce(sum(amount),0) from public.payment_claims where invoice_id=i.id and status='Verified') paid,(select coalesce(sum(amount),0) from public.credit_notes where invoice_id=i.id and status='Issued') credit)c on true where links.project_id=p.id and i.status='Issued' and i.currency='PKR';
 select coalesce(jsonb_agg(jsonb_build_object('category',cat,'approved_expenses',expense_cost,'issued_material',stock_cost,'recorded_cost',expense_cost+stock_cost) order by cat),'[]') into categories from (select cat,coalesce((select sum(e.amount) from public.fin_expenses e where e.project_id=p.id and e.status='Approved' and e.category=cat),0) expense_cost,case when cat='Materials' then material else 0 end stock_cost from (select distinct category cat from public.fin_expenses where project_id=p.id and status='Approved' union select 'Materials') names) costs;
 return jsonb_build_object('project_id',p.id,'project',p.title,'company',(select name from public.companies where id=p.company_id),'status',p.status,'start_date',p.start_date,'deadline',p.deadline,'closed_at',p.closed_at,'currency','PKR','contract_value',s.total,'contract_net',contract_net,'invoiced',invoiced,'received',received,'credited',credited,'outstanding',outstanding,'yet_to_invoice',case when s.id is not null then greatest(0,s.total-invoiced) end,'planned_cost',planned,'planned_material',case when s.id is not null then (select coalesce(sum(round((x->>'quantity')::numeric*(x->>'unit_cost')::numeric,2)),0) from jsonb_array_elements(s.planned_budget->'lines') x where x->>'block'='Material') end,'planned_labour',case when s.id is not null then (select coalesce(sum(round((x->>'quantity')::numeric*(x->>'unit_cost')::numeric,2)),0) from jsonb_array_elements(s.planned_budget->'lines') x where x->>'block'='Labour') end,'material_issued_net',material,'approved_expenses',expenses,'recorded_cost',recorded,'remaining_against_recorded',planned-recorded,'recorded_utilisation_percent',case when planned>0 then round(recorded/planned*100,2) end,'planned_profit',contract_net-planned,'profit_before_unrecorded_costs',contract_net-recorded,'margin_before_unrecorded_costs',case when contract_net>0 then round((contract_net-recorded)/contract_net*100,2) end,'purchases_committed',purchased,'vendor_bills_approved',billed,'supplier_cash_out',paid_vendor,'expense_cash_out',paid_expense,'loan_cash_out',loan_out,'loan_cash_in',loan_in,'operating_cash_position',received-paid_vendor-paid_expense,'cash_position_including_loans',received-paid_vendor-paid_expense-loan_out+loan_in,'days_delayed',case when p.deadline is not null and not(p.status='Completed' and p.closed_at is null) then greatest(0,coalesce((p.closed_at at time zone 'Asia/Karachi')::date,(now() at time zone 'Asia/Karachi')::date)-p.deadline) else null end,'categories',categories,'cost_complete',false,'labour_hours_pending',true,'note','Material cost is net issues minus site returns, excluding returnable tool custody. Vendor material bills are purchase liabilities and not added again. Approved expenses are additional non-inventory costs. Hourly labour, unrecorded costs, tax treatment and budget revisions remain pending; profitability is provisional.');
 end$$;

create function public.finance_dashboard() returns jsonb language plpgsql stable security definer set search_path='' as $$declare receivables jsonb;cash jsonb;expense_due numeric;vendor_due numeric;given numeric;taken numeric;pkr_due numeric;begin
 if not portal_private.payables_access() then raise exception 'Accounts access required';end if;
 select coalesce(jsonb_agg(to_jsonb(t)),'[]') into receivables from (select i.currency,sum(i.total) invoiced,sum(c.paid) received,sum(c.credit) credits,sum(greatest(0,i.total-c.paid-c.credit)) outstanding,sum(case when i.due_on<(now() at time zone 'Asia/Karachi')::date then greatest(0,i.total-c.paid-c.credit) else 0 end) overdue from public.invoices i cross join lateral(select (select coalesce(sum(amount),0) from public.payment_claims where invoice_id=i.id and status='Verified') paid,(select coalesce(sum(amount),0) from public.credit_notes where invoice_id=i.id and status='Issued') credit)c where i.status='Issued' group by i.currency order by i.currency)t;
 select coalesce(sum((r->>'balance')::numeric),0) into expense_due from jsonb_array_elements(public.finance_ledger_report('Expense')) r where r->>'status'='Approved';
 select coalesce(sum(balance),0) into vendor_due from public.vendor_payables_report() where approval_status='Approved';
 select coalesce(sum((r->>'balance')::numeric) filter(where r->>'direction'='Given'),0),coalesce(sum((r->>'balance')::numeric) filter(where r->>'direction'='Taken'),0) into given,taken from jsonb_array_elements(public.finance_ledger_report('Loan')) r where r->>'status'='Approved';
 select coalesce(sum((r->>'outstanding')::numeric),0) into pkr_due from jsonb_array_elements(receivables) r where r->>'currency'='PKR';
 select coalesce(jsonb_agg(to_jsonb(t) order by t.month_key desc,t.currency),'[]') into cash from (select month_key,currency,sum(amount) filter(where kind='Customer receipts') customer_in,sum(amount) filter(where kind='Supplier payments') supplier_out,sum(amount) filter(where kind='Expense payments') expense_out,sum(amount) filter(where kind='Loan in') loan_in,sum(amount) filter(where kind='Loan out') loan_out from (
 select to_char(c.paid_on,'YYYY-MM') as month_key,i.currency,c.amount,'Customer receipts' kind from public.payment_claims c join public.invoices i on i.id=c.invoice_id where c.status='Verified'
 union all select to_char(payment_date,'YYYY-MM'),'PKR',amount,'Supplier payments' from public.sc_vendor_payments where reversed_by is null
 union all select to_char(paid_on,'YYYY-MM'),'PKR',amount,case when expense_id is not null then 'Expense payments' when direction='In' then 'Loan in' else 'Loan out' end from public.fin_cash_entries where reversed_by is null
 ) movements group by month_key,currency)t;
 return jsonb_build_object('receivables',receivables,'expense_payables',expense_due,'vendor_payables',vendor_due,'approved_payables',expense_due+vendor_due,'pkr_net_trade_position',pkr_due-expense_due-vendor_due,'loans_given_outstanding',given,'loans_taken_outstanding',taken,'cash_by_month',cash,'business_date',(now() at time zone 'Asia/Karachi')::date,'note','Trade position excludes loans and advances. Cash movements are records of payments already made; reversed records are excluded. Each currency is reported separately.');end$$;
do $$declare f record;begin for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('save_finance_expense','save_finance_loan','finance_ledger_action','record_finance_cash','reverse_finance_cash','finance_projects','finance_staff','finance_ledger_report','link_finance_invoice','finance_invoices','project_financials','finance_dashboard') loop execute format('revoke all on function %s from public,anon',f.sig);execute format('grant execute on function %s to authenticated',f.sig);end loop;end$$;
commit;
