begin;
create table public.work_activities(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,
 link_kind text not null check(link_kind in ('Project','Ticket','Deal','Internal')),project_id uuid references public.projects,task_id uuid references public.tasks,ticket_id uuid references public.tickets,deal_id uuid references public.crm_deals,
 location text not null check(length(trim(location)) between 1 and 300),activity_type text not null check(activity_type in ('Installation','Survey','Complaint','Purchase / pickup','Meeting','Training','Office work','Travel')),
 description text not null check(length(trim(description)) between 1 and 2000),given_by uuid references public.profiles,
 planned_start timestamptz,planned_end timestamptz,actual_start timestamptz not null,actual_end timestamptz not null,
 outcome text not null check(outcome in ('Done','Partly done','Not done','Rescheduled')),quantity numeric(14,3) not null default 0 check(quantity>=0),crew integer not null default 1 check(crew between 1 and 100),
 delay_reason text not null default '',delay_note text not null default '' check(length(delay_note)<=2000),lost_minutes integer not null default 0 check(lost_minutes>=0),blocker text not null default '' check(length(blocker)<=2000),remarks text not null default '' check(length(remarks)<=2000),evidence text not null default '' check(length(evidence)<=2000),
 status text not null default 'Draft' check(status in ('Draft','Submitted','Rejected','Approved','Voided')),reviewed_by uuid references public.profiles,reviewed_at timestamptz,version integer not null default 1,created_at timestamptz not null default now(),
 check(actual_end>actual_start and actual_end-actual_start<=interval '16 hours'),check((planned_start is null and planned_end is null) or (planned_start is not null and planned_end is not null and planned_end>planned_start and planned_end-planned_start<=interval '16 hours')),
 check(lost_minutes<=extract(epoch from actual_end-actual_start)/60),
 check((link_kind='Internal' and project_id is null and task_id is null and ticket_id is null and deal_id is null) or (link_kind='Project' and project_id is not null and ticket_id is null and deal_id is null) or (link_kind='Ticket' and project_id is not null and ticket_id is not null and deal_id is null) or (link_kind='Deal' and deal_id is not null and project_id is null and task_id is null and ticket_id is null))
);
create index work_activity_user_time on public.work_activities(user_id,actual_start,actual_end);
create index work_activity_project on public.work_activities(project_id,status);
create table public.work_activity_history(id uuid primary key default gen_random_uuid(),activity_id uuid not null references public.work_activities,actor_id uuid not null references public.profiles,action text not null,note text not null default '',snapshot jsonb not null default '{}',created_at timestamptz not null default now());
create table public.work_hourly_rates(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,effective_on date not null,rate numeric(14,2) not null check(rate between 0 and 1000000),reason text not null check(length(trim(reason)) between 1 and 2000),created_by uuid not null references public.profiles,created_at timestamptz not null default now(),unique(user_id,effective_on));
create table public.work_labour_costs(id uuid primary key default gen_random_uuid(),activity_id uuid not null unique references public.work_activities,rate_id uuid not null references public.work_hourly_rates,hours numeric not null,rate numeric(14,2) not null,cost numeric(16,2) not null,approved_by uuid not null references public.profiles,approved_at timestamptz not null default now());
create policy activity_delay_options on public.crm_settings for select to authenticated using(id='delay_reasons' and public.is_staff());
create function portal_private.activity_scope(p_kind text,p_project uuid,p_task uuid,p_ticket uuid,p_deal uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_staff() and case p_kind when 'Internal' then true when 'Project' then public.is_admin() or (public.can_project(p_project) and ((p_task is null and portal_private.project_assigned(p_project)) or (p_task is not null and exists(select 1 from public.tasks where id=p_task and project_id=p_project) and (portal_private.project_assigned(p_project) or portal_private.task_assigned(p_task))))) when 'Ticket' then exists(select 1 from public.tickets where id=p_ticket and project_id=p_project) and (public.is_admin() or portal_private.ticket_visible(p_ticket)) and (p_task is null or exists(select 1 from public.tasks where id=p_task and ticket_id=p_ticket and project_id=p_project) and (public.is_admin() or portal_private.project_assigned(p_project) or portal_private.task_assigned(p_task))) when 'Deal' then portal_private.deal_access(p_deal) else false end;$$;
create function portal_private.activity_worker_authorized(a public.work_activities) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=a.user_id and active and role in ('admin','team')) and (exists(select 1 from public.profiles where id=a.user_id and role='admin') or a.link_kind='Internal' or (a.link_kind in ('Project','Ticket') and (exists(select 1 from public.project_assignments where project_id=a.project_id and technician_id=a.user_id) or exists(select 1 from public.tasks t where t.project_id=a.project_id and (t.assignee=a.user_id or a.user_id=any(t.collaborators)) and (a.task_id=t.id or a.link_kind='Ticket' and a.task_id is null and t.ticket_id=a.ticket_id)))) or (a.link_kind='Deal' and exists(select 1 from public.crm_deals d join public.crm_product_lines l on l.deal_id=d.id join public.crm_board_memberships b on b.board_id=l.board_id where d.id=a.deal_id and b.user_id=a.user_id and (portal_private.crm_user_permission(a.user_id,'sales.manage') or portal_private.crm_user_permission(a.user_id,'sales.own') and d.owner_id=a.user_id or portal_private.crm_user_permission(a.user_id,'product.own')))));$$;
create function portal_private.activity_reviewer(p public.work_activities) returns boolean language sql stable security definer set search_path='' as $$select public.is_admin() or (p.project_id is not null and portal_private.execution_manager(p.project_id)) or (p.link_kind='Deal' and portal_private.crm_permission('sales.manage') and portal_private.deal_access(p.deal_id));$$;
create function portal_private.activity_read(p public.work_activities) returns boolean language sql stable security definer set search_path='' as $$select public.is_admin() or (public.is_staff() and ((p.user_id=auth.uid() and portal_private.activity_scope(p.link_kind,p.project_id,p.task_id,p.ticket_id,p.deal_id)) or portal_private.activity_reviewer(p) or (portal_private.payables_access() and p.status='Approved')));$$;
create function portal_private.activity_open(p_project uuid) returns void language plpgsql security definer set search_path='' as $$begin if p_project is not null then perform 1 from public.projects where id=p_project for update;if not found then raise exception 'Project unavailable';end if;if exists(select 1 from public.projects where id=p_project and status='Completed') or exists(select 1 from public.crm_handovers where project_id=p_project and status in ('Awaiting signatures','Signed','Closed')) then raise exception 'Released or closed project activity is locked';end if;end if;end$$;
alter table public.work_activities enable row level security;alter table public.work_activity_history enable row level security;alter table public.work_hourly_rates enable row level security;alter table public.work_labour_costs enable row level security;
revoke all on public.work_activities,public.work_activity_history,public.work_hourly_rates,public.work_labour_costs from public,anon,authenticated;
grant select on public.work_activities,public.work_activity_history,public.work_hourly_rates,public.work_labour_costs to authenticated;
create policy activity_read on public.work_activities for select to authenticated using(portal_private.activity_read(work_activities));
create policy activity_history_read on public.work_activity_history for select to authenticated using(exists(select 1 from public.work_activities a where a.id=activity_id));
create policy hourly_rate_read on public.work_hourly_rates for select to authenticated using(portal_private.payables_access());
create policy labour_cost_read on public.work_labour_costs for select to authenticated using(portal_private.payables_access() or exists(select 1 from public.work_activities a where a.id=activity_id and a.project_id is not null and portal_private.execution_manager(a.project_id)));
create function public.set_work_hourly_rate(p_user uuid,p_effective date,p_rate numeric,p_reason text) returns uuid language plpgsql security definer set search_path='' as $$declare result uuid;begin
 if not public.is_admin() then raise exception 'Administrator rate configuration required';end if;
 if not exists(select 1 from public.profiles where id=p_user and active and role in ('admin','team')) or p_effective is null or p_rate is null or p_rate::text in ('NaN','Infinity','-Infinity') or p_rate<0 or p_rate>1000000 or round(p_rate,2)<>p_rate or length(trim(coalesce(p_reason,''))) not between 1 and 2000 then raise exception 'Active staff, effective date, finite PKR rate and reason required';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_user::text,24));
 insert into public.work_hourly_rates(user_id,effective_on,rate,reason,created_by) values(p_user,p_effective,p_rate,trim(p_reason),auth.uid()) returning id into result;return result;
end$$;
create function public.save_work_activity(p_id uuid,p_version integer,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare a public.work_activities;n public.work_activities;result uuid;begin
 if not public.is_staff() then raise exception 'Active staff required';end if;
 n.user_id:=auth.uid();n.link_kind:=p_data->>'link_kind';n.project_id:=nullif(p_data->>'project_id','')::uuid;n.task_id:=nullif(p_data->>'task_id','')::uuid;n.ticket_id:=nullif(p_data->>'ticket_id','')::uuid;n.deal_id:=nullif(p_data->>'deal_id','')::uuid;
 if n.task_id is not null and not exists(select 1 from public.tasks where id=n.task_id and project_id=n.project_id) then raise exception 'Task belongs to a different project';end if;
 if not portal_private.activity_scope(n.link_kind,n.project_id,n.task_id,n.ticket_id,n.deal_id) then raise exception 'Assigned activity scope required';end if;
 perform portal_private.activity_open(n.project_id);perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text,24));
 if p_id is not null then select * into a from public.work_activities where id=p_id for update;if a.id is null or a.user_id<>auth.uid() or a.version<>p_version or a.status not in ('Draft','Rejected') or not portal_private.activity_read(a) then raise exception 'Own current editable activity required';end if;if row(a.link_kind,a.project_id,a.task_id,a.ticket_id,a.deal_id) is distinct from row(n.link_kind,n.project_id,n.task_id,n.ticket_id,n.deal_id) then raise exception 'Original activity scope is fixed';end if;end if;
 n.actual_start:=(p_data->>'actual_start')::timestamptz;n.actual_end:=(p_data->>'actual_end')::timestamptz;n.planned_start:=nullif(p_data->>'planned_start','')::timestamptz;n.planned_end:=nullif(p_data->>'planned_end','')::timestamptz;
 if n.actual_start is null or n.actual_end is null or not isfinite(n.actual_start) or not isfinite(n.actual_end) or n.actual_end>now() or n.actual_end<=n.actual_start or n.actual_end-n.actual_start>interval '16 hours' then raise exception 'Actual interval must be completed, finite and at most 16 hours';end if;
 if n.planned_start is not null and not isfinite(n.planned_start) or n.planned_end is not null and not isfinite(n.planned_end) then raise exception 'Finite planned times required';end if;
 if exists(select 1 from public.work_activities where user_id=auth.uid() and id is distinct from p_id and status in ('Draft','Submitted','Approved') and actual_start<n.actual_end and actual_end>n.actual_start) then raise exception 'Activity overlaps existing work';end if;
 if (select coalesce(sum(extract(epoch from actual_end-actual_start)/60),0) from public.work_activities where user_id=auth.uid() and id is distinct from p_id and status in ('Draft','Submitted','Approved') and (actual_start at time zone 'Asia/Karachi')::date=(n.actual_start at time zone 'Asia/Karachi')::date)+extract(epoch from n.actual_end-n.actual_start)/60>960 then raise exception 'Working day exceeds 16 logged hours';end if;
 n.delay_reason:=trim(coalesce(p_data->>'delay_reason',''));n.delay_note:=trim(coalesce(p_data->>'delay_note',''));n.lost_minutes:=coalesce(nullif(p_data->>'lost_minutes','')::integer,0);
 if n.delay_reason<>'' and not exists(select 1 from public.crm_settings s,jsonb_array_elements_text(s.value) v where s.id='delay_reasons' and v=n.delay_reason) then raise exception 'Choose configured delay reason';end if;
 if (n.planned_end is not null and n.actual_end>n.planned_end or n.lost_minutes>0) and (n.delay_reason='' or n.delay_note='') or n.delay_reason='Other' and n.delay_note='' then raise exception 'Late or lost time requires delay reason and note';end if;
 n.quantity:=coalesce(nullif(p_data->>'quantity','')::numeric,0);if n.quantity::text in ('NaN','Infinity','-Infinity') then raise exception 'Finite quantity required';end if;n.crew:=coalesce(nullif(p_data->>'crew','')::integer,1);
 n.location:=trim(p_data->>'location');n.activity_type:=p_data->>'activity_type';n.description:=trim(p_data->>'description');n.outcome:=p_data->>'outcome';n.blocker:=trim(coalesce(p_data->>'blocker',''));n.remarks:=trim(coalesce(p_data->>'remarks',''));n.evidence:=trim(coalesce(p_data->>'evidence',''));n.given_by:=nullif(p_data->>'given_by','')::uuid;
 if n.given_by is not null and not exists(select 1 from public.profiles where id=n.given_by and active and role in ('admin','team')) then raise exception 'Active staff assigner required';end if;
 if p_id is null then
 insert into public.work_activities(user_id,link_kind,project_id,task_id,ticket_id,deal_id,location,activity_type,description,given_by,planned_start,planned_end,actual_start,actual_end,outcome,quantity,crew,delay_reason,delay_note,lost_minutes,blocker,remarks,evidence) values(n.user_id,n.link_kind,n.project_id,n.task_id,n.ticket_id,n.deal_id,n.location,n.activity_type,n.description,n.given_by,n.planned_start,n.planned_end,n.actual_start,n.actual_end,n.outcome,n.quantity,n.crew,n.delay_reason,n.delay_note,n.lost_minutes,n.blocker,n.remarks,n.evidence) returning id into result;
 else
 update public.work_activities set location=n.location,activity_type=n.activity_type,description=n.description,given_by=n.given_by,planned_start=n.planned_start,planned_end=n.planned_end,actual_start=n.actual_start,actual_end=n.actual_end,outcome=n.outcome,quantity=n.quantity,crew=n.crew,delay_reason=n.delay_reason,delay_note=n.delay_note,lost_minutes=n.lost_minutes,blocker=n.blocker,remarks=n.remarks,evidence=n.evidence,status='Draft',reviewed_by=null,reviewed_at=null,version=version+1 where id=a.id;result:=a.id;end if;
 insert into public.work_activity_history(activity_id,actor_id,action,snapshot) select result,auth.uid(),case when p_id is null then 'Created' else 'Revised' end,to_jsonb(x) from public.work_activities x where x.id=result;return result;
end$$;
create function public.work_activity_action(p_id uuid,p_version integer,p_action text,p_note text default '') returns void language plpgsql security definer set search_path='' as $$declare a public.work_activities;r public.work_hourly_rates;begin
 if not public.is_staff() then raise exception 'Active staff required';end if;
 select * into a from public.work_activities where id=p_id;if a.id is null or not portal_private.activity_read(a) then raise exception 'Activity unavailable';end if;
 perform portal_private.activity_open(a.project_id);perform pg_advisory_xact_lock(hashtextextended(a.user_id::text,24));select * into a from public.work_activities where id=p_id for update;
 if a.version<>p_version then raise exception 'Stale activity version';end if;
 if length(coalesce(p_note,''))>2000 then raise exception 'Review note too long';end if;
 if p_action='Submit' then
 if a.user_id<>auth.uid() or a.status<>'Draft' or not portal_private.activity_scope(a.link_kind,a.project_id,a.task_id,a.ticket_id,a.deal_id) then raise exception 'Own assigned draft required';end if;
 if exists(select 1 from public.work_activities where user_id=a.user_id and id<>a.id and status in ('Draft','Submitted','Approved') and actual_start<a.actual_end and actual_end>a.actual_start) then raise exception 'Activity overlaps existing work';end if;
 elsif p_action in ('Approve','Reject') then
 if a.status<>'Submitted' or a.user_id=auth.uid() or not portal_private.activity_reviewer(a) or not exists(select 1 from public.profiles where id=a.user_id and active) then raise exception 'Separate assigned manager review required';end if;
 if trim(coalesce(p_note,''))='' then raise exception 'Review reason required';end if;
 if p_action='Approve' then
 if not portal_private.activity_worker_authorized(a) then raise exception 'Worker assignment was revoked';end if;
 if a.project_id is not null and portal_private.finance_project_currency(a.project_id)<>'PKR' then raise exception 'Foreign-currency labour costing pending';end if;
 select * into r from public.work_hourly_rates where user_id=a.user_id and effective_on<=(a.actual_start at time zone 'Asia/Karachi')::date order by effective_on desc limit 1;
 if r.id is null then raise exception 'Configure an effective hourly rate before approval';end if;
 insert into public.work_labour_costs(activity_id,rate_id,hours,rate,cost,approved_by) values(a.id,r.id,extract(epoch from a.actual_end-a.actual_start)/3600,r.rate,round(extract(epoch from a.actual_end-a.actual_start)/3600*r.rate,2),auth.uid());end if;
 elsif p_action='Void' then
 if a.status<>'Approved' or not public.is_admin() or a.user_id=auth.uid() or a.reviewed_by=auth.uid() or trim(coalesce(p_note,''))='' then raise exception 'Separate administrator and reason required to void approved activity';end if;
 elsif p_action='Cancel' then if a.user_id<>auth.uid() or a.status not in ('Draft','Rejected') or trim(coalesce(p_note,''))='' then raise exception 'Own unpaid draft and reason required';end if;
 else raise exception 'Unsupported activity action';end if;
 update public.work_activities set status=case p_action when 'Submit' then 'Submitted' when 'Approve' then 'Approved' when 'Reject' then 'Rejected' else 'Voided' end,reviewed_by=case when p_action in ('Approve','Reject') then auth.uid() else reviewed_by end,reviewed_at=case when p_action in ('Approve','Reject') then now() else reviewed_at end,version=version+1 where id=a.id;
 insert into public.work_activity_history(activity_id,actor_id,action,note,snapshot) select a.id,auth.uid(),p_action,trim(coalesce(p_note,'')),to_jsonb(x) from public.work_activities x where x.id=a.id;
end$$;
alter function portal_private.handover_ready(uuid) rename to handover_ready_before_activity;
revoke all on function portal_private.handover_ready_before_activity(uuid) from public,anon,authenticated;
create function portal_private.handover_ready(p_project uuid) returns void language plpgsql security definer set search_path='' as $$begin
 perform portal_private.handover_ready_before_activity(p_project);
 if exists(select 1 from public.work_activities where project_id=p_project and status in ('Draft','Submitted','Rejected')) then raise exception 'Review or cancel open project activity logs before handover';end if;
end$$;
revoke all on function portal_private.handover_ready(uuid) from public,anon,authenticated;
-- Preserve the independently checked financial baseline in the private schema.
alter function public.project_financials(uuid) set schema portal_private;
alter function portal_private.project_financials(uuid) rename to project_financials_before_labour;
revoke all on function portal_private.project_financials_before_labour(uuid) from public,anon,authenticated;
create function public.project_financials(p_project uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare base jsonb;cost numeric;hours numeric;recorded numeric;net numeric;planned numeric;cats jsonb;begin
 base:=portal_private.project_financials_before_labour(p_project);
 select coalesce(sum(c.cost),0),coalesce(sum(c.hours),0) into cost,hours from public.work_labour_costs c join public.work_activities a on a.id=c.activity_id where a.project_id=p_project and a.status='Approved';
 recorded:=(base->>'recorded_cost')::numeric+cost;net:=(base->>'contract_net')::numeric;planned:=(base->>'planned_cost')::numeric;
 select coalesce(jsonb_agg(case when x->>'category'='Labour' then x||jsonb_build_object('approved_hourly_labour',cost,'recorded_cost',(x->>'recorded_cost')::numeric+cost) else x||jsonb_build_object('approved_hourly_labour',0) end),'[]') into cats from jsonb_array_elements(base->'categories') x;
 if not exists(select 1 from jsonb_array_elements(cats) x where x->>'category'='Labour') then cats:=cats||jsonb_build_array(jsonb_build_object('category','Labour','approved_expenses',0,'issued_material',0,'approved_hourly_labour',cost,'recorded_cost',cost));end if;
 return base||jsonb_build_object('approved_labour_hours',hours,'approved_hourly_labour',cost,'recorded_cost',recorded,'remaining_against_recorded',planned-recorded,'recorded_utilisation_percent',case when planned>0 then round(recorded/planned*100,2) end,'profit_before_unrecorded_costs',net-recorded,'margin_before_unrecorded_costs',case when net>0 then round((net-recorded)/net*100,2) end,'categories',cats,'labour_hours_pending',false,'cost_complete',false,'note','Recorded costs include net non-returnable material issues, additional approved expenses and approved activity hours at the saved effective PKR rate. Crew count is context: each employee logs their own hours. Labour cash/payroll, overtime premiums, unrecorded work, tax treatment and budget revisions remain pending; profitability is provisional.');
end$$;
create function public.work_activity_report() returns jsonb language plpgsql stable security invoker set search_path='' as $$begin if not public.is_staff() then raise exception 'Active staff required';end if;return (select coalesce(jsonb_agg(to_jsonb(a)||jsonb_build_object('hours',extract(epoch from a.actual_end-a.actual_start)/3600,'working_date',(a.actual_start at time zone 'Asia/Karachi')::date,'employee',coalesce((select name from public.profiles where id=a.user_id),'Staff member'),'project',(select title from public.projects where id=a.project_id),'labour_cost',(select cost from public.work_labour_costs where activity_id=a.id)) order by a.actual_start desc),'[]') from public.work_activities a);end$$;
do $$declare f record;begin for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='portal_private' and p.proname like 'activity_%' loop execute format('revoke all on function %s from public,anon,authenticated',f.sig);end loop;end$$;
grant execute on function portal_private.activity_read(public.work_activities),portal_private.activity_reviewer(public.work_activities) to authenticated;
do $$declare f record;begin for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('set_work_hourly_rate','save_work_activity','work_activity_action','work_activity_report','project_financials') loop execute format('revoke all on function %s from public,anon',f.sig);execute format('grant execute on function %s to authenticated',f.sig);end loop;end$$;
commit;
