begin;
create table public.hr_policies(id uuid primary key default gen_random_uuid(),role_id text not null default 'default',effective_on date not null check(isfinite(effective_on)),shift_start time not null,shift_end time not null,grace_minutes integer not null check(grace_minutes between 0 and 120),half_day_minutes integer not null check(half_day_minutes between 1 and 720),off_days integer[] not null check(cardinality(off_days)<=7 and off_days<@array[0,1,2,3,4,5,6]),holidays date[] not null default '{}',ot_mode text not null check(ot_mode in ('Fixed rate','Hourly multiplier')),ot_rate numeric(14,2) not null check(ot_rate between 0 and 1000000),off_multiplier numeric(5,2) not null check(off_multiplier between 0 and 10),holiday_multiplier numeric(5,2) not null check(holiday_multiplier between 0 and 10),weights jsonb not null,bonus_slabs jsonb not null,reason text not null,created_by uuid not null references public.profiles,created_at timestamptz not null default now(),unique(role_id,effective_on));
create table public.hr_terms(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,effective_on date not null check(isfinite(effective_on)),role_id text not null references public.crm_roles,salary numeric(14,2) not null check(salary between 0 and 100000000),monthly_hours numeric(10,2) not null check(monthly_hours between 1 and 744),lead_id uuid not null references public.profiles,manager_id uuid not null references public.profiles,reason text not null,created_by uuid not null references public.profiles,created_at timestamptz not null default now(),unique(user_id,effective_on),check(lead_id<>manager_id and lead_id<>user_id and manager_id<>user_id));
create table public.hr_overtime(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,working_date date not null,source jsonb not null,source_hash text not null,hours numeric not null check(hours>0 and hours<=16),rate numeric(14,2) not null,amount numeric(16,2) not null,status text not null default 'Submitted' check(status in ('Submitted','Approved','Rejected','Voided')),reviewed_by uuid references public.profiles,version integer not null default 1,created_at timestamptz not null default now());
create unique index hr_one_active_overtime on public.hr_overtime(user_id,working_date) where status in ('Submitted','Approved');
create table public.hr_monthly(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,month date not null check(extract(day from month)=1),snapshot jsonb not null,source_hash text not null,deductions numeric(14,2) not null check(deductions>=0),deduction_note text not null default '',status text not null default 'Draft' check(status in ('Draft','Lead reviewed','Manager reviewed','Locked')),created_by uuid not null references public.profiles,lead_by uuid references public.profiles,manager_by uuid references public.profiles,accounts_by uuid references public.profiles,acknowledged_at timestamptz,version integer not null default 1,created_at timestamptz not null default now(),unique(user_id,month));
create table public.hr_history(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,overtime_id uuid references public.hr_overtime,monthly_id uuid references public.hr_monthly,actor_id uuid not null references public.profiles,action text not null,note text not null default '',snapshot jsonb not null default '{}',created_at timestamptz not null default now());
create index hr_terms_lookup on public.hr_terms(user_id,effective_on desc);
create index hr_policy_lookup on public.hr_policies(role_id,effective_on desc);
create index hr_ot_month on public.hr_overtime(user_id,working_date,status);
create index hr_history_employee on public.hr_history(user_id,created_at);
create function portal_private.hr_access() returns boolean language sql stable security definer set search_path='' as $$select public.is_admin() or portal_private.crm_permission('hr.manage');$$;
create function portal_private.hr_term(p_user uuid,p_day date) returns public.hr_terms language sql stable security definer set search_path='' as $$select t from public.hr_terms t where user_id=p_user and effective_on<=p_day order by effective_on desc limit 1;$$;
create function portal_private.hr_policy(p_user uuid,p_day date) returns public.hr_policies language sql stable security definer set search_path='' as $$select p from public.hr_policies p where effective_on<=p_day and role_id in ('default',(portal_private.hr_term(p_user,p_day)).role_id) order by (role_id<>'default') desc,effective_on desc limit 1;$$;
create function portal_private.hr_supervisor(p_user uuid,p_day date,p_stage text) returns boolean language sql stable security definer set search_path='' as $$select public.is_staff() and case p_stage when 'Lead' then (portal_private.hr_term(p_user,(now() at time zone 'Asia/Karachi')::date)).lead_id=auth.uid() and portal_private.crm_user_permission(auth.uid(),'team.own') when 'Manager' then (portal_private.hr_term(p_user,(now() at time zone 'Asia/Karachi')::date)).manager_id=auth.uid() and portal_private.crm_user_permission(auth.uid(),'project.own') else false end;$$;
create function portal_private.hr_read(p_user uuid,p_day date) returns boolean language sql stable security definer set search_path='' as $$select public.is_staff() and (p_user=auth.uid() or portal_private.hr_access() or portal_private.payables_access() or portal_private.hr_supervisor(p_user,p_day,'Lead') or portal_private.hr_supervisor(p_user,p_day,'Manager'));$$;
create function portal_private.hr_locked(p_user uuid,p_day date) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.hr_monthly where user_id=p_user and month=date_trunc('month',p_day)::date and status='Locked');$$;
create function public.save_hr_policy(p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare result_id uuid;weights jsonb:=p_data->'weights';slabs jsonb:=p_data->'bonus_slabs';r text:=coalesce(p_data->>'role_id','default');begin
 if not public.is_admin() then raise exception 'Administrator policy configuration required';end if;
 if r<>'default' and not exists(select 1 from public.crm_roles where crm_roles.id=r and active) then raise exception 'Choose active role or default';end if;
 if jsonb_typeof(weights) is distinct from 'object' or weights is null or exists(select 1 from jsonb_each(weights) x where x.key not in ('attendance','punctuality','task_completion','billable_utilisation','report_discipline') or jsonb_typeof(x.value)<>'number' or (x.value#>>'{}')::numeric not between 0 and 100) or coalesce((select sum((value#>>'{}')::numeric) from jsonb_each(weights)),0)<>100 then raise exception 'Supported KPI weights must total 100';end if;
 if slabs is null or jsonb_typeof(slabs) is distinct from 'array' or jsonb_array_length(slabs)>20 or exists(select 1 from jsonb_array_elements(slabs) x where jsonb_typeof(x->'score') is distinct from 'number' or jsonb_typeof(x->'amount') is distinct from 'number' or (x->>'score')::numeric not between 0 and 100 or (x->>'amount')::numeric not between 0 and 100000000 or round((x->>'amount')::numeric,2)<>(x->>'amount')::numeric) or (select count(*) from jsonb_array_elements(slabs))<>(select count(distinct x->>'score') from jsonb_array_elements(slabs) x) then raise exception 'Unique bonus thresholds and bounded PKR amounts required';end if;
 if exists(select 1 from jsonb_array_elements_text(coalesce(p_data->'holidays','[]')) x where not isfinite(x.value::date)) or round((p_data->>'ot_rate')::numeric,2)<>(p_data->>'ot_rate')::numeric or length(trim(coalesce(p_data->>'reason',''))) not between 3 and 2000 then raise exception 'Policy reason required';end if;
 insert into public.hr_policies(role_id,effective_on,shift_start,shift_end,grace_minutes,half_day_minutes,off_days,holidays,ot_mode,ot_rate,off_multiplier,holiday_multiplier,weights,bonus_slabs,reason,created_by) values(r,(p_data->>'effective_on')::date,(p_data->>'shift_start')::time,(p_data->>'shift_end')::time,(p_data->>'grace_minutes')::integer,(p_data->>'half_day_minutes')::integer,array(select value::integer from jsonb_array_elements_text(p_data->'off_days')),array(select value::date from jsonb_array_elements_text(coalesce(p_data->'holidays','[]'))),p_data->>'ot_mode',(p_data->>'ot_rate')::numeric,(p_data->>'off_multiplier')::numeric,(p_data->>'holiday_multiplier')::numeric,weights,slabs,trim(p_data->>'reason'),auth.uid()) returning hr_policies.id into result_id;return result_id;
end$$;
create function public.save_hr_terms(p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare result_id uuid;u uuid:=(p_data->>'user_id')::uuid;l uuid:=(p_data->>'lead_id')::uuid;m uuid:=(p_data->>'manager_id')::uuid;day date:=(p_data->>'effective_on')::date;begin
 if not portal_private.hr_access() then raise exception 'HR required';end if;
 if round((p_data->>'salary')::numeric,2)<>(p_data->>'salary')::numeric or not exists(select 1 from public.crm_roles where id=p_data->>'role_id' and active) or not exists(select 1 from public.profiles where profiles.id=u and active and role in ('admin','team')) or not portal_private.crm_user_permission(l,'team.own') or not portal_private.crm_user_permission(m,'project.own') or length(trim(coalesce(p_data->>'reason',''))) not between 3 and 2000 then raise exception 'Active staff, separate lead/manager and reason required';end if;
 perform pg_advisory_xact_lock(hashtextextended('hr:'||u::text,25));
 insert into public.hr_terms(user_id,effective_on,role_id,salary,monthly_hours,lead_id,manager_id,reason,created_by) values(u,day,p_data->>'role_id',(p_data->>'salary')::numeric,(p_data->>'monthly_hours')::numeric,l,m,trim(p_data->>'reason'),auth.uid()) returning hr_terms.id into result_id;
 if exists(select 1 from public.work_hourly_rates where user_id=u and effective_on=day and rate<>round((p_data->>'salary')::numeric/(p_data->>'monthly_hours')::numeric,2)) then raise exception 'Existing effective project hourly rate differs from salary terms';end if;
 insert into public.work_hourly_rates(user_id,effective_on,rate,reason,created_by) values(u,day,round((p_data->>'salary')::numeric/(p_data->>'monthly_hours')::numeric,2),'Hourly salary cost from HR terms: '||trim(p_data->>'reason'),auth.uid()) on conflict(user_id,effective_on) do nothing;
 insert into public.hr_history(user_id,actor_id,action,note,snapshot) select u,auth.uid(),'Terms configured',trim(p_data->>'reason'),to_jsonb(t) from public.hr_terms t where t.id=result_id;
 return result_id;
end$$;
-- Union recorded intervals to avoid counting attendance and activity twice.
create function portal_private.hr_day(p_user uuid,p_day date) returns jsonb language plpgsql stable security definer set search_path='' as $$declare t public.hr_terms;p public.hr_policies;start_at timestamptz;end_at timestamptz;mins numeric;ot numeric;first_at timestamptz;first_checkin timestamptz;last_at timestamptz;day_kind text;rate numeric;source jsonb;begin
 t:=portal_private.hr_term(p_user,p_day);p:=portal_private.hr_policy(p_user,p_day);if t.id is null or p.id is null then raise exception 'Configure effective employee terms and shift policy';end if;
 start_at:=(p_day+p.shift_start) at time zone 'Asia/Karachi';end_at:=(p_day+p.shift_end+case when p.shift_end<=p.shift_start then interval '1 day' else interval '0 day' end) at time zone 'Asia/Karachi';
 day_kind:=case when p_day=any(p.holidays) then 'Holiday' when extract(dow from p_day)::integer=any(p.off_days) then 'Off-day' else 'Working day' end;
 select coalesce(jsonb_agg(x order by x->>'kind',x->>'id'),'[]') into source from (
 select jsonb_build_object('kind','Attendance','id',a.id,'version',a.version,'start',a.checked_in,'end',a.checked_out) x from public.attendance_entries a where a.user_id=p_user and not a.voided and a.checked_out is not null and (a.checked_in at time zone 'Asia/Karachi')::date=p_day
 union all select jsonb_build_object('kind','Activity','id',a.id,'version',a.version,'start',a.actual_start,'end',a.actual_end) from public.work_activities a where a.user_id=p_user and a.status='Approved' and (a.actual_start at time zone 'Asia/Karachi')::date=p_day) s;
 select coalesce(sum(extract(epoch from upper(r)-lower(r))/60),0),coalesce(sum(greatest(0,extract(epoch from upper(r)-greatest(lower(r),end_at))/3600)),0),min(lower(r)),max(upper(r)) into mins,ot,first_at,last_at from (select unnest(range_agg(tstzrange((x->>'start')::timestamptz,(x->>'end')::timestamptz,'[)'))) r from jsonb_array_elements(source) x) intervals;
 select min(checked_in) into first_checkin from public.attendance_entries where user_id=p_user and not voided and checked_out is not null and (checked_in at time zone 'Asia/Karachi')::date=p_day;
 if day_kind<>'Working day' then ot:=mins/60;end if;
 rate:=case p.ot_mode when 'Fixed rate' then p.ot_rate else round(t.salary/t.monthly_hours*p.ot_rate,2) end*case day_kind when 'Holiday' then p.holiday_multiplier when 'Off-day' then p.off_multiplier else 1 end;
 return jsonb_build_object('working_date',p_day,'kind',day_kind,'minutes',mins,'overtime_hours',ot,'overtime_rate',round(rate,2),'overtime_amount',round(ot*round(rate,2),2),'first_at',first_at,'last_at',last_at,'first_checkin',first_checkin,'late',first_checkin>start_at+make_interval(mins=>p.grace_minutes),'attendance_status',case when day_kind<>'Working day' then day_kind when mins=0 then 'Absent' when mins<p.half_day_minutes then 'Half-day' when coalesce(first_checkin,first_at)>start_at+make_interval(mins=>p.grace_minutes) then 'Late' else 'Present' end,'source',source,'terms_id',t.id,'policy_id',p.id,'note','Completed attendance and approved activity intervals are merged. Unrecorded breaks, leave and holiday feeds are not inferred.');
end$$;
create function public.hr_daily_preview(p_user uuid,p_day date) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if p_day is null or not isfinite(p_day) or not portal_private.hr_read(p_user,p_day) then raise exception 'Own or designated HR scope required';end if;return portal_private.hr_day(p_user,p_day);end$$;
create function public.submit_hr_overtime(p_day date) returns uuid language plpgsql security definer set search_path='' as $$declare data jsonb;result_id uuid;begin
 if not public.is_staff() or p_day is null or not isfinite(p_day) or p_day>(now() at time zone 'Asia/Karachi')::date then raise exception 'Active staff and past/current working date required';end if;
 perform pg_advisory_xact_lock(hashtextextended('hr:'||auth.uid()::text,25));if portal_private.hr_locked(auth.uid(),p_day) then raise exception 'Month locked';end if;
 data:=portal_private.hr_day(auth.uid(),p_day);if (data->>'overtime_hours')::numeric not between 0.000001 and 16 or (data->>'last_at')::timestamptz>now() then raise exception 'Completed recorded overtime of at most 16 hours required';end if;
 insert into public.hr_overtime(user_id,working_date,source,source_hash,hours,rate,amount) values(auth.uid(),p_day,data,md5(data::text),(data->>'overtime_hours')::numeric,(data->>'overtime_rate')::numeric,(data->>'overtime_amount')::numeric) returning hr_overtime.id into result_id;
 insert into public.hr_history(user_id,overtime_id,actor_id,action,snapshot) values(auth.uid(),result_id,auth.uid(),'Overtime submitted',data);return result_id;
end$$;
create function public.review_hr_overtime(p_id uuid,p_version integer,p_action text,p_note text) returns void language plpgsql security definer set search_path='' as $$declare o public.hr_overtime;data jsonb;begin
 select * into o from public.hr_overtime where id=p_id;if o.id is null or not portal_private.hr_read(o.user_id,o.working_date) then raise exception 'Overtime unavailable';end if;
 perform pg_advisory_xact_lock(hashtextextended('hr:'||o.user_id::text,25));select * into o from public.hr_overtime where id=p_id for update;
 if o.version<>p_version or o.user_id=auth.uid() or not public.is_staff() or length(trim(coalesce(p_note,''))) not between 3 and 2000 or portal_private.hr_locked(o.user_id,o.working_date) then raise exception 'Separate review, current version, reason and unlocked month required';end if;
 if p_action in ('Approve','Reject') then if o.status<>'Submitted' or not (portal_private.hr_supervisor(o.user_id,o.working_date,'Lead') or portal_private.hr_supervisor(o.user_id,o.working_date,'Manager')) then raise exception 'Designated lead or manager review required';end if;if p_action='Approve' then data:=portal_private.hr_day(o.user_id,o.working_date);if md5(data::text)<>o.source_hash then raise exception 'Overtime source changed; reject and submit again';end if;end if;
 elsif p_action='Void' then if o.status<>'Approved' or not public.is_admin() or o.reviewed_by=auth.uid() then raise exception 'Separate administrator correction required';end if;
 else raise exception 'Unsupported overtime action';end if;
 update public.hr_overtime set status=case p_action when 'Approve' then 'Approved' when 'Reject' then 'Rejected' else 'Voided' end,reviewed_by=auth.uid(),version=version+1 where id=o.id;
 insert into public.hr_history(user_id,overtime_id,actor_id,action,note,snapshot) values(o.user_id,o.id,auth.uid(),p_action,trim(p_note),to_jsonb(o));
end$$;
create function portal_private.hr_month(p_user uuid,p_month date) returns jsonb language plpgsql stable security definer set search_path='' as $$declare t public.hr_terms;p public.hr_policies;day date;d jsonb;days jsonb:='[]';working integer:=0;present integer:=0;on_time integer:=0;checkin_days integer:=0;logged integer:=0;all_hours numeric;billable numeric;training numeric;assigned integer;done integer;metrics jsonb;score numeric:=0;coverage numeric:=0;weight numeric;val numeric;bonus numeric;ot numeric;claims numeric;basis jsonb;begin
 if p_month is null or not isfinite(p_month) or extract(day from p_month)<>1 then raise exception 'Choose first day of month';end if;
 t:=portal_private.hr_term(p_user,p_month);p:=portal_private.hr_policy(p_user,p_month);if t.id is null or p.id is null then raise exception 'Effective employee terms and policy required';end if;
 for day in select x::date from generate_series(p_month::timestamp,(p_month+interval '1 month' - interval '1 day')::timestamp,interval '1 day') x loop
 d:=portal_private.hr_day(p_user,day);days:=days||jsonb_build_array(d);if d->>'kind'='Working day' then working:=working+1;if d->>'attendance_status' in ('Present','Late') then present:=present+1;if d->>'first_checkin' is not null then checkin_days:=checkin_days+1;if not (d->>'late')::boolean then on_time:=on_time+1;end if;end if;end if;if exists(select 1 from public.work_activities where user_id=p_user and status='Approved' and (actual_start at time zone 'Asia/Karachi')::date=day) then logged:=logged+1;end if;end if;end loop;
 select coalesce(sum(c.hours),0),coalesce(sum(c.hours) filter(where a.link_kind in ('Project','Ticket')),0),coalesce(sum(c.hours) filter(where a.activity_type='Training'),0) into all_hours,billable,training from public.work_activities a join public.work_labour_costs c on c.activity_id=a.id where a.user_id=p_user and a.status='Approved' and (a.actual_start at time zone 'Asia/Karachi')::date>=p_month and (a.actual_start at time zone 'Asia/Karachi')::date<p_month+interval '1 month';
 select count(*),count(*) filter(where status='Done') into assigned,done from public.tasks where (assignee=p_user or p_user=any(collaborators)) and deadline>=p_month and deadline<p_month+interval '1 month';
 metrics:=jsonb_build_object('attendance',case when working>0 then round(present::numeric/working*100,2) end,'punctuality',case when present>0 and checkin_days=present then round(on_time::numeric/present*100,2) end,'task_completion',case when assigned>0 then round(done::numeric/assigned*100,2) end,'billable_utilisation',case when all_hours>0 then round(billable/all_hours*100,2) end,'report_discipline',case when working>0 then round(logged::numeric/working*100,2) end);
 for weight,val in select (x.value#>>'{}')::numeric,(metrics->>x.key)::numeric from jsonb_each(p.weights) x loop if val is not null then score:=score+weight*val/100;coverage:=coverage+weight;end if;end loop;
 if coverage<>100 then score:=null;end if;select (x->>'amount')::numeric into bonus from jsonb_array_elements(p.bonus_slabs) x where (x->>'score')::numeric<=score order by (x->>'score')::numeric desc limit 1;bonus:=coalesce(bonus,0);
 if score is null then bonus:=null;end if;
 if exists(select 1 from public.hr_overtime o where o.user_id=p_user and o.working_date>=p_month and o.working_date<p_month+interval '1 month' and o.status='Approved' and o.source_hash<>md5(portal_private.hr_day(p_user,o.working_date)::text)) then raise exception 'Approved overtime source changed; correct before monthly review';end if;
 select coalesce(sum(amount),0) into ot from public.hr_overtime where user_id=p_user and working_date>=p_month and working_date<p_month+interval '1 month' and status='Approved';
 select coalesce(sum(greatest(0,e.amount-coalesce((select sum(c.amount) from public.fin_cash_entries c where c.expense_id=e.id and c.reversed_by is null),0))),0) into claims from public.fin_expenses e where e.created_by=p_user and e.category='TADA' and e.status='Approved' and e.incurred_on>=p_month and e.incurred_on<p_month+interval '1 month';
 basis:=jsonb_build_object('pending_activities',(select count(*) from public.work_activities where user_id=p_user and status in ('Draft','Submitted','Rejected') and (actual_start at time zone 'Asia/Karachi')::date>=p_month and (actual_start at time zone 'Asia/Karachi')::date<p_month+interval '1 month'),'pending_overtime_days',(select count(*) from jsonb_array_elements(days) x where (x->>'overtime_hours')::numeric>0 and not exists(select 1 from public.hr_overtime o where o.user_id=p_user and o.working_date=(x->>'working_date')::date and o.status in ('Approved','Rejected') and o.source_hash=md5(x::text))),'pending_overtime',(select count(*) from public.hr_overtime where user_id=p_user and status='Submitted' and working_date>=p_month and working_date<p_month+interval '1 month'),'open_attendance',(select count(*) from public.attendance_entries where user_id=p_user and not voided and checked_out is null and (checked_in at time zone 'Asia/Karachi')::date>=p_month and (checked_in at time zone 'Asia/Karachi')::date<p_month+interval '1 month'),'employee',(select name from public.profiles where id=p_user),'month',p_month,'terms',to_jsonb(t),'policy',to_jsonb(p),'daily',days,'metrics',metrics,'score',round(score,2),'coverage',coverage,'learning_hours',training,'approved_activity_hours',all_hours,'assigned_due_tasks',assigned,'done_due_tasks',done,'overtime_pay',ot,'bonus',bonus,'salary',t.salary,'tada_outstanding_informational',claims,'gross_salary_summary',case when bonus is not null then t.salary+ot+bonus end,'task_sources',coalesce((select jsonb_agg(jsonb_build_object('id',id,'status',status,'assignee',assignee,'collaborators',collaborators,'deadline',deadline) order by id) from public.tasks where (assignee=p_user or p_user=any(collaborators)) and deadline>=p_month and deadline<p_month+interval '1 month'),'[]'),'overtime_sources',coalesce((select jsonb_agg(to_jsonb(o) order by id) from public.hr_overtime o where o.user_id=p_user and o.working_date>=p_month and o.working_date<p_month+interval '1 month'),'[]'),'note','Recorded attendance and approved activities only. Half-days below the threshold are excluded from present days. Task completion uses current outcomes of tasks due this month; historical on-time/SLA/CSAT, leave and employment-day proration remain pending. Unavailable weighted KPIs leave score and bonus unknown. TADA is informational and settled in Finance separately; this summary does not send or record salary payments.');return basis;
end$$;
create function public.hr_month_preview(p_user uuid,p_month date) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not portal_private.hr_read(p_user,p_month) then raise exception 'Own/designated HR scope required';end if;if exists(select 1 from public.hr_monthly where user_id=p_user and month=p_month and status='Locked') then return (select snapshot from public.hr_monthly where user_id=p_user and month=p_month and status='Locked');end if;return portal_private.hr_month(p_user,p_month);end$$;
create function public.save_hr_month(p_user uuid,p_month date,p_version integer,p_deductions numeric,p_note text) returns uuid language plpgsql security definer set search_path='' as $$declare r public.hr_monthly;data jsonb;begin
 if not portal_private.hr_access() or p_month is null or p_month>=date_trunc('month',now() at time zone 'Asia/Karachi')::date or p_deductions is null or p_deductions::text in ('NaN','Infinity','-Infinity') or p_deductions<0 or round(p_deductions,2)<>p_deductions or p_deductions>100000000 or length(coalesce(p_note,''))>2000 or (p_deductions>0 and length(trim(coalesce(p_note,'')))<3) then raise exception 'HR, completed month and documented finite deductions required';end if;
 perform pg_advisory_xact_lock(hashtextextended('hr:'||p_user::text,25));select * into r from public.hr_monthly where user_id=p_user and month=p_month for update;if found and (r.status<>'Draft' or r.version is distinct from p_version) then raise exception 'Current draft required';end if;
 data:=portal_private.hr_month(p_user,p_month);if data->>'gross_salary_summary' is not null and p_deductions>(data->>'gross_salary_summary')::numeric then raise exception 'Deductions exceed gross summary';end if;
 data:=data||jsonb_build_object('deductions',p_deductions,'deduction_note',p_note,'net_salary_summary',(data->>'gross_salary_summary')::numeric-p_deductions);
 if r.id is null then insert into public.hr_monthly(user_id,month,snapshot,source_hash,deductions,deduction_note,created_by) values(p_user,p_month,data,md5(portal_private.hr_month(p_user,p_month)::text),p_deductions,coalesce(p_note,''),auth.uid()) returning * into r;
 else update public.hr_monthly set snapshot=data,source_hash=md5(portal_private.hr_month(p_user,p_month)::text),deductions=p_deductions,deduction_note=coalesce(p_note,''),lead_by=null,manager_by=null,accounts_by=null,acknowledged_at=null,version=version+1 where id=r.id returning * into r;end if;
 insert into public.hr_history(user_id,monthly_id,actor_id,action,note,snapshot) values(p_user,r.id,auth.uid(),'Monthly draft saved',coalesce(p_note,''),data);return r.id;
end$$;
create function public.hr_month_action(p_id uuid,p_version integer,p_action text,p_note text) returns void language plpgsql security definer set search_path='' as $$declare r public.hr_monthly;begin
 select * into r from public.hr_monthly where id=p_id;if r.id is null or not portal_private.hr_read(r.user_id,r.month) then raise exception 'Monthly summary unavailable';end if;
 perform pg_advisory_xact_lock(hashtextextended('hr:'||r.user_id::text,25));select * into r from public.hr_monthly where id=p_id for update;
 if r.version<>p_version or not public.is_staff() then raise exception 'Current monthly version required';end if;
 if p_action='Acknowledge' then if r.user_id<>auth.uid() or r.status not in ('Manager reviewed','Locked') then raise exception 'Own reviewed scorecard required';end if;if r.acknowledged_at is not null then return;end if;update public.hr_monthly set acknowledged_at=now(),version=version+1 where id=r.id;
 else
 if r.status='Locked' or r.user_id=auth.uid() or r.created_by=auth.uid() or length(trim(coalesce(p_note,''))) not between 3 and 2000 then raise exception 'Separate reviewer, unlocked summary and reason required';end if;
 if p_action<>'Return' and r.source_hash<>md5(portal_private.hr_month(r.user_id,r.month)::text) then raise exception 'Monthly source changed; return and rebuild';end if;
 if p_action='Lead review' then if r.status<>'Draft' or not portal_private.hr_supervisor(r.user_id,r.month,'Lead') then raise exception 'Designated team lead required';end if;
 elsif p_action='Manager review' then if r.status<>'Lead reviewed' or r.lead_by=auth.uid() or not portal_private.hr_supervisor(r.user_id,r.month,'Manager') then raise exception 'Separate designated manager required';end if;
 elsif p_action='Lock' then if r.status<>'Manager reviewed' or not portal_private.payables_access() or auth.uid() in (r.lead_by,r.manager_by) or r.snapshot->>'net_salary_summary' is null or (r.snapshot->>'pending_activities')::integer>0 or (r.snapshot->>'pending_overtime')::integer>0 or (r.snapshot->>'pending_overtime_days')::integer>0 or (r.snapshot->>'open_attendance')::integer>0 then raise exception 'Separate Accounts review and complete score required';end if;
 elsif p_action='Return' then if not (portal_private.hr_supervisor(r.user_id,r.month,'Lead') or portal_private.hr_supervisor(r.user_id,r.month,'Manager') or portal_private.payables_access()) then raise exception 'Review scope required';end if;
 else raise exception 'Unsupported monthly action';end if;
 update public.hr_monthly set status=case p_action when 'Lead review' then 'Lead reviewed' when 'Manager review' then 'Manager reviewed' when 'Lock' then 'Locked' else 'Draft' end,lead_by=case when p_action='Lead review' then auth.uid() when p_action='Return' then null else lead_by end,manager_by=case when p_action='Manager review' then auth.uid() when p_action='Return' then null else manager_by end,accounts_by=case when p_action='Lock' then auth.uid() else null end,acknowledged_at=case when p_action='Return' then null else acknowledged_at end,version=version+1 where id=r.id;
 end if;
 insert into public.hr_history(user_id,monthly_id,actor_id,action,note,snapshot) values(r.user_id,r.id,auth.uid(),p_action,coalesce(p_note,''),r.snapshot);
end$$;
-- Freeze time sources; reviewed task outcomes remain in the immutable monthly snapshot.
create function portal_private.hr_time_lock() returns trigger language plpgsql security definer set search_path='' as $$declare u uuid;day date;old_user uuid;old_day date;begin
 if tg_table_name='attendance_entries' then if tg_op<>'INSERT' then u:=old.user_id;day:=(old.checked_in at time zone 'Asia/Karachi')::date;if portal_private.hr_locked(u,day) then raise exception 'Locked monthly attendance';end if;end if;if tg_op<>'DELETE' then u:=new.user_id;day:=(new.checked_in at time zone 'Asia/Karachi')::date;end if;
 else if tg_op<>'INSERT' then u:=old.user_id;day:=(old.actual_start at time zone 'Asia/Karachi')::date;if portal_private.hr_locked(u,day) then raise exception 'Locked monthly activity';end if;end if;if tg_op<>'DELETE' then u:=new.user_id;day:=(new.actual_start at time zone 'Asia/Karachi')::date;end if;end if;
 if tg_op<>'INSERT' then old_user:=old.user_id;if tg_table_name='attendance_entries' then old_day:=(old.checked_in at time zone 'Asia/Karachi')::date;else old_day:=(old.actual_start at time zone 'Asia/Karachi')::date;end if;end if;perform pg_advisory_xact_lock(hashtextextended('hr:'||u::text,25));if portal_private.hr_locked(old_user,old_day) or portal_private.hr_locked(u,day) then raise exception 'Locked monthly source';end if;if tg_op='DELETE' then return old;end if;return new;
end$$;
create trigger hr_attendance_lock before insert or update or delete on public.attendance_entries for each row execute function portal_private.hr_time_lock();
create trigger hr_activity_lock before insert or update or delete on public.work_activities for each row execute function portal_private.hr_time_lock();
create function public.hr_people() returns table(id uuid,name text) language plpgsql stable security definer set search_path='' as $$begin if not public.is_staff() then raise exception 'Staff required';end if;return query select u.id,u.name from public.profiles u where u.active and u.role in ('admin','team') and (u.id=auth.uid() or portal_private.hr_access() or portal_private.payables_access() or portal_private.hr_supervisor(u.id,(now() at time zone 'Asia/Karachi')::date,'Lead') or portal_private.hr_supervisor(u.id,(now() at time zone 'Asia/Karachi')::date,'Manager')) order by u.name;end$$;
do $$declare tab text;begin foreach tab in array array['hr_policies','hr_terms','hr_overtime','hr_monthly','hr_history'] loop execute format('alter table public.%I enable row level security',tab);execute format('revoke all on public.%I from public,anon,authenticated',tab);execute format('grant select on public.%I to authenticated',tab);end loop;end$$;
create policy hr_policy_read on public.hr_policies for select to authenticated using(public.is_staff());
create policy hr_terms_read on public.hr_terms for select to authenticated using(portal_private.hr_read(user_id,effective_on));
create policy hr_ot_read on public.hr_overtime for select to authenticated using(portal_private.hr_read(user_id,working_date));
create policy hr_month_read on public.hr_monthly for select to authenticated using(portal_private.hr_read(user_id,month) and (user_id<>auth.uid() or status in ('Manager reviewed','Locked') or portal_private.hr_access()));
create policy hr_history_read on public.hr_history for select to authenticated using(portal_private.hr_read(user_id,created_at::date) and (user_id<>auth.uid() or overtime_id is not null or exists(select 1 from public.hr_monthly m where m.id=monthly_id and m.status in ('Manager reviewed','Locked'))));
do $$declare f record;begin for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='portal_private' and p.proname like 'hr_%' loop execute format('revoke all on function %s from public,anon,authenticated',f.sig);end loop;end$$;
grant execute on function portal_private.hr_read(uuid,date),portal_private.hr_access() to authenticated;
do $$declare f record;begin for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('save_hr_policy','save_hr_terms','hr_daily_preview','submit_hr_overtime','review_hr_overtime','hr_month_preview','save_hr_month','hr_month_action','hr_people') loop execute format('revoke all on function %s from public,anon',f.sig);execute format('grant execute on function %s to authenticated',f.sig);end loop;end$$;
commit;
