import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema storage;create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to authenticated;
`);
await pg.exec(await fs.readFile(new URL('../supabase/001_portal.sql', import.meta.url),'utf8'));
const ids={admin:'00000000-0000-0000-0000-000000000001',clientA:'00000000-0000-0000-0000-000000000002',clientB:'00000000-0000-0000-0000-000000000003',team:'00000000-0000-0000-0000-000000000004',outsider:'00000000-0000-0000-0000-000000000005',a:'10000000-0000-0000-0000-000000000001',b:'10000000-0000-0000-0000-000000000002',pa:'20000000-0000-0000-0000-000000000001',pb:'20000000-0000-0000-0000-000000000002',ticket:'30000000-0000-0000-0000-000000000001',file:'40000000-0000-0000-0000-000000000001',fileb:'40000000-0000-0000-0000-000000000002'};
await pg.exec(`insert into auth.users values ('${ids.admin}'),('${ids.clientA}'),('${ids.clientB}'),('${ids.team}'),('${ids.outsider}');
insert into companies values ('${ids.a}','A'),('${ids.b}','B');
insert into profiles values('${ids.admin}','Admin','admin',null),('${ids.clientA}','Client A','client','${ids.a}'),('${ids.clientB}','Client B','client','${ids.b}'),('${ids.team}','Team','team',null);
insert into projects(id,company_id,title) values('${ids.pa}','${ids.a}','A project'),('${ids.pb}','${ids.b}','B project');
insert into tasks(project_id,title,internal) values('${ids.pa}','Shared task',false),('${ids.pa}','Private task',true),('${ids.pb}','Other client task',false);
insert into milestones(project_id,title) values('${ids.pa}','A milestone'),('${ids.pb}','B milestone');
insert into messages(project_id,body,internal,author_id) values('${ids.pa}','Shared comment',false,'${ids.admin}'),('${ids.pa}','Internal comment',true,'${ids.admin}'),('${ids.pb}','B comment',false,'${ids.admin}');
insert into tickets(id,project_id,title,description,priority,author_id) values('${ids.ticket}','${ids.pb}','B ticket','Description','Normal','${ids.clientB}');
insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/deliverable.pdf','${ids.admin}'),('project-files','${ids.pb}/deliverable.pdf','${ids.admin}');
insert into files(id,project_id,name,path,size,deliverable,author_id) values('${ids.file}','${ids.pa}','A.pdf','${ids.pa}/deliverable.pdf',100,true,'${ids.admin}'),('${ids.fileb}','${ids.pb}','B.pdf','${ids.pb}/deliverable.pdf',100,true,'${ids.admin}');`);

await pg.exec(await fs.readFile(new URL('../supabase/002_operations.sql',import.meta.url),'utf8'));

await pg.exec(await fs.readFile(new URL('../supabase/003_business.sql',import.meta.url),'utf8'));
let passed=0;
const q=async(s,p=[])=>(await pg.query(s,p)).rows;const one=async(s,p=[])=>(await q(s,p))[0];
async function user(id){await pg.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);select set_config('request.jwt.claim.role','authenticated',false);set role authenticated;`);}
function eq(a,b,t){assert.deepEqual(a,b,t);passed++;console.log('PASS',t);}
async function deny(s,p,t){await assert.rejects(()=>q(s,p),undefined,t);passed++;console.log('PASS',t);}
await pg.exec(await fs.readFile(new URL('../supabase/004_service_work.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/005_workspace.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/006_calendar_estimates.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/007_orders_agreements.sql',import.meta.url),'utf8'));
await user(ids.admin);

await pg.exec('reset role');
await pg.exec(await fs.readFile(new URL('../supabase/008_attendance.sql',import.meta.url),'utf8'));
await pg.exec('reset role');
await pg.exec(await fs.readFile(new URL('../supabase/009_billing.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/010_billing_automation.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/011_it_operations.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/012_assigned_work.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/013_portal_reminders.sql',import.meta.url),'utf8'));

await user(ids.admin);
const task=(await one("select id from tasks where title='Shared task'")).id;
const hidden=(await one("select id from tasks where title='Private task'")).id;
const other=(await one("select id from tasks where project_id=$1",[ids.pb])).id;
await q("update tasks set assignee=$1,deadline=(now() at time zone 'UTC')::date where id=$2",[ids.team,task]);
const sa=(await one("select save_client_site(null,null,$1,'A site','Lahore','Reception',true) id",[ids.a])).id;
const sb=(await one("select save_client_site(null,null,$1,'B site','Other','Private contact',true) id",[ids.b])).id;
const asset=(await one("insert into equipment(company_id,name,site_id) values($1,'Assigned router',$2) returning id",[ids.a,sa])).id;
const secretAsset=(await one("insert into equipment(company_id,name,site_id) values($1,'Unassigned server',$2) returning id",[ids.b,sb])).id;
await q('update tasks set equipment_id=$1 where id=$2',[asset,task]);
const item=(await one("insert into task_items(task_id,title) values($1,'Verify connectivity') returning id",[task])).id;
await user(ids.team);
eq((await q('select id from projects')).map(r=>r.id),[ids.pa],'Technician sees only assigned project');
eq((await q('select id from tasks')).map(r=>r.id),[task],'Task-only assignment does not grant other tasks in project');
eq((await q('select id from companies')).map(r=>r.id),[ids.a],'Only related company visible');
eq((await q('select id from client_sites')).map(r=>r.id),[sa],'Only related site visible');
eq((await q('select id from equipment')).map(r=>r.id),[asset],'Only assigned asset visible');
eq((await q('select id from profiles')).map(r=>r.id),[ids.team],'Other staff accounts hidden');
eq((await q('update tasks set status=\'Done\' where id=$1 returning id',[task])).length,0,'Technician cannot bypass completion review with direct task update');
eq((await q('update projects set title=\'Forged\' where id=$1 returning id',[ids.pa])).length,0,'Technician cannot alter project');
await deny("insert into project_assignments(project_id,technician_id) values($1,$2)",[ids.pb,ids.team],'Technician cannot assign self');
await deny("select bulk_update_tasks($1,$2,'{\"status\":\"Done\"}')",[ids.pb,[other]],'Bulk RPC blocks unassigned changes');
await deny("select import_tasks($1,gen_random_uuid(),'[]')",[ids.pb],'Import RPC administrator only');
await deny('select generate_maintenance()',[],'Technician cannot run global generator');
await deny("select save_task_completion($1,null,'Other work','{}')",[other],'Unassigned completion denied');
await deny("select record_work(gen_random_uuid(),$1,null,$2,current_date,20,'On site','Forged work','',false)",[ids.pb,other],'Unassigned work RPC denied');
await deny('select technician_checklist($1,true)',[crypto.randomUUID()],'Unknown checklist denied');
await q("select save_task_completion($1,null,'Router connectivity restored','{}')",[task]);
await deny("select task_completion_action($1,1,'Submit','')",[task],'Incomplete checklist blocks submission');
await q('select technician_checklist($1,true)',[item]);
const evidence=crypto.randomUUID(),path=`${ids.pa}/new-evidence.png`;
await q("insert into storage.objects(bucket_id,name,owner_id) values('project-files',$1,$2)",[path,ids.team]);
await q("insert into files(id,project_id,name,path,size,deliverable,published) values($1,$2,'Evidence.png',$3,100,true,true)",[evidence,ids.pa,path]);
eq((await one('select published,deliverable from files where id=$1',[evidence])),{published:false,deliverable:false},'Technician cannot publish uploads by forging flags');
const log=(await one("select record_work(gen_random_uuid(),$1,null,$2,current_date,20,'On site','Router connectivity restored','',false) id",[ids.pa,task])).id;
eq((await one('select published from work_logs where id=$1',[log])).published,false,'Technician work log remains draft');
await q('select save_task_completion($1,1,$2,$3)',[task,'Router restored; evidence attached',[evidence]]);
await q("select task_completion_action($1,2,'Submit','')",[task]);
await deny('select technician_checklist($1,false)',[item],'Submitted checklist locked');
await deny("select save_task_completion($1,3,'Overwrite','{}')",[task],'Submitted work locked');
await deny("select task_completion_action($1,3,'Publish','')",[task],'Technician cannot publish own result');
await user(ids.clientA);
eq((await q('select * from task_completions')).length,0,'Client cannot see submitted work');
eq((await q('select * from files where id=$1',[evidence])).length,0,'Client cannot see draft evidence metadata');
eq((await q('select * from storage.objects where name=$1',[path])).length,0,'Direct storage access blocks draft evidence');
eq((await q('select * from work_logs where id=$1',[log])).length,0,'Client cannot see draft work logs');
await user(ids.admin);
await q("select task_completion_action($1,3,'Return','Check backup link')",[task]);
await user(ids.team);
await q('select save_task_completion($1,4,$2,$3)',[task,'Connectivity and backup verified',[evidence]]);
await q("select task_completion_action($1,5,'Submit','')",[task]);
await user(ids.admin);
await deny("select task_completion_action($1,3,'Publish','')",[task],'Stale review version rejected');
await q("select task_completion_action($1,6,'Publish','')",[task]);
await user(ids.clientA);
eq((await one('select status from task_completions where task_id=$1',[task])).status,'Published','Client sees published result');
eq((await q('select * from storage.objects where name=$1',[path])).length,1,'Client can download published evidence');
eq((await q('select * from work_logs where id=$1',[log])).length,1,'Published work logs visible');
await q("select task_completion_action($1,7,'Request changes','Recheck cable label')",[task]);
await user(ids.team);
await q('select save_task_completion($1,8,$2,$3)',[task,'Cable labelled and connectivity verified',[evidence]]);
await q("select task_completion_action($1,9,'Submit','')",[task]);
await user(ids.admin);await q("select task_completion_action($1,10,'Publish','')",[task]);
await user(ids.clientB);
eq((await q('select * from task_completions')).length,0,'Other company cannot read published result');
await deny("select task_completion_action($1,11,'Confirm','')",[task],'Other client cannot confirm');
await user(ids.clientA);await q("select task_completion_action($1,11,'Confirm','')",[task]);
eq((await one('select status from task_completions where task_id=$1',[task])).status,'Confirmed','Client confirms corrected result');
eq((await q("select * from task_completion_history where task_id=$1 and action='Publish'",[task])).length,2,'Published revision history retained');
await user(ids.admin);
await q('insert into project_assignments(project_id,technician_id) values($1,$2)',[ids.pb,ids.team]);
await user(ids.team);
eq((await q('select id from tasks where project_id=$1',[ids.pb])).length,1,'Explicit project assignment grants project tasks');
await user(ids.admin);await q('delete from project_assignments where project_id=$1 and technician_id=$2',[ids.pb,ids.team]);
await user(ids.team);
eq((await q('select id from projects where id=$1',[ids.pb])).length,0,'Assignment removal revokes project immediately');
eq((await q('select id from tasks where project_id=$1',[ids.pb])).length,0,'Assignment removal revokes tasks immediately');

await user(ids.admin);
const job=(await one("select save_it_job(null,null,'Visit',$1,$2,$3,'Assigned visit',now()+interval '2 hours',now()+interval '3 hours','Verified site','[]','[]','{}') id",[sb,ids.pb,ids.team])).id;
await user(ids.team);
eq((await q('select id from projects where id=$1',[ids.pb])).length,1,'Job assignment grants its related project');
eq((await q('select id from equipment where id=$1',[secretAsset])).length,1,'Job assignment grants assets at its site');
eq((await q('select id from tasks where project_id=$1',[ids.pb])).length,0,'Job without task does not grant other project tasks');
await q("select it_job_action($1,1,'Submit','')",[job]);
await user(ids.admin);await q("select it_job_action($1,2,'Return','Recheck uplink')",[job]);
await user(ids.team);eq((await one('select status from it_jobs where id=$1',[job])).status,'Changes requested','Administrator can return submitted visit');
await user(ids.admin);await q("select it_job_action($1,3,'Cancel','Visit cancelled by client')",[job]);
await user(ids.team);
eq((await q('select id from client_sites where id=$1',[sb])).length,0,'Cancelled job revokes related site');
eq((await q('select id from projects where id=$1',[ids.pb])).length,0,'Cancelled job revokes related project');

await user(ids.admin);
await pg.exec('reset role');
for(const state of ['Submitted','Published','Changes requested']){
 await q('update task_completions set status=$2,version=version+1 where task_id=$1',[task,state]);
 await q('select queue_portal_reminders()');
 eq((await q("select id from portal_reminders where task_id=$1 and event_key like 'task-review:%'",[task])).length>0,true,`${state} completion generates review reminders`);
}
await q("update task_completions set status='Confirmed' where task_id=$1",[task]);
await pg.exec('reset role;alter table tickets disable trigger tickets_sla_stamp');
await q("update tickets set response_due_at=now()-interval '1 hour',resolution_due_at=now()-interval '1 hour' where id=$1",[ids.ticket]);
await pg.exec('alter table tickets enable trigger tickets_sla_stamp');
const targets=Object.fromEntries(['Low','Normal','High','Urgent'].map(x=>[x,{response:60,resolution:120}]));
await q("insert into contracts(company_id,title,status,start_date,end_date,renewal_date,targets) values($1,'Renewal fixture','Active',current_date-30,current_date+30,current_date+15,$2)",[ids.a,targets]);
await user(ids.admin);
await q('select queue_portal_reminders()');
eq((await q('select id from portal_reminders where ticket_id=$1',[ids.ticket])).length>0,true,'SLA breach generates portal reminders');
eq((await q('select id from portal_reminders where contract_id is not null')).length>0,true,'AMC renewal generates portal reminders');
await q("update tasks set status='In progress' where id=$1",[task]);
await q('select queue_portal_reminders()');
const before=Number((await one('select count(*) n from portal_reminders')).n);
await q('select queue_portal_reminders()');
eq(Number((await one('select count(*) n from portal_reminders')).n),before,'Repeated reminder scans do not duplicate alerts');
await user(ids.team);
const reminder=await one('select * from portal_reminders where task_id=$1',[task]);assert.ok(reminder);passed++;console.log('PASS technician receives assigned deadline reminder');
await q('select read_portal_reminder($1)',[reminder.id]);assert.ok((await one('select read_at from portal_reminders where id=$1',[reminder.id])).read_at);passed++;console.log('PASS mark read persists');
await deny('select queue_portal_reminders()',[],'Technician cannot run global reminder scanner');
await q('select save_portal_reminder_preferences(false)');
await user(ids.admin);await q('update tasks set deadline=current_date-3 where id=$1',[task]);await q('select queue_portal_reminders()');
await user(ids.team);eq((await q("select * from portal_reminders where task_id=$1 and event_key like '%overdue'",[task])).length,0,'Opt-out blocks future reminders');
await user(ids.admin);await q('update tasks set assignee=null where id=$1',[task]);
await user(ids.team);
eq((await q('select * from projects')).length,0,'Removing final task assignment revokes project');
eq((await q('select * from portal_reminders')).length,0,'Old reminders disappear when work access revoked');
eq((await q('select * from storage.objects')).length,0,'Revoked technician cannot download project evidence');
await deny('select void_work($1,\'No assignment\')',[log],'Revoked technician cannot mutate old work');
await pg.exec('reset role');
await pg.exec(await fs.readFile(new URL('../supabase/014_crm_foundation.sql',import.meta.url),'utf8'));
await user(ids.admin);
eq((await q('select id from crm_roles')).length,12,'Department roles seeded');
const dept=(await one("select save_crm_configuration('team',null,null,'Support department') id")).id;
await deny("select save_crm_configuration('team',$1,99,'Wrong revision')",[dept],'Stale team changes rejected');
await q("select save_crm_configuration('setting','delay_reasons',1,'Delay reasons',$1)",[JSON.stringify(['Material missing','Access blocked'])]);
await deny("select save_crm_configuration('setting','delay_reasons',2,'Delay reasons',$1)",[JSON.stringify(['Repeat','repeat'])],'Duplicate configuration options rejected');
await q('select set_crm_membership($1,$2,$3,true)',[ids.team,'sales_agent',dept]);
eq((await q('select id from crm_config_history')).length>=3,true,'Configuration changes audited');
eq((await q('select * from customer_history($1)',[ids.a])).length>0,true,'Administrator sees connected customer history');
await user(ids.team);
eq((await one('select my_crm_permissions() p')).p.includes('customer.read'),true,'Department capabilities resolve for current staff only');
await deny("select save_crm_configuration('team',null,null,'Unauthorized department')",[],'Staff cannot create departments');
await deny('select set_crm_membership($1,$2,$3,true)',[ids.team,'accounts',dept],'Staff cannot grant their own permissions');
eq((await q('select * from crm_settings')).length,0,'Administrator configuration private');
eq((await q('select * from crm_memberships')).length,1,'Staff sees only own memberships');
await deny('select * from customer_history($1)',[ids.a],'Department role cannot bypass customer assignment');
await user(ids.admin);await q('insert into project_assignments(project_id,technician_id) values($1,$2)',[ids.pa,ids.team]);
await user(ids.team);
const related=await q('select * from customer_history($1)',[ids.a]);
eq(related.some(r=>r.kind==='Task'),true,'Authorized staff sees assigned customer work');
eq(related.every(r=>r.kind!=='Invoice'&&r.kind!=='Estimate'&&r.kind!=='Contract'),true,'Customer timeline preserves commercial restrictions');
await deny('select * from customer_history($1)',[ids.b],'Customer history blocks unrelated company');
await user(ids.admin);await q('select set_crm_membership($1,$2,$3,false)',[ids.team,'sales_agent',dept]);
await user(ids.team);eq((await one('select my_crm_permissions() p')).p.length,0,'Removed membership clears department capabilities');await deny('select * from customer_history($1)',[ids.a],'Membership removal immediately revokes customer history');
await user(ids.admin);await q('delete from project_assignments where project_id=$1 and technician_id=$2',[ids.pa,ids.team]);
await user(ids.admin);await q('update profiles set active=false where id=$1',[ids.team]);
await user(ids.team);eq((await q('select * from tasks')).length,0,'Disabled technician has no work access');
await user(ids.outsider);eq((await q('select * from projects')).length,0,'Unprofiled account has no project access');
await pg.exec("reset role;select set_config('request.jwt.claim.sub','',false);set role anon;");
await deny('select * from project_assignments',[],'Anonymous cannot read assignments');
await deny('select queue_portal_reminders()',[],'Anonymous cannot invoke reminder scanner');
console.log(`${passed} assigned-work and portal reminder assertions passed`);
await pg.close();
