const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{build}=require('esbuild');
(async()=>{
 const {JSDOM}=await import('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://example.test/portal'});Object.assign(global,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});
 const React=require('react'),{createRoot}=require('react-dom/client');let writes=[],opened=[];const data={task_completions:[],task_completion_history:[],portal_reminders:[{id:'r',user_id:'team',event_key:'x',title:'Assigned task due soon',view:'projects',project_id:'p',created_at:'2026-10-05T10:00Z',read_at:null}],portal_reminder_preferences:[]};
 global.__db={from(table){let filter={};const q={select(){return q},order(){return q},range(){return q},eq(k,v){filter[k]=v;return q},maybeSingle(){q.single=true;return q},then(a,b){const rows=(data[table]||[]).filter(r=>Object.entries(filter).every(([k,v])=>r[k]===v));return Promise.resolve({data:q.single?rows[0]||null:rows,error:null}).then(a,b)}};return q},rpc:async(name,args)=>{writes.push({name,args});if(name==='save_task_completion')data.task_completions=[{id:'c',task_id:'t',project_id:'p',version:1,status:'Draft',summary:args.p_summary,evidence:args.p_evidence}];if(name==='task_completion_action')data.task_completions[0]={...data.task_completions[0],version:args.p_version+1,status:args.p_action==='Submit'?'Submitted':args.p_action==='Publish'?'Published':'Confirmed'};if(name==='read_portal_reminder')data.portal_reminders[0].read_at=new Date().toISOString();return {data:null,error:null}}};
 const dir=fs.mkdtempSync(path.join(__dirname,'assigned-ui-')),file=path.join(dir,'bundle.cjs');await build({stdin:{contents:"export {TaskCompletion,ProjectAssignments} from './src/portal/assigned-work';export {PortalReminders} from './src/portal/reminders';export {OperationalReports} from './src/portal/operational-reports';export {navigationGroups} from './src/portal/navigation'",resolveDir:process.cwd(),loader:'tsx'},bundle:true,platform:'node',outfile:file,loader:{'.css':'empty'},plugins:[{name:'mock',setup(b){b.onResolve({filter:/^react$/},()=>({path:require.resolve('react'),external:true}));b.onResolve({filter:/^\.\/client$/},()=>({path:'client',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const db=globalThis.__db;export function check(r){if(r.error)throw r.error;return r.data}',loader:'js'}));b.onResolve({filter:/^\.\/report-export$/},()=>({path:'pdf',namespace:'pdf'}));b.onLoad({filter:/.*/,namespace:'pdf'},()=>({contents:'export async function downloadReportPDF(...args){globalThis.__pdf=args}',loader:'js'}));}}]});
 const {TaskCompletion,PortalReminders,OperationalReports,navigationGroups}=require(file),root=createRoot(document.getElementById('root'));const flush=fn=>React.act(async()=>{await fn();await new Promise(r=>setTimeout(r,10));});let passed=0;const pass=s=>{passed++;console.log('PASS',s)};const click=async text=>{const el=[...document.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(el,text);await flush(()=>el.click());};
 const props={projectId:'p',tasks:[{id:'t',title:'Restore network',project_id:'p',internal:false}],items:[{id:'ci',task_id:'t',title:'Verify link',done:true}],files:[{id:'f',name:'Evidence.png'}],refresh:async()=>{}};
 await flush(()=>root.render(React.createElement(TaskCompletion,{...props,profile:{id:'team',role:'team'}})));assert.doesNotMatch(document.body.textContent,/Publish task result|Assign project/);await click('Record work & evidence');let form=document.querySelector('form');form.elements.namedItem('summary').value='Network restored';form.elements.namedItem('evidence').checked=true;await flush(()=>form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.equal(writes.at(-1).name,'save_task_completion');assert.deepEqual(writes.at(-1).args.p_evidence,['f']);pass('Technician records work with selected private evidence');
 await click('Submit task completion');assert.deepEqual(writes.at(-1).args,{p_task:'t',p_version:1,p_action:'Submit',p_note:''});assert.doesNotMatch(document.body.textContent,/Record work & evidence/);pass('Submit carries version and locks work editor');
 await flush(()=>root.render(React.createElement(TaskCompletion,{...props,key:'admin',profile:{id:'admin',role:'admin'}})));await click('Publish task result to client');assert.equal(writes.at(-1).args.p_action,'Publish');pass('Administrator can publish submitted result');
 await flush(()=>root.render(React.createElement(TaskCompletion,{...props,key:'client',profile:{id:'client',role:'client'}})));assert.doesNotMatch(document.body.textContent,/Record work & evidence|Submit task completion|Publish task/);await click('Confirm task completion');assert.equal(writes.at(-1).args.p_action,'Confirm');pass('Client can review published result without staff controls');
 await flush(()=>root.render(React.createElement(PortalReminders,{profile:{id:'team',role:'team'},onOpen:(...a)=>opened.push(a)})));assert.doesNotMatch(document.body.textContent,/Check reminders now|Email service alerts|SMS service alerts/);await click('Open work');assert.deepEqual(opened.at(-1),['projects','p']);await click('Mark read');assert.equal(writes.at(-1).name,'read_portal_reminder');assert.match(document.body.textContent,/0 unread/);pass('Reminder links assigned work and persists read state');
 const reports={tasks:[{id:'t',project_id:'p',title:'A task',status:'In progress',priority:'High',created_at:'2026-10-04'},{id:'other',project_id:'other',title:'B task',status:'Done',created_at:'2026-10-04'}]};
 await flush(()=>root.render(React.createElement(OperationalReports,{data:reports,companies:[{id:'a',name:'A'},{id:'b',name:'B'}],projects:[{id:'p',company_id:'a',title:'A project'},{id:'other',company_id:'b',title:'B project'}]})));const company=[...document.querySelectorAll('select')].find(s=>s.parentElement.textContent.startsWith('Company'));await flush(()=>{company.value='a';company.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});await click('Download filtered PDF');assert.equal(global.__pdf[3][0].rows.length,1);assert.equal(global.__pdf[3][0].rows[0][0],'t');pass('PDF export matches filtered on-screen report');
 const dates=document.querySelectorAll('input[type=date]');await flush(()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(dates[0],'2026-10-10');dates[0].dispatchEvent(new dom.window.Event('input',{bubbles:true}));});await flush(()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(dates[1],'2026-10-01');dates[1].dispatchEvent(new dom.window.Event('input',{bubbles:true}));});assert.ok([...document.querySelectorAll('button')].find(b=>b.textContent==='Download filtered PDF').disabled);assert.match(document.body.textContent,/Start date must not follow/);pass('Reversed report dates block exports');
 const teamViews=navigationGroups('team').flatMap(g=>g.items.map(i=>i.view));assert.ok(!teamViews.some(v=>['clients','directory','billing','renewals'].includes(v)));pass('Technician navigation hides unrelated administrative and commercial modules');
 await flush(()=>root.unmount());dom.window.close();fs.rmSync(dir,{recursive:true,force:true});console.log(`${passed} assigned-work interface assertions passed`);
})().catch(e=>{console.error(e);process.exit(1)});
