const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{build}=require('esbuild');
(async()=>{const {JSDOM}=await import('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://example.test/portal'});Object.assign(global,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});const React=require('react'),{createRoot}=require('react-dom/client');let writes=[],reads=[];const data={projects:[{id:'p',title:'Network',status:'Planning',company_id:'c'}],tasks:[{id:'t',project_id:'p',title:'Install router',start_date:'2026-10-01',deadline:'2026-10-05',status:'To do',collaborators:['team']}],tickets:[],invoices:[{id:'i',status:'Issued',currency:'PKR',total:100},{id:'usd',status:'Issued',currency:'USD',total:10}],payment_claims:[{id:'pay',invoice_id:'i',status:'Verified',amount:25},{id:'pending',invoice_id:'i',status:'Pending',amount:50}],workspace_activity:[],client_contacts:[]};global.__db={from(table){reads.push(table);let values;const q={select(){return q},order(){return q},range(){return q},limit(){return q},eq(){return q},update(v){values=v;writes.push({table,values:v});return q},single(){return q},then(a,b){return Promise.resolve({data:values||data[table]||[],error:null}).then(a,b)}};return q},rpc:async(name,args)=>{writes.push({name,args});return {data:1,error:null}}};
const dir=fs.mkdtempSync(path.join(__dirname,'workspace-ui-')),file=path.join(dir,'bundle.cjs');await build({entryPoints:[path.resolve(__dirname,'../src/portal/attendance.tsx')],bundle:true,platform:'node',outfile:file,loader:{'.css':'empty'},plugins:[{name:'test',setup(b){b.onResolve({filter:/^react$/},()=>({path:require.resolve('react'),external:true}));b.onResolve({filter:/^\.\/client$/},()=>({path:'client',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const db=globalThis.__db;export function check(r){if(r.error)throw r.error;return r.data}',loader:'js'}));}}]});const {Attendance}=require(file),root=createRoot(document.getElementById('root'));const flush=fn=>React.act(async()=>{await fn();await new Promise(r=>setTimeout(r,20));});let passed=0;const pass=s=>{passed++;console.log('PASS',s)};const click=async text=>{const el=[...document.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(el);await flush(()=>el.click());};

data.attendance_entries=[{id:'a',user_id:'team',checked_in:'2026-09-30T03:00:00Z',checked_out:'2026-09-30T11:00:00Z',version:2,voided:false},{id:'b',user_id:'team',checked_in:'2026-08-31T20:00:00Z',checked_out:'2026-08-31T21:00:00Z',version:1,voided:false},{id:'c',user_id:'team',checked_in:'2026-09-29T03:00:00Z',checked_out:'2026-09-29T11:00:00Z',version:1,voided:true}];data.attendance_history=[];
const members=[{id:'team',role:'team',name:'Engineer'},{id:'admin',role:'admin',name:'Admin'}];
await flush(()=>root.render(React.createElement(Attendance,{profile:{id:'team',role:'team'},members})));
assert.match(document.body.textContent,/9.00 recorded hours/);pass('Pakistan month includes boundary session and excludes void hours');
assert.doesNotMatch(document.body.textContent,/Add missed attendance|Correct entry/);pass('Staff hides administrator correction controls');
await click('Check in');assert.equal(writes.at(-1).name,'attendance_clock');assert.equal(writes.at(-1).args.p_action,'in');pass('Staff check in uses checked RPC');
data.attendance_entries.push({id:'open',user_id:'team',checked_in:'2026-09-30T12:00:00Z',checked_out:null,version:3,voided:false});
await flush(()=>root.render(React.createElement(Attendance,{key:'open',profile:{id:'team',role:'team'},members})));await click('Check out');assert.equal(writes.at(-1).args.p_id,'open');assert.equal(writes.at(-1).args.p_version,3);pass('Check out targets current entry version');
await flush(()=>root.render(React.createElement(Attendance,{key:'admin',profile:{id:'admin',role:'admin'},members})));await click('Add missed attendance');const form=document.querySelector('form');form.elements.namedItem('user').value='team';form.elements.namedItem('start').value='2026-09-28T09:00';form.elements.namedItem('end').value='2026-09-28T17:00';form.elements.namedItem('reason').value='Missed clock';await flush(()=>form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.equal(writes.at(-1).name,'correct_attendance');assert.equal(writes.at(-1).args.p_in,'2026-09-28T04:00:00.000Z');pass('Correction converts Pakistan input to UTC');
await flush(()=>root.unmount());dom.window.close();fs.rmSync(dir,{recursive:true,force:true});console.log(`${passed} attendance UI assertions passed`);})().catch(e=>{console.error(e);process.exit(1)});
