import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema storage;create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to authenticated;
`);
await pg.exec(await fs.readFile(new URL('../supabase/001_portal.sql', import.meta.url),'utf8'));
const ids={admin:'00000000-0000-0000-0000-000000000001',clientA:'00000000-0000-0000-0000-000000000002',clientB:'00000000-0000-0000-0000-000000000003',team:'00000000-0000-0000-0000-000000000004',outsider:'00000000-0000-0000-0000-000000000005',a:'10000000-0000-0000-0000-000000000001',b:'10000000-0000-0000-0000-000000000002',pa:'20000000-0000-0000-0000-000000000001',pb:'20000000-0000-0000-0000-000000000002',ticket:'30000000-0000-0000-0000-000000000001',file:'40000000-0000-0000-0000-000000000001',fileb:'40000000-0000-0000-0000-000000000002'};
await pg.exec(`insert into auth.users values ('${ids.admin}'),('${ids.clientA}'),('${ids.clientB}'),('${ids.team}'),('${ids.outsider}');
insert into companies values ('${ids.a}','A'),('${ids.b}','B');
insert into profiles values('${ids.admin}','Admin','admin',null),('${ids.clientA}','Client A','client','${ids.a}'),('${ids.clientB}','Client B','client','${ids.b}'),('${ids.team}','Team','team',null);
insert into projects(id,company_id,title) values('${ids.pa}','${ids.a}','A project'),('${ids.pb}','${ids.b}','B project');
insert into tasks(project_id,title,internal) values('${ids.pa}','Shared task',false),('${ids.pa}','Private task',true),('${ids.pb}','Other client task',false);
insert into milestones(project_id,title) values('${ids.pa}','A milestone'),('${ids.pb}','B milestone');
insert into messages(project_id,body,internal,author_id) values('${ids.pa}','Shared comment',false,'${ids.admin}'),('${ids.pa}','Internal comment',true,'${ids.admin}'),('${ids.pb}','B comment',false,'${ids.admin}');
insert into tickets(id,project_id,title,description,priority,author_id) values('${ids.ticket}','${ids.pb}','B ticket','Description','Normal','${ids.clientB}');
insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/deliverable.pdf','${ids.admin}'),('project-files','${ids.pb}/deliverable.pdf','${ids.admin}');
insert into files(id,project_id,name,path,size,deliverable,author_id) values('${ids.file}','${ids.pa}','A.pdf','${ids.pa}/deliverable.pdf',100,true,'${ids.admin}'),('${ids.fileb}','${ids.pb}','B.pdf','${ids.pb}/deliverable.pdf',100,true,'${ids.admin}');`);

await pg.exec(await fs.readFile(new URL('../supabase/002_operations.sql',import.meta.url),'utf8'));

await pg.exec(await fs.readFile(new URL('../supabase/003_business.sql',import.meta.url),'utf8'));
let passed=0;
const q=async(s,p=[])=>(await pg.query(s,p)).rows;const one=async(s,p=[])=>(await q(s,p))[0];
async function user(id){await pg.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);select set_config('request.jwt.claim.role','authenticated',false);set role authenticated;`);}
function eq(a,b,t){assert.deepEqual(a,b,t);passed++;console.log('PASS',t);}
async function deny(s,p,t){await assert.rejects(()=>q(s,p),undefined,t);passed++;console.log('PASS',t);}
await pg.exec(await fs.readFile(new URL('../supabase/004_service_work.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/005_workspace.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/006_calendar_estimates.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/007_orders_agreements.sql',import.meta.url),'utf8'));
await user(ids.admin);

await pg.exec('reset role');
await pg.exec(await fs.readFile(new URL('../supabase/008_attendance.sql',import.meta.url),'utf8'));
await user(ids.team);
const clock=async(action='in',id=null,version=null)=>one('select attendance_clock($1,$2,$3) id',[action,id,version]);
const entry=(await clock()).id;
eq((await clock()).id,entry,'Repeated check in returns open session');
eq((await q('select * from attendance_entries')).length,1,'Staff reads own attendance');
await deny('update attendance_entries set checked_out=now() where id=$1',[entry],'Direct attendance writes denied');
await deny('select attendance_clock($1,$2,$3)',['out',entry,99],'Stale check out rejected');
await user(ids.admin);
eq((await q('select * from attendance_entries')).length,1,'Administrator reads staff attendance');
const correction=async(id=entry,version=1,userId=ids.team,start='2026-09-29T03:00:00Z',end='2026-09-29T11:00:00Z',voided=false,reason='Missed clock')=>one('select correct_attendance($1,$2,$3,$4,$5,$6,$7) id',[id,version,userId,start,end,voided,reason]);
await correction();
eq((await one('select version from attendance_entries where id=$1',[entry])).version,2,'Correction increments version');
eq((await q('select * from attendance_history')).length,2,'Correction preserves audit history');
await assert.rejects(()=>correction());passed++;console.log('PASS Stale correction rejected');
await assert.rejects(()=>correction(null,null,ids.clientA));passed++;console.log('PASS Client attendance cannot be added');
await assert.rejects(()=>correction(null,null,ids.team,'2099-01-01','2099-01-02'));passed++;console.log('PASS Future attendance denied');
await assert.rejects(()=>correction(null,null,ids.team,'2026-09-29T04:00:00Z','2026-09-29T05:00:00Z'));passed++;console.log('PASS Overlapping attendance denied');
await assert.rejects(()=>correction(entry,2,ids.team,'2026-09-29T03:00:00Z','2026-09-29T11:00:00Z',false,''));passed++;console.log('PASS Reason required');
await assert.rejects(()=>correction(null,null,ids.team,'2026-09-20','2026-09-23'));passed++;console.log('PASS Overlong session denied');
await assert.rejects(()=>correction(entry,2,ids.admin));passed++;console.log('PASS Entry owner immutable');
await user(ids.clientA);eq((await q('select * from attendance_entries')).length,0,'Client cannot read attendance');
eq((await q('select * from attendance_history')).length,0,'Client cannot read history');
await assert.rejects(()=>clock());passed++;console.log('PASS Client cannot check in');
await assert.rejects(()=>correction());passed++;console.log('PASS Client cannot correct attendance');
await user(ids.admin);const adminEntry=(await clock()).id;
await user(ids.team);eq((await q('select * from attendance_entries')).length,1,'Staff cannot read other staff attendance');
await assert.rejects(()=>clock('out',adminEntry,1));passed++;console.log('PASS Staff cannot check out another user');
await assert.rejects(()=>correction(entry,2));passed++;console.log('PASS Team cannot correct attendance');
const next=(await clock()).id;eq(next!==entry,true,'Closed entry permits next check in');
await pg.exec('reset role');await pg.query("update attendance_entries set checked_in=now()-interval '1 hour' where id=$1",[next]);
await user(ids.team);await clock('out',next,1);eq((await clock('out',next,1)).id,next,'Repeated check out returns original');
await user(ids.admin);await correction(entry,2,ids.team,'2026-09-29T03:00:00Z','2026-09-29T11:00:00Z',true,'Duplicate record');
eq((await one('select voided from attendance_entries where id=$1',[entry])).voided,true,'Void retains record');
eq((await q('select * from attendance_history where entry_id=$1',[entry])).length,3,'Void preserves audit history');
await pg.exec('reset role');await pg.query('update profiles set active=false where id=$1',[ids.team]);
await user(ids.team);eq((await q('select * from attendance_entries')).length,0,'Disabled staff loses read access');
await assert.rejects(()=>clock());passed++;console.log('PASS Disabled staff cannot check in');
console.log(passed+' attendance assertions passed');await pg.close();
