import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema storage;create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to authenticated;
`);
await pg.exec(await fs.readFile(new URL('../supabase/001_portal.sql', import.meta.url),'utf8'));
const ids={admin:'00000000-0000-0000-0000-000000000001',clientA:'00000000-0000-0000-0000-000000000002',clientB:'00000000-0000-0000-0000-000000000003',team:'00000000-0000-0000-0000-000000000004',outsider:'00000000-0000-0000-0000-000000000005',a:'10000000-0000-0000-0000-000000000001',b:'10000000-0000-0000-0000-000000000002',pa:'20000000-0000-0000-0000-000000000001',pb:'20000000-0000-0000-0000-000000000002',ticket:'30000000-0000-0000-0000-000000000001',file:'40000000-0000-0000-0000-000000000001',fileb:'40000000-0000-0000-0000-000000000002'};
await pg.exec(`insert into auth.users values ('${ids.admin}'),('${ids.clientA}'),('${ids.clientB}'),('${ids.team}'),('${ids.outsider}');
insert into companies values ('${ids.a}','A'),('${ids.b}','B');
insert into profiles values('${ids.admin}','Admin','admin',null),('${ids.clientA}','Client A','client','${ids.a}'),('${ids.clientB}','Client B','client','${ids.b}'),('${ids.team}','Team','team',null);
insert into projects(id,company_id,title) values('${ids.pa}','${ids.a}','A project'),('${ids.pb}','${ids.b}','B project');
insert into tasks(project_id,title,internal) values('${ids.pa}','Shared task',false),('${ids.pa}','Private task',true),('${ids.pb}','Other client task',false);
insert into milestones(project_id,title) values('${ids.pa}','A milestone'),('${ids.pb}','B milestone');
insert into messages(project_id,body,internal,author_id) values('${ids.pa}','Shared comment',false,'${ids.admin}'),('${ids.pa}','Internal comment',true,'${ids.admin}'),('${ids.pb}','B comment',false,'${ids.admin}');
insert into tickets(id,project_id,title,description,priority,author_id) values('${ids.ticket}','${ids.pb}','B ticket','Description','Normal','${ids.clientB}');
insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/deliverable.pdf','${ids.admin}'),('project-files','${ids.pb}/deliverable.pdf','${ids.admin}');
insert into files(id,project_id,name,path,size,deliverable,author_id) values('${ids.file}','${ids.pa}','A.pdf','${ids.pa}/deliverable.pdf',100,true,'${ids.admin}'),('${ids.fileb}','${ids.pb}','B.pdf','${ids.pb}/deliverable.pdf',100,true,'${ids.admin}');`);

await pg.exec(await fs.readFile(new URL('../supabase/002_operations.sql',import.meta.url),'utf8'));

await pg.exec(await fs.readFile(new URL('../supabase/003_business.sql',import.meta.url),'utf8'));
let passed=0;
const q=async(s,p=[])=>(await pg.query(s,p)).rows;const one=async(s,p=[])=>(await q(s,p))[0];
async function user(id){await pg.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);select set_config('request.jwt.claim.role','authenticated',false);set role authenticated;`);}
function eq(a,b,t){assert.deepEqual(a,b,t);passed++;console.log('PASS',t);}
async function deny(s,p,t){await assert.rejects(()=>q(s,p),undefined,t);passed++;console.log('PASS',t);}
await user(ids.admin);
const batch='50000000-0000-0000-0000-000000000001';const rows=[{title:'Imported',priority:'High',status:'To do',assignee_id:ids.team,internal:false}];
eq((await one('select import_tasks($1,$2,$3) n',[ids.pa,batch,rows])).n,1,'Bulk import saves rows');
eq((await one('select import_tasks($1,$2,$3) n',[ids.pa,batch,rows])).n,1,'Retry same batch is idempotent');
eq((await q("select * from tasks where title='Imported'")).length,1,'No duplicate on retry');
await deny('select import_tasks($1,$2,$3)',[ids.pb,batch,rows],'Reused batch cannot change project');
await deny('select import_tasks($1,$2,$3)',[ids.pa,'50000000-0000-0000-0000-000000000002',[{title:'Rollback me'},{title:''}]],'Invalid import rolls back all rows');
eq((await q("select * from tasks where title='Rollback me'")).length,0,'Atomic import rollback');
await user(ids.clientA);await deny('select import_tasks($1,$2,$3)',[ids.pa,'50000000-0000-0000-0000-000000000003',rows],'Client cannot import');
await deny('select generate_maintenance()',[],'Client cannot execute scheduler');await deny('select queue_due_alerts()',[],'Client cannot queue global notifications');
await deny("select claim_notifications(array['email'])",[],'Client cannot claim outbound messages');
await user(ids.admin);
const lines=[{description:'Service',quantity:2,unit_price:100.10,tax_percent:5}];
let inv=(await one("select save_invoice(null,$1,'PKR',current_date,current_date+10,'Notes','Bank details',$2) id",[ids.a,lines])).id;
let v=await one('select * from invoices where id=$1',[inv]);eq(Number(v.total),210.21,'Server computes rounded invoice totals');
await user(ids.clientA);eq((await q('select * from invoices')).length,0,'Client cannot see draft invoices');
await user(ids.team);eq((await q('select * from invoices')).length,0,'Team cannot read financial records');await deny('select invoice_action($1,$2)',[inv,'issue'],'Team cannot issue invoices');
await user(ids.admin);await q('select invoice_action($1,$2)',[inv,'issue']);
await deny("select save_invoice($1,$2,'PKR',current_date,current_date+10,'','Bank',$3)",[inv,ids.a,lines],'Issued invoice cannot be changed');
await deny('update invoices set total=1 where id=$1',[inv],'Direct invoice totals cannot be forged');
await user(ids.clientB);eq((await q('select * from invoices')).length,0,'Client B cannot read A invoice');await deny("select submit_payment($1,10,'wrong',current_date,'')",[inv],'Cross-client payment blocked');
await user(ids.clientA);eq((await q('select * from invoice_items')).length,1,'Client sees own issued invoice lines');
let claim=(await one("select submit_payment($1,100,'BANK-1',current_date,'partial') id",[inv])).id;
await deny("select submit_payment($1,120,'BANK-2',current_date,'')",[inv],'Pending amounts prevent oversubmission');
await deny("select review_payment($1,'verify','')",[claim],'Client cannot verify payment');
await deny("update payment_claims set status='Verified' where id=$1",[claim],'Client cannot forge receipt');
await user(ids.admin);await q("select review_payment($1,'verify','Bank checked')",[claim]);eq((await one('select status from payment_claims where id=$1',[claim])).status,'Verified','Administrator verifies receipt');
await deny("select review_payment($1,'verify','')",[claim],'Repeated verification rejected');
await deny("select invoice_action($1,'void')",[inv],'Verified payment blocks invoice void');
await deny("select review_payment($1,'reverse','')",[claim],'Reversal requires reason');
await q("select review_payment($1,'reverse','Entered in error')",[claim]);eq((await one('select status from payment_claims where id=$1',[claim])).status,'Reversed','Reversal preserves history');
await q("select invoice_action($1,'void')",[inv]);eq((await q('select * from billing_events where invoice_id=$1',[inv])).length,6,'Billing history records every action');
await user(ids.team);
let plan=(await one("insert into maintenance_plans(project_id,title,frequency,anchor_date,next_due,end_date,lead_days,assignee,checklist) values($1,'Month end','Monthly','2026-01-31','2026-01-31','2026-03-31',0,$2,jsonb_build_array('Inspect','Clean')) returning id",[ids.pa,ids.team])).id;
eq((await one('select generate_maintenance() n')).n,3,'Monthly plan generates three occurrences');
eq((await q('select due_on::text d from maintenance_runs where plan_id=$1 order by due_on',[plan])).map(r=>r.d),['2026-01-31','2026-02-28','2026-03-31'],'Month end retains original anchor day');
eq((await one('select generate_maintenance() n')).n,0,'Repeated generation is idempotent');
eq((await q('select * from task_items')).length,6,'Generated tasks inherit checklists');
await deny("update maintenance_plans set next_due='2020-01-01' where id=$1",[plan],'Browser cannot rewind scheduler');
await user(ids.clientB);eq((await q('select * from maintenance_plans')).length,0,'Other client cannot read maintenance plan');
await user(ids.clientA);eq((await q('select * from maintenance_runs')).length,3,'Client can see shared maintenance runs');
await user(ids.team);await q('update maintenance_plans set internal=true where id=$1',[plan]);
await user(ids.clientA);eq((await q('select * from maintenance_plans')).length,0,'Internal maintenance plans hidden');
await q("select save_notification_preferences(true,true,true,'+923001234567')");
await deny("select save_notification_preferences(false,true,false,'123')",[],'Invalid SMS phone rejected');
await user(ids.admin);await q("select save_notification_preferences(true,false,false,'')");
await q("insert into tasks(project_id,title,assignee) values($1,'notify', $2)",[ids.pa,ids.admin]);
eq((await q("select * from notifications where event_type='Task assigned'")).length,1,'Task assignment queues opted in staff');
let inv2=(await one("select save_invoice(null,$1,'PKR',current_date,current_date,'','Bank',$2) id",[ids.a,lines])).id;
await q("select invoice_action($1,'issue')",[inv2]);
eq((await q("select * from notifications where event_type='Invoice issued'")).length,4,'Issued invoice queues client channels and admin email');
await user(ids.clientB);eq((await q('select * from notifications')).length,0,'Other client cannot read notification queue');
await user(ids.clientA);eq((await q('select * from notifications')).length,3,'Client sees only own notification entries');
await deny("insert into notifications(user_id,event_key,event_type,channel) values($1,'forged','test','sms')",[ids.admin],'Client cannot forge outgoing notifications');
await pg.exec(`reset role;select set_config('request.jwt.claim.sub','',false);select set_config('request.jwt.claim.role','service_role',false);set role service_role;`);
eq((await q("select * from claim_notifications(array['email'])")).length,3,'Worker atomically claims configured channels');
eq((await q("select * from claim_notifications(array['email'])")).length,0,'Second worker cannot claim in-flight notifications');
eq((await q("select * from notifications where status='Unconfigured'")).length,2,'Unavailable channels clearly marked');
await pg.exec(`reset role;select set_config('request.jwt.claim.role','authenticated',false);update profiles set active=false where id='${ids.clientA}';`);
await user(ids.clientA);eq((await q('select * from invoices')).length,0,'Disabled client loses billing access');
eq((await q('select * from notifications')).length,0,'Disabled client loses notifications');
await user(ids.admin);
await q("insert into maintenance_plans(project_id,title,frequency,anchor_date,next_due,end_date,lead_days,assignee) values($1,'Inactive owner','Daily',current_date,current_date,current_date,0,$2)",[ids.pa,ids.team]);
await pg.exec(`reset role;update profiles set active=false where id='${ids.team}';select set_config('request.jwt.claim.sub','',false);select set_config('request.jwt.claim.role','service_role',false);set role service_role;`);
eq((await one('select generate_maintenance() n')).n,1,'Service scheduler handles inactive assignee');
await pg.exec('reset role');eq((await one("select assignee from tasks where title like 'Inactive owner%' ")).assignee,null,'Inactive assignee generates unassigned task');
console.log(`${passed} business database assertions passed`);await pg.close();
