const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const {build}=require('esbuild');
(async()=>{
 const {JSDOM}=await import('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/portal'});
 Object.assign(global,{window:dom.window,document:dom.window.document,DOMParser:dom.window.DOMParser,HTMLElement:dom.window.HTMLElement,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});
 const dir=fs.mkdtempSync(path.resolve('../../business-qa-'));const out=path.join(dir,'utils.cjs');
 await build({entryPoints:[path.resolve('src/portal/business-utils.ts')],bundle:true,platform:'node',outfile:out});const utils=require(out);let n=0;
 const pass=t=>{n++;console.log('PASS',t)};
 assert.deepEqual(utils.parseCSV('title,priority\r\n"Fix, router",High\r\n"Two\nlines",Normal'),[['title','priority'],['Fix, router','High'],['Two\nlines','Normal']]);pass('CSV quoting CRLF and multiline fields');
 assert.throws(()=>utils.parseCSV('title\n"bad'));pass('Malformed CSV rejected');
 assert.ok(utils.csvText([['=1+1','+cmd','@SUM(A1)','normal']]).includes("'=1+1"));pass('CSV export neutralizes spreadsheet formulas');
 const parsed=utils.validateImport([['title','deadline','internal'],['Inspect','2026-02-30','false']],[]);assert.equal(parsed.errors.length,1);pass('Impossible date rejected');
 assert.equal(utils.validateImport([['title','assignee_id'],['Inspect','missing']],[]).errors.length,1);pass('Unknown assignee rejected');
 assert.throws(()=>utils.validateImport([['title','title'],['a','b']],[]));pass('Duplicate headers rejected');
 assert.throws(()=>utils.validateImport([['title'],...Array.from({length:501},()=>['x'])],[]));pass('Import row cap enforced');
 const buffer=fs.readFileSync(path.resolve('tests/fixtures/tasks.xlsx'));const xrows=await utils.readXLSX(buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength));assert.deepEqual(xrows,[['title','deadline'],['Inspect router','2026-12-01']]);pass('Real compressed XLSX reads shared and inline strings');
 const bad=fs.readFileSync(path.resolve('tests/fixtures/formula.xlsx'));await assert.rejects(()=>utils.readXLSX(bad.buffer.slice(bad.byteOffset,bad.byteOffset+bad.byteLength)),/formulas/);pass('XLSX formulas rejected');
 const rpt=utils.reportRows([{id:'1',project_id:'a',created_at:'2026-01-01T00:00:00Z',response_due_at:'2026-01-01T00:01:00Z',status:'Resolved'},{id:'2',project_id:'b',created_at:'2026-01-01T00:00:00Z'}],'2026-01-01','2026-01-01','A',[{id:'a',company_id:'A'},{id:'b',company_id:'B'}],Date.now());assert.equal(rpt.length,1);assert.equal(rpt[0].response_result,'Closed without reply');pass('SLA report scopes company and treats unanswered closure as failure');
 const paused={project_id:'a',created_at:'2026-01-01',status:'Waiting on client',sla_paused_at:'2026-01-01T00:00:00Z',response_due_at:'2026-01-01T00:10:00Z',resolution_due_at:'2026-01-01T01:00:00Z'};
 const pausedReport=utils.reportRows([paused],'','','',[{id:'a'}],Date.parse('2026-01-02'))[0];assert.equal(pausedReport.response_result,'Paused');assert.equal(pausedReport.resolution_result,'Paused');pass('Report clocks freeze at waiting entry');
 const breachedReport=utils.reportRows([{...paused,response_due_at:'2025-12-31T23:00:00Z'}],'','','',[{id:'a'}],Date.parse('2026-01-02'))[0];assert.equal(breachedReport.response_result,'Overdue');pass('Reports preserve breaches predating wait');
 const workerOut=path.join(dir,'worker.cjs');await build({entryPoints:[path.resolve('api/portal-worker.ts')],bundle:true,platform:'node',outfile:workerOut,plugins:[{name:'supabase',setup(b){b.onResolve({filter:/^@supabase\/supabase-js$/},()=>({path:require.resolve('@supabase/supabase-js'),external:true}));}}]});const worker=require(workerOut);
 assert.deepEqual(worker.configuredChannels({RESEND_API_KEY:'x',NOTIFICATION_FROM_EMAIL:'x'}),[]);pass('Sending disabled by default');
 const env={NOTIFICATIONS_ENABLED:'true',RESEND_API_KEY:'x',NOTIFICATION_FROM_EMAIL:'test@example.com',TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_AUTH_TOKEN:'x',TWILIO_SMS_FROM:'+12345678901',TWILIO_WHATSAPP_FROM:'whatsapp:+12345678901',TWILIO_WHATSAPP_CONTENT_SID:'HXtest'};
 assert.deepEqual(worker.configuredChannels(env),[]);pass('External delivery stays disabled even when provider credentials exist');
 await assert.rejects(()=>worker.submitAlert('email','test@example.com','event-1',env,()=>{throw new Error('Network must not be called');}),/delivery is excluded/);pass('External delivery cannot call a provider');
 let captured;const fake=async(url,init)=>{captured={url,init};return {ok:true,json:async()=>({id:'provider-1'})};};
 const React=require('react'),{createRoot}=require('react-dom/client');let writes=[];
 const uiOut=path.join(dir,'ops.cjs');await build({entryPoints:[path.resolve('src/portal/operations.tsx')],bundle:true,platform:'node',outfile:uiOut,plugins:[{name:'react',setup(b){b.onResolve({filter:/^react$/},()=>({path:require.resolve('react'),external:true}));}}]});const {TasksBoard}=require(uiOut);const root=createRoot(document.getElementById('root'));
 const props={tasks:[{id:'t',title:'Drag me',status:'To do',priority:'Normal'}],items:[],members:[],equipment:[],tickets:[],projectId:'p',staff:true,profileId:'u',busy:false,insert:async()=>true,update:async(...args)=>{writes.push(args);return true;}};
 await React.act(async()=>root.render(React.createElement(TasksBoard,props)));
 assert.equal(document.querySelector('.p-task-card').draggable,true);const event=new dom.window.Event('drop',{bubbles:true,cancelable:true});Object.defineProperty(event,'dataTransfer',{value:{getData:()=> 't'}});await React.act(async()=>document.querySelectorAll('.p-lane')[1].dispatchEvent(event));assert.deepEqual(writes[0],['tasks','t',{status:'In progress'}]);pass('Dragging a staff task persists new lane status');
 await React.act(async()=>root.render(React.createElement(TasksBoard,{...props,staff:false})));assert.equal(document.querySelector('.p-task-card').draggable,false);writes=[];await React.act(async()=>document.querySelectorAll('.p-lane')[2].dispatchEvent(event));assert.equal(writes.length,0);pass('Client drag and drop is disabled');
 await React.act(async()=>root.unmount());dom.window.close();fs.rmSync(dir,{recursive:true,force:true});console.log(`${n} business utility UI and provider assertions passed`);
})().catch(e=>{console.error(e);process.exit(1)});
