const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{build}=require('esbuild');
(async()=>{const {JSDOM}=await import('jsdom'),dom=new JSDOM('<div id="root"></div>',{url:'https://example.test/portal'});Object.assign(global,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});
 const React=require('react'),{createRoot}=require('react-dom/client');let writes=[],exports=[],canReview=false,people=[{id:'tech',name:'Worker'},{id:'hr',name:'HR'}];const data={hr_leave_requests:[{id:'request',user_id:'tech',kind:'Annual',starts_on:'2026-10-12',ends_on:'2026-10-12',units:1,status:'Submitted',version:4,reason:'Private personal reason'}],hr_leave_allowances:[{id:'allowance',user_id:'tech',year:2026,kind:'Annual',units:12,version:3}],hr_leave_history:[]};
 global.__db={from(table){const q={select(){return q},order(){return q},range(){return q},then(a,b){return Promise.resolve({data:data[table]||[],error:null}).then(a,b)}};return q;},rpc:async(name,args)=>{writes.push({name,args});return {data:name==='hr_leave_people'?people.map(p=>({...p,can_review:p.id==='tech'&&canReview})):name==='hr_leave_balances'?[{kind:'Annual',allowance:12,used:0,pending:1,available:11}]:name==='request_hr_leave'?'id':null,error:null}}};
 const dir=fs.mkdtempSync(path.join(__dirname,'leave-ui-'));try{await build({entryPoints:['src/portal/hr-leave.tsx'],bundle:true,platform:'node',outfile:path.join(dir,'bundle.cjs'),plugins:[{name:'mock',setup(b){b.onResolve({filter:/^react$/},()=>({path:require.resolve('react'),external:true}));for(const [filter,name,contents] of [[/^\.\/client$/,'client','export const db=globalThis.__db;export function check(r){if(r.error)throw r.error;return r.data}'],[/^\.\/workspace$/,'workspace','export async function workspaceRows(t){return (await globalThis.__db.from(t)).data}'],[/^\.\/business-utils$/,'exports','export function csvText(rows){globalThis.__leaveCSV=rows;return "csv";}export function downloadText(...a){globalThis.__leaveExports.push(a)}']]){b.onResolve({filter},()=>({path:name,namespace:name}));b.onLoad({filter:/.*/,namespace:name},()=>({contents,loader:'js'}));}}}]});global.__leaveExports=exports;
 const {HrLeave}=require(path.join(dir,'bundle.cjs')),root=createRoot(document.getElementById('root'));const flush=fn=>React.act(async()=>{await fn();await new Promise(r=>setTimeout(r,15));}),render=profile=>flush(()=>root.render(React.createElement(HrLeave,{key:profile.id,profile}))),submit=form=>flush(()=>form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}))),click=text=>flush(()=>[...document.querySelectorAll('button')].find(b=>b.textContent===text).click());
 await render({id:'client',role:'client',crm_permissions:['hr.manage']});assert.equal(writes.length,0);console.log('PASS Client leave view makes no queries with stale permission props');
 await render({id:'tech',role:'team'});assert.doesNotMatch(document.body.textContent,/Configure annual allowance/);let form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Submit leave request'));form.elements.kind.value='Annual';form.elements.starts_on.value='2026-10-12';form.elements.ends_on.value='2026-10-12';form.elements.half_day.checked=true;form.elements.half_part.value='Afternoon';form.elements.reason.value='Personal leave';await submit(form);const request=writes.find(w=>w.name==='request_hr_leave');assert.equal(request.args.p_half,true);assert.equal(request.args.p_half_part,'Afternoon');assert.match(request.args.p_id,/^[0-9a-f-]{36}$/);assert.ok(!('p_user' in request.args));console.log('PASS Employee submits a retry identifier and half-day part without assigning request ownership');
 form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Record leave action'));assert.deepEqual([...form.elements.action.options].map(o=>o.value),['Withdraw']);form.elements.note.value='Plans changed';await submit(form);assert.equal(writes.at(-2).name==='hr_leave_action'||writes.some(w=>w.name==='hr_leave_action'&&w.args.p_version===4),true);console.log('PASS Own pending leave offers withdrawal with current request version');
 await click('Export leave balances CSV');assert.equal(global.__leaveCSV.length,2);assert.doesNotMatch(JSON.stringify(global.__leaveCSV),/Private personal reason|request/);console.log('PASS Leave balance export excludes private request reasons');
 await render({id:'hr',role:'team',crm_permissions:['hr.manage']});let select=[...document.querySelectorAll('select')].find(s=>s.parentElement.textContent.startsWith('Employee'));await flush(()=>{select.value='tech';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}))});assert.match(document.body.textContent,/Configure annual allowance/);assert.doesNotMatch(document.body.textContent,/Record leave action/);form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Save leave allowance'));form.elements.kind.value='Annual';form.elements.units.value='15';form.elements.reason.value='Annual policy allocation';await submit(form);assert.ok(writes.some(w=>w.name==='save_hr_leave_allowance'&&w.args.p_version===3&&w.args.p_user==='tech'));console.log('PASS HR adjusts versioned allowance without impersonating designated manager approval');
 canReview=true;people=[{id:'manager',name:'Manager'},{id:'tech',name:'Worker'}];await render({id:'manager',role:'team',crm_permissions:['project.own']});select=[...document.querySelectorAll('select')].find(s=>s.parentElement.textContent.startsWith('Employee'));await flush(()=>{select.value='tech';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}))});form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Record leave action'));assert.deepEqual([...form.elements.action.options].map(o=>o.value),['Approve','Reject']);form.elements.note.value='Leave reviewed';await submit(form);assert.ok(writes.some(w=>w.name==='hr_leave_action'&&w.args.p_action==='Approve'&&w.args.p_version===4));console.log('PASS Designated manager receives approval and rejection actions with current version');
 await flush(()=>root.unmount());dom.window.close();}finally{fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exit(1)});
