import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;
create schema auth;create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to authenticated;
`);
await pg.exec(await fs.readFile(new URL('../supabase/001_portal.sql', import.meta.url),'utf8'));
const ids={admin:'00000000-0000-0000-0000-000000000001',clientA:'00000000-0000-0000-0000-000000000002',clientB:'00000000-0000-0000-0000-000000000003',team:'00000000-0000-0000-0000-000000000004',outsider:'00000000-0000-0000-0000-000000000005',a:'10000000-0000-0000-0000-000000000001',b:'10000000-0000-0000-0000-000000000002',pa:'20000000-0000-0000-0000-000000000001',pb:'20000000-0000-0000-0000-000000000002',ticket:'30000000-0000-0000-0000-000000000001',file:'40000000-0000-0000-0000-000000000001',fileb:'40000000-0000-0000-0000-000000000002'};
await pg.exec(`insert into auth.users values ('${ids.admin}'),('${ids.clientA}'),('${ids.clientB}'),('${ids.team}'),('${ids.outsider}');
insert into companies values ('${ids.a}','A'),('${ids.b}','B');
insert into profiles values('${ids.admin}','Admin','admin',null),('${ids.clientA}','Client A','client','${ids.a}'),('${ids.clientB}','Client B','client','${ids.b}'),('${ids.team}','Team','team',null);
insert into projects(id,company_id,title) values('${ids.pa}','${ids.a}','A project'),('${ids.pb}','${ids.b}','B project');
insert into tasks(project_id,title,internal) values('${ids.pa}','Shared task',false),('${ids.pa}','Private task',true),('${ids.pb}','Other client task',false);
insert into milestones(project_id,title) values('${ids.pa}','A milestone'),('${ids.pb}','B milestone');
insert into messages(project_id,body,internal,author_id) values('${ids.pa}','Shared comment',false,'${ids.admin}'),('${ids.pa}','Internal comment',true,'${ids.admin}'),('${ids.pb}','B comment',false,'${ids.admin}');
insert into tickets(id,project_id,title,description,priority,author_id) values('${ids.ticket}','${ids.pb}','B ticket','Description','Normal','${ids.clientB}');
insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/deliverable.pdf','${ids.admin}'),('project-files','${ids.pb}/deliverable.pdf','${ids.admin}');
insert into files(id,project_id,name,path,size,deliverable,author_id) values('${ids.file}','${ids.pa}','A.pdf','${ids.pa}/deliverable.pdf',100,true,'${ids.admin}'),('${ids.fileb}','${ids.pb}','B.pdf','${ids.pb}/deliverable.pdf',100,true,'${ids.admin}');`);

await pg.exec(await fs.readFile(new URL('../supabase/002_operations.sql',import.meta.url),'utf8'));
let passed=0;
async function user(id){await pg.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated;`);}
async function count(sql,n,title){const {rows}=await pg.query(sql);assert.equal(rows.length,n,title);passed++;console.log('PASS',title);}
async function denied(sql,title){await assert.rejects(()=>pg.exec(sql),undefined,title);passed++;console.log('PASS',title);}
const targets={Low:{response:240,resolution:2880},Normal:{response:120,resolution:1440},High:{response:60,resolution:480},Urgent:{response:15,resolution:120}};
const query=async(sql,params=[])=>(await pg.query(sql,params)).rows;
const one=async(sql,params=[])=>(await query(sql,params))[0];
function eq(actual,expected,title){assert.deepEqual(actual,expected,title);passed++;console.log('PASS',title)}
await user(ids.admin);
eq((await one(`select sla_note from tickets where id='${ids.ticket}'`)).sla_note,'Legacy ticket — SLA not measured','Existing ticket preserved without invented SLA');
const ca=(await one(`insert into contracts(company_id,title,status,start_date,end_date,renewal_date,targets) values($1,'A Gold','Active',current_date-1,current_date+365,current_date+330,$2) returning *`,[ids.a,targets])).id;
const cb=(await one(`insert into contracts(company_id,title,status,start_date,end_date,targets) values($1,'B Silver','Active',current_date-1,current_date+365,$2) returning *`,[ids.b,targets])).id;
await denied(`insert into contracts(company_id,title,start_date,end_date,targets) values('${ids.a}','Invalid',current_date,current_date,'{}')`,'Incomplete target matrix rejected');
const bad={...targets,Urgent:{response:120,resolution:15}};
await assert.rejects(()=>query(`insert into contracts(company_id,title,start_date,end_date,targets) values($1,'Invalid',current_date,current_date,$2)`,[ids.a,bad]));passed++;console.log('PASS resolution shorter than response rejected');
await denied(`update projects set contract_id='${cb}' where id='${ids.pa}'`,'Project cannot link another company contract');
await pg.exec(`update projects set contract_id='${ca}' where id='${ids.pa}';update projects set contract_id='${cb}' where id='${ids.pb}'`);
const ea=(await one(`insert into equipment(company_id,contract_id,name,serial_number) values($1,$2,'A router','A-100') returning id`,[ids.a,ca])).id;
const eb=(await one(`insert into equipment(company_id,contract_id,name) values($1,$2,'B router') returning id`,[ids.b,cb])).id;
const eu=(await one(`insert into equipment(company_id,name) values($1,'Uncovered printer') returning id`,[ids.a])).id;
await denied(`update equipment set contract_id='${cb}' where id='${ea}'`,'Equipment contract company validated');
await denied(`update equipment set company_id='${ids.b}' where id='${ea}'`,'Equipment cannot be moved across companies');
await denied(`update contracts set company_id='${ids.b}' where id='${ca}'`,'Contract cannot be moved across companies');
await pg.exec(`insert into equipment_service(equipment_id,serviced_on,summary) values('${ea}',current_date,'A service'),('${eb}',current_date,'B service')`);
await user(ids.clientA);
await count('select * from contracts',1,'Client sees only own contracts');
await count('select * from equipment',2,'Client sees only own equipment');
await count('select * from equipment_service',1,'Service history isolated');
await count(`update contracts set title='tamper' returning *`,0,'Client cannot edit contract terms');
await count(`update equipment set name='tamper' returning *`,0,'Client cannot edit equipment');
await denied(`insert into equipment(company_id,name) values('${ids.a}','Client asset')`,'Client cannot create equipment');
await denied(`insert into equipment_service(equipment_id,serviced_on,summary) values('${ea}',current_date,'Fake maintenance')`,'Client cannot create service history');
await denied(`insert into tickets(project_id,equipment_id,title,description,priority) values('${ids.pa}','${eb}','Bad link','description','Urgent')`,'Ticket equipment cannot cross companies');
let t=await one(`insert into tickets(project_id,equipment_id,title,description,priority,created_at,first_response_at,response_due_at,contract_id) values($1,$2,'Router offline','Cannot connect','Urgent','2000-01-01','2000-01-01','2100-01-01',$3) returning *`,[ids.pa,ea,cb]);
eq(t.contract_id,ca,'Server derives contract instead of trusting supplied contract');
eq(t.first_response_at,null,'Client cannot forge first response');
eq(t.response_minutes,15,'Priority picks contract response target');
eq(t.resolution_minutes,120,'Priority picks contract resolution target');
eq(Date.parse(t.response_due_at)-Date.parse(t.created_at),15*60000,'Response deadline uses elapsed minutes');
eq(Date.parse(t.resolution_due_at)-Date.parse(t.created_at),120*60000,'Resolution deadline uses elapsed minutes');
assert.ok(Math.abs(Date.now()-Date.parse(t.created_at))<60000);passed++;console.log('PASS creation uses server time');
const tid=t.id;
await pg.exec(`insert into messages(project_id,ticket_id,body) values('${ids.pa}','${tid}','Client follow up')`);
eq((await one(`select first_response_at from tickets where id='${tid}'`)).first_response_at,null,'Client reply does not meet response target');
const uncovered=await one(`insert into tickets(project_id,equipment_id,title,description,priority) values($1,$2,'Printer','Help','Normal') returning *`,[ids.pa,eu]);
eq(uncovered.response_due_at,null,'Uncovered equipment does not claim SLA coverage');
const general=await one(`insert into tickets(project_id,title,description,priority) values($1,'General request','Help','High') returning *`,[ids.pa]);
eq(general.response_minutes,60,'General request uses project contract');
await user(ids.team);
await count(`update contracts set title='Team edit' returning *`,0,'Team cannot edit contract terms');
await denied(`insert into contracts(company_id,title,start_date,end_date,targets) values('${ids.a}','Team contract',current_date,current_date,'${JSON.stringify(targets)}')`,'Team cannot create contract');
await pg.exec(`insert into messages(project_id,ticket_id,body,internal) values('${ids.pa}','${tid}','Internal investigation',true)`);
eq((await one(`select first_response_at from tickets where id='${tid}'`)).first_response_at,null,'Internal staff note does not meet response target');
await pg.exec(`update tickets set first_response_at=now(),response_due_at=now()+interval '1 year',resolution_minutes=999 where id='${tid}'`);
t=await one(`select * from tickets where id='${tid}'`);
eq(t.first_response_at,null,'Direct staff update cannot forge response evidence');
eq(t.resolution_minutes,120,'Direct staff update cannot alter SLA targets');
eq(Date.parse(t.response_due_at)-Date.parse(t.created_at),15*60000,'Direct staff update cannot alter deadline');
await pg.exec(`insert into messages(project_id,ticket_id,body) values('${ids.pa}','${tid}','We are investigating')`);
const responded=await one(`select * from tickets where id='${tid}'`);
assert.ok(responded.first_response_at);passed++;console.log('PASS shared staff reply records first response');
await pg.exec(`insert into messages(project_id,ticket_id,body) values('${ids.pa}','${tid}','Second reply')`);
eq((await one(`select first_response_at from tickets where id='${tid}'`)).first_response_at,responded.first_response_at,'Later replies preserve first response');
await pg.exec(`update tickets set status='Waiting on client' where id='${tid}'`);
eq((await one(`select resolution_due_at from tickets where id='${tid}'`)).resolution_due_at,t.resolution_due_at,'Waiting on client never pauses or extends deadline');
await pg.exec(`update tickets set status='Resolved' where id='${tid}'`);
assert.ok((await one(`select resolved_at from tickets where id='${tid}'`)).resolved_at);passed++;console.log('PASS resolution captures server completion time');
await pg.exec(`update tickets set status='Open' where id='${tid}'`);
const reopened=await one(`select * from tickets where id='${tid}'`);
eq(reopened.resolved_at,null,'Reopening resumes unresolved state');
eq(reopened.resolution_due_at,t.resolution_due_at,'Reopening retains original deadline');
await count(`select * from ticket_events where ticket_id='${tid}'`,4,'Open waiting resolved reopened transitions recorded');
await denied(`update tickets set priority='Low' where id='${tid}'`,'Priority cannot silently change snapshot targets');
await denied(`update tickets set project_id='${ids.pb}' where id='${tid}'`,'Ticket cannot move across companies');
await denied(`insert into task_items(task_id,title) values('00000000-0000-0000-0000-999999999999','Missing task')`,'Checklist requires existing task');
await denied(`insert into tasks(project_id,title,assignee) values('${ids.pa}','Bad assignee','${ids.clientA}')`,'Client cannot be task assignee');
await denied(`insert into tasks(project_id,title,equipment_id) values('${ids.pa}','Bad equipment','${eb}')`,'Task equipment must share company');
await denied(`insert into tasks(project_id,title,ticket_id) values('${ids.pa}','Bad ticket','${ids.ticket}')`,'Task ticket must share project');
const task=(await one(`insert into tasks(project_id,title,assignee,priority,ticket_id,equipment_id) values($1,'Inspect router',$2,'High',$3,$4) returning id`,[ids.pa,ids.team,tid,ea])).id;
const privateTask=(await one(`insert into tasks(project_id,title,internal) values($1,'Private work',true) returning id`,[ids.pa])).id;
await pg.exec(`insert into task_items(task_id,title) values('${task}','Public checklist'),('${privateTask}','Secret checklist')`);
await user(ids.clientA);
await count('select * from task_items',1,'Internal task checklists hidden from client');
await count(`update task_items set done=true returning *`,0,'Client cannot change checklist completion');
await count(`update tasks set status='Done' returning *`,0,'Client cannot change task status');
await user(ids.clientB);
await count(`select * from ticket_events where ticket_id='${tid}'`,0,'Ticket event history isolated');
await count('select * from task_items',0,'Other company cannot read checklists');
await user(ids.admin);
await pg.exec(`update contracts set targets=jsonb_set(targets,'{Urgent,response}','30') where id='${ca}'`);
eq((await one(`select response_minutes from tickets where id='${tid}'`)).response_minutes,15,'Contract edits preserve prior ticket snapshot');
const next=await one(`insert into tickets(project_id,title,description,priority) values($1,'New terms','Help','Urgent') returning *`,[ids.pa]);
eq(next.response_minutes,30,'Future tickets use updated terms');
await pg.exec(`update contracts set status='Cancelled' where id='${ca}'`);
const cancelled=await one(`insert into tickets(project_id,title,description,priority) values($1,'Cancelled contract','Help','Urgent') returning *`,[ids.pa]);
eq(cancelled.response_due_at,null,'Cancelled contract grants no new SLA');
await pg.exec(`update contracts set status='Active',start_date=current_date-10,end_date=current_date-1 where id='${ca}'`);
const expired=await one(`insert into tickets(project_id,title,description,priority) values($1,'Expired contract','Help','Urgent') returning *`,[ids.pa]);
eq(expired.response_due_at,null,'Expired contract grants no new SLA');
await pg.exec(`update contracts set start_date=current_date+1,end_date=current_date+10 where id='${ca}'`);
const future=await one(`insert into tickets(project_id,title,description,priority) values($1,'Future contract','Help','Urgent') returning *`,[ids.pa]);
eq(future.response_due_at,null,'Future contract grants no new SLA');
await pg.exec(`update profiles set active=false where id='${ids.clientA}'`);
await user(ids.clientA);await count('select * from contracts',0,'Disabled account cannot read contracts');await count('select * from equipment',0,'Disabled account cannot read equipment');await count('select * from equipment_service',0,'Disabled account cannot read maintenance history');await count('select * from task_items',0,'Disabled account cannot read checklists');
await user(ids.outsider);await count('select * from contracts',0,'Unassigned account cannot read contracts');await count('select * from equipment',0,'Unassigned account cannot read equipment');
await pg.exec('reset role;set role anon');await denied('select * from equipment','Anonymous equipment access denied');await denied('select * from contracts','Anonymous contract access denied');
await pg.exec('reset role');
// Calendar proof: Friday night + four elapsed hours crosses into Saturday; no business-hours calendar.
eq(new Date((await one(`select ('2026-09-25T23:00:00Z'::timestamptz + 240*interval '1 minute') as due`)).due).toISOString(),'2026-09-26T03:00:00.000Z','24/7 calculation includes overnight and weekend hours');
console.log(`${passed} operations assertions passed. Real Supabase transport and email still need hosted acceptance checks.`);
await pg.close();
