// Interaction checks using a simulated transport. Database policies have a separate PostgreSQL suite.
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const os=require('node:os');
const project=path.resolve(__dirname,'..');
const {build}=require('esbuild');
(async()=>{
const {JSDOM}=await import('jsdom');
const dom=new JSDOM('<!doctype html><div id="root"></div>',{url:'http://localhost/portal'});
Object.assign(global,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});
const React=require('react'),{createRoot}=require('react-dom/client');
let session={user:{id:'admin'}},callback;const writes=[];
const targets=Object.fromEntries(['Low','Normal','High','Urgent'].map(p=>[p,{response:60,resolution:240}]));
const data={profiles:[{id:'admin',name:'Admin',role:'admin',active:true},{id:'team',name:'Engineer',role:'team',active:true},{id:'client',name:'Client A',role:'client',company_id:'a',active:true}],companies:[{id:'a',name:'Company A'},{id:'b',name:'Company B'}],projects:[{id:'pa',title:'Network Audit',company_id:'a',status:'Planning',description:'Scope',contract_id:'ca'}],contracts:[{id:'ca',title:'Gold AMC',company_id:'a',status:'Active',start_date:'2020-01-01',end_date:'2099-12-31',renewal_date:'2099-12-01',targets}],equipment:[{id:'ea',name:'Office router',company_id:'a',contract_id:'ca',category:'Router',status:'In service',serial_number:'R-123'}],equipment_service:[],tasks:[{id:'task',title:'Inspect router',project_id:'pa',priority:'High',status:'To do',assignee:'team',internal:false},{id:'private',title:'Private audit',project_id:'pa',priority:'Normal',status:'To do',internal:true}],task_items:[{id:'item',task_id:'task',title:'Check ports',done:false}],milestones:[],files:[],approvals:[],messages:[],tickets:[{id:'ticket',project_id:'pa',title:'Router offline',description:'Help',priority:'High',status:'Open',equipment_id:'ea',contract_title:'Gold AMC',response_due_at:'2020-01-01T00:00:00Z',resolution_due_at:'2020-01-02T00:00:00Z'}],ticket_events:[]};
global.__db={auth:{getSession:async()=>({data:{session}}),onAuthStateChange:fn=>{callback=fn;return {data:{subscription:{unsubscribe(){}}}}},signOut:async()=>{session=null;callback('SIGNED_OUT',null);return {error:null}}},from(table){let filters=[],values,verb='select',single=false;const q={select(){return q},order(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},insert(v){values=v;verb='insert';return q},update(v){values=v;verb='update';return q},single(){single=true;return q},maybeSingle(){single=true;return q},then(resolve,reject){try{let rows=data[table]||[];if(verb==='insert'){const r={id:`new-${writes.length}`,created_at:new Date().toISOString(),...values};data[table].push(r);writes.push({table,verb,values});rows=[r];}else if(verb==='update'){rows=rows.filter(r=>filters.every(f=>f(r)));rows.forEach(r=>Object.assign(r,values));writes.push({table,verb,values});}else{rows=rows.filter(r=>filters.every(f=>f(r)));if(session?.user.id==='client'){if(table==='profiles')rows=rows.filter(r=>r.id==='client');if(table==='tasks')rows=rows.filter(r=>!r.internal);}}return Promise.resolve({data:single?rows[0]||null:structuredClone(rows),error:null}).then(resolve,reject)}catch(e){return Promise.reject(e).then(resolve,reject)}}};return q;}};
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'portal-ui-'));const outfile=path.join(dir,'portal.cjs');
await build({entryPoints:[project+'/src/portal/Portal.tsx'],bundle:true,platform:'node',format:'cjs',outfile,loader:{'.css':'empty'},plugins:[{name:'test-dependencies',setup(b){b.onResolve({filter:/^react$/},()=>({path:require.resolve('react'),external:true}));b.onResolve({filter:/^\.\/client$/},()=>({path:'client',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const db=globalThis.__db;export const configured=true;export function check(r){if(r.error)throw r.error;return r.data}',loader:'js'}));}}]});
const Portal=require(outfile).default,root=createRoot(document.getElementById('root'));
const helperOut=path.join(dir,'operations.cjs');
await build({entryPoints:[project+'/src/portal/operations.tsx'],bundle:true,platform:'node',format:'cjs',outfile:helperOut,plugins:[{name:'react-external',setup(b){b.onResolve({filter:/^react$/},()=>({path:require.resolve('react'),external:true}));}}]});
const {slaState}=require(helperOut);
const flush=async(fn=()=>{})=>React.act(async()=>{await fn();await new Promise(r=>setTimeout(r,25));});
const click=async(text)=>{const el=[...document.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(el,`Button ${text}`);await flush(()=>el.click());};
const set=async(el,value)=>{assert.ok(el);await flush(()=>{el.value=value;el.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});};
const submit=async form=>{await flush(()=>form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));};
let passed=0;const pass=t=>{passed++;console.log('PASS',t)};
const deadline='2026-09-26T03:00:00.000Z',clock=Date.parse(deadline);
assert.equal(slaState(undefined,undefined,clock).text,'Not measured');pass('Missing SLA is not shown as met');
assert.equal(slaState(deadline,undefined,clock-60000).text,'Due in 1m');pass('Countdown uses remaining elapsed time');
assert.equal(slaState(deadline,undefined,clock+60000).text,'Overdue by 1m');pass('Expired deadline is marked overdue');
assert.equal(slaState(deadline,deadline,clock).text,'Met');pass('Completion exactly on deadline meets target');
assert.equal(slaState(deadline,'2026-09-26T03:00:01.000Z',clock).text,'Missed');pass('Late completion remains missed');
await flush(()=>root.render(React.createElement(Portal)));
assert.ok(document.body.textContent.includes('1 overdue tickets'));pass('Dashboard shows overdue service attention');
await click('AMC & SLA');assert.ok(document.body.textContent.includes('Gold AMC'));await click('New contract');
let form=document.querySelector('form');for(const [name,value] of Object.entries({company_id:'a',title:'New client contract',status:'Active',start_date:'2026-01-01',end_date:'2027-01-01',Low_response:'240',Low_resolution:'2880',Normal_response:'120',Normal_resolution:'1440',High_response:'60',High_resolution:'480',Urgent_response:'15',Urgent_resolution:'120'}))form.elements.namedItem(name).value=value;
await submit(form);const contractWrite=writes.find(x=>x.table==='contracts');assert.equal(contractWrite.values.targets.Urgent.response,15);assert.equal(typeof contractWrite.values.targets.Urgent.response,'number');assert.ok(document.body.textContent.includes('New client contract'));pass('Contract form saves all per-priority targets as numbers');
await click('Projects');await flush(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Network Audit')).click());await click('Tasks');
assert.equal(document.querySelectorAll('.p-lane').length,3);assert.ok(document.body.textContent.includes('Inspect router'));pass('Task board renders all three workflow columns');
await set(document.querySelector('[aria-label="Status for Inspect router"]'),'In progress');assert.equal(data.tasks[0].status,'In progress');pass('Board status change persists through refresh');
await flush(()=>document.querySelector('.p-check-item input').click());assert.equal(data.task_items[0].done,true);pass('Checklist completion persists');
await click('Add task');form=document.querySelector('form');for(const [name,value] of Object.entries({title:'Replace router',assignee:'team',priority:'Urgent',deadline:'2026-12-01',equipment_id:'ea',ticket_id:'ticket'}))form.elements.namedItem(name).value=value;await submit(form);
const tw=writes.find(x=>x.table==='tasks'&&x.verb==='insert');assert.equal(tw.values.ticket_id,'ticket');assert.equal(tw.values.equipment_id,'ea');assert.equal(tw.values.assignee,'team');pass('Task creation links team assignee equipment and support ticket');
await click('Equipment');assert.ok(document.body.textContent.includes('Office router'));form=document.querySelector('form');form.elements.namedItem('serviced_on').value='2026-09-22';form.elements.namedItem('summary').value='Replaced patch cable';await submit(form);assert.ok(document.body.textContent.includes('Replaced patch cable'));pass('Equipment service entry is saved and displayed');
await click('Clients & team');await click('Sign out');await flush(()=>{session={user:{id:'client'}};callback('SIGNED_IN',session)});
assert.ok(!document.body.textContent.includes('Clients & team'));assert.ok(!document.body.textContent.includes('Grant account access'));pass('Admin to client switching clears administration view');
await click('AMC & SLA');assert.ok(document.body.textContent.includes('Gold AMC'));assert.ok(![...document.querySelectorAll('button')].some(b=>['New contract','Edit contract'].includes(b.textContent)));pass('Client contract view is read only');
await click('Equipment');assert.ok(!document.querySelector('form'));pass('Client equipment view has no mutation forms');
await click('Projects');await flush(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Network Audit')).click());await click('Tasks');assert.ok(!document.body.textContent.includes('Private audit'));assert.ok(![...document.querySelectorAll('button')].some(b=>b.textContent==='Add task'));assert.ok(document.querySelector('.p-check-item input').disabled);pass('Client board has no staff controls and cannot change checklists');
await flush(()=>[...document.querySelectorAll('[role=tab]')].find(b=>b.textContent==='Support').click());assert.ok(document.body.textContent.includes('Overdue by'));pass('Client ticket view includes SLA deadline status');
await flush(()=>root.unmount());dom.window.close();fs.rmSync(dir,{recursive:true,force:true});console.log(`${passed} UI interaction checks passed. Transport is simulated; this is not visual browser QA.`);
})().catch(e=>{console.error(e);process.exit(1)});
