const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{build}=require('esbuild');
(async()=>{
 const {JSDOM}=await import('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://example.test/portal'});
 Object.assign(global,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});Object.defineProperty(global,'navigator',{value:dom.window.navigator,configurable:true});Object.defineProperty(window,'isSecureContext',{value:true});
 let registered=[],prompts=0,permissions=0,unsubscribed=0,closed=0,subscription=null,writes=[],saved=false;
 window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
 const makeSubscription=()=>({endpoint:'https://fcm.googleapis.com/fcm/send/test',toJSON:()=>({keys:{p256dh:'B'.repeat(87),auth:'C'.repeat(22)}}),unsubscribe:async()=>{unsubscribed++;subscription=null;return true;}});
 const registration={active:{},pushManager:{getSubscription:async()=>subscription,subscribe:async()=>subscription=makeSubscription()},getNotifications:async()=>[{close:()=>closed++}]};
 navigator.serviceWorker={register:async(...args)=>{registered.push(args);return registration;},getRegistration:async()=>registration};window.PushManager=function(){};window.Notification={requestPermission:async()=>{permissions++;return 'granted'}};global.Notification=window.Notification;
 global.fetch=async()=>({ok:true,json:async()=>({publicKey:'B'.repeat(87)})});
 global.__db={rpc:async(name,args)=>{writes.push({name,args});if(name==='save_portal_push')saved=true;if(name==='remove_portal_push')saved=false;return {data:'id',error:null};},from(){const q={select(){return q},eq(){return q},maybeSingle(){return Promise.resolve({data:saved?{id:'s',endpoint:'test',expires_at:'2099-01-01'}:null,error:null});}};return q;}};
 const dir=fs.mkdtempSync(path.join(__dirname,'pwa-ui-')),file=path.join(dir,'bundle.cjs');
 try{
 await build({entryPoints:['src/portal/pwa.tsx','src/portal/push.tsx'],bundle:true,platform:'node',outdir:dir,outExtension:{'.js':'.cjs'},format:'cjs',plugins:[{name:'mock',setup(b){b.onResolve({filter:/^react$/},()=>({path:require.resolve('react'),external:true}));b.onResolve({filter:/^\.\/client$/},()=>({path:'client',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const db=globalThis.__db;export function check(r){if(r.error)throw r.error;return r.data}',loader:'js'}));}}]});
 const {PortalPwa,CameraEvidence}=require(path.join(dir,'pwa.cjs')),{DevicePush,disableDevicePush,reconcileDevicePush}=require(path.join(dir,'push.cjs'));const React=require('react'),{createRoot}=require('react-dom/client'),root=createRoot(document.getElementById('root'));let passed=0;const pass=t=>{passed++;console.log('PASS',t)},flush=fn=>React.act(async()=>{await fn();await new Promise(r=>setTimeout(r,15));}),click=async text=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(button,text);await flush(()=>button.click());};
 await flush(()=>root.render(React.createElement(PortalPwa)));assert.deepEqual(registered[0],['/portal/sw.js',{scope:'/portal',updateViaCache:'none'}]);assert.equal(document.querySelector('link[rel=manifest]').getAttribute('href'),'/portal/manifest.webmanifest');assert.equal(prompts,0);pass('Phone access registers scoped worker without showing an automatic install prompt');
 const offer=new dom.window.Event('beforeinstallprompt',{cancelable:true});offer.prompt=async()=>{prompts++};offer.userChoice=Promise.resolve({outcome:'accepted'});await flush(()=>window.dispatchEvent(offer));assert.equal(offer.defaultPrevented,true);await click('Install portal on this device');assert.equal(prompts,1);pass('Explicit installation click consumes browser install prompt');
 Object.defineProperty(navigator,'onLine',{value:false,configurable:true});await flush(()=>window.dispatchEvent(new dom.window.Event('offline')));assert.match(document.body.textContent,/No work is saved offline/);pass('Lost connection is announced without claiming offline work storage');
 let uploads=0;await flush(()=>root.render(React.createElement(CameraEvidence,{upload:async e=>{e.preventDefault();uploads++},busy:false})));const input=document.querySelector('input[type=file]');assert.equal(input.getAttribute('capture'),'environment');assert.equal(input.accept,'image/jpeg,image/png');assert.match(document.body.textContent,/private until administrator publication/);await flush(()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.equal(uploads,1);pass('Camera evidence submits through existing private project upload handler');
 assert.equal(document.querySelector('link[rel=manifest]'),null);pass('Unmount cleans install listeners and manifest link');
 await flush(()=>root.render(React.createElement(DevicePush,{userId:'u',remindersEnabled:true})));assert.equal(permissions,0);await click('Enable device notifications');assert.equal(permissions,1);assert.equal(writes.at(-1).name,'save_portal_push');assert.ok(!('user_id' in writes.at(-1).args));assert.match(document.body.textContent,/Notifications enabled/);pass('Push opt-in requests permission only on click and leaves account ownership to database');
 await click('Disable device notifications');assert.equal(writes.at(-1).name,'remove_portal_push');assert.equal(unsubscribed,1);assert.equal(closed,1);pass('Device opt-out deletes account subscription, unsubscribes browser and closes notifications');
 await flush(()=>root.render(React.createElement(DevicePush,{key:'off',userId:'u',remindersEnabled:false})));assert.ok([...document.querySelectorAll('button')].find(b=>b.textContent==='Enable device notifications').disabled);pass('Reminder opt-out blocks enabling new device notifications');
 subscription=makeSubscription();saved=false;await reconcileDevicePush('other');assert.equal(subscription,null);pass('Account switch removes a device subscription that the new account does not own');
 subscription=makeSubscription();global.__db.rpc=async()=>({error:new Error('Network unavailable')});await assert.rejects(()=>disableDevicePush(),/Network unavailable/);assert.equal(subscription,null);pass('Browser unsubscribes even when account cleanup request fails');
 await flush(()=>root.unmount());dom.window.close();console.log(`${passed} PWA interface checks passed`);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exit(1)});
