import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;
create schema auth;create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to authenticated;
`);
await pg.exec(await fs.readFile(new URL('../supabase/001_portal.sql', import.meta.url),'utf8'));
if(process.env.PORTAL_TEST_OPERATIONS==='1') await pg.exec(await fs.readFile(new URL('../supabase/002_operations.sql',import.meta.url),'utf8'));
const ids={admin:'00000000-0000-0000-0000-000000000001',clientA:'00000000-0000-0000-0000-000000000002',clientB:'00000000-0000-0000-0000-000000000003',team:'00000000-0000-0000-0000-000000000004',outsider:'00000000-0000-0000-0000-000000000005',a:'10000000-0000-0000-0000-000000000001',b:'10000000-0000-0000-0000-000000000002',pa:'20000000-0000-0000-0000-000000000001',pb:'20000000-0000-0000-0000-000000000002',ticket:'30000000-0000-0000-0000-000000000001',file:'40000000-0000-0000-0000-000000000001',fileb:'40000000-0000-0000-0000-000000000002'};
await pg.exec(`insert into auth.users values ('${ids.admin}'),('${ids.clientA}'),('${ids.clientB}'),('${ids.team}'),('${ids.outsider}');
insert into companies values ('${ids.a}','A'),('${ids.b}','B');
insert into profiles values('${ids.admin}','Admin','admin',null),('${ids.clientA}','Client A','client','${ids.a}'),('${ids.clientB}','Client B','client','${ids.b}'),('${ids.team}','Team','team',null);
insert into projects(id,company_id,title) values('${ids.pa}','${ids.a}','A project'),('${ids.pb}','${ids.b}','B project');
insert into tasks(project_id,title,internal) values('${ids.pa}','Shared task',false),('${ids.pa}','Private task',true),('${ids.pb}','Other client task',false);
insert into milestones(project_id,title) values('${ids.pa}','A milestone'),('${ids.pb}','B milestone');
insert into messages(project_id,body,internal,author_id) values('${ids.pa}','Shared comment',false,'${ids.admin}'),('${ids.pa}','Internal comment',true,'${ids.admin}'),('${ids.pb}','B comment',false,'${ids.admin}');
insert into tickets(id,project_id,title,description,priority,author_id) values('${ids.ticket}','${ids.pb}','B ticket','Description','Normal','${ids.clientB}');
insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/deliverable.pdf','${ids.admin}'),('project-files','${ids.pb}/deliverable.pdf','${ids.admin}');
insert into files(id,project_id,name,path,size,deliverable,author_id) values('${ids.file}','${ids.pa}','A.pdf','${ids.pa}/deliverable.pdf',100,true,'${ids.admin}'),('${ids.fileb}','${ids.pb}','B.pdf','${ids.pb}/deliverable.pdf',100,true,'${ids.admin}');`);
let passed=0;
async function user(id){await pg.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated;`);}
async function count(sql,n,title){const {rows}=await pg.query(sql);assert.equal(rows.length,n,title);passed++;console.log('PASS',title);}
async function denied(sql,title){await assert.rejects(()=>pg.exec(sql),undefined,title);passed++;console.log('PASS',title);}
await user(ids.clientA);
await count('select * from projects',1,'Client sees only own projects');
await count('select * from companies',1,'Client sees only own company');
await count('select * from profiles',1,'Client cannot enumerate users');
await count('select * from tasks',1,'Internal tasks and other clients hidden');
await count('select * from milestones',1,'Milestones isolated');
await count('select * from messages',1,'Internal notes and other clients hidden');
await count('select * from files',1,'Files isolated');
await count('select * from storage.objects',1,'Storage download/list access isolated');
await count(`update profiles set role='admin' where id='${ids.clientA}' returning *`,0,'Cannot promote own role');
await count(`update profiles set company_id='${ids.b}' where id='${ids.clientA}' returning *`,0,'Cannot switch client company');
await count(`update projects set title='tampered' where id='${ids.pa}' returning *`,0,'Client cannot modify projects');
await denied(`insert into messages(project_id,body) values('${ids.pb}','attack')`,'Cross-client message rejected');
await denied(`insert into messages(project_id,body,internal) values('${ids.pa}','private',true)`,'Client cannot create internal note');
await denied(`insert into messages(project_id,ticket_id,body) values('${ids.pa}','${ids.ticket}','attack')`,'Cross-project ticket link rejected');
await denied(`insert into messages(project_id,body,author_id) values('${ids.pa}','spoof','${ids.admin}')`,'Author spoof rejected');
await denied(`insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pb}/attack.pdf','${ids.clientA}')`,'Cross-client upload rejected');
await denied(`insert into files(project_id,name,path,size) values('${ids.pa}','fake.pdf','${ids.pa}/fake.pdf',100)`,'File metadata without owned upload rejected');
await denied(`insert into approvals(file_id,decision) values('${ids.fileb}','Approved')`,'Cross-client approval rejected');
await pg.exec(`insert into messages(project_id,body) values('${ids.pa}','Client feedback');insert into tickets(project_id,title,description,priority) values('${ids.pa}','Help','Please assist','High');insert into approvals(file_id,decision,note) values('${ids.file}','Approved','Accepted');`);
await count('select * from approvals',1,'Client approval recorded');
await count(`update approvals set decision='Changes requested' returning *`,0,'Approval history immutable');
await pg.exec(`insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/client.pdf','${ids.clientA}');insert into files(project_id,name,path,size) values('${ids.pa}','client.pdf','${ids.pa}/client.pdf',100);`);
await count('select * from files',2,'Client can upload own project file');
await count(`delete from storage.objects where name='${ids.pa}/client.pdf' returning *`,0,'Finalized file protected from deletion');
await pg.exec(`insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/orphan.pdf','${ids.clientA}');`);
await count(`delete from storage.objects where name='${ids.pa}/orphan.pdf' returning *`,1,'Failed-upload cleanup allowed');
await user(ids.clientB);await count('select * from approvals',0,'Other client cannot read approval history');
await user(ids.team);await count('select * from projects',2,'Team sees both projects');await count('select * from tasks',3,'Team sees internal tasks');
await denied(`insert into profiles(id,name,role) values('${ids.outsider}','Escalation','admin')`,'Team cannot grant admin access');
await denied(`insert into approvals(file_id,decision) values('${ids.file}','Approved')`,'Staff cannot impersonate client approval');
await user(ids.outsider);await count('select * from projects',0,'Unassigned account has no project access');
await user(ids.admin);await pg.exec(`insert into profiles(id,name,role) values('${ids.outsider}','New team member','team')`);await count(`select * from profiles where id='${ids.outsider}'`,1,'Admin can grant membership');
await pg.exec(`update profiles set active=false where id='${ids.clientA}'`);await user(ids.clientA);await count('select * from projects',0,'Disabled client immediately loses project access');await count('select * from storage.objects',0,'Disabled client loses file access');
await pg.exec('reset role;set role anon;');await denied('select * from projects','Anonymous database access denied');
console.log(`${passed} security assertions passed. Storage schema is simulated; run hosted acceptance checklist before launch.`);
await pg.close();
