import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema storage;create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to authenticated;
`);
await pg.exec(await fs.readFile(new URL('../supabase/001_portal.sql', import.meta.url),'utf8'));
const ids={admin:'00000000-0000-0000-0000-000000000001',clientA:'00000000-0000-0000-0000-000000000002',clientB:'00000000-0000-0000-0000-000000000003',team:'00000000-0000-0000-0000-000000000004',outsider:'00000000-0000-0000-0000-000000000005',a:'10000000-0000-0000-0000-000000000001',b:'10000000-0000-0000-0000-000000000002',pa:'20000000-0000-0000-0000-000000000001',pb:'20000000-0000-0000-0000-000000000002',ticket:'30000000-0000-0000-0000-000000000001',file:'40000000-0000-0000-0000-000000000001',fileb:'40000000-0000-0000-0000-000000000002'};
await pg.exec(`insert into auth.users values ('${ids.admin}'),('${ids.clientA}'),('${ids.clientB}'),('${ids.team}'),('${ids.outsider}');
insert into companies values ('${ids.a}','A'),('${ids.b}','B');
insert into profiles values('${ids.admin}','Admin','admin',null),('${ids.clientA}','Client A','client','${ids.a}'),('${ids.clientB}','Client B','client','${ids.b}'),('${ids.team}','Team','team',null);
insert into projects(id,company_id,title) values('${ids.pa}','${ids.a}','A project'),('${ids.pb}','${ids.b}','B project');
insert into tasks(project_id,title,internal) values('${ids.pa}','Shared task',false),('${ids.pa}','Private task',true),('${ids.pb}','Other client task',false);
insert into milestones(project_id,title) values('${ids.pa}','A milestone'),('${ids.pb}','B milestone');
insert into messages(project_id,body,internal,author_id) values('${ids.pa}','Shared comment',false,'${ids.admin}'),('${ids.pa}','Internal comment',true,'${ids.admin}'),('${ids.pb}','B comment',false,'${ids.admin}');
insert into tickets(id,project_id,title,description,priority,author_id) values('${ids.ticket}','${ids.pb}','B ticket','Description','Normal','${ids.clientB}');
insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/deliverable.pdf','${ids.admin}'),('project-files','${ids.pb}/deliverable.pdf','${ids.admin}');
insert into files(id,project_id,name,path,size,deliverable,author_id) values('${ids.file}','${ids.pa}','A.pdf','${ids.pa}/deliverable.pdf',100,true,'${ids.admin}'),('${ids.fileb}','${ids.pb}','B.pdf','${ids.pb}/deliverable.pdf',100,true,'${ids.admin}');`);

await pg.exec(await fs.readFile(new URL('../supabase/002_operations.sql',import.meta.url),'utf8'));

await pg.exec(await fs.readFile(new URL('../supabase/003_business.sql',import.meta.url),'utf8'));
let passed=0;
const q=async(s,p=[])=>(await pg.query(s,p)).rows;const one=async(s,p=[])=>(await q(s,p))[0];
async function user(id){await pg.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);select set_config('request.jwt.claim.role','authenticated',false);set role authenticated;`);}
function eq(a,b,t){assert.deepEqual(a,b,t);passed++;console.log('PASS',t);}
async function deny(s,p,t){await assert.rejects(()=>q(s,p),undefined,t);passed++;console.log('PASS',t);}
await pg.exec(await fs.readFile(new URL('../supabase/004_service_work.sql',import.meta.url),'utf8'));
await user(ids.admin);
const t=(await one("insert into tickets(project_id,title,description,priority) values($1,'A visit','Repair router','High') returning id",[ids.pa])).id;
const task=(await one("insert into tasks(project_id,title,ticket_id) values($1,'Repair',$2) returning id",[ids.pa,t])).id;
const privateTask=(await one("insert into tasks(project_id,title,internal) values($1,'Private task',true) returning id",[ids.pa])).id;
const log='60000000-0000-0000-0000-000000000001';
await user(ids.team);
const args=[log,ids.pa,t,task,'2026-01-01',90,'On site','Router replaced','Router x1',false];
await q('select record_work($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',args);
await q('select record_work($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',args);
eq((await q('select * from work_logs')).length,1,'Work log retries are idempotent');
await deny('select record_work($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[...args.slice(0,5),91,...args.slice(6)],'Reusing entry ID cannot overwrite evidence');
await deny("update work_logs set minutes=1 where id=$1",[log],'Direct work edits blocked');
await deny("select record_work(gen_random_uuid(),$1,$2,null,current_date,10,'Remote','Mismatch','',false)",[ids.pb,t],'Cross-project ticket rejected');
await deny("select record_work(gen_random_uuid(),$1,null,$2,current_date,10,'Remote','Private','',false)",[ids.pa,privateTask],'Shared logs cannot link private tasks');
await deny("select record_work(gen_random_uuid(),$1,null,null,current_date,10,'Remote','No subject','',false)",[ids.pa],'Work needs a task or ticket');
await deny("select record_work(gen_random_uuid(),$1,$2,null,current_date+1,10,'Remote','Future','',false)",[ids.pa,t],'Future work date blocked');
await deny("select record_work(gen_random_uuid(),$1,$2,null,current_date,0,'Remote','Zero','',false)",[ids.pa,t],'Zero minutes rejected');
await q("select record_work(gen_random_uuid(),$1,$2,null,current_date,5,'Remote','Internal investigation','',true)",[ids.pa,t]);
await user(ids.clientB);eq((await q('select * from work_logs')).length,0,'Other company cannot read work');
await user(ids.clientA);eq((await q('select * from work_logs')).length,1,'Client only sees shared work');
await deny("select record_work(gen_random_uuid(),$1,$2,null,current_date,10,'Remote','Forged','',false)",[ids.pa,t],'Client cannot forge technician work');
await deny("select void_work($1,'mistake')",[log],'Client cannot void work');
await user(ids.admin);await deny("select request_service_signoff($1,'Finished')",[t],'Sign-off requires resolution');
await q("update tickets set status='Resolved' where id=$1",[t]);
const resolved=(await one('select resolved_at from tickets where id=$1',[t])).resolved_at;
let sid=(await one("select request_service_signoff($1,'Router restored and tested') id",[t])).id;
eq((await one('select work_snapshot from service_signoffs where id=$1',[sid])).work_snapshot.length,1,'Review snapshot excludes internal evidence');
await deny("select request_service_signoff($1,'Duplicate')",[t],'Only one pending review');
await deny("select decide_service_signoff($1,'Accepted','')",[sid],'Administrator cannot impersonate client sign-off');
await user(ids.clientB);eq((await q('select * from service_signoffs')).length,0,'Review tenant isolation');
await deny("select decide_service_signoff($1,'Accepted','')",[sid],'Wrong client cannot accept');
await user(ids.clientA);await deny("select decide_service_signoff($1,'Changes requested','')",[sid],'Corrections require explanation');
await q("select decide_service_signoff($1,'Changes requested','Still intermittent')",[sid]);
eq((await one('select status from tickets where id=$1',[t])).status,'In progress','Corrections reopen ticket');
await deny("select decide_service_signoff($1,'Accepted','')",[sid],'Decision cannot be overwritten');
await user(ids.team);await q("update tickets set status='Resolved' where id=$1",[t]);
sid=(await one("select request_service_signoff($1,'Further repair complete') id",[t])).id;
eq((await one('select revision from service_signoffs where id=$1',[sid])).revision,2,'Follow-up review keeps revision history');
await q("select void_work($1,'Logged wrong duration')",[log]);
eq((await one('select work_snapshot from service_signoffs where id=$1',[sid])).work_snapshot.length,1,'Saved review evidence remains immutable after correction');
await user(ids.clientA);await q("select decide_service_signoff($1,'Accepted','Works correctly')",[sid]);
eq((await one('select status from tickets where id=$1',[t])).status,'Resolved','Acceptance preserves resolved status');
await user(ids.admin);sid=(await one("select request_service_signoff($1,'Final review') id",[t])).id;
await q("update tickets set status='In progress' where id=$1",[t]);
eq((await one('select status from service_signoffs where id=$1',[sid])).status,'Superseded','Staff reopen invalidates pending review');
await user(ids.clientA);await deny("select decide_service_signoff($1,'Accepted','')",[sid],'Stale review cannot be accepted');
await user(ids.team);await deny('select set_escalation_route($1,$2)',[ids.pa,ids.team],'Only administrator configures supervisor');
await user(ids.admin);await q('select set_escalation_route($1,$2)',[ids.pa,ids.team]);
await deny('select set_escalation_route($1,$2)',[ids.pa,ids.clientA],'Client cannot be supervisor');
// Simulate elapsed deadlines using owner fixture setup, never browser privileges.
await pg.exec(`reset role;alter table tickets disable trigger tickets_sla_stamp;update tickets set response_due_at=now()-interval '2 hour',resolution_due_at=now()-interval '1 hour' where id='${t}';alter table tickets enable trigger tickets_sla_stamp;`);
await user(ids.admin);eq((await one('select scan_sla_escalations() n')).n,2,'Response and resolution breach create separate escalations');
eq((await one('select scan_sla_escalations() n')).n,0,'Repeated scan deduplicates breaches');
eq((await q('select * from sla_escalations')).map(e=>e.supervisor_id),[ids.team,ids.team],'Project supervisor receives escalations');
const escalation=(await one("select id from sla_escalations where metric='Resolution'")).id;
await user(ids.clientA);eq((await q('select * from sla_escalations')).length,0,'Clients cannot read staff escalation queue');
await deny("select acknowledge_escalation($1,'Taking ownership')",[escalation],'Clients cannot acknowledge escalation');
await deny('select scan_sla_escalations()',[],'Clients cannot invoke scheduler');
await deny('select queue_due_alerts()',[],'Wrapper keeps scheduler authorization');
await user(ids.team);await q("select acknowledge_escalation($1,'Dispatching technician')",[escalation]);
eq((await one('select acknowledged_by from sla_escalations where id=$1',[escalation])).acknowledged_by,ids.team,'Assigned supervisor records ownership');
await q("update tickets set status='Resolved' where id=$1",[t]);
await user(ids.admin);await q('select queue_due_alerts()');
eq((await q('select * from sla_escalations where cleared_at is not null')).length,2,'Resolved ticket clears active breaches');
await q("update tickets set status='In progress' where id=$1",[t]);await q('select queue_due_alerts()');
eq((await q('select * from sla_escalations where cleared_at is null')).length,2,'Reopening reactivates original breaches');
eq((await q('select * from sla_escalations')).length,2,'Reopening does not duplicate original deadline');
await user(ids.clientA);await pg.exec(`reset role;update profiles set active=false where id='${ids.clientA}';`);await user(ids.clientA);
eq((await q('select * from service_signoffs')).length,0,'Disabled account loses service access');
await pg.exec(`reset role;select set_config('request.jwt.claim.sub','',false);select set_config('request.jwt.claim.role','service_role',false);set role service_role;`);
await q('select queue_due_alerts()');passed++;console.log('PASS Existing worker can execute combined scheduler');
console.log(`${passed} service workflow assertions passed`);await pg.close();
