const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{build}=require('esbuild');
(async()=>{
const {JSDOM}=await import('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://example.test/portal'});Object.assign(global,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});const React=require('react'),{createRoot}=require('react-dom/client'),writes=[];
const req={id:'mr',number:'MR-000001',project_id:'project',task_id:'task',purpose:'Install cable',site:'Site A',required_by:'2026-10-06',status:'Requested',created_by:'tech',version:1};const rows={sc_requests:[req],sc_request_lines:[{id:'line',request_id:'mr',item_id:'item',item_name:'Cable',unit:'metre',quantity:8,reserved:5}],sc_locations:[{id:'location',name:'Office rack'}],tasks:[{id:'task',project_id:'project',title:'Install cable'}],sc_orders:[{id:'po',number:'PO-000001',request_id:'mr',line_id:'line',quote_id:'quote',quantity:3,received:0,rejected:0,rate:12,total:36,version:2,status:'Approved'}],sc_quotes:[{id:'quote',requisition_id:'pr',vendor_id:'vendor',rate:12}],sc_requisitions:[{id:'pr',request_id:'mr',line_id:'line',number:'PR-000001',quantity:3,status:'Approved',estimated_total:30}],sc_vendors:[{id:'vendor',name:'Vendor',status:'Approved',rating:4}],sc_issues:[{id:'issue',number:'MIN-000001',request_id:'mr',line_id:'line',quantity:8,total:86,status:'In transit',version:4}],sc_history:[]};const items=[{id:'item',name:'Cable',unit:'metre',tracking:'Quantity'}];global.__db={from:t=>Promise.resolve({data:rows[t]||[],error:null}),rpc:async(name,args)=>{writes.push({name,args});return {error:null,data:name==='supply_request_items'?items:name==='supply_stock_report'?[]:name==='supply_staff'?[{id:'tech',name:'Technician',role:'team',active:true}]:name==='supply_deliveries'?[{id:'issue',number:'MIN-000001',quantity:8,status:'In transit',version:4}]:null};}};
const dir=fs.mkdtempSync(path.join(__dirname,'supply-ui-')),file=path.join(dir,'bundle.cjs');await build({entryPoints:[path.resolve(__dirname,'../src/portal/supply-chain.tsx')],bundle:true,platform:'node',outfile:file,external:['react'],plugins:[{name:'mock',setup(b){b.onResolve({filter:/^\.\/(client|workspace|report-export)$/},a=>({path:a.path,namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='./client'?'export const db=globalThis.__db;export function check(r){if(r.error)throw r.error;return r.data}':a.path==='./workspace'?"export async function workspaceRows(t){return (await globalThis.__db.from(t)).data}":'export async function downloadReportPDF(){}',loader:'js'}));}}]});const {SupplyChain}=require(file),root=createRoot(document.getElementById('root')),flush=fn=>React.act(async()=>{await fn();await new Promise(r=>setTimeout(r,25));}),projects=[{id:'project',title:'Assigned project'}];
const render=async(key,profile)=>flush(()=>root.render(React.createElement(SupplyChain,{key,profile,projects,members:[]})));const submit=async form=>flush(()=>form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));const click=async text=>flush(()=>[...document.querySelectorAll('button')].find(b=>b.textContent===text).click());
await render('tech',{id:'tech',name:'Technician',role:'team',crm_permissions:['work.own']});assert.doesNotMatch(document.body.textContent,/Stock by location|Vendor assessment|Raise purchase order/);assert.ok(!writes.some(w=>w.name==='supply_stock_report'));console.log('PASS Technician interface avoids global valuation and department controls');
let form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Add request line'));form.elements.namedItem('item').value='item';form.elements.quantity.value='8';await submit(form);form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Submit material request'));form.elements.project.value='project';form.elements.task.value='task';form.elements.purpose.value='Install assigned cable';form.elements.site.value='Site A';form.elements.required.value='2026-10-06';await submit(form);const saved=writes.find(w=>w.name==='create_supply_request');assert.equal(saved.args.p_task,'task');assert.deepEqual(saved.args.p_lines,[{item_id:'item',quantity:8}]);console.log('PASS Material request sends assigned project/task and structured item lines');
await click('Open chain');form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Confirm site delivery'));form.elements.name.value='Field receiver';form.elements.consent.checked=true;await submit(form);const delivery=writes.find(w=>w.name==='supply_issue_action');assert.equal(delivery.args.p_version,4);assert.equal(delivery.args.p_consent,true);console.log('PASS Field receiving sends consent and current sanitized delivery version');
await render('store',{id:'store',role:'team',crm_permissions:['stock.manage']});assert.match(document.body.textContent,/Stock by location/);await click('Requests');await click('Open chain');form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Check & reserve stock'));form.elements.location.value='location';await submit(form);const reserve=writes.find(w=>w.name==='check_supply_stock');assert.deepEqual(reserve.args,{p_request:'mr',p_version:1,p_location:'location'});console.log('PASS Store reservation action binds selected location and optimistic MR version');
await click('Inbound');form=[...document.querySelectorAll('form')].find(f=>f.textContent.includes('Post inspected goods receipt'));form.elements.location.value='location';form.elements.arrived.value='2';form.elements.accepted.value='1';form.elements.note.value='One rejected after inspection';form.elements.serials.value='';await submit(form);const receipt=writes.find(w=>w.name==='receive_supply_order');assert.equal(receipt.args.p_accepted,1);assert.equal(receipt.args.p_arrived,2);assert.equal(receipt.args.p_version,2);console.log('PASS Inbound form separates arrival, inspection acceptance and PO version');
await render('purchase',{id:'purchase',role:'team',crm_permissions:['purchase.manage']});assert.match(document.body.textContent,/Approved shortfalls/);assert.doesNotMatch(document.body.textContent,/Approve PO \/ budget step/);console.log('PASS Purchase queue exposes sourcing without independent approval controls');
await flush(()=>root.unmount());dom.window.close();fs.rmSync(dir,{recursive:true,force:true});
})().catch(e=>{console.error(e);process.exit(1)});
