import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema storage;create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to authenticated;
`);
await pg.exec(await fs.readFile(new URL('../supabase/001_portal.sql', import.meta.url),'utf8'));
const ids={admin:'00000000-0000-0000-0000-000000000001',clientA:'00000000-0000-0000-0000-000000000002',clientB:'00000000-0000-0000-0000-000000000003',team:'00000000-0000-0000-0000-000000000004',outsider:'00000000-0000-0000-0000-000000000005',a:'10000000-0000-0000-0000-000000000001',b:'10000000-0000-0000-0000-000000000002',pa:'20000000-0000-0000-0000-000000000001',pb:'20000000-0000-0000-0000-000000000002',ticket:'30000000-0000-0000-0000-000000000001',file:'40000000-0000-0000-0000-000000000001',fileb:'40000000-0000-0000-0000-000000000002'};
await pg.exec(`insert into auth.users values ('${ids.admin}'),('${ids.clientA}'),('${ids.clientB}'),('${ids.team}'),('${ids.outsider}');
insert into companies values ('${ids.a}','A'),('${ids.b}','B');
insert into profiles values('${ids.admin}','Admin','admin',null),('${ids.clientA}','Client A','client','${ids.a}'),('${ids.clientB}','Client B','client','${ids.b}'),('${ids.team}','Team','team',null);
insert into projects(id,company_id,title) values('${ids.pa}','${ids.a}','A project'),('${ids.pb}','${ids.b}','B project');
insert into tasks(project_id,title,internal) values('${ids.pa}','Shared task',false),('${ids.pa}','Private task',true),('${ids.pb}','Other client task',false);
insert into milestones(project_id,title) values('${ids.pa}','A milestone'),('${ids.pb}','B milestone');
insert into messages(project_id,body,internal,author_id) values('${ids.pa}','Shared comment',false,'${ids.admin}'),('${ids.pa}','Internal comment',true,'${ids.admin}'),('${ids.pb}','B comment',false,'${ids.admin}');
insert into tickets(id,project_id,title,description,priority,author_id) values('${ids.ticket}','${ids.pb}','B ticket','Description','Normal','${ids.clientB}');
insert into storage.objects(bucket_id,name,owner_id) values('project-files','${ids.pa}/deliverable.pdf','${ids.admin}'),('project-files','${ids.pb}/deliverable.pdf','${ids.admin}');
insert into files(id,project_id,name,path,size,deliverable,author_id) values('${ids.file}','${ids.pa}','A.pdf','${ids.pa}/deliverable.pdf',100,true,'${ids.admin}'),('${ids.fileb}','${ids.pb}','B.pdf','${ids.pb}/deliverable.pdf',100,true,'${ids.admin}');`);

await pg.exec(await fs.readFile(new URL('../supabase/002_operations.sql',import.meta.url),'utf8'));

await pg.exec(await fs.readFile(new URL('../supabase/003_business.sql',import.meta.url),'utf8'));
let passed=0;
const q=async(s,p=[])=>(await pg.query(s,p)).rows;const one=async(s,p=[])=>(await q(s,p))[0];
async function user(id){await pg.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);select set_config('request.jwt.claim.role','authenticated',false);set role authenticated;`);}
function eq(a,b,t){assert.deepEqual(a,b,t);passed++;console.log('PASS',t);}
async function deny(s,p,t){await assert.rejects(()=>q(s,p),undefined,t);passed++;console.log('PASS',t);}
await pg.exec(await fs.readFile(new URL('../supabase/004_service_work.sql',import.meta.url),'utf8'));
await pg.exec(await fs.readFile(new URL('../supabase/005_workspace.sql',import.meta.url),'utf8'));
await user(ids.admin);
let ms=(await one('select id from milestones where project_id=$1',[ids.pa])).id;
let other=(await one('select id from milestones where project_id=$1',[ids.pb])).id;
let t=(await one('select id from tasks where project_id=$1 and not internal',[ids.pa])).id;
await q('update tasks set start_date=$1,deadline=$2,milestone_id=$3,collaborators=$4,labels=$5 where id=$6',['2026-10-01','2026-10-10',ms,[ids.team],['Network'],t]);
eq((await one('select labels from tasks where id=$1',[t])).labels,['Network'],'Task planning persists');
await deny('update tasks set milestone_id=$1 where id=$2',[other,t],'Cross-project milestone blocked');
await deny('update tasks set collaborators=$1 where id=$2',[[ids.clientA],t],'Client collaborator blocked');
await deny('update tasks set collaborators=$1 where id=$2',[[ids.team,ids.team],t],'Duplicate collaborator blocked');
await deny('update tasks set start_date=$1 where id=$2',['2026-11-01',t],'Reversed task dates rejected');
await deny('update milestones set project_id=$1 where id=$2',[ids.pb,ms],'Milestone cannot be moved across projects');
await deny('update tasks set labels=$1 where id=$2',[['x'.repeat(41)],t],'Oversized label rejected');
await q('insert into client_contacts(company_id,name,email,notes) values($1,$2,$3,$4)',[ids.a,'Contact A','a@example.test','Staff notes']);
eq((await one('select count(*)::int n from client_contacts')).n,1,'Admin creates contact');
await q('update projects set start_date=$1,deadline=$2,labels=$3 where id=$4',['2026-10-01','2026-10-20',['Priority'],ids.pa]);
eq((await one("select count(*)::int n from workspace_activity where entity='projects'")).n,1,'Project update records activity');
await deny('insert into workspace_activity(project_id,entity,entity_id,title,action) values($1,$2,$3,$4,$5)',[ids.pa,'tasks',t,'Fake','Updated'],'Direct activity forgery denied');
const batch='90000000-0000-0000-0000-000000000001';const payload=[{name:'Imported client',email:'new@example.test',labels:'Managed,Priority'}];
eq((await one('select import_workspace($1,$2,$3) n',[batch,'clients',JSON.stringify(payload)])).n,1,'Client batch import works');
eq((await one('select import_workspace($1,$2,$3) n',[batch,'clients',JSON.stringify(payload)])).n,1,'Retry import is idempotent');
eq((await one("select count(*)::int n from companies where name='Imported client'")).n,1,'Retry does not duplicate client');
await deny('select import_workspace($1,$2,$3)',[batch,'clients',JSON.stringify([{name:'Different'}])],'Reused import ID with different payload rejected');
await deny('select import_workspace($1,$2,$3)',['90000000-0000-0000-0000-000000000002','clients',JSON.stringify([{name:'Rollback client'},{name:''}])],'Invalid batch rolls back');
eq((await one("select count(*)::int n from companies where name='Rollback client'")).n,0,'No partial client import');
await user(ids.team);
await deny('select import_workspace($1,$2,$3)',['90000000-0000-0000-0000-000000000003','clients',JSON.stringify(payload)],'Team cannot import companies');
// RLS updates can return zero rows, which also enforces denial.
eq((await q("update client_contacts set name='Unauthorized' returning id")).length,0,'Team cannot edit contacts');
eq((await one('select count(*)::int n from client_contacts')).n,1,'Team can read staff contacts');
eq((await one('select import_workspace($1,$2,$3) n',['90000000-0000-0000-0000-000000000004','projects',JSON.stringify([{company_id:ids.a,title:'Imported project',start_date:'2026-10-01',deadline:'2026-10-20'}])])).n,1,'Staff imports project');
eq((await one('select bulk_update_tasks($1,$2,$3) n',[ids.pa,[t],JSON.stringify({status:'In progress',priority:'High'})])).n,1,'Staff bulk edit works');
const tb=(await one('select id from tasks where project_id=$1',[ids.pb])).id;
await deny('select bulk_update_tasks($1,$2,$3)',[ids.pa,[t,tb],JSON.stringify({status:'Done'})],'Cross-project bulk edit rejected');
eq((await one('select status from tasks where id=$1',[t])).status,'In progress','Invalid batch preserves prior task state');
await deny('select bulk_update_tasks($1,$2,$3)',[ids.pa,[t],JSON.stringify({internal:true})],'Unsupported bulk fields rejected');
await deny('select bulk_update_tasks($1,$2,$3)',[ids.pa,[t],JSON.stringify({deadline:'2026-09-01'})],'Bulk date validation enforced');
await user(ids.clientA);
eq((await q('select * from client_contacts')).length,0,'Client cannot see staff contact notes');
eq((await q('select * from workspace_activity')).length,0,'Client cannot see staff activity');
eq((await q('select * from tasks where project_id=$1',[ids.pb])).length,0,'Other company tasks hidden');
eq((await q("select * from tasks where internal")).length,0,'Internal tasks hidden');
await deny('select bulk_update_tasks($1,$2,$3)',[ids.pa,[t],JSON.stringify({status:'Done'})],'Client cannot bulk-edit');
await deny('select import_workspace($1,$2,$3)',['90000000-0000-0000-0000-000000000005','projects',JSON.stringify([{company_id:ids.a,title:'Unauthorized'}])],'Client cannot import');
eq((await q('update tasks set labels=$1 where id=$2 returning id',[['Forged'],t])).length,0,'Client cannot change planning');
await user(ids.admin);await q('update profiles set active=false where id=$1',[ids.team]);await user(ids.team);
eq((await q('select * from client_contacts')).length,0,'Disabled staff loses directory access');
await deny('select bulk_update_tasks($1,$2,$3)',[ids.pa,[t],JSON.stringify({status:'Done'})],'Disabled staff cannot bulk-edit');
console.log(`${passed} workspace database assertions passed`);await pg.close();
