import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {workspaceRows} from './workspace';
import {csvText,downloadText} from './business-utils';
import {ActivityEvidence} from './activity-evidence';
import {downloadReportPDF} from './report-export';
const local=(v:string)=>v?new Date(Date.parse(v)+18000000).toISOString().slice(0,16):'';
const iso=(v:unknown)=>v?new Date(String(v)+':00+05:00').toISOString():null;
function Field({name,label,value='',type='text',required=false,options}:any){return <label className="p-field">{label}{options?<select name={name} defaultValue={value} required={required}><option value="">Choose…</option>{options.map((r:any)=>typeof r==='string'?<option key={r}>{r}</option>:<option key={r.id} value={r.id}>{r.title||r.name||r.id}</option>)}</select>:type==='textarea'?<textarea name={name} defaultValue={value} required={required} maxLength={2000}/>:<input name={name} type={type} defaultValue={value} required={required} maxLength={type==='text'?300:undefined} step={type==='number'?'0.001':undefined} min={type==='number'?0:undefined}/>}</label>;}
export function ActivityLog({profile}:{profile:Row}){
 const staff=['admin','team'].includes(profile.role),admin=profile.role==='admin',manager=admin||profile.crm_permissions?.some((p:string)=>['project.own','sales.manage'].includes(p)),finance=admin||profile.crm_permissions?.includes('finance.manage');
 const [files,setFiles]=useState<Row[]>([]),[rows,setRows]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[projects,setProjects]=useState<Row[]>([]),[tasks,setTasks]=useState<Row[]>([]),[tickets,setTickets]=useState<Row[]>([]),[deals,setDeals]=useState<Row[]>([]),[people,setPeople]=useState<Row[]>([]),[rates,setRates]=useState<Row[]>([]),[delays,setDelays]=useState<string[]>([]),[editing,setEditing]=useState<Row|null|false>(false),[kind,setKind]=useState('Project'),[project,setProject]=useState(''),[month,setMonth]=useState(()=>local(new Date().toISOString()).slice(0,7)),[tab,setTab]=useState('My activities'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;if(!staff)return;Promise.all([Promise.resolve(db!.rpc('work_activity_report')).then(check),...['work_activity_history','projects','tasks','tickets','crm_deals','crm_settings'].map(t=>workspaceRows(t)),workspaceRows('profiles'),finance?workspaceRows('work_hourly_rates'):Promise.resolve([]),workspaceRows('work_activity_files')]).then(([a,h,p,t,ti,d,s,u,r,f])=>{if(!live)return;setFiles(f);setRows(a||[]);setHistory(h);setProjects(p);setTasks(t);setTickets(ti);setDeals(d.map((x:Row)=>({...x,title:x.title||'Deal '+x.id.slice(0,8)})));setDelays(s.find((x:Row)=>x.id==='delay_reasons')?.value||[]);setPeople(u);setRates(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[profile.id,staff,finance,revision]);
 async function run(name:string,args:Record<string,unknown>){if(busy)return false;setBusy(true);setError('');setNotice('');try{check(await db!.rpc(name,args));setRevision(r=>r+1);setNotice('Activity record saved.');return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 if(!staff)return <p>Staff access is required.</p>;
 const visible=rows.filter(r=>r.working_date?.startsWith(month)&&(tab==='My activities'?r.user_id===profile.id:tab==='Review queue'?r.status==='Submitted':true));
 const exports=[['Employee','Working day','Link','Project','Location','Activity','Start (PKT)','End (PKT)','Hours','Outcome','Approval','Delay','Lost minutes','Blocker','Evidence filenames'],...visible.map(r=>[r.employee,r.working_date,r.link_kind,r.project||'',r.location,r.description,local(r.actual_start),local(r.actual_end),Number(r.hours).toFixed(3),r.outcome,r.status,r.delay_reason,r.lost_minutes,r.blocker,files.filter(f=>f.activity_id===r.id&&!f.removed_at).map(f=>f.name).join('; ')])];
 const action=(r:Row,a:string,n='')=>run('work_activity_action',{p_id:r.id,p_version:r.version,p_action:a,p_note:n});
 return <><h1>Daily activity log</h1><p>Enter your actual start and end in Pakistan time. Duration is calculated. Work across midnight belongs to its start date. Each crew member records their own hours; crew count does not multiply labour cost.</p>{error&&<p role="alert" className="p-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="p-toolbar">{['My activities',...(manager?['Review queue','Team report']:[]),...(finance?['Hourly rates']:[])].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setEditing(false);}}>{t}</button>)}<label>Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button disabled={busy} onClick={()=>setRevision(r=>r+1)}>Refresh activity log</button></div>
 {tab==='Hourly rates'&&finance?<section className="p-panel"><h2>Effective hourly rates · PKR</h2><p>Rates are private. Approval copies the effective rate into an immutable cost record. Later rates do not rewrite approved costs. A zero rate must be explicitly configured.</p>{rates.map(r=><p key={r.id}>{people.find(u=>u.id===r.user_id)?.name||'Staff member'} · {r.effective_on} · PKR {r.rate} / hour · {r.reason}</p>)}{admin&&<form className="p-form" onSubmit={async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);if(await run('set_work_hourly_rate',{p_user:d.get('user_id'),p_effective:d.get('effective_on'),p_rate:Number(d.get('rate')),p_reason:d.get('reason')}))f.reset();}}><Field name="user_id" label="Staff member" options={people} required/><Field name="effective_on" label="Effective from" type="date" required/><Field name="rate" label="PKR per hour" type="number" required/><Field name="reason" label="Rate calculation / reason" type="textarea" required/><button disabled={busy}>Save effective hourly rate</button></form>}</section>:<><div className="p-toolbar">{tab==='My activities'&&<button onClick={()=>{setEditing(null);setKind('Project');setProject('');}}>New activity</button>}<button disabled={busy} onClick={()=>downloadText('daily-activities.csv',csvText(exports))}>Export activities CSV</button><button disabled={busy} onClick={async()=>{setBusy(true);try{await downloadReportPDF('daily-activities.pdf','Daily activity report',month+' · Asia/Karachi · Authorized records',[{title:'Activities',headers:['Employee / day','Project / location','Activity','Hours','Outcome / review','Delay'],rows:visible.map(r=>[r.employee+' / '+r.working_date,(r.project||r.link_kind)+' / '+r.location,r.description,Number(r.hours).toFixed(3),r.outcome+' / '+r.status,r.delay_reason+(r.delay_note?' · '+r.delay_note:'')])}]);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Export activities PDF</button></div>
 {editing!==false&&tab==='My activities'&&<section className="p-panel"><h2>{editing?'Revise activity':'Create activity'}</h2><label className="p-field">Linked to<select value={editing?.link_kind||kind} disabled={!!editing} onChange={e=>{setKind(e.target.value);setProject('');}}>{['Project','Ticket','Deal','Internal'].map(t=><option key={t}>{t}</option>)}</select></label>{['Project','Ticket'].includes(editing?.link_kind||kind)&&<label className="p-field">Assigned project<select required value={editing?.project_id||project} disabled={!!editing} onChange={e=>setProject(e.target.value)}><option value="">Choose…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}
 <form key={(editing?.id||'new')+project+kind} className="p-form" onSubmit={async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),k=editing?.link_kind||kind,p=editing?.project_id||project;const payload={...d,link_kind:k,project_id:['Project','Ticket'].includes(k)?p:null,task_id:editing?editing.task_id:d.task_id||null,ticket_id:k==='Ticket'?(editing?editing.ticket_id:d.ticket_id):null,deal_id:k==='Deal'?(editing?editing.deal_id:d.deal_id):null,actual_start:iso(d.actual_start),actual_end:iso(d.actual_end),planned_start:iso(d.planned_start),planned_end:iso(d.planned_end),quantity:Number(d.quantity||0),crew:Number(d.crew||1),lost_minutes:Number(d.lost_minutes||0)};if(await run('save_work_activity',{p_id:editing?.id||null,p_version:editing?.version||null,p_data:payload}))setEditing(false);}}>
 {['Project','Ticket'].includes(editing?.link_kind||kind)&&(!editing?<Field name="task_id" label="Assigned task (required for task-only access)" options={tasks.filter(t=>t.project_id===project)}/>:<p>Original task: {tasks.find(t=>t.id===editing.task_id)?.title||'Project scope'}</p>)}{(editing?.link_kind||kind)==='Ticket'&&!editing&&<Field name="ticket_id" label="Assigned ticket" options={tickets.filter(t=>t.project_id===project)} required/>}{(editing?.link_kind||kind)==='Deal'&&!editing&&<Field name="deal_id" label="Accessible deal" options={deals} required/>}
 <Field name="location" label="Site / location" value={editing?.location} required/><Field name="activity_type" label="Task type" value={editing?.activity_type||'Installation'} options={['Installation','Survey','Complaint','Purchase / pickup','Meeting','Training','Office work','Travel']} required/><Field name="description" label="Work description" value={editing?.description} type="textarea" required/><Field name="given_by" label="Given by" options={people.filter(u=>u.active!==false&&['admin','team'].includes(u.role))} value={editing?.given_by}/>
 {['planned_start','planned_end','actual_start','actual_end'].map(n=><Field key={n} name={n} label={n.replace('_',' ')+ ' · Pakistan time'} type="datetime-local" value={local(editing?.[n]||'')} required={n.startsWith('actual')}/>)}<Field name="outcome" label="Work outcome" options={['Done','Partly done','Not done','Rescheduled']} value={editing?.outcome||'Done'} required/><Field name="quantity" label="Quantity completed" type="number" value={editing?.quantity||0}/><Field name="crew" label="Crew size (context only)" type="number" value={editing?.crew||1}/><Field name="delay_reason" label="Delay reason" options={delays} value={editing?.delay_reason}/><Field name="delay_note" label="Delay explanation (required for late work)" type="textarea" value={editing?.delay_note}/><Field name="lost_minutes" label="Minutes lost to delay" type="number" value={editing?.lost_minutes||0}/><Field name="blocker" label="Requirement / blocker" type="textarea" value={editing?.blocker}/><Field name="remarks" label="Remarks" type="textarea" value={editing?.remarks}/><Field name="evidence" label="Evidence document reference (optional)" value={editing?.evidence}/><button disabled={busy}>Save activity draft</button><button type="button" onClick={()=>setEditing(false)}>Close editor</button></form></section>}
 {!visible.length&&<p>No activities in this month.</p>}{visible.map(r=><section key={r.id} className="p-panel"><h2>{r.employee} · {r.working_date} · {r.status}</h2><p>{r.project||r.link_kind} · {r.location} · {r.activity_type}</p><p>{r.description} · {r.outcome}</p><p>{local(r.actual_start)} → {local(r.actual_end)} · {Number(r.hours).toFixed(3)} hours</p>{r.labour_cost!=null&&<p>Approved hourly labour cost: PKR {r.labour_cost}</p>}{r.delay_reason&&<p>Delay: {r.delay_reason} · {r.delay_note} · {r.lost_minutes} minutes</p>}{r.blocker&&<p>Blocker: {r.blocker}</p>}{r.evidence&&<p>Evidence reference: {r.evidence}</p>}
 {r.user_id===profile.id&&['Draft','Rejected'].includes(r.status)&&<button disabled={busy} onClick={()=>{setEditing(r);setKind(r.link_kind);setProject(r.project_id||'');}}>Edit activity</button>}{r.user_id===profile.id&&r.status==='Draft'&&<button disabled={busy} onClick={()=>action(r,'Submit')}>Submit activity</button>}
 {((manager&&r.user_id!==profile.id&&r.status==='Submitted')||(admin&&r.user_id!==profile.id&&r.reviewed_by!==profile.id&&r.status==='Approved')||(r.user_id===profile.id&&['Draft','Rejected'].includes(r.status)))&&<form className="p-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);action(r,String(d.get('action')),String(d.get('note')));}}><Field name="action" label="Review action" options={r.status==='Submitted'?['Approve','Reject']:r.status==='Approved'?['Void']:['Cancel']} required/><Field name="note" label="Review / correction reason" type="textarea" required/><button disabled={busy}>Record activity action</button></form>}
 <ActivityEvidence key={profile.id+':'+r.id} activity={r} profile={profile} files={files.filter(f=>f.activity_id===r.id)} busy={busy} onBusy={setBusy} onRefresh={()=>setRevision(v=>v+1)}/>
 <details><summary>Activity history</summary>{history.filter(h=>h.activity_id===r.id).map(h=><p key={h.id}>{h.action} · {local(h.created_at)} · {h.note}</p>)}</details></section>)}</>}
 <p>Activity approval records labour cost; it does not publish client results, finish a task or approve overtime/payroll. Expense claims are submitted separately in Work expenses. Private evidence files are reviewed with the activity. Calendar scheduling automation remains pending.</p></>;
}
