import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {Input,SaveForm,taskStatuses} from './operations';
import {workspaceRows} from './workspace';
import {csvText,downloadText} from './business-utils';
import './calendar-estimates.css';
const utcToday=()=>new Date().toISOString().slice(0,10);
const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const localInput=(s:string)=>{const d=new Date(s);return `${localDate(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
const options=(rows:Row[])=>rows.map(r=><option value={r.id} key={r.id}>{r.title||r.name}</option>);
export function CalendarWorkspace({profile,projects,onOpen}:any){
 const [events,setEvents]=useState<Row[]>([]),[tasks,setTasks]=useState<Row[]>([]),[milestones,setMilestones]=useState<Row[]>([]),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[edit,setEdit]=useState<Row|null>(null),[month,setMonth]=useState(localDate(new Date()).slice(0,7)),[scope,setScope]=useState('all'),[mode,setMode]=useState('month'),[now,setNow]=useState(Date.now());
 const staff=profile.role!=='client';
 async function load(){const [e,t,m]=await Promise.all(['calendar_events','tasks','milestones'].map(x=>workspaceRows(x)));setEvents(e);setTasks(t);setMilestones(m);}
 useEffect(()=>{let active=true;Promise.all(['calendar_events','tasks','milestones'].map(x=>workspaceRows(x))).then(([e,t,m])=>{if(active){setEvents(e);setTasks(t);setMilestones(m);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});const timer=setInterval(()=>setNow(Date.now()),30000);return()=>{active=false;clearInterval(timer);};},[profile.id]);
 async function run(fn:()=>PromiseLike<any>){if(busy)return false;setBusy(true);setError('');try{check(await fn());await load();setEdit(null);setNote('Saved');return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 const mine=tasks.filter(t=>t.status!=='Done'&&(t.assignee===profile.id||(t.collaborators||[]).includes(profile.id))).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));
 const entries=[...events.filter(e=>!e.cancelled).map(e=>({id:e.id,day:localDate(new Date(e.starts_at)),title:e.title,kind:'Event',project:e.project_id,event:e})),...tasks.filter(t=>t.deadline&&t.status!=='Done').map(t=>({id:t.id,day:t.deadline,title:t.title,kind:'Task due',project:t.project_id,event:null})),...milestones.filter(m=>m.deadline&&m.status!=='Completed').map(m=>({id:m.id,day:m.deadline,title:m.title,kind:'Milestone',project:m.project_id,event:null})),...projects.filter((p:Row)=>p.deadline&&p.status!=='Completed').map((p:Row)=>({id:p.id,day:p.deadline,title:p.title,kind:'Project due',project:p.id,event:null}))].filter(e=>scope==='all'||scope==='personal'&&!e.project||e.project===scope).sort((a,b)=>a.day.localeCompare(b.day));
 const visible=entries.filter(e=>e.day.startsWith(month));const first=new Date(`${month}-01T12:00:00`),days=Number.isFinite(first.getTime())?new Date(first.getFullYear(),first.getMonth()+1,0).getDate():0;
 const reminders=events.filter(e=>!e.cancelled&&Date.parse(e.starts_at)-e.reminder_minutes*60000<=now&&Date.parse(e.ends_at)>=now);
 const display=(e:any)=><button className="ce-entry" key={e.kind+e.id} onClick={()=>e.event?setEdit(e.event):onOpen(e.project)}><small>{e.kind}</small><span>{e.title}</span>{e.event&&<small>{new Date(e.event.starts_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>}</button>;
 return <><h1>My workspace & calendar</h1><p>Events use your timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Task and project deadlines retain their recorded dates. Reminders appear here while the portal is open.</p>{error&&<p role="alert" className="p-error">{error}</p>}{note&&<p role="status">{note}</p>}{loading&&<p role="status">Loading calendar…</p>}<div className="p-toolbar"><button disabled={busy} onClick={()=>setEdit({} as Row)}>New event</button><button disabled={busy} onClick={()=>run(()=>load().then(()=>({data:null,error:null})))}>Refresh calendar</button><label>Month<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><label>Calendar scope<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">All accessible records</option><option value="personal">Private events</option>{options(projects)}</select></label><label>View<select value={mode} onChange={e=>setMode(e.target.value)}><option value="month">Month</option><option value="agenda">Agenda</option></select></label><button onClick={()=>downloadText('calendar.csv',csvText([['Date','Type','Title','Project'],...visible.map(e=>[e.day,e.kind,e.title,projects.find((p:Row)=>p.id===e.project)?.title||'Private'])]))}>Export month CSV</button></div>
 {reminders.length>0&&<section className="p-panel"><h2>Event reminders</h2>{reminders.map(e=><p key={e.id}>{e.title} · {new Date(e.starts_at).toLocaleString()} <button onClick={()=>setEdit(e)}>Open event</button></p>)}</section>}
 {edit&&<section className="p-panel"><h2>{edit.id?'Event details':'New calendar event'}</h2><button onClick={()=>setEdit(null)}>Close event</button>{(!edit.id||(!edit.project_id&&edit.owner_id===profile.id)||edit.project_id&&staff)?<SaveForm key={edit.id||'new'} busy={busy} label="Save event" onSave={v=>run(()=>db!.rpc('save_calendar_event',{p_id:edit.id||null,p_version:edit.version||null,p_project:edit.id?edit.project_id:v.project_id||null,p_title:v.title,p_notes:v.notes,p_start:new Date(v.starts_at).toISOString(),p_end:new Date(v.ends_at).toISOString(),p_internal:v.internal==='true',p_reminder:Number(v.reminder_minutes),p_cancelled:v.cancelled==='true'}))}>{!edit.id&&staff&&<Input name="project_id" label="Event audience"><option value="">Private — only me</option>{options(projects)}</Input>}<Input name="title" label="Event title" required value={edit.title}/><Input name="notes" label="Event notes" type="textarea" value={edit.notes}/><Input name="starts_at" label="Starts (local time)" type="datetime-local" required value={edit.starts_at?localInput(edit.starts_at):''}/><Input name="ends_at" label="Ends (local time)" type="datetime-local" required value={edit.ends_at?localInput(edit.ends_at):''}/>{staff&&<Input name="internal" label="Project event visibility" value={String(edit.internal??true)}><option value="true">Staff only</option><option value="false">Shared with project client</option></Input>}<label className="p-field">Reminder minutes before start<input name="reminder_minutes" type="number" min="0" max="10080" required defaultValue={edit.reminder_minutes??15}/></label><Input name="cancelled" label="Event state" value={String(edit.cancelled??false)}><option value="false">Scheduled</option><option value="true">Cancelled</option></Input><p>Private events remain private regardless of the project visibility selection.</p></SaveForm>:<><h3>{edit.title}</h3><p>{new Date(edit.starts_at).toLocaleString()} — {new Date(edit.ends_at).toLocaleString()}</p><p className="p-pre">{edit.notes}</p></>}</section>}
 {mode==='month'?<div className="ce-month" aria-label="Monthly calendar">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:first.getDay()||0},(_,i)=><div key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`;return <section key={day} className={day===localDate(new Date())?'ce-today':''}><strong>{i+1}</strong>{visible.filter(e=>e.day===day).map(display)}</section>;})}</div>:<section className="p-panel"><h2>Monthly agenda</h2>{visible.map(e=><div className="p-list-row" key={e.kind+e.id}><span>{e.day}</span>{display(e)}</div>)}{!visible.length&&<p>No scheduled records in this month.</p>}</section>}
 <section className="p-panel"><h2>My open tasks</h2>{mine.map(t=><div className="p-list-row" key={t.id}><div><strong>{t.title}</strong><p>{t.deadline||'No deadline'} · {t.priority}{t.deadline&&t.deadline<utcToday()?' · Overdue':''}</p></div>{staff&&<select aria-label={`My task status: ${t.title}`} value={t.status} disabled={busy} onChange={e=>run(()=>db!.from('tasks').update({status:e.target.value}).eq('id',t.id).select().single())}>{taskStatuses.map(s=><option key={s}>{s}</option>)}</select>}<button onClick={()=>onOpen(t.project_id)}>Open project</button></div>)}{!mine.length&&<p>No open tasks assigned to you or listing you as a collaborator.</p>}</section><details className="p-panel"><summary>Cancelled events</summary>{events.filter(e=>e.cancelled).map(e=><p key={e.id}>{e.title} <button onClick={()=>setEdit(e)}>View / restore</button></p>)}</details></>;
}
const emptyLine=()=>({description:'',quantity:1,unit_price:0,tax_percent:0});
export function Estimates({profile,companies,refresh,onOpen}:any){
 const [rows,setRows]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState(false),[lines,setLines]=useState<any[]>([emptyLine()]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[decision,setDecision]=useState('');const admin=profile.role==='admin';const current=rows.find(e=>e.id===selected);
 const load=async()=>{const [e,h]=await Promise.all(['estimates','estimate_history'].map(x=>workspaceRows(x)));setRows(e.sort((a,b)=>b.created_at.localeCompare(a.created_at)));setHistory(h);};
 useEffect(()=>{let active=true;Promise.all(['estimates','estimate_history'].map(x=>workspaceRows(x))).then(([e,h])=>{if(active){setRows(e.sort((a,b)=>b.created_at.localeCompare(a.created_at)));setHistory(h);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[profile.id]);
 async function run(fn:()=>PromiseLike<any>,message='Saved'){if(busy)return false;setBusy(true);setError('');setNote('');try{const id=check(await fn());await load();if(typeof id==='string')setSelected(id);setEditing(false);setDecision('');setNote(message);return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 const action=(a:string)=>run(()=>db!.rpc('estimate_action',{p_id:current!.id,p_version:current!.version,p_action:a,p_note:''}),a==='publish'?'Published in the client portal. External messages are not sent automatically.':'Updated');
 const filtered=rows.filter(e=>(!status||e.status===status)&&`${e.number} ${e.title} ${e.company_name}`.toLowerCase().includes(search.toLowerCase()));
 return <><h1>Estimates & proposals</h1><p>Prepare an offer, publish it for the client’s decision, then convert an accepted offer into a project or draft invoice.</p>{error&&<p role="alert" className="p-error">{error}</p>}{note&&<p role="status">{note}</p>}<div className="p-toolbar">{admin&&<button onClick={()=>{setSelected(null);setEditing(true);setLines([emptyLine()]);}}>New estimate / proposal</button>}<button disabled={busy} onClick={()=>run(()=>load().then(()=>({data:null,error:null})),'Refreshed')}>Refresh estimates</button><label>Search estimates<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Estimate status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All states</option>{['Draft','Published','Accepted','Declined','Withdrawn','Superseded'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 <div className="p-table-scroll"><table className="p-table"><thead><tr><th>Number</th><th>Title / client</th><th>Status</th><th>Valid until (UTC)</th><th>Total</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><button onClick={()=>{setSelected(e.id);setEditing(false);setDecision('');}}>{e.number} · r{e.revision}</button></td><td>{e.title}<br/>{e.company_name}</td><td>{e.status}{e.status==='Published'&&e.valid_until<utcToday()?' · Expired':''}</td><td>{e.valid_until}</td><td>{e.currency} {Number(e.total).toFixed(2)}</td></tr>)}</tbody></table></div>{!filtered.length&&<p>No estimates match.</p>}
 {editing&&admin&&<section className="p-panel"><h2>{current?'Edit draft':'Create draft'}</h2><button onClick={()=>setEditing(false)}>Cancel editing</button><SaveForm key={current?.id||'new'} busy={busy} label="Save draft" onSave={v=>run(()=>db!.rpc('save_estimate',{p_id:current?.id||null,p_version:current?.version||null,p_company:current?.company_id||v.company_id,p_kind:v.kind,p_title:v.title,p_currency:v.currency,p_valid:v.valid_until,p_scope:v.scope,p_terms:v.terms,p_items:lines}))}>{!current&&<Input name="company_id" label="Client company" required><option value="">Choose client</option>{options(companies)}</Input>}<Input name="kind" label="Document type" value={current?.kind||'Estimate'}><option>Estimate</option><option>Proposal</option></Input><Input name="title" label="Offer title" value={current?.title} required/><Input name="currency" label="Currency (3-letter code)" value={current?.currency||'PKR'} required max={3}/><Input name="valid_until" label="Valid until (inclusive, UTC)" type="date" value={current?.valid_until||utcToday()} required/><Input name="scope" label="Scope of work" type="textarea" value={current?.scope}/><Input name="terms" label="Terms and exclusions" type="textarea" value={current?.terms}/><div className="p-table-scroll"><table className="p-table"><thead><tr><th>Description</th><th>Quantity</th><th>Unit price</th><th>Tax %</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={i}>{['description','quantity','unit_price','tax_percent'].map(k=><td key={k}><input aria-label={`${k} line ${i+1}`} required type={k==='description'?'text':'number'} maxLength={k==='description'?500:undefined} min={k==='quantity'?0.001:0} max={k==='quantity'?100000:k==='tax_percent'?100:undefined} step={k==='quantity'?'0.001':'0.01'} value={l[k]} onChange={e=>setLines(ls=>ls.map((r,n)=>n===i?{...r,[k]:e.target.value}:r))}/></td>)}<td><button type="button" disabled={lines.length===1} onClick={()=>setLines(ls=>ls.filter((_,n)=>n!==i))}>Remove line {i+1}</button></td></tr>)}</tbody></table></div><button type="button" disabled={lines.length>=100} onClick={()=>setLines(ls=>[...ls,emptyLine()])}>Add line</button><p>Saved totals are calculated by the server, with each line and tax rounded to two decimal places.</p></SaveForm></section>}
 {current&&!editing&&<section className="p-panel ce-document"><h2>{current.kind} {current.number} · revision {current.revision}</h2><h3>{current.title}</h3><p>{current.company_name} · {current.status} · Valid until {current.valid_until} (UTC)</p><h3>Scope of work</h3><p className="p-pre">{current.scope||'No additional scope.'}</p><div className="p-table-scroll"><table className="p-table"><thead><tr><th>Description</th><th>Quantity</th><th>Unit price</th><th>Tax %</th><th>Line total</th></tr></thead><tbody>{current.items.map((l:any,i:number)=><tr key={i}><td>{l.description}</td><td>{l.quantity}</td><td>{Number(l.unit_price).toFixed(2)}</td><td>{l.tax_percent}</td><td>{(Number(l.net)+Number(l.tax)).toFixed(2)}</td></tr>)}</tbody></table></div><p>Subtotal {current.currency} {Number(current.subtotal).toFixed(2)} · Tax {Number(current.tax_total).toFixed(2)}</p><h3>Total {current.currency} {Number(current.total).toFixed(2)}</h3><h3>Terms and exclusions</h3><p className="p-pre">{current.terms||'No additional terms.'}</p><button onClick={()=>downloadText(`${current.number}.txt`,`${current.kind} ${current.number} / revision ${current.revision}\n${current.company_name}\n${current.title}\nStatus: ${current.status}\nValid until: ${current.valid_until} UTC\n\n${current.scope}\n\n${current.items.map((l:any)=>`${l.description}: ${l.quantity} x ${l.unit_price}, tax ${l.tax_percent}%, total ${(Number(l.net)+Number(l.tax)).toFixed(2)}`).join('\n')}\n\nTotal: ${current.currency} ${current.total}\n\nTerms:\n${current.terms}\n\nDecision: ${current.decision_note||''}`, 'text/plain')}>Download offer text</button>
 {admin&&<div className="p-toolbar">{current.status==='Draft'&&<><button disabled={busy} onClick={()=>{setLines(current.items.map((l:any)=>({...l})));setEditing(true);}}>Edit draft</button><button disabled={busy} onClick={()=>action('publish')}>Publish to client portal</button></>}{current.status==='Published'&&<button disabled={busy} onClick={()=>action('withdraw')}>Withdraw offer</button>}{['Published','Declined','Withdrawn'].includes(current.status)&&<button disabled={busy} onClick={()=>action('revise')}>Create revised draft</button>}</div>}
 {!admin&&current.status==='Published'&&current.valid_until>=utcToday()&&<><p>Review the scope, total, and terms before recording your company’s decision.</p><button onClick={()=>setDecision('accept')}>Accept offer</button><button onClick={()=>setDecision('decline')}>Decline offer</button>{decision&&<SaveForm busy={busy} label={decision==='accept'?'Confirm acceptance':'Confirm decline'} onSave={v=>run(()=>db!.rpc('estimate_action',{p_id:current.id,p_version:current.version,p_action:decision,p_note:v.note}),'Decision recorded')}><Input name="note" label="Decision note" type="textarea"/><label className="p-check"><input type="checkbox" required/>I have reviewed this revision and am authorized to {decision} this offer for my company.</label><button type="button" onClick={()=>setDecision('')}>Cancel decision</button></SaveForm>}</>}
 {current.decided_at&&<p>Decision recorded {new Date(current.decided_at).toLocaleString()}: {current.decision_note||current.status}</p>}
 {admin&&current.status==='Accepted'&&<section><h3>Convert accepted offer</h3>{current.project_id?<button onClick={()=>onOpen(current.project_id)}>Open created project</button>:<button disabled={busy} onClick={()=>run(async()=>{const r=await db!.rpc('convert_estimate',{p_id:current.id,p_target:'project',p_due:null});check(r);await refresh();return {data:null,error:null};},'Project created. Use Open created project below.')}>Create project</button>}{current.invoice_id?<p>Draft invoice created. Open Invoices to add bank instructions, review, and issue it.</p>:<SaveForm busy={busy} label="Create draft invoice" onSave={v=>run(async()=>{check(await db!.rpc('convert_estimate',{p_id:current.id,p_target:'invoice',p_due:v.due}));return {data:null,error:null};},'Draft invoice created. Review it in Invoices before issuing.')}><Input name="due" label="Invoice due date (UTC)" type="date" value={utcToday()} required/></SaveForm>}<p>Conversion creates at most one project and one draft invoice per accepted offer. It does not collect payment or issue an invoice.</p></section>}
 <details><summary>Revision and action history</summary>{current.previous_id&&<p>Previous revision: {rows.find(r=>r.id===current.previous_id)?.number||'Earlier offer'}</p>}{history.filter(h=>h.estimate_id===current.id).sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(h=><p key={h.id}>{new Date(h.created_at).toLocaleString()} · {h.action}</p>)}</details></section>}</>;
}
