import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {workspaceRows} from './workspace';
const permissions=['customer.read','sales.manage','sales.own','product.own','project.own','team.own','work.own','finance.manage','hr.manage','support.own','stock.manage','purchase.manage','logistics.manage'];
export function CrmConfiguration({profile,members}:{key?:string;profile:Row;members:Row[]}){
 const [data,setData]=useState<Record<string,Row[]>>({roles:[],teams:[],memberships:[],settings:[],history:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const load=async()=>{const tables=['roles','teams','memberships','settings','config_history'];const rows=await Promise.all(tables.map(t=>workspaceRows('crm_'+t)));setData(Object.fromEntries(tables.map((t,i)=>[t==='config_history'?'history':t,rows[i]])));setLoaded(true);};
 useEffect(()=>{if(profile.role==='admin')load().catch(e=>setError(e.message));},[profile.id]);
 const save=async(name:string,args:any)=>{setBusy(true);setError('');try{check(await db!.rpc(name,args));await load();return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}};
 if(profile.role!=='admin')return <p role="alert">Administrator access required.</p>;
 return <><h1>CRM configuration</h1><p>Manage department teams, roles and shared categories. Department permissions apply to CRM workflows that use them; existing project assignment restrictions still apply.</p>{error&&<p role="alert" className="p-error">{error}</p>}{!loaded&&<p>Loading configuration…</p>}
 <section className="p-panel"><h2>Teams</h2><form className="p-form" onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const d=new FormData(f);if(await save('save_crm_configuration',{p_kind:'team',p_id:null,p_version:null,p_name:d.get('name')}))f.reset();}}><label className="p-field">Team name<input name="name" required maxLength={100}/></label><button disabled={busy}>Create team</button></form>{data.teams.map(t=><div className="p-list-row" key={t.id}><strong>{t.name}</strong><span>{t.active?'Active':'Inactive'}</span><button disabled={busy} onClick={()=>save('save_crm_configuration',{p_kind:'team',p_id:t.id,p_version:t.version,p_name:t.name,p_active:!t.active})}>{t.active?'Deactivate team':'Activate team'}</button></div>)}</section>
 <section className="p-panel"><h2>Department roles</h2>{data.roles.map(r=><details key={r.id}><summary>{r.name} · {r.active?'Active':'Inactive'}</summary><form className="p-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);save('save_crm_configuration',{p_kind:'role',p_id:r.id,p_version:r.version,p_name:d.get('name'),p_active:d.get('active')==='on',p_value:d.getAll('permission')});}}><label className="p-field">Role name<input name="name" required maxLength={100} defaultValue={r.name}/></label><label className="p-check"><input type="checkbox" name="active" defaultChecked={r.active}/>Active role</label>{permissions.map(p=><label className="p-check" key={p}><input type="checkbox" name="permission" value={p} defaultChecked={r.permissions.includes(p)}/>{p}</label>)}<button disabled={busy}>Save role</button></form></details>)}</section>
 <section className="p-panel"><h2>Staff memberships</h2><form className="p-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);save('set_crm_membership',{p_user:d.get('user'),p_role:d.get('role'),p_team:d.get('team'),p_enabled:true});}}><label className="p-field">Staff<select name="user" required><option value="">Choose staff…</option>{members.filter(u=>u.active&&u.role==='team').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="p-field">Department role<select name="role" required><option value="">Choose role…</option>{data.roles.filter(r=>r.active).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="p-field">Team<select name="team" required><option value="">Choose team…</option>{data.teams.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button disabled={busy}>Assign department membership</button></form>{data.memberships.map(m=><div className="p-list-row" key={m.id}><span>{members.find(u=>u.id===m.user_id)?.name||'Staff'} · {data.roles.find(r=>r.id===m.role_id)?.name} · {data.teams.find(t=>t.id===m.team_id)?.name}</span><button disabled={busy} onClick={()=>save('set_crm_membership',{p_user:m.user_id,p_role:m.role_id,p_team:m.team_id,p_enabled:false})}>Remove membership</button></div>)}</section>
 <section className="p-panel"><h2>Shared categories</h2>{data.settings.filter(s=>Array.isArray(s.value)).map(s=><form className="p-form" key={s.id+':'+s.version} onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);save('save_crm_configuration',{p_kind:'setting',p_id:s.id,p_version:s.version,p_name:s.label,p_value:String(d.get('options')).split('\n').map(x=>x.trim()).filter(Boolean)});}}><label className="p-field">{s.label}<textarea name="options" rows={5} defaultValue={s.value.join('\n')} required/></label><button disabled={busy}>Save {s.label.toLowerCase()}</button></form>)}</section>
 <section className="p-panel"><h2>Configuration history</h2>{data.history.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,50).map(h=><p key={h.id}>{new Date(h.created_at).toLocaleString()} · {h.entity} · {h.action} · {members.find(u=>u.id===h.actor_id)?.name||'Administrator'}</p>)}</section></>;
}
export function CustomerHistory({profile,companies,onOpen}:{key?:string;profile:Row;companies:Row[];onOpen:(id:string)=>void}){
 const [company,setCompany]=useState(''),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;setRows([]);setError('');if(!company)return;setLoading(true);db!.rpc('customer_history',{p_company:company}).then(r=>{if(live){try{setRows(check(r));}catch(e:any){setError(e.message);}setLoading(false);}});return()=>{live=false;};},[company,profile.id]);
 return <><h1>Customer history</h1><p>Connected projects, tasks, support, estimates, contracts and invoices. Only records permitted for your account appear. The latest 500 events are shown.</p><label className="p-field">Customer<select value={company} onChange={e=>setCompany(e.target.value)}><option value="">Choose customer…</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{error&&<p role="alert" className="p-error">{error}</p>}{loading&&<p>Loading history…</p>}{company&&!loading&&!error&&!rows.length&&<p>No visible history for this customer.</p>}<section className="p-panel">{rows.map(r=><div className="p-list-row" key={r.kind+':'+r.id}><div><strong>{r.kind}: {r.title}</strong><p>{r.state} · {new Date(r.happened_at).toLocaleString()}</p></div>{r.project_id&&<button onClick={()=>onOpen(r.project_id)}>Open project</button>}</div>)}</section></>;
}
