import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {workspaceRows} from './workspace';
import {csvText,downloadText} from './business-utils';

export function HrLeave({profile}:{key?:string;profile:Row}){
 const staff=['admin','team'].includes(profile.role),hr=staff&&(profile.role==='admin'||profile.crm_permissions?.includes('hr.manage'));
 const [rows,setRows]=useState<Row[]>([]),[allowances,setAllowances]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[people,setPeople]=useState<Row[]>([]),[balances,setBalances]=useState<Row[]>([]),[employee,setEmployee]=useState(profile.id),[year,setYear]=useState(new Date(Date.now()+18000000).getUTCFullYear()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;setBalances([]);setRows([]);setError('');if(!staff)return;Promise.all([workspaceRows('hr_leave_requests'),workspaceRows('hr_leave_allowances'),workspaceRows('hr_leave_history'),db!.rpc('hr_leave_people').then(check),db!.rpc('hr_leave_balances',{p_user:employee,p_year:year}).then(check)]).then(([r,a,h,p,b])=>{if(live){setRows(r);setAllowances(a);setHistory(h);setPeople(p||[]);setBalances(b||[]);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[profile.id,staff,employee,year,revision]);
 async function run(name:string,args:any){if(busy)return false;setBusy(true);setError('');setNotice('');try{check(await db!.rpc(name,args));setRevision(r=>r+1);setNotice('Leave record saved.');return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 if(!staff)return <p>Staff access required.</p>;
 const name=(id:string)=>people.find(p=>p.id===id)?.name||'Staff member',shown=rows.filter(r=>r.user_id===employee&&Number(r.starts_on.slice(0,4))===year);
 return <section className="p-panel"><h2>Leave requests & balances</h2><p>HR allocates each annual allowance. Pending requests reserve the balance; the designated manager approves or rejects them. Off-days and confirmed holidays do not consume leave. Approved leave cancellation requires manager review.</p>{error&&<p role="alert" className="p-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="p-toolbar"><label>Employee<select value={employee} onChange={e=>setEmployee(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Leave year<input type="number" min="2000" max="2200" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><button disabled={busy} onClick={()=>setRevision(v=>v+1)}>Refresh leave</button></div>
 <h3>Balances · {year}</h3>{balances.map(b=><p key={b.kind}>{b.kind} · Allowance {b.allowance} days · Approved {b.used} · Pending {b.pending} · Available {b.available}</p>)}{!balances.length&&<p>No allowance configured for this employee and year.</p>}
 {employee===profile.id&&<form className="p-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);let id=form.dataset.requestId;if(!id){id=crypto.randomUUID();form.dataset.requestId=id;}if(await run('request_hr_leave',{p_id:id,p_kind:d.get('kind'),p_start:d.get('starts_on'),p_end:d.get('ends_on'),p_half:d.get('half_day')==='on',p_reason:d.get('reason'),p_half_part:String(d.get('half_part')||'Morning')})){form.reset();delete form.dataset.requestId;}}}><h3>Request my leave</h3><label className="p-field">Leave type<select name="kind" required>{['Annual','Sick','Casual','Unpaid'].map(k=><option key={k}>{k}</option>)}</select></label><label className="p-field">First day<input name="starts_on" type="date" required/></label><label className="p-field">Last day<input name="ends_on" type="date" required/></label><label className="p-check"><input name="half_day" type="checkbox"/>Half-day (single working date)</label><label className="p-field">Half-day part (only for half-day requests)<select name="half_part"><option>Morning</option><option>Afternoon</option></select></label><label className="p-field">Reason<textarea name="reason" maxLength={2000} required/></label><p>Dates must be in one year. Do not include medical documents or diagnoses in this text. Resolve any conflicting attendance or activity first.</p><button disabled={busy}>Submit leave request</button></form>}
 {hr&&<details><summary>Configure annual allowance</summary><form key={employee+'-'+year} className="p-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),kind=String(d.get('kind')),a=allowances.find(a=>a.user_id===employee&&a.year===year&&a.kind===kind);run('save_hr_leave_allowance',{p_user:employee,p_year:year,p_kind:kind,p_units:Number(d.get('units')),p_version:a?.version||null,p_reason:d.get('reason'),p_half_part:String(d.get('half_part')||'Morning')});}}><label className="p-field">Type<select name="kind">{['Annual','Sick','Casual','Unpaid'].map(k=><option key={k}>{k}</option>)}</select></label><label className="p-field">Allowed days<input type="number" name="units" min="0" max="366" step="0.5" required/></label><label className="p-field">Allocation / adjustment basis<textarea name="reason" maxLength={2000} required/></label><button disabled={busy}>Save leave allowance</button></form></details>}
 <button disabled={busy} onClick={()=>downloadText('leave-balances.csv',csvText([['Employee','Year','Type','Allowance days','Approved days','Pending days','Available days'],...balances.map(b=>[name(employee),year,b.kind,b.allowance,b.used,b.pending,b.available])]))}>Export leave balances CSV</button>
 <h3>Requests · {name(employee)}</h3>{shown.map(r=>{const own=r.user_id===profile.id,actions=own?(r.status==='Submitted'?['Withdraw']:r.status==='Approved'?['Request cancellation']:[]):!people.find(p=>p.id===r.user_id)?.can_review?[]:r.status==='Submitted'?['Approve','Reject']:r.status==='Cancellation requested'?['Cancel approved','Keep approved']:[];return <article className="p-panel" key={r.id}><h4>{r.kind} · {r.starts_on} → {r.ends_on} · {r.units} days · {r.status}</h4><p>{r.reason}</p>{r.review_note&&<p>Review: {r.review_note}</p>}{actions.length>0&&<form className="p-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);run('hr_leave_action',{p_id:r.id,p_version:r.version,p_action:d.get('action'),p_note:d.get('note')});}}><label className="p-field">Action<select name="action">{actions.map(a=><option key={a}>{a}</option>)}</select></label><label className="p-field">Action reason<textarea name="note" maxLength={2000} required/></label><button disabled={busy}>Record leave action</button></form>}<details><summary>Leave history</summary>{history.filter(h=>h.request_id===r.id).map(h=><p key={h.id}>{h.action} · {h.created_at} · {h.note}</p>)}</details></article>;})}{!shown.length&&<p>No leave requests in this year.</p>}
 <p>Approved leave appears in attendance and monthly review calculations. Unpaid leave units are shown for documented HR deductions. Locked months cannot be changed.</p></section>;
}
