import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {workspaceRows} from './workspace';
export function HrSalaryBasis({profile,people,roles}:{key?:string;profile:Row;people:Row[];roles:Row[]}){
 const staff=['admin','team'].includes(profile.role),admin=profile.role==='admin',hr=admin||profile.crm_permissions?.includes('hr.manage');
 const [employment,setEmployment]=useState<Row[]>([]),[policies,setPolicies]=useState<Row[]>([]),[employee,setEmployee]=useState(profile.id),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let live=true;setEmployment([]);setPolicies([]);if(staff)Promise.all([workspaceRows('hr_employment'),workspaceRows('hr_payout_policies')]).then(([e,p])=>{if(live){setEmployment(e);setPolicies(p);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[profile.id,staff,revision]);
 async function save(name:string,args:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{check(await db!.rpc(name,args));setRevision(r=>r+1);setNotice('Salary basis saved. Recalculate and rebuild any affected unlocked monthly summary.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 if(!staff)return <p>Staff access is required.</p>;
 const current=employment.find(e=>e.user_id===employee);
 return <section className="p-panel"><h2>Employment & salary rules</h2><p>Employment dates and deduction rules must be explicitly confirmed. Salary changes use the effective employee terms. Calendar-day proration includes employed off-days; working-day proration uses scheduled days excluding confirmed holidays. These rules do not record salary payments.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<label className="p-field">Employee<select value={employee} onChange={e=>setEmployee(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={busy} onClick={()=>setRevision(r=>r+1)}>Refresh salary basis</button><p>{current?`Employment: ${current.starts_on} through ${current.ends_on||'ongoing'} · Version ${current.version} · ${current.reason}`:'Employment dates are not configured.'}</p>
 {hr&&<form key={employee+':'+(current?.version||0)} className="p-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);save('save_hr_employment',{p_user:employee,p_start:d.get('starts_on'),p_end:d.get('ends_on')||null,p_version:current?.version||null,p_reason:d.get('reason')});}}><h3>Confirm employment period</h3><label className="p-field">Employment starts<input name="starts_on" type="date" required defaultValue={current?.starts_on||''}/></label><label className="p-field">Employment ends (optional)<input name="ends_on" type="date" defaultValue={current?.ends_on||''}/></label><label className="p-field">Employment reason<textarea name="reason" required maxLength={2000}/></label><button disabled={busy}>Save employment dates</button></form>}
 <h3>Effective payout policies</h3>{!policies.length&&<p>No payout policies configured. Existing summaries retain their manual deduction basis until explicit configuration.</p>}{policies.map(p=><p key={p.id}>{roles.find(r=>r.id===p.role_id)?.name||p.role_id} · {p.effective_on} · {p.proration} · Absence fraction {p.absence_fraction} · {p.late_free} late check-ins allowed · {p.late_mode} {p.late_rate} · {p.reason}</p>)}
 {admin&&<form className="p-form" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));save('save_hr_payout_policy',{p_data:{...d,absence_fraction:Number(d.absence_fraction),late_free:Number(d.late_free),late_rate:Number(d.late_rate)}});}}><h3>Add effective payout policy</h3><label className="p-field">Payout policy role<select name="role_id" required><option value="default">Default for roles without a specific policy</option>{roles.filter(r=>r.active!==false).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="p-field">Effective month<input name="effective_on" type="date" required/></label><p>Choose the first day of a month. Saving creates a new policy revision; locked summaries retain their approved basis.</p><label className="p-field">Salary proration basis<select name="proration"><option>Calendar days</option><option>Working days</option></select></label><label className="p-field">Absence deduction fraction<input name="absence_fraction" type="number" min="0" max="1" step="0.0001" required/></label><label className="p-field">Monthly late check-ins allowed<input name="late_free" type="number" min="0" max="31" step="1" required/></label><label className="p-field">Late deduction mode<select name="late_mode"><option>None</option><option>Fixed amount</option><option>Day fraction</option></select></label><label className="p-field">Late rate (PKR amount or day fraction)<input name="late_rate" type="number" min="0" step="0.0001" required/></label><p>None requires zero. A day fraction ranges from 0 to 1. Paid leave is excused; unpaid leave is deducted once at that day’s salary rate. Recorded half-days count as half a working day. Late rules require completed attendance check-ins; missing evidence blocks locking.</p><label className="p-field">Policy reason<textarea name="reason" required maxLength={2000}/></label><button disabled={busy}>Save payout policy</button></form>}
 </section>;
}
