import React,{useState} from 'react';
import {type Row} from './client';
import {csvText,downloadText} from './business-utils';
import {downloadReportPDF} from './report-export';
const kinds:Record<string,{table:string;date:string;columns:[string,string][]}>={
 tasks:{table:'tasks',date:'created_at',columns:[['Task','title'],['Status','status'],['Priority','priority'],['Due UTC','deadline']]},
 work:{table:'work_logs',date:'worked_on',columns:[['Work date UTC','worked_on'],['Minutes','minutes'],['Type','work_type'],['Work performed','summary'],['Parts','parts']]},
 audits:{table:'it_jobs',date:'scheduled_at',columns:[['Title','title'],['Status','status'],['Appointment UTC','scheduled_at'],['Work performed','work']]},
 assets:{table:'equipment',date:'created_at',columns:[['Asset','name'],['Category','category'],['Status','status'],['Serial / tag','serial_number'],['Warranty end','warranty_end']]},
 sites:{table:'client_sites',date:'',columns:[['Site','name'],['Address','address'],['Contact','contact'],['Active','active']]}
};
export function OperationalReports({data,companies,projects,loading=false}:{loading?:boolean;data:Record<string,Row[]>;companies:Row[];projects:Row[]}) {
 const [kind,setKind]=useState('tasks'),[company,setCompany]=useState(''),[project,setProject]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const config=kinds[kind],invalid=Boolean(from&&to&&from>to),source=data[config.table]||[];
 const scoped=source.filter(r=>kind!=='audits'||r.kind==='Audit').filter(r=>!r.voided_at);
 const rows=invalid?[]:scoped.filter(r=>{const p=projects.find(p=>p.id===r.project_id),cid=r.company_id||p?.company_id,d=String(r[config.date]||'').slice(0,10);return (!company||cid===company)&&(!project||r.project_id===project)&&(!status||String(r.status)===status)&&(!from||d>=from)&&(!to||d<=to);});
 const headers=['Record ID','Project',...config.columns.map(c=>c[0])],values=rows.map(r=>[r.id,projects.find(p=>p.id===r.project_id)?.title||'—',...config.columns.map(c=>r[c[1]]??'—')]);
 const title=({tasks:'Task report',work:'Technician work report',audits:'Network audit report',assets:'IT asset report',sites:'Client site report'} as Record<string,string>)[kind];
 const context=`Company: ${companies.find(c=>c.id===company)?.name||'All available'} | Project: ${projects.find(p=>p.id===project)?.title||'All available'} | Status: ${status||'All'} | ${config.date?`${config.date}: ${from||'Any'} through ${to||'Any'} UTC`:'Current snapshot'} | ${rows.length} records`;
 return <section className="p-panel"><h2>Operational reports</h2><p>Exports include only records your account can access. Work reports exclude voided entries. Dates filter the field shown below.</p>{error&&<p role="alert" className="p-error">{error}</p>}<div className="p-toolbar"><label>Report<select value={kind} onChange={e=>{setKind(e.target.value);setStatus('');setProject('');setFrom('');setTo('');}}>{Object.keys(kinds).map(k=><option key={k} value={k}>{k==='work'?'Technician work':k==='audits'?'Network audits':k[0].toUpperCase()+k.slice(1)}</option>)}</select></label><label>Company<select value={company} onChange={e=>{setCompany(e.target.value);setProject('');}}><option value="">All available</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{['tasks','work','audits'].includes(kind)&&<label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">All available</option>{projects.filter(p=>!company||p.company_id===company).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}<label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{[...new Set(scoped.map(r=>r.status).filter(Boolean))].map(s=><option key={s}>{s}</option>)}</select></label>{config.date&&<><label>{config.date} from UTC<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through UTC<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}<button disabled={invalid||busy||loading} onClick={()=>downloadText(`${kind}-report.csv`,csvText([['Report',title],['Scope',context],headers,...values]))}>Download filtered CSV</button><button disabled={invalid||busy||loading} onClick={async()=>{setBusy(true);setError('');try{await downloadReportPDF(`${kind}-report.pdf`,title,context,[{title:`${rows.length} records`,headers,rows:values}]);}catch(e:any){setError(e.message||'PDF export failed');}finally{setBusy(false);}}}>{busy?'Preparing PDF…':'Download filtered PDF'}</button></div>{invalid&&<p role="alert">Start date must not follow end date.</p>}<p>{rows.length} matching records.</p><div className="p-table-scroll"><table className="p-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}>{values[i].map((v,n)=><td key={n}>{String(v)}</td>)}</tr>)}</tbody></table></div></section>;
}
