import React, {useState} from 'react';
import type {Row} from './client';
export const priorities=['Low','Normal','High','Urgent'];
export const taskStatuses=['To do','In progress','Done'];
export type Mutations={key?:string;busy:boolean; insert:(table:string,values:any)=>Promise<boolean>; update:(table:string,id:string,values:any)=>Promise<boolean>};
export const shortDate=(v?:string)=>v?new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString():'Not set';
const localToday=()=>{const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`;};
export function Input({name,label,value='',type='text',required=false,children,max=200}:any){return <label className="p-field"><span>{label}</span>{children?<select name={name} defaultValue={value} required={required}>{children}</select>:type==='textarea'?<textarea name={name} defaultValue={value} maxLength={10000} rows={3}/>:<input name={name} type={type} defaultValue={value} required={required} maxLength={type==='text'?max:undefined}/>}</label>}
export function SaveForm({children,onSave,busy,label='Save'}:{children:React.ReactNode;onSave:(v:any)=>Promise<boolean>;busy:boolean;label?:string}){return <form className="p-form" onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const ok=await onSave(Object.fromEntries(new FormData(f)));if(ok&&f.isConnected)f.reset();}}>{children}<button disabled={busy} className="p-primary">{busy?'Saving…':label}</button></form>}
const options=(rows:Row[])=>rows.map(r=><option key={r.id} value={r.id}>{r.title||r.name}</option>);
const textOptions=(rows:string[])=>rows.map(r=><option key={r}>{r}</option>);
export function ContractSelector({contracts,value='',name='contract_id'}:{key?:string;contracts:Row[];value?:string;name?:string}){return <Input name={name} label="Service contract" value={value||''}><option value="">No contract</option>{options(contracts)}</Input>}
export function EquipmentSelector({equipment,value=''}:{equipment:Row[];value?:string}){return <Input name="equipment_id" label="Equipment (optional)" value={value||''}><option value="">General request / no equipment</option>{options(equipment)}</Input>}
export function slaState(due?:string,finished?:string,now=Date.now()){
 if(!due)return {text:'Not measured',tone:''};
 const deadline=Date.parse(due), end=finished?Date.parse(finished):now;
 if(finished)return {text:end<=deadline?'Met':'Missed',tone:end<=deadline?'p-good':'p-danger'};
 const mins=Math.ceil(Math.abs(deadline-now)/60000), remaining=mins>=1440?`${Math.floor(mins/1440)}d ${Math.floor(mins%1440/60)}h`:mins>=60?`${Math.floor(mins/60)}h ${mins%60}m`:`${mins}m`;
 return now>deadline?{text:`Overdue by ${remaining}`,tone:'p-danger'}:{text:`Due in ${remaining}`,tone:deadline-now<=3600000?'p-warning':''};
}
export function SlaSummary({ticket,now}:{ticket:Row;now:number}){
 if(!ticket.response_due_at)return <p className="p-muted">SLA: {ticket.sla_note||'No recorded SLA'}</p>;
 const response= ticket.status==='Resolved'&&!ticket.first_response_at?{text:'Closed without reply',tone:'p-danger'}:slaState(ticket.response_due_at,ticket.first_response_at,now);
 const resolution=slaState(ticket.resolution_due_at,ticket.resolved_at,now);
 return <div className="p-sla"><strong>{ticket.contract_title}</strong><div className="p-sla-grid">{[['Response',response,ticket.response_due_at],['Resolution',resolution,ticket.resolution_due_at]].map(([title,state,due]:any)=><div key={title}><span>{title}</span><span className={`p-badge ${state.tone}`}>{state.text}</span><small>Due {new Date(due).toLocaleString()}</small></div>)}</div><small>24/7 · Waiting on client does not pause the clock · Times shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}</small></div>;
}
export function TasksBoard({tasks,items,members,equipment,tickets,projectId,staff,profileId,...m}:Mutations&{tasks:Row[];items:Row[];members:Row[];equipment:Row[];tickets:Row[];projectId:string;staff:boolean;profileId:string}){
 const [editing,setEditing]=useState<string|null>(null),[mode,setMode]=useState('board'),[filter,setFilter]=useState('all'),[priority,setPriority]=useState('all');
 const activeMembers=members.filter(x=>x.active&&x.role!=='client');
 const filtered=tasks.filter(t=>(filter==='all'||filter==='mine'&&t.assignee===profileId||filter==='unassigned'&&!t.assignee||t.assignee===filter)&&(priority==='all'||priority===t.priority));
 function taskForm(t?:Row){return <SaveForm busy={m.busy} label={t?'Update task':'Create task'} onSave={async v=>{const values={title:v.title.trim(),assignee:v.assignee||null,deadline:v.deadline||null,priority:v.priority,internal:v.internal==='on',equipment_id:v.equipment_id||null,ticket_id:v.ticket_id||null};const ok=t?await m.update('tasks',t.id,values):await m.insert('tasks',{...values,project_id:projectId});if(ok)setEditing(null);return ok;}}><Input name="title" label="Task" value={t?.title} required/><Input name="assignee" label="Assignee" value={t?.assignee||''}><option value="">Unassigned</option>{t?.assignee&&!activeMembers.some(x=>x.id===t.assignee)&&<option value={t.assignee}>Previous assignee (inactive)</option>}{options(activeMembers)}</Input><Input name="priority" label="Priority" value={t?.priority||'Normal'}>{textOptions(priorities)}</Input><Input name="deadline" label="Deadline" type="date" value={t?.deadline||''}/><EquipmentSelector equipment={equipment} value={t?.equipment_id}/><Input name="ticket_id" label="Related support ticket" value={t?.ticket_id||''}><option value="">No ticket</option>{options(tickets)}</Input><label className="p-check"><input type="checkbox" name="internal" defaultChecked={!!t?.internal}/>Internal task — team only</label></SaveForm>}
 function card(t:Row){const checklist=items.filter(x=>x.task_id===t.id);return <article key={t.id} className="p-task-card"><div className="p-card-top"><span className={`p-badge ${t.priority==='Urgent'?'p-danger':''}`}>{t.priority}</span>{t.internal&&<span className="p-badge">Internal</span>}</div><h3>{t.title}</h3><p className="p-muted">{t.assignee===profileId?'You':members.find(x=>x.id===t.assignee)?.name||(t.assignee?'Team member':'Unassigned')} · Due {shortDate(t.deadline)}</p>{t.deadline&&t.deadline<localToday()&&t.status!=='Done'&&<span className="p-badge p-danger">Overdue</span>}{t.equipment_id&&<p className="p-muted">Equipment: {equipment.find(x=>x.id===t.equipment_id)?.name||'Equipment record'}</p>}{t.ticket_id&&<p className="p-muted">Ticket: {tickets.find(x=>x.id===t.ticket_id)?.title||'Support request'}</p>}{staff?<label className="p-field"><span>Status</span><select aria-label={`Status for ${t.title}`} value={t.status} disabled={m.busy} onChange={e=>m.update('tasks',t.id,{status:e.target.value})}>{textOptions(taskStatuses)}</select></label>:<span className="p-badge">{t.status}</span>}<details><summary>Checklist ({checklist.filter(x=>x.done).length}/{checklist.length})</summary>{!checklist.length&&<p className="p-muted">No checklist items yet.</p>}{checklist.map(x=><label className="p-check p-check-item" key={x.id}><input type="checkbox" checked={x.done} disabled={!staff||m.busy} onChange={e=>m.update('task_items',x.id,{done:e.target.checked})}/><span>{x.title}</span></label>)}{staff&&<SaveForm busy={m.busy} label="Add checklist item" onSave={v=>m.insert('task_items',{task_id:t.id,title:v.title.trim()})}><Input name="title" label="Checklist item" required/></SaveForm>}</details>{staff&&<button onClick={()=>setEditing(editing===t.id?null:t.id)}>{editing===t.id?'Close editor':'Edit task'}</button>}{staff&&editing===t.id&&taskForm(t)}</article>}
 return <><div className="p-section-heading"><h2>Tasks and team</h2>{staff&&<button className="p-primary" onClick={()=>setEditing(editing==='new'?null:'new')}>{editing==='new'?'Close form':'Add task'}</button>}</div>{editing==='new'&&staff&&<section className="p-panel"><h2>Create task</h2>{taskForm()}</section>}<div className="p-toolbar"><label>View<select value={mode} onChange={e=>setMode(e.target.value)}><option value="board">Board</option><option value="list">List</option></select></label><label>Assignee<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Everyone</option>{staff&&<option value="mine">Assigned to me</option>}<option value="unassigned">Unassigned</option>{staff&&options(activeMembers)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option>{textOptions(priorities)}</select></label></div>{mode==='board'?<div className="p-board">{taskStatuses.map(status=><section className="p-lane" key={status}><h3>{status} <span>{filtered.filter(t=>t.status===status).length}</span></h3>{filtered.filter(t=>t.status===status).map(card)}{!filtered.some(t=>t.status===status)&&<p className="p-muted">No tasks</p>}</section>)}</div>:<div className="p-grid">{filtered.map(card)}</div>}{!filtered.length&&<p>No tasks match these filters.</p>}</>;
}
export function Contracts({contracts,companies,isAdmin,now,...m}:Mutations&{contracts:Row[];companies:Row[];isAdmin:boolean;now:number}){
 const [editing,setEditing]=useState<string|null>(null); const today=new Date(now).toISOString().slice(0,10);
 function form(c?:Row){return <SaveForm busy={m.busy} label={c?'Update contract':'Create contract'} onSave={async v=>{const targets=Object.fromEntries(priorities.map(p=>[p,{response:Number(v[`${p}_response`]),resolution:Number(v[`${p}_resolution`])}]));const values={title:v.title.trim(),status:v.status,start_date:v.start_date,end_date:v.end_date,renewal_date:v.renewal_date||null,services:v.services,targets};const ok=c?await m.update('contracts',c.id,values):await m.insert('contracts',{...values,company_id:v.company_id});if(ok)setEditing(null);return ok;}}>{!c&&<Input name="company_id" label="Client company" required><option value="">Choose company…</option>{options(companies)}</Input>}<Input name="title" label="Contract name" value={c?.title} required/><Input name="status" label="Status" value={c?.status||'Draft'}>{textOptions(['Draft','Active','Cancelled'])}</Input><div className="p-form-grid"><Input name="start_date" label="Start date (UTC)" type="date" value={c?.start_date} required/><Input name="end_date" label="End date (inclusive, UTC)" type="date" value={c?.end_date} required/></div><Input name="renewal_date" label="Renewal follow-up date" type="date" value={c?.renewal_date||''}/><Input name="services" label="Covered services and exclusions" type="textarea" value={c?.services}/><p>Enter the agreed targets in minutes. 60 minutes = 1 hour; 1,440 minutes = 1 day. Resolution must be at least as long as response. The clock runs 24/7 without pauses.</p><div className="p-table-scroll"><table className="p-table"><thead><tr><th>Priority</th><th>Response minutes</th><th>Resolution minutes</th></tr></thead><tbody>{priorities.map(p=><tr key={p}><th>{p}</th>{['response','resolution'].map(k=><td key={k}><input aria-label={`${p} ${k} minutes`} name={`${p}_${k}`} type="number" min={1} max={525600} step={1} required defaultValue={c?.targets?.[p]?.[k]??''}/></td>)}</tr>)}</tbody></table></div><p className="p-muted">Changes apply only to future tickets. Existing ticket deadlines are preserved.</p></SaveForm>}
 return <><div className="p-heading"><div><span className="p-eyebrow">SERVICE AGREEMENTS</span><h1>AMC & SLA</h1><p>Contract coverage, renewals and 24/7 service targets.</p></div>{isAdmin&&<button className="p-primary" onClick={()=>setEditing(editing==='new'?null:'new')}>{editing==='new'?'Close form':'New contract'}</button>}</div>{editing==='new'&&isAdmin&&<section className="p-panel"><h2>Create contract</h2>{form()}</section>}{!contracts.length&&<section className="p-empty">No contracts yet.{isAdmin&&' Add a contract, then link it to a project.'}</section>}{contracts.map(c=>{const expired=c.end_date<today,renewal=c.renewal_date&&Math.ceil((Date.parse(c.renewal_date)-Date.parse(today))/86400000);return <section className="p-panel" key={c.id}><div className="p-section-heading"><div><span className="p-eyebrow">{companies.find(x=>x.id===c.company_id)?.name}</span><h2>{c.title}</h2></div><span className={`p-badge ${expired&&c.status==='Active'?'p-danger':''}`}>{c.status==='Active'?(expired?'Expired':c.start_date>today?'Scheduled':'Active'):c.status}</span></div><p>{shortDate(c.start_date)} – {shortDate(c.end_date)} · Renewal follow-up: {shortDate(c.renewal_date)}</p>{c.status!=='Cancelled'&&c.renewal_date&&renewal<=30&&<p className={renewal<0?'p-error':'p-notice'}>{renewal<0?'Renewal follow-up overdue':renewal===0?'Renewal follow-up due today':`Renewal follow-up in ${renewal} days`}</p>}<p className="p-pre">{c.services||'No service description recorded.'}</p><div className="p-table-scroll"><table className="p-table"><thead><tr><th>Priority</th><th>Response</th><th>Resolution</th></tr></thead><tbody>{priorities.map(p=><tr key={p}><th>{p}</th><td>{c.targets[p].response} min</td><td>{c.targets[p].resolution} min</td></tr>)}</tbody></table></div><p className="p-muted">24/7 elapsed time. Waiting on client does not pause the clock.</p>{isAdmin&&<button onClick={()=>setEditing(editing===c.id?null:c.id)}>{editing===c.id?'Close editor':'Edit contract'}</button>}{editing===c.id&&isAdmin&&form(c)}</section>})}</>;
}
export function Equipment({equipment,service,contracts,companies,tickets,staff,now,...m}:Mutations&{equipment:Row[];service:Row[];contracts:Row[];companies:Row[];tickets:Row[];staff:boolean;now:number}){
 const [editing,setEditing]=useState<string|null>(null),[company,setCompany]=useState(companies[0]?.id||''),[search,setSearch]=useState('');
 const today=new Date(now).toISOString().slice(0,10);
 function form(e?:Row){const cid=e?.company_id||company;return <SaveForm busy={m.busy} label={e?'Update equipment':'Add equipment'} onSave={async v=>{const values={name:v.name.trim(),category:v.category,serial_number:v.serial_number.trim(),location:v.location.trim(),warranty_end:v.warranty_end||null,status:v.status,contract_id:v.contract_id||null,notes:v.notes};const ok=e?await m.update('equipment',e.id,values):await m.insert('equipment',{...values,company_id:cid});if(ok)setEditing(null);return ok;}}>{!e&&<label className="p-field">Client company<select required value={company} onChange={ev=>setCompany(ev.target.value)}><option value="">Choose company…</option>{options(companies)}</select></label>}<Input name="name" label="Equipment name" value={e?.name} required/><Input name="category" label="Type" value={e?.category||'Computer'}>{textOptions(['Computer','Server','Router','Switch','Wi-Fi','Printer','Other'])}</Input><Input name="serial_number" label="Serial number / asset tag" value={e?.serial_number}/><Input name="location" label="Location" value={e?.location} max={300}/><Input name="warranty_end" label="Warranty expiry" type="date" value={e?.warranty_end||''}/><Input name="status" label="Status" value={e?.status||'In service'}>{textOptions(['In service','Under repair','Retired'])}</Input><ContractSelector key={cid} contracts={contracts.filter(c=>c.company_id===cid)} value={e?.contract_id}/><Input name="notes" label="Notes shared with client" type="textarea" value={e?.notes}/><p className="p-muted">Notes and service history are visible to this client company. Do not enter passwords or private team notes.</p></SaveForm>}
 return <><div className="p-heading"><div><span className="p-eyebrow">CLIENT ASSETS</span><h1>Equipment</h1><p>Devices, warranties and service history.</p></div>{staff&&<button className="p-primary" onClick={()=>setEditing(editing==='new'?null:'new')}>{editing==='new'?'Close form':'Add equipment'}</button>}</div>{editing==='new'&&staff&&<section className="p-panel"><h2>Add equipment</h2>{form()}</section>}<label className="p-search">Find equipment<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, serial number, location or company"/></label>{equipment.filter(e=>`${e.name} ${e.serial_number} ${e.location} ${companies.find(c=>c.id===e.company_id)?.name}`.toLowerCase().includes(search.toLowerCase())).map(e=><section className="p-panel" key={e.id}><div className="p-section-heading"><div><span className="p-eyebrow">{companies.find(c=>c.id===e.company_id)?.name}</span><h2>{e.name}</h2></div><span className="p-badge">{e.status}</span></div><p>{e.category} · Serial / tag: {e.serial_number||'Not recorded'} · {e.location||'Location not recorded'}</p><p>Warranty: {shortDate(e.warranty_end)} {e.warranty_end&&e.warranty_end<today&&<span className="p-badge p-warning">Expired</span>}</p><p>Contract: {contracts.find(c=>c.id===e.contract_id)?.title||'Not linked'}</p><p className="p-pre">{e.notes}</p>{staff&&<button onClick={()=>setEditing(editing===e.id?null:e.id)}>{editing===e.id?'Close editor':'Edit equipment'}</button>}{editing===e.id&&staff&&form(e)}<details><summary>Service history ({service.filter(x=>x.equipment_id===e.id).length})</summary>{service.filter(x=>x.equipment_id===e.id).map(x=><article key={x.id} className="p-service-entry"><strong>{shortDate(x.serviced_on)}</strong><p className="p-pre">{x.summary}</p></article>)}{staff&&<SaveForm busy={m.busy} label="Add service record" onSave={v=>m.insert('equipment_service',{equipment_id:e.id,serviced_on:v.serviced_on,summary:v.summary.trim()})}><Input name="serviced_on" label="Service date" type="date" required/><Input name="summary" label="Work performed (visible to client)" type="textarea"/><p className="p-muted">Service records cannot be edited after saving. Add a correction as a new record.</p></SaveForm>}</details><details><summary>Linked support tickets ({tickets.filter(t=>t.equipment_id===e.id).length})</summary>{tickets.filter(t=>t.equipment_id===e.id).map(t=><p key={t.id}>{t.title} · {t.status} · {t.priority}</p>)}</details></section>)}{!equipment.length&&<p>No equipment recorded yet.</p>}</>;
}
export function ServiceAlerts({tickets,contracts,now,onOpen}:{tickets:Row[];contracts:Row[];now:number;onOpen:(t:Row)=>void}){
 const overdue=tickets.filter(t=>t.status!=='Resolved'&&((t.response_due_at&&!t.first_response_at&&Date.parse(t.response_due_at)<now)||(t.resolution_due_at&&Date.parse(t.resolution_due_at)<now)));
 const renewals=contracts.filter(c=>c.status!=='Cancelled'&&c.renewal_date&&Date.parse(c.renewal_date)<=now+30*86400000);
 return <section className="p-panel"><div className="p-section-heading"><h2>Service attention</h2><span className={`p-badge ${overdue.length?'p-danger':''}`}>{overdue.length} overdue tickets</span></div><p className="p-muted">{renewals.length} contract renewal follow-ups due or within 30 days. Check AMC & SLA for details. Alerts appear here; no email or SMS is sent.</p>{overdue.slice(0,10).map(t=><button className="p-ticket" key={t.id} onClick={()=>onOpen(t)}><strong>{t.title}</strong><span className="p-badge p-danger">{t.priority} · SLA overdue</span></button>)}{overdue.length>10&&<p>Showing 10 of {overdue.length} overdue tickets. Open Support to review the remaining projects.</p>}</section>;
}
