import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {Input,SaveForm} from './operations';
import {workspaceRows} from './workspace';
import {downloadText} from './business-utils';
const today=()=>new Date().toISOString().slice(0,10);
const opts=(rs:Row[])=>rs.map(r=><option key={r.id} value={r.id}>{r.name||r.title}</option>);
const money=(v:any)=>Number(v).toFixed(2);
function Lines({items,currency}:any){return <div className="p-table-scroll"><table className="p-table"><thead><tr><th>Item</th><th>Quantity</th><th>Unit price</th><th>Tax %</th><th>Total ({currency})</th></tr></thead><tbody>{items.map((r:any,i:number)=><tr key={i}><td>{r.description}</td><td>{r.quantity}</td><td>{money(r.unit_price)}</td><td>{r.tax_percent}</td><td>{money(Number(r.net)+Number(r.tax))}</td></tr>)}</tbody></table></div>}
export function OrdersCatalogue({profile,companies,refresh,onOpen}:any){
 const admin=profile.role==='admin';const [items,setItems]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[selected,setSelected]=useState(''),[cart,setCart]=useState<Record<string,string>>({}),[batch,setBatch]=useState(()=>crypto.randomUUID()),[company,setCompany]=useState(profile.company_id||''),[notes,setNotes]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){const [a,b,c]=await Promise.all(['catalogue_items','client_orders','order_history'].map(x=>workspaceRows(x)));setItems(a);setOrders(b.sort((a,b)=>b.created_at.localeCompare(a.created_at)));setHistory(c);setBatch(crypto.randomUUID());}
 useEffect(()=>{let active=true;Promise.all(['catalogue_items','client_orders','order_history'].map(x=>workspaceRows(x))).then(([a,b,c])=>{if(active){setItems(a);setOrders(b.sort((a,b)=>b.created_at.localeCompare(a.created_at)));setHistory(c);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[profile.id]);
 async function run(fn:()=>PromiseLike<any>,message='Saved'){if(busy)return false;setBusy(true);setError('');setNotice('');try{check(await fn());await load();setEditing(null);setNotice(message);return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 const order=orders.find(o=>o.id===selected);const cartRows=Object.entries(cart).filter(([,q])=>Number(q)>0).map(([id,q])=>{const i=items.find(x=>x.id===id);return i?{...i,quantity:Number(q),description:i.name,net:Math.round(Number(q)*Number(i.unit_price)*100)/100,tax:Math.round(Math.round(Number(q)*Number(i.unit_price)*100)/100*Number(i.tax_percent))/100}:null;}).filter(Boolean) as any[];
 const currencies=[...new Set(cartRows.map(r=>r.currency))];const validCart=cartRows.length>0&&currencies.length===1&&cartRows.every(r=>r.active)&&!!company;
 const editCart=(id:string,value:string)=>{setCart(c=>({...c,[id]:value}));setBatch(crypto.randomUUID());};
 return <><h1>Orders & catalogue</h1><p>Submit an order request for review. Prices and taxes are saved with the order. Payment and invoice issuance are handled separately.</p>{error&&<p role="alert" className="p-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">Loading orders…</p>}<div className="p-toolbar"><button disabled={busy} onClick={()=>run(()=>load().then(()=>({data:null,error:null})),'Catalogue and orders refreshed. Review your cart prices again.')}>Refresh catalogue & orders</button>{admin&&<button onClick={()=>setEditing({} as Row)}>New catalogue item</button>}<label>Search catalogue<input value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {editing&&admin&&<section className="p-panel"><h2>{editing.id?'Edit catalogue item':'New catalogue item'}</h2><button onClick={()=>setEditing(null)}>Close item editor</button><SaveForm key={editing.id||'new'} busy={busy} label="Save catalogue item" onSave={v=>run(()=>db!.rpc('save_catalogue_item',{p_id:editing.id||null,p_version:editing.version||null,p_sku:v.sku,p_name:v.name,p_description:v.description,p_kind:v.kind,p_currency:v.currency,p_price:Number(v.price),p_tax:Number(v.tax),p_active:v.active==='true'}))}><Input name="sku" label="SKU / service code" value={editing.sku} required max={60}/><Input name="name" label="Item name" value={editing.name} required/><Input name="description" label="Item description" type="textarea" value={editing.description}/><Input name="kind" label="Item type" value={editing.kind||'Service'}><option>Service</option><option>Product</option></Input><Input name="currency" label="Currency code" value={editing.currency||'PKR'} required max={3}/><label className="p-field">Unit price<input name="price" type="number" min="0" step="0.01" required defaultValue={editing.unit_price??0}/></label><label className="p-field">Tax percent<input name="tax" type="number" min="0" max="100" step="0.01" required defaultValue={editing.tax_percent??0}/></label><Input name="active" label="Availability" value={String(editing.active??true)}><option value="true">Active</option><option value="false">Archived</option></Input><p>Price changes apply to future orders. Existing order snapshots are preserved.</p></SaveForm></section>}
 <div className="p-grid">{items.filter(i=>`${i.sku} ${i.name}`.toLowerCase().includes(search.toLowerCase())).map(i=><section className="p-panel" key={i.id}><span className="p-eyebrow">{i.kind} · {i.sku}</span><h2>{i.name}</h2><p className="p-pre">{i.description}</p><p>{i.currency} {money(i.unit_price)} + {i.tax_percent}% tax · {i.active?'Active':'Archived'}</p>{admin&&<button onClick={()=>setEditing(i)}>Edit {i.sku}</button>}{i.active&&<label className="p-field">Quantity for {i.sku}<input aria-label={`Quantity for ${i.sku}`} type="number" min="0" max="100000" step="0.001" value={cart[i.id]||''} disabled={busy} onChange={e=>editCart(i.id,e.target.value)}/></label>}</section>)}</div>{!items.length&&!loading&&<p>No catalogue items yet.</p>}
 {cartRows.length>0&&<section className="p-panel"><h2>Review order request</h2>{admin&&<label className="p-field">Ordering client<select value={company} disabled={busy} onChange={e=>{setCompany(e.target.value);setBatch(crypto.randomUUID());}}><option value="">Choose client</option>{opts(companies)}</select></label>}<Lines items={cartRows} currency={currencies.length===1?currencies[0]:'mixed currencies'}/>{currencies.length===1&&<h3>Total {currencies[0]} {money(cartRows.reduce((s,r)=>s+r.net+r.tax,0))}</h3>}{currencies.length>1&&<p role="alert">Use one currency per order. Set unwanted quantities to zero.</p>}{cartRows.some(r=>!r.active)&&<p role="alert">Your cart contains an archived item. Clear the cart and choose available items.</p>}<form className="p-form" onSubmit={async e=>{e.preventDefault();const id=batch;if(await run(()=>db!.rpc('submit_order',{p_id:id,p_company:company,p_lines:cartRows.map(r=>({id:r.id,version:r.version,quantity:r.quantity})),p_notes:notes}),'Order submitted for review')){setSelected(id);setCart({});setNotes('');setBatch(crypto.randomUUID());}}}><label className="p-field">Order notes<textarea value={notes} maxLength={4000} disabled={busy} onChange={e=>{setNotes(e.target.value);setBatch(crypto.randomUUID());}}/></label><label className="p-check"><input type="checkbox" key={batch} required/>I have reviewed the items, quantities and prices and am authorized to submit this request.</label><button disabled={busy||!validCart}>Submit order request</button><button type="button" disabled={busy} onClick={()=>{setCart({});setBatch(crypto.randomUUID());}}>Clear cart</button></form></section>}
 <section className="p-panel"><h2>Orders</h2><label className="p-field">Order status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Submitted','Confirmed','In progress','Fulfilled','Cancelled','Rejected'].map(s=><option key={s}>{s}</option>)}</select></label>{orders.filter(o=>!status||o.status===status).map(o=><div className="p-list-row" key={o.id}><button onClick={()=>setSelected(o.id)}>{o.number}</button><span>{o.company_name} · {o.status}</span><strong>{o.currency} {money(o.total)}</strong></div>)}{!orders.length&&<p>No orders yet.</p>}</section>
 {order&&<section className="p-panel"><h2>{order.number} · {order.status}</h2><p>{order.company_name} · Submitted {new Date(order.created_at).toLocaleString()}</p><Lines items={order.items} currency={order.currency}/><h3>Total {order.currency} {money(order.total)}</h3><p className="p-pre">{order.notes}</p><button onClick={()=>downloadText(`${order.number}.txt`,`${order.number}\n${order.company_name}\n${order.status}\n${order.items.map((l:any)=>`${l.description} x ${l.quantity}: ${money(Number(l.net)+Number(l.tax))}`).join('\n')}\nTotal ${order.currency} ${money(order.total)}\n${order.notes}`,'text/plain')}>Download order text</button>
 {(admin&&['Submitted','Confirmed','In progress'].includes(order.status)||!admin&&order.status==='Submitted')&&<SaveForm key={order.id+order.version} busy={busy} label="Update order status" onSave={v=>run(()=>db!.rpc('order_action',{p_id:order.id,p_version:order.version,p_status:v.status,p_note:v.note}))}><Input name="status" label="Next order status" required><option value="">Choose status</option>{(admin?(order.status==='Submitted'?['Confirmed','Rejected','Cancelled']:order.status==='Confirmed'?['In progress','Cancelled']:['Fulfilled','Cancelled']):['Cancelled']).map(s=><option key={s}>{s}</option>)}</Input><Input name="note" label="Status note / cancellation reason" type="textarea"/><p>Status notes are visible to the client. Cancellation and rejection require a reason.</p></SaveForm>}
 {admin&&['Confirmed','In progress','Fulfilled'].includes(order.status)&&<><h3>Order delivery & billing</h3>{order.project_id?<button onClick={()=>onOpen(order.project_id)}>Open order project</button>:<button disabled={busy} onClick={()=>run(async()=>{check(await db!.rpc('convert_order',{p_id:order.id,p_target:'project',p_due:null}));await refresh();return {data:null,error:null};},'Project created')}>Create order project</button>}{order.invoice_id?<p>Draft invoice created. Open Invoices to review and issue it.</p>:<SaveForm busy={busy} label="Create order draft invoice" onSave={v=>run(()=>db!.rpc('convert_order',{p_id:order.id,p_target:'invoice',p_due:v.due}),'Draft invoice created; review and add bank details in Invoices.')}><Input name="due" label="Invoice due date (UTC)" type="date" value={today()} required/></SaveForm>}<p>Conversion creates at most one project and one draft invoice. Converted orders cannot be cancelled here.</p></>}
 <details><summary>Order history</summary>{history.filter(h=>h.order_id===order.id).sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(h=><p key={h.id}>{new Date(h.created_at).toLocaleString()} · {h.action} · {h.note}</p>)}</details></section>}</>;
}
export function ContractDocuments({profile,contracts}:any){
 const admin=profile.role==='admin';const [rows,setRows]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[selected,setSelected]=useState(''),[editing,setEditing]=useState(false),[decision,setDecision]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');const doc=rows.find(d=>d.id===selected);
 const load=async()=>{const [d,h]=await Promise.all(['contract_documents','contract_document_history'].map(x=>workspaceRows(x)));setRows(d.sort((a,b)=>b.created_at.localeCompare(a.created_at)));setHistory(h);};
 useEffect(()=>{let active=true;Promise.all(['contract_documents','contract_document_history'].map(x=>workspaceRows(x))).then(([d,h])=>{if(active){setRows(d.sort((a,b)=>b.created_at.localeCompare(a.created_at)));setHistory(h);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[profile.id]);
 async function run(fn:()=>PromiseLike<any>,message='Saved'){if(busy)return false;setBusy(true);setError('');setNotice('');try{const id=check(await fn());await load();if(typeof id==='string')setSelected(id);setEditing(false);setDecision('');setNotice(message);return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 const action=(a:string)=>run(()=>db!.rpc('contract_document_action',{p_id:doc!.id,p_version:doc!.version,p_action:a,p_note:''}),a==='publish'?'Published in the client portal':'Document updated');
 return <><h1>Contract documents & acceptance</h1><p>Review a fixed copy of contract terms and SLA details. Acceptance records the client’s decision on this revision. Operational AMC/SLA settings are managed separately.</p>{error&&<p role="alert" className="p-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="p-toolbar">{admin&&<button onClick={()=>{setSelected('');setEditing(true);}}>New contract document</button>}<button disabled={busy} onClick={()=>run(()=>load().then(()=>({data:null,error:null})),'Refreshed')}>Refresh documents</button><label>Search documents<input value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {rows.filter(d=>`${d.title} ${d.snapshot.title}`.toLowerCase().includes(search.toLowerCase())).map(d=><div className="p-list-row" key={d.id}><button onClick={()=>{setSelected(d.id);setEditing(false);setDecision('');}}>{d.title} · revision {d.revision}</button><span>{d.status}</span></div>)}{!rows.length&&<p>No contract documents available.</p>}
 {editing&&admin&&<section className="p-panel"><h2>{doc?'Edit draft':'Create contract document'}</h2><button onClick={()=>setEditing(false)}>Cancel editing</button><SaveForm key={doc?.id||'new'} busy={busy} label="Save contract draft" onSave={v=>run(()=>db!.rpc('save_contract_document',{p_id:doc?.id||null,p_version:doc?.version||null,p_contract:doc?.contract_id||v.contract,p_title:v.title,p_body:v.body}))}>{!doc&&<Input name="contract" label="Source AMC/SLA contract" required><option value="">Choose contract</option>{opts(contracts.filter((c:Row)=>!rows.some(d=>d.contract_id===c.id)))}</Input>}<Input name="title" label="Document title" required value={doc?.title}/><label className="p-field">Contract terms and conditions<textarea name="body" required maxLength={20000} rows={10} defaultValue={doc?.body}/></label><p>Saving captures the source contract’s current dates, services and SLA targets. Review that snapshot before publishing.</p></SaveForm></section>}
 {doc&&!editing&&<section className="p-panel"><h2>{doc.title} · revision {doc.revision}</h2><p>{doc.status} · {doc.snapshot.title}</p><h3>Terms and conditions</h3><p className="p-pre">{doc.body}</p><h3>Contract snapshot</h3><p>{doc.snapshot.start_date} — {doc.snapshot.end_date} · Source status at capture: {doc.snapshot.status}</p><p className="p-pre">{doc.snapshot.services}</p><div className="p-table-scroll"><table className="p-table"><thead><tr><th>Priority</th><th>Response minutes</th><th>Resolution minutes</th></tr></thead><tbody>{Object.entries(doc.snapshot.targets||{}).map(([p,t]:any)=><tr key={p}><th>{p}</th><td>{t.response}</td><td>{t.resolution}</td></tr>)}</tbody></table></div><p>SLA clocks operate continuously, 24/7; waiting on the client does not pause counting.</p><button onClick={()=>downloadText(`contract-revision-${doc.revision}-${doc.id}.txt`,`${doc.title}\nRevision ${doc.revision} / ${doc.status}\nDocument ID ${doc.id}\n\n${doc.body}\n\nContract snapshot\n${doc.snapshot.title}\n${doc.snapshot.start_date} - ${doc.snapshot.end_date}\n${doc.snapshot.services}\n${Object.entries(doc.snapshot.targets||{}).map(([p,t]:any)=>`${p}: response ${t.response} min; resolution ${t.resolution} min`).join('\n')}\n\nDecision: ${doc.decided_at||'Pending'} ${doc.decision_note||''}`,'text/plain')}>Download contract text</button>
 {admin&&<div className="p-toolbar">{doc.status==='Draft'&&<><button onClick={()=>setEditing(true)}>Edit contract draft</button><button disabled={busy} onClick={()=>action('publish')}>Publish contract document</button></>}{doc.status==='Published'&&<button disabled={busy} onClick={()=>action('withdraw')}>Withdraw document</button>}{['Published','Accepted','Declined','Withdrawn'].includes(doc.status)&&!rows.some(d=>d.contract_id===doc.contract_id&&d.revision>doc.revision)&&<button disabled={busy} onClick={()=>action('revise')}>Create contract revision</button>}</div>}
 {!admin&&doc.status==='Published'&&<><button onClick={()=>setDecision('accept')}>Accept contract document</button><button onClick={()=>setDecision('decline')}>Decline contract document</button>{decision&&<SaveForm busy={busy} label={decision==='accept'?'Confirm contract acceptance':'Confirm contract decline'} onSave={v=>run(()=>db!.rpc('contract_document_action',{p_id:doc.id,p_version:doc.version,p_action:decision,p_note:v.note}),'Client decision recorded')}><Input name="note" label="Decision note" type="textarea"/><label className="p-check"><input type="checkbox" required/>I have read revision {doc.revision}, including its terms and SLA snapshot, and am authorized to {decision} it for my company.</label><button type="button" onClick={()=>setDecision('')}>Cancel decision</button></SaveForm>}</>}
 {doc.decided_at&&<p>Decision recorded {new Date(doc.decided_at).toLocaleString()} · {doc.decision_note||doc.status}</p>}<p>Published content is fixed. A later revision requires a separate decision. Earlier accepted revisions remain in the history. This is a portal acceptance record, without an electronic-signature provider.</p><details><summary>Document history</summary>{history.filter(h=>h.document_id===doc.id).sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(h=><p key={h.id}>{new Date(h.created_at).toLocaleString()} · {h.action}</p>)}</details></section>}</>;
}
