import React, { useEffect, useState, useRef } from 'react';
import { FolderKanban, LifeBuoy, Building2, LogOut, ArrowLeft, Plus, FileText, Clock, CheckCircle2, RefreshCw, LockKeyhole, MessageSquare } from 'lucide-react';
import type { Session } from '@supabase/supabase-js';
import { db, configured, check, type Row } from './client';
import './portal.css';

const statuses = ['Planning', 'In progress', 'On hold', 'Completed'];
const date = (v?: string) => v ? new Date(v.length === 10 ? `${v}T12:00:00` : v).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }) : 'No deadline';
const label = (r: Row) => r.title || r.name;
function Field({ name, title, type = 'text', required = false, options, value }: {name: string; title: string; type?: string; required?: boolean; options?: string[] | Row[]; value?: string}) {
  return <label className="p-field"><span>{title}</span>{options ? <select name={name} defaultValue={value ?? ''} required={required}><option value="">Choose…</option>{options.map(o => typeof o === 'string' ? <option key={o}>{o}</option> : <option key={o.id} value={o.id}>{label(o)}</option>)}</select> : type === 'textarea' ? <textarea name={name} required={required} defaultValue={value} maxLength={10000} rows={3}/> : <input name={name} type={type} required={required} defaultValue={value} maxLength={type === 'text' ? 200 : undefined}/>}</label>;
}
function Form({ children, submit, text = 'Save', busy }: {children: React.ReactNode; submit: (data: any) => Promise<any>; text?: string; busy: boolean}) {
 return <form className="p-form" onSubmit={async e => { e.preventDefault(); const f=e.currentTarget; const values=Object.fromEntries(new FormData(f)); const saved = await submit(values); if(saved && f.isConnected) f.reset(); }}>{children}<button className="p-primary" disabled={busy}>{busy ? 'Please wait…' : text}</button></form>;
}
export default function Portal() {
 const [session, setSession] = useState<Session | null>(null);
 const [initializing, setInitializing] = useState(true);
 const [recovery, setRecovery] = useState(() => /type=(invite|recovery)/.test(window.location.hash));
 const accountRef = useRef<string | null>(null);
 accountRef.current = session?.user.id || null;
 const [profile, setProfile] = useState<Row | null>(null);
 const [projects, setProjects] = useState<Row[]>([]), [companies, setCompanies] = useState<Row[]>([]), [members, setMembers] = useState<Row[]>([]);
 const [current, setCurrent] = useState<string | null>(null);
 const [view, setView] = useState('projects'), [tab, setTab] = useState('Overview');
 const [records, setRecords] = useState<Record<string, Row[]>>({tasks:[],milestones:[],files:[],messages:[],tickets:[],approvals:[]});
 const [selectedTicket, setSelectedTicket] = useState<string | null>(null);
 const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [loading, setLoading] = useState(false);
 const [add, setAdd] = useState(false), [query, setQuery] = useState('');
 const staff = profile?.role === 'admin' || profile?.role === 'team';
 const project = projects.find(p=>p.id===current);
 useEffect(() => {
   document.title='Client portal | i Man Service';
   const robots = document.createElement('meta');robots.name='robots';robots.content='noindex, nofollow';document.head.appendChild(robots);
   if (!db) { setInitializing(false); return; }
   const {data:{subscription}}=db.auth.onAuthStateChange((event,s)=>{setSession(s);setInitializing(false);if(event==='PASSWORD_RECOVERY')setRecovery(true);});
   db.auth.getSession().then(({data,error})=>{if(error)setError(error.message);setSession(data.session);setInitializing(false);});
   return ()=>{subscription.unsubscribe();robots.remove();};
 }, []);
 async function loadRoot() {
   if (!db || !session) return;
   const account = session.user.id;
   const me = check(await db.from('profiles').select('*').eq('id',session.user.id).maybeSingle());
   if(accountRef.current !== account) return;
   setProfile(me?.active ? me : null);
   if (!me?.active) { setProjects([]); return; }
   const [p,c,m]=await Promise.all([db.from('projects').select('*').order('created_at',{ascending:false}),db.from('companies').select('*').order('name'),db.from('profiles').select('*').order('name')]);
   if(accountRef.current !== account) return;
   setProjects(check(p)||[]);setCompanies(check(c)||[]);setMembers(check(m)||[]);
 }
 useEffect(()=>{setProfile(null);setProjects([]);setCompanies([]);setMembers([]);setCurrent(null);setRecords({tasks:[],milestones:[],files:[],messages:[],tickets:[],approvals:[]}); if(session){setLoading(true);loadRoot().catch(e=>setError(e.message)).finally(()=>setLoading(false));}},[session?.user.id]);
 async function loadProject(id: string) {
   if (!db) return;
   const tables=['tasks','milestones','files','messages','tickets'];
   const results=await Promise.all(tables.map(t=>db.from(t).select('*').eq('project_id',id).order('created_at')));
   const next: Record<string,Row[]>={}; results.forEach((r,i)=>next[tables[i]]=check(r)||[]);
   next.approvals=next.files.length ? check(await db.from('approvals').select('*').in('file_id',next.files.map(f=>f.id)).order('created_at',{ascending:false}))||[] : [];
   return next;
 }
 useEffect(()=>{let active=true;setSelectedTicket(null);setAdd(false);setTab('Overview');setError('');setRecords({tasks:[],milestones:[],files:[],messages:[],tickets:[],approvals:[]});if(current){setLoading(true);loadProject(current).then(r=>{if(active&&r)setRecords(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});}return()=>{active=false;};},[current]);
 async function act(fn:()=>Promise<any>, message='Saved') {
   if(busy)return false;setBusy(true);setError('');setNotice('');
   try {await fn();setNotice(message);setAdd(false);return true;} catch(e:any){setError(e.message||'Something went wrong. Please try again.');return false;} finally{setBusy(false);}
 }
 async function refresh() { await loadRoot(); if(current){const r=await loadProject(current);if(r)setRecords(r);} }
 async function insert(table:string, values:any) {return await act(async()=>{check(await db!.from(table).insert(values));await refresh();});}
 async function update(table:string,id:string,values:any) {return await act(async()=>{check(await db!.from(table).update(values).eq('id',id).select().single());await refresh();});}
 const alerts=<>{error&&<div className="p-error" role="alert">{error}</div>}{notice&&<div className="p-notice" role="status">{notice}</div>}</>;
 const origin = `${window.location.origin}/portal`;
 const badge=(s:string)=><span className={`p-badge ${['Completed','Done','Approved','Resolved'].includes(s)?'p-good':''}`}>{s}</span>;
 const statusControl=(table:string,r:Row,options:string[])=>staff?<select aria-label={`Status for ${r.title}`} disabled={busy} value={r.status} onChange={e=>update(table,r.id,{status:e.target.value})}>{options.map(s=><option key={s}>{s}</option>)}</select>:badge(r.status);
 const name=(id:string)=>id===profile?.id?'You':members.find(m=>m.id===id)?.name||'Project participant';
 async function upload(e: React.FormEvent<HTMLFormElement>) {
   e.preventDefault();const form=e.currentTarget, data=new FormData(form), file=data.get('file') as File;
   if(!file?.size)return;
   await act(async()=>{
    if(file.size>10*1024*1024)throw new Error('Choose a file smaller than 10 MB.');
    const allowed=['application/pdf','image/png','image/jpeg','text/plain','text/csv','application/zip','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'];
    if(!allowed.includes(file.type))throw new Error('Use PDF, PNG, JPG, TXT, CSV, ZIP, DOCX or XLSX.');
    const path=`${current}/${crypto.randomUUID()}/${file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-160)}`;
    check(await db!.storage.from('project-files').upload(path,file,{upsert:false,contentType:file.type}));
    const result=await db!.from('files').insert({project_id:current,name:file.name,path,size:file.size,deliverable:staff&&data.get('deliverable')==='on'});
    if(result.error){await db!.storage.from('project-files').remove([path]);throw result.error;}
    form.reset();await refresh();
   },'File shared with the project');
 }
 async function download(file:Row) {await act(async()=>{const blob=check(await db!.storage.from('project-files').download(file.path));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},'Download ready');}
 function comments(ticketId:string|null) {
  return <section className="p-panel"><h2>{ticketId?'Replies':'Project conversation'}</h2><div className="p-thread">{records.messages.filter(m=>(m.ticket_id||null)===ticketId).map(m=><article key={m.id}><header><strong>{name(m.author_id)}</strong><span>{date(m.created_at)} {m.internal&&' · Internal note'}</span></header><p>{m.body}</p></article>)}{!records.messages.some(m=>(m.ticket_id||null)===ticketId)&&<p className="p-muted">No messages yet.</p>}</div><Form busy={busy} text="Post message" submit={async d=>{return await insert('messages',{project_id:current,ticket_id:ticketId,body:d.body.trim(),internal:staff&&d.internal==='on'});}}><Field name="body" title="Message" type="textarea" required/>{staff&&<label className="p-check"><input type="checkbox" name="internal"/>Internal note — visible to your team only</label>}</Form></section>;
 }
 if(initializing) return <div className="portal p-auth">Loading your workspace…</div>;
 if(!configured)return <div className="portal p-auth"><div className="p-auth-card"><img src="/logo.svg" alt="i Man Service" width="150"/><LockKeyhole size={32}/><h1>Client portal</h1><p>The portal is awaiting its secure account and storage connection.</p><p className="p-muted">The site owner can complete the steps in PORTAL_SETUP.md. Client access will open once setup is complete.</p><a href="/">Return to website</a></div></div>;
 if(!session)return <div className="portal p-auth"><div className="p-auth-card"><a href="/"><img src="/logo.svg" alt="i Man Service" width="160"/></a><span className="p-eyebrow">YOUR PROJECTS. ONE PLACE.</span><h1>Welcome back.</h1><p className="p-muted">Sign in to follow your projects and work with our team.</p>{alerts}<Form busy={busy} text="Sign in" submit={d=>act(async()=>{check(await db!.auth.signInWithPassword({email:d.email,password:d.password}));},'')}><Field name="email" title="Email address" type="email" required/><Field name="password" title="Password" type="password" required/></Form><details><summary>Set or reset your password</summary><Form busy={busy} text="Email reset link" submit={d=>act(async()=>{check(await db!.auth.resetPasswordForEmail(d.email,{redirectTo:origin}));},'If your account exists, a password link has been sent.')}><Field name="email" title="Account email" type="email" required/></Form></details><p className="p-muted">Access is by invitation. Contact your i Man Service project manager for an account.</p><a href="/">← Back to website</a></div></div>;
 if(recovery)return <div className="portal p-auth"><div className="p-auth-card"><h1>Set your password</h1>{alerts}<Form busy={busy} text="Save password" submit={d=>act(async()=>{if(d.password.length<12)throw new Error('Use at least 12 characters.');if(d.password!==d.confirm)throw new Error('Passwords do not match.');check(await db!.auth.updateUser({password:d.password}));setRecovery(false);},'Password updated')}><Field name="password" title="New password (at least 12 characters)" type="password" required/><Field name="confirm" title="Confirm password" type="password" required/></Form></div></div>;
 return <div className="portal p-shell"><aside className="p-sidebar"><a className="p-brand" href="/"><img src="/logo.svg" alt="i Man Service"/></a><div className="p-eyebrow">PROJECT WORKSPACE</div><nav aria-label="Portal navigation"><button className={view==='projects'?'active':''} onClick={()=>{setView('projects');setCurrent(null);setAdd(false);}}><FolderKanban size={19}/>Projects</button><button className={view==='support'?'active':''} onClick={()=>{setView('support');setCurrent(null);setAdd(false);}}><LifeBuoy size={19}/>Support</button>{profile?.role==='admin'&&<button className={view==='clients'?'active':''} onClick={()=>{setView('clients');setCurrent(null);setAdd(false);}}><Building2 size={19}/>Clients & team</button>}</nav><div className="p-sidebar-bottom"><span>{profile?.name||session.user.email}</span><small>{profile?.role||'Account pending'}</small><button disabled={busy} onClick={()=>act(async()=>{check(await db!.auth.signOut());},'')}><LogOut size={17}/>Sign out</button><a href="/">Visit website ↗</a></div></aside><main className="p-main"><header className="p-top"><span>i Man Service <span className="p-muted">/ {view==='clients'?'Administration':view==='support'?'Support':'Projects'}</span></span><button aria-label="Refresh workspace" disabled={busy||loading} onClick={()=>act(refresh,'Workspace refreshed')}><RefreshCw size={17}/></button></header>{alerts}{loading&&<p role="status">Loading workspace…</p>}{!profile&&!loading?<section className="p-panel"><h1>Your account is awaiting access</h1><p>Your administrator needs to assign your account to a company or team role.</p></section>:profile&&<>
 {view==='clients'?<><div className="p-heading"><div><span className="p-eyebrow">ADMINISTRATION</span><h1>Clients & team</h1></div></div><div className="p-columns"><section className="p-panel"><h2>Client companies</h2>{companies.map(c=><div className="p-list-row" key={c.id}>{c.name}</div>)}<Form busy={busy} text="Add company" submit={d=>insert('companies',{name:d.name.trim()})}><Field name="name" title="Company name" required/></Form></section><section className="p-panel"><h2>Grant account access</h2><p className="p-muted">First create the account in Supabase Authentication. Paste its user ID below, then assign a role. Clients must have a company.</p><Form busy={busy} text="Assign account" submit={d=>insert('profiles',{id:d.id.trim(),name:d.name.trim(),role:d.role,company_id:d.company_id||null})}><Field name="id" title="Authentication user ID" required/><Field name="name" title="Full name" required/><Field name="role" title="Role" options={['client','team','admin']} required/><Field name="company_id" title="Client company" options={companies}/></Form></section></div><section className="p-panel"><h2>People with access</h2>{members.map(m=><div className="p-list-row" key={m.id}><strong>{m.name}</strong><span>{m.role} · {companies.find(c=>c.id===m.company_id)?.name||'i Man Service'}</span><button disabled={busy||m.id===profile.id} onClick={()=>update('profiles',m.id,{active:!m.active})}>{m.active?'Disable access':'Enable access'}</button></div>)}</section></>:!current?<>
 <div className="p-heading"><div><span className="p-eyebrow">{staff?'TEAM WORKSPACE':'CLIENT WORKSPACE'}</span><h1>{view==='support'?'How can we help?':'Your projects'}</h1><p className="p-muted">{view==='support'?'Choose a project to create a request or follow an existing ticket.':'Progress, conversations and deliverables, together.'}</p></div>{staff&&view==='projects'&&<button className="p-primary" onClick={()=>setAdd(!add)}><Plus size={18}/>{add?'Close form':'New project'}</button>}</div>
 {add&&staff&&<section className="p-panel"><h2>Create a project</h2><Form busy={busy} text="Create project" submit={d=>insert('projects',{...d,title:d.title.trim(),deadline:d.deadline||null})}><Field name="title" title="Project title" required/><Field name="company_id" title="Client company" options={companies} required/><Field name="description" title="Scope" type="textarea"/><Field name="deadline" title="Project deadline" type="date"/></Form>{!companies.length&&<p>Add a client company in Clients & team first.</p>}</section>}
 <div className="p-stats"><div><FolderKanban/><span>Total projects</span><strong>{projects.length}</strong></div><div><Clock/><span>In progress</span><strong>{projects.filter(p=>p.status==='In progress').length}</strong></div><div><CheckCircle2/><span>Completed</span><strong>{projects.filter(p=>p.status==='Completed').length}</strong></div></div><label className="p-search">Find a project<input placeholder="Search by project or company…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="p-grid">{projects.filter(p=>`${p.title} ${companies.find(c=>c.id===p.company_id)?.name}`.toLowerCase().includes(query.toLowerCase())).map(p=><button className="p-project" key={p.id} onClick={()=>{setCurrent(p.id);}}><div className="p-card-top"><span className="p-project-icon"><FolderKanban size={23}/></span>{badge(p.status)}</div><span className="p-eyebrow">{companies.find(c=>c.id===p.company_id)?.name}</span><h2>{p.title}</h2><p>{p.description||'Project details and updates from your team.'}</p><footer><span>Due {date(p.deadline)}</span><span>Open project ↗</span></footer></button>)}</div>{!projects.length&&<section className="p-empty"><FolderKanban size={36}/><h2>No projects yet</h2><p>{staff?'Create a client company, then add your first project.':'Your projects will appear here when the team assigns them to your company.'}</p></section>}{projects.length>0&&!projects.some(p=>`${p.title} ${companies.find(c=>c.id===p.company_id)?.name}`.toLowerCase().includes(query.toLowerCase()))&&<p>No matching projects.</p>}
 </>:project?<><button className="p-back" onClick={()=>setCurrent(null)}><ArrowLeft size={16}/>All projects</button><div className="p-heading"><div><span className="p-eyebrow">{companies.find(c=>c.id===project.company_id)?.name}</span><h1>{project.title}</h1><p className="p-muted">Due {date(project.deadline)}</p></div>{statusControl('projects',project,statuses)}</div><div className="p-tabs" role="tablist" aria-label="Project sections">{['Overview','Tasks','Files & approvals','Conversation','Support'].map(t=><button role="tab" aria-selected={(view==='support'&&tab==='Overview'?'Support':tab)===t} key={t} onClick={()=>{setView('projects');setTab(t);setAdd(false);setSelectedTicket(null);}}>{t}</button>)}</div>{!loading&&<div role="tabpanel">
 {tab==='Overview'&&view!=='support'&&<><section className="p-panel"><h2>Project overview</h2><p className="p-pre">{project.description||'No scope description yet.'}</p><div className="p-progress-label"><span>Milestones completed</span><strong>{records.milestones.filter(m=>m.status==='Completed').length} / {records.milestones.length}</strong></div><progress max={records.milestones.length||1} value={records.milestones.filter(m=>m.status==='Completed').length}/>{staff&&<details><summary>Edit project details</summary><Form busy={busy} text="Update project" submit={d=>update('projects',project.id,{...d,deadline:d.deadline||null})}><Field name="title" title="Project title" value={project.title} required/><Field name="description" title="Scope" value={project.description} type="textarea"/><Field name="deadline" title="Deadline" value={project.deadline||''} type="date"/></Form></details>}</section><section className="p-panel"><div className="p-section-heading"><h2>Milestones</h2>{staff&&<button onClick={()=>setAdd(!add)}><Plus size={16}/>Add milestone</button>}</div>{records.milestones.map(m=><div className="p-list-row" key={m.id}><div><strong>{m.title}</strong><p className="p-muted">{date(m.deadline)}</p></div>{statusControl('milestones',m,['Upcoming','In progress','Completed'])}</div>)}{!records.milestones.length&&<p className="p-muted">Milestones have not been scheduled yet.</p>}{add&&staff&&<Form busy={busy} submit={d=>insert('milestones',{...d,deadline:d.deadline||null,project_id:current})}><Field name="title" title="Milestone" required/><Field name="deadline" title="Deadline" type="date"/></Form>}</section></>}
 {tab==='Tasks'&&<section className="p-panel"><div className="p-section-heading"><h2>Project tasks</h2>{staff&&<button onClick={()=>setAdd(!add)}><Plus size={16}/>Add task</button>}</div>{records.tasks.map(t=><div className="p-list-row" key={t.id}><div><strong>{t.title}</strong><p className="p-muted">{t.assignee?name(t.assignee):'Unassigned'} · {date(t.deadline)} {t.internal&&' · Internal'}</p></div>{statusControl('tasks',t,['To do','In progress','Done'])}</div>)}{!records.tasks.length&&<p className="p-muted">No tasks to show.</p>}{staff&&add&&<Form busy={busy} submit={d=>insert('tasks',{...d,project_id:current,assignee:d.assignee||null,deadline:d.deadline||null,internal:d.internal==='on'})}><Field name="title" title="Task" required/><Field name="assignee" title="Assignee" options={members.filter(m=>m.role!=='client')}/><Field name="deadline" title="Deadline" type="date"/><label className="p-check"><input type="checkbox" name="internal"/>Internal task</label></Form>}</section>}
 {tab==='Files & approvals'&&<><section className="p-panel"><h2>Share a file</h2><p className="p-muted">Files are visible to this client company and the i Man Service team. Up to 10 MB: PDF, images, documents, spreadsheets and ZIP.</p><form className="p-form" onSubmit={upload}><label className="p-field"><span>Choose file</span><input type="file" name="file" required accept=".pdf,.png,.jpg,.jpeg,.txt,.csv,.zip,.docx,.xlsx"/></label>{staff&&<label className="p-check"><input type="checkbox" name="deliverable"/>Request client approval for this deliverable</label>}<button disabled={busy} className="p-primary">{busy?'Uploading…':'Upload file'}</button></form></section><section className="p-panel"><h2>Files & deliverables</h2>{!records.files.length&&<p className="p-muted">No files shared yet.</p>}{records.files.map(f=>{const history=records.approvals.filter(a=>a.file_id===f.id);return <article className="p-file" key={f.id}><div className="p-list-row"><div><FileText size={20}/><strong>{f.name}</strong><p className="p-muted">{(f.size/1024).toFixed(0)} KB · {date(f.created_at)} {f.deliverable&&' · Approval requested'}</p></div><button disabled={busy} onClick={()=>download(f)}>Download</button></div>{f.deliverable&&badge(history[0]?.decision||'Awaiting approval')}{history.map(a=><p className="p-approval" key={a.id}><strong>{a.decision}</strong> · {name(a.author_id)} · {date(a.created_at)}{a.note&&<span className="p-pre"> — {a.note}</span>}</p>)}{f.deliverable&&!staff&&<Form busy={busy} text="Submit decision" submit={d=>insert('approvals',{file_id:f.id,...d})}><Field name="decision" title="Decision" options={['Approved','Changes requested']} required/><Field name="note" title="Feedback" type="textarea"/></Form>}</article>;})}</section></>}
 {tab==='Conversation'&&comments(null)}
 {(tab==='Support'||view==='support')&&<>{selectedTicket?<><button className="p-back" onClick={()=>setSelectedTicket(null)}>← All tickets</button>{records.tickets.filter(t=>t.id===selectedTicket).map(t=><section className="p-panel" key={t.id}><div className="p-section-heading"><h2>{t.title}</h2>{statusControl('tickets',t,['Open','In progress','Waiting on client','Resolved'])}</div><p className="p-muted">{t.priority} priority · {date(t.created_at)}</p><p className="p-pre">{t.description}</p></section>)}{comments(selectedTicket)}</>:<section className="p-panel"><div className="p-section-heading"><h2>Requests & support tickets</h2><button onClick={()=>setAdd(!add)}><Plus size={16}/>{add?'Close form':'New request'}</button></div>{add&&<Form busy={busy} text="Submit request" submit={d=>insert('tickets',{...d,project_id:current})}><Field name="title" title="Subject" required/><Field name="priority" title="Priority" options={['Low','Normal','High','Urgent']} value="Normal" required/><Field name="description" title="What do you need help with?" type="textarea" required/></Form>}{records.tickets.map(t=><button className="p-ticket" key={t.id} onClick={()=>{setSelectedTicket(t.id);setAdd(false);}}><div><strong>{t.title}</strong><p>{t.priority} priority · {date(t.created_at)}</p></div>{badge(t.status)}</button>)}{!records.tickets.length&&<div className="p-empty"><MessageSquare/><h3>No requests yet</h3><p>Create a request when you need help from our team.</p></div>}</section>}</>}
 </div>}</>:<p>Project unavailable. Return to the project list.</p>}
 </>}</main></div>;
}
