import React from 'react';
import type {Row} from './client';
import {toolAvailability} from './tool-availability';
import {csvText,downloadText} from './business-utils';
export function ProjectToolAvailability({resources,bookings,asOf,disabled}:{resources:Row[];bookings:Row[];asOf:number;disabled:boolean}){
 const byIssue=new Map<string,Row[]>();for(const booking of bookings){const group=byIssue.get(booking.issue_id)||[];group.push(booking);byIssue.set(booking.issue_id,group);}
 const until=asOf+7*86400000,rows=resources.map(pool=>({pool,a:toolAvailability(pool as any,(byIssue.get(pool.id)||[]) as any,asOf,until)}));
 const cell=(v:number|null)=>v===null?'Unavailable':v.toFixed(2),stamp=(v:number)=>new Date(v).toISOString();
 return <section><h3>Delivered tool availability · next seven days</h3><p>Snapshot window: {stamp(asOf)} → {stamp(until)} (UTC). Reserved quantity-hours are clipped to this window; cancelled, expired and later bookings are excluded. Peak quantity is simultaneous use, not the sum of sequential bookings. Minimum spare compares peak use with current outstanding quantity across all visible tasks sharing each issue pool. These are planning estimates using the current balance; later returns/deliveries, individual tool condition and physical availability are not forecast. Refresh tool bookings to update this snapshot. Booking saves still validate current capacity in the database.</p><button disabled={disabled} onClick={()=>downloadText('project-tool-availability.csv',csvText([['As of / window start UTC','Window end UTC','Project ID','Issue ID','Issue number','Tool','Unit','Current outstanding quantity','Peak reserved quantity','Minimum spare quantity','Reserved quantity-hours','Bookings intersecting window','Calculation status'],...rows.map(({pool,a})=>[stamp(asOf),stamp(until),pool.project_id,pool.id,pool.number,pool.item_name,pool.unit,pool.outstanding,a.peak??'Unavailable',a.spare??'Unavailable',cell(a.toolHours),a.bookings??'Unavailable',a.known?((a.spare??0)<0?'Overcommitted':'Calculated'):'Unavailable'])]))}>Export tool availability CSV</button><div className="p-table-scroll"><table className="p-table"><thead><tr><th>Delivered issue / tool</th><th>Current outstanding</th><th>Peak reserved quantity</th><th>Minimum spare quantity</th><th>Reserved quantity-hours</th><th>Bookings in window</th><th>Status</th></tr></thead><tbody>{rows.map(({pool,a})=><tr key={pool.id}><td>{pool.number} · {pool.item_name} · {pool.id}</td><td>{pool.outstanding} {pool.unit}</td><td>{a.peak??'Unavailable'}</td><td>{a.spare??'Unavailable'}</td><td>{cell(a.toolHours)}</td><td>{a.bookings??'Unavailable'}</td><td>{a.known?((a.spare??0)<0?'Overcommitted':'Calculated'):'Unavailable'}</td></tr>)}</tbody></table></div>{!rows.length&&<p>No outstanding delivered tool pools in these projects.</p>}</section>;
}
