import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {workspaceRows} from './workspace';
import {WorkSchedules} from './work-schedules';
import {taskAllocation} from './task-allocation';
import {csvText,downloadText} from './business-utils';
export function ProjectResourceAllocation({profile,streams}:{profile:Row;streams:Row[]}){
 const authorized=profile.role==='admin'||profile.role==='team'&&profile.crm_permissions?.includes('project.own');
 const projectScope=[...new Set(streams.map(s=>s.project_id))].sort().join(',');
 const [data,setData]=useState<Record<string,Row[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;if(!authorized)return;setLoading(true);setError('');setData({});const tables=['projects','tasks','crm_task_plans','work_schedules','work_activities'];Promise.all([Promise.all(tables.map(async t=>[t,await workspaceRows(t)] as const)),Promise.all(projectScope.split(',').filter(Boolean).map(async id=>(check(await db!.rpc('project_allocation_people',{p_project:id})) as Row[]).map(p=>({...p,allocation_projects:[id]}))))]).then(([rows,groups])=>{const people=new Map<string,Row>();for(const p of groups.flat()){const prior=people.get(p.id);people.set(p.id,{...p,allocation_projects:[...(prior?.allocation_projects||[]),...p.allocation_projects]});}if(active)setData({...Object.fromEntries(rows),profiles:[...people.values()]});}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[profile.id,authorized,revision,projectScope]);
 if(!authorized)return null;
 const projects=(data.projects||[]).filter(p=>streams.some(s=>s.project_id===p.id));const plans=(data.crm_task_plans||[]).filter(p=>streams.some(s=>s.id===p.workstream_id));const tasks=(data.tasks||[]).filter(t=>projects.some(p=>p.id===t.project_id)&&plans.some(p=>p.task_id===t.id));const people=data.profiles||[];
 const name=(id:string)=>people.find(p=>p.id===id)?.name||id;const rows=plans.map(p=>{const a=taskAllocation(p.task_id,p.crew,p.duration_minutes,(data.work_schedules||[]) as any);return {p,a,title:tasks.find(t=>t.id===p.task_id)?.title||p.task_key};});
 const cell=(v:number|null)=>v===null?'Unavailable':v.toFixed(2);
 return <section className="p-panel"><h2>Project worker allocation</h2><p>Current generated task plans and visible Scheduled worker bookings, including past and future intervals. Cancelled bookings are excluded. Worker-hours and peak simultaneous workers are planning measures; they do not prove continuous crew coverage or actual completion. Allocations require workers already authorized for the linked work and do not grant project access. Physical tool reservations remain pending.</p><button disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh worker allocation</button><button disabled={loading||!!error} onClick={()=>downloadText('project-worker-allocation.csv',csvText([['Task','Task ID','Project ID','Plan revision','Planned crew','Planned worker-hours','Scheduled worker-hours (visible)','Peak simultaneous workers (visible)','Named worker accounts (visible)','Worker names (visible)'],...rows.map(({p,a,title})=>[title,p.task_id,tasks.find(t=>t.id===p.task_id)?.project_id,p.version,p.crew,cell(a.plannedHours),cell(a.workerHours),a.peak??'Unavailable',a.workers.join('; '),a.workers.map(name).join('; ')])]))}>Export worker allocation CSV</button>{loading?<p role="status">Loading worker allocation…</p>:error?<p role="alert">Worker allocation unavailable: {error}</p>:<><div className="p-table-scroll"><table className="p-table"><thead><tr><th>Task</th><th>Planned crew</th><th>Planned worker-hours</th><th>Scheduled worker-hours · visible</th><th>Peak workers · visible</th><th>Named workers · visible</th></tr></thead><tbody>{rows.map(({p,a,title})=><tr key={p.task_id}><td>{title} · v{p.version}</td><td>{p.crew}</td><td>{cell(a.plannedHours)}</td><td>{cell(a.workerHours)}</td><td>{a.peak??'Unavailable'}</td><td>{a.known?(a.workers.map(name).join(', ')||'None scheduled'):'Unavailable'}</td></tr>)}</tbody></table></div>{!rows.length&&<p>No visible generated tasks for allocation.</p>}<WorkSchedules profile={profile} projects={projects} tasks={tasks} tickets={[]} deals={[]} people={people} activities={data.work_activities||[]} allowRecord={false} projectOnly onSaved={()=>setRevision(v=>v+1)} onRecord={()=>{}}/></>}</section>;
}
