import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {workspaceRows} from './workspace';

export function PortalReminders({profile,onOpen}:{key?:string;profile:Row;onOpen:(view:string,project?:string)=>void}) {
 const [rows,setRows]=useState<Row[]>([]),[enabled,setEnabled]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[unread,setUnread]=useState(false);
 useEffect(()=>{let live=true;Promise.all([workspaceRows('portal_reminders'),db!.from('portal_reminder_preferences').select('*').eq('user_id',profile.id).maybeSingle()]).then(([r,p])=>{check(p);if(live){setRows(r);setEnabled(p.data?.enabled??true);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[profile.id]);
 async function run(fn:()=>PromiseLike<any>){setBusy(true);setError('');try{check(await fn());setRows(await workspaceRows('portal_reminders'));return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 return <><section className="p-panel"><h2>Portal reminders</h2><p>Task deadlines, upcoming visits, overdue SLA deadlines, renewals and work awaiting review appear here. Reminders are checked automatically every 15 minutes.</p>{error&&<p className="p-error" role="alert">{error}</p>}<label className="p-check"><input type="checkbox" checked={enabled} disabled={busy} onChange={async e=>{const value=e.target.checked;if(await run(()=>db!.rpc('save_portal_reminder_preferences',{p_enabled:value})))setEnabled(value);}}/>Receive future portal reminders</label><p className="p-muted">Email, SMS and WhatsApp delivery are excluded.</p><div className="p-toolbar"><button disabled={busy} onClick={()=>run(()=>Promise.resolve({data:null,error:null}))}>Refresh reminders</button>{profile.role==='admin'&&<button disabled={busy} onClick={()=>run(()=>db!.rpc('queue_portal_reminders'))}>Check reminders now</button>}<label className="p-check"><input type="checkbox" checked={unread} onChange={e=>setUnread(e.target.checked)}/>Unread only</label></div></section><section className="p-panel"><h2>Your inbox · {rows.filter(r=>!r.read_at).length} unread</h2>{rows.filter(r=>!unread||!r.read_at).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(r=><article className="p-list-row" key={r.id}><div><strong>{r.title}</strong><p>{new Date(r.created_at).toLocaleString()} · {r.read_at?'Read':'Unread'}</p></div><button onClick={()=>onOpen(r.view,r.project_id||undefined)}>Open work</button>{!r.read_at&&<button disabled={busy} onClick={()=>run(()=>db!.rpc('read_portal_reminder',{p_id:r.id}))}>Mark read</button>}</article>)}{!rows.some(r=>!unread||!r.read_at)&&<p>No reminders in this view.</p>}</section></>;
}
