import React,{useEffect,useState} from 'react';
import {db,check,type Row} from './client';
import {ActivityLocation} from './activity-location';
import {workspaceRows} from './workspace';
const local=(s:string)=>s?new Date(Date.parse(s)+18000000).toISOString().slice(0,16):'';
function Field({name,label,value='',options,type='text',required=false}:any){return <label className="p-field">{label}{options?<select name={name} defaultValue={value} required={required}><option value="">Choose…</option>{options.map((x:any)=>typeof x==='string'?<option key={x}>{x}</option>:<option key={x.id} value={x.id}>{x.title||x.name||x.id}</option>)}</select>:<input name={name} type={type} defaultValue={value} required={required} maxLength={name==='location'?300:2000}/>}</label>;}
export function WorkSchedules({profile,projects,tasks,tickets,deals,people,activities,onRecord,allowRecord=true,projectOnly=false,onSaved}:{profile:Row;projects:Row[];tasks:Row[];tickets:Row[];deals:Row[];people:Row[];activities:Row[];onRecord:(s:Row)=>void;allowRecord?:boolean;projectOnly?:boolean;onSaved?:()=>void}){
 const staff=['admin','team'].includes(profile.role),manager=profile.role==='admin'||profile.crm_permissions?.some((p:string)=>['project.own','sales.manage'].includes(p));
 const [rows,setRows]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null|false>(false),[kind,setKind]=useState('Project'),[project,setProject]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[notice,setNotice]=useState('');
 useEffect(()=>{let live=true;if(!staff)return;setError('');setRows([]);setHistory([]);Promise.all(['work_schedules','work_schedule_history'].map(t=>workspaceRows(t))).then(([r,h])=>{if(live){setRows(r.sort((a,b)=>a.planned_start.localeCompare(b.planned_start)));setHistory(h);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[profile.id,profile.role,staff,manager,revision]);
 if(!staff)return null;
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{const d=Object.fromEntries(new FormData(e.currentTarget)),k=editing?.link_kind||kind,p=editing?.project_id||project;const data={...d,user_id:editing?.user_id||d.user_id,link_kind:k,project_id:['Project','Ticket'].includes(k)?p:null,task_id:['Project','Ticket'].includes(k)?editing?.task_id||d.task_id||null:null,ticket_id:k==='Ticket'?editing?.ticket_id||d.ticket_id:null,deal_id:k==='Deal'?editing?.deal_id||d.deal_id:null,planned_start:new Date(String(d.planned_start)+':00+05:00').toISOString(),planned_end:new Date(String(d.planned_end)+':00+05:00').toISOString(),status:d.status||'Scheduled'};check(await db!.rpc('save_work_schedule',{p_id:editing?.id||null,p_version:editing?.version||null,p_data:data,p_note:d.reason}));setEditing(false);setRevision(v=>v+1);setNotice('Work schedule saved.');onSaved?.();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="p-panel"><h2>Assigned work schedule</h2><p>Plans appear in My tasks & calendar. Recording a plan prefills its work details and planned times; enter actual times and outcome yourself. One activity can be recorded per schedule. Recorded plans retain their original assignment.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy} onClick={()=>setRevision(v=>v+1)}>Refresh work schedules</button>{manager&&<button disabled={busy} onClick={()=>{setEditing(null);setKind('Project');setProject('');}}>Schedule work</button>}
 {editing!==false&&manager&&<section><h3>{editing?'Revise work schedule':'Create work schedule'}</h3>{!editing&&<><label>Schedule linked to<select value={kind} onChange={e=>{setKind(e.target.value);setProject('');}}>{(projectOnly?['Project']:['Project','Ticket','Deal','Internal']).map(k=><option key={k}>{k}</option>)}</select></label>{['Project','Ticket'].includes(kind)&&<label>Schedule project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Choose…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}</>}
 <form key={editing?.id||kind+project} className="p-form" onSubmit={save}>{editing?<p>Assigned worker: {people.find(p=>p.id===editing.user_id)?.name||'Staff member'} · {editing.link_kind}</p>:<><Field name="user_id" label="Scheduled worker" options={people.filter(p=>p.active!==false&&['admin','team'].includes(p.role)&&(!projectOnly||!project||p.allocation_projects?.includes(project)))} required/>{['Project','Ticket'].includes(kind)&&<Field name="task_id" label="Schedule task (required for task-only assignment)" options={tasks.filter(t=>t.project_id===project)} required={projectOnly}/>} {kind==='Ticket'&&<Field name="ticket_id" label="Schedule ticket" options={tickets.filter(t=>t.project_id===project)} required/>}{kind==='Deal'&&<Field name="deal_id" label="Schedule deal" options={deals} required/>}</>}
 <ActivityLocation profile={profile} value={editing?.location||''} label="Scheduled location" projectRequired={['Project','Ticket'].includes(editing?.link_kind||kind)} companyId={projects.find(p=>p.id===(editing?.project_id||project))?.company_id}/><Field name="description" label="Scheduled work description" value={editing?.description} required/><Field name="activity_type" label="Scheduled activity type" options={['Installation','Survey','Complaint','Purchase / pickup','Meeting','Training','Office work','Travel']} value={editing?.activity_type||'Installation'} required/><Field name="planned_start" label="Scheduled start · Pakistan time" type="datetime-local" value={local(editing?.planned_start)} required/><Field name="planned_end" label="Scheduled end · Pakistan time" type="datetime-local" value={local(editing?.planned_end)} required/><Field name="status" label="Work schedule status" options={['Scheduled','Cancelled']} value={editing?.status||'Scheduled'} required/><Field name="reason" label="Scheduling / cancellation reason" required/><button disabled={busy}>Save work schedule</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Close schedule editor</button></form></section>}
 {!rows.some(s=>!projectOnly||s.link_kind==='Project'&&projects.some(p=>p.id===s.project_id)&&tasks.some(t=>t.id===s.task_id))&&<p>No assigned work schedules.</p>}{rows.filter(s=>!projectOnly||s.link_kind==='Project'&&projects.some(p=>p.id===s.project_id)&&tasks.some(t=>t.id===s.task_id)).map(s=>{const recorded=activities.find(a=>a.schedule_id===s.id);return <article key={s.id}><h3>{s.description}</h3><p>{people.find(p=>p.id===s.user_id)?.name||'Staff member'} · {s.location} · {s.status} · {local(s.planned_start)} → {local(s.planned_end)}{recorded?' · Activity '+recorded.status:''}</p>{allowRecord&&s.user_id===profile.id&&s.status==='Scheduled'&&!recorded&&<button disabled={busy} onClick={()=>onRecord(s)}>Record actual work</button>}{manager&&!recorded&&<button disabled={busy} onClick={()=>{setEditing(s);setKind(s.link_kind);setProject(s.project_id||'');}}>Revise schedule</button>}<details><summary>Schedule history</summary>{history.filter(h=>h.schedule_id===s.id).map(h=><p key={h.id}>{h.action} · {local(h.created_at)} · {h.note}</p>)}</details></article>;})}</section>;
}
