begin;
do $$
declare qa_admin uuid;qa_company uuid:=gen_random_uuid();qa_project uuid:=gen_random_uuid();qa_lead uuid:=gen_random_uuid();qa_deal uuid:=gen_random_uuid();qa_board uuid:=gen_random_uuid();qa_product uuid:=gen_random_uuid();qa_quote uuid:=gen_random_uuid();qa_publication uuid:=gen_random_uuid();qa_invoice uuid:=gen_random_uuid();qa_sale uuid:=gen_random_uuid();qa_template uuid:=gen_random_uuid();qa_template_version uuid:=gen_random_uuid();qa_stream uuid:=gen_random_uuid();qa_task uuid:=gen_random_uuid();qa_client uuid:=gen_random_uuid();qa_count int:=0;qa_item uuid:=gen_random_uuid();qa_location uuid:=gen_random_uuid();qa_batch uuid:=gen_random_uuid();qa_request uuid;qa_rows jsonb;qa_report jsonb;
begin
select id into qa_admin from public.profiles where active and role='admin' order by id limit 1;if qa_admin is null then raise exception 'Administrator required';end if;
perform set_config('request.jwt.claim.sub',qa_admin::text,true);perform set_config('request.jwt.claim.role','authenticated',true);
insert into public.companies(id,name) values(qa_company,'QA task tool company');
insert into auth.users(id) values(qa_client);insert into public.profiles(id,name,role,company_id) values(qa_client,'QA task tool client','client',qa_company);
insert into public.projects(id,company_id,title) values(qa_project,qa_company,'QA task tool project');
insert into public.crm_leads(id,name,email,source) values(qa_lead,'QA task tool',qa_lead::text||'@example.test','QA');
insert into public.crm_deals(id,lead_id,company_id,title,owner_id) values(qa_deal,qa_lead,qa_company,'QA adjustment deal',qa_admin);
insert into public.crm_boards(id,code,name,color,outcome) values(qa_board,'qa_'||replace(qa_board::text,'-',''),'QA adjustment board','#112233','Project');
insert into public.crm_product_lines(id,deal_id,board_id) values(qa_product,qa_deal,qa_board);
insert into public.crm_quotes(id,deal_id,number,title,valid_until) values(qa_quote,qa_deal,'QA-'||qa_quote::text,'QA adjustment quote',current_date);
insert into public.crm_quote_publications(id,quote_id,deal_id,company_id,number,revision,title,option_name,currency,valid_until,terms,company_name,items,subtotal,tax_total,total,wht_total,receivable) values(qa_publication,qa_quote,qa_deal,qa_company,'QA-'||qa_quote::text,1,'QA adjustment quote','QA option','PKR',current_date,'QA','QA company','[]',1,0,1,0,1);
insert into public.invoices(id,company_id,company_name,number,currency,total,author_id,due_on) values(qa_invoice,qa_company,'QA company','QA-'||qa_invoice::text,'PKR',1,qa_admin,current_date);
insert into public.crm_sales(id,deal_id,publication_id,company_id,project_id,invoice_id,owner_id,total,currency,payment_terms,planned_budget,created_by) values(qa_sale,qa_deal,qa_publication,qa_company,qa_project,qa_invoice,qa_admin,1,'PKR','{}','{}',qa_admin);
insert into public.crm_project_templates(id,board_id,name) values(qa_template,qa_board,'QA adjustment template');
insert into public.crm_template_versions(id,template_id,revision,parameters,tasks,author_id) values(qa_template_version,qa_template,1,'[]','[]',qa_admin);
insert into public.crm_project_workstreams(id,sale_id,project_id,product_line_id,template_version_id,parameters,plan) values(qa_stream,qa_sale,qa_project,qa_product,qa_template_version,'{}','{"qa_fixed_baseline":true}');
insert into public.tasks(id,project_id,title,assignee,internal,deadline) values(qa_task,qa_project,'QA adjustment task',qa_admin,true,current_date);
insert into public.crm_task_plans(task_id,workstream_id,task_key,phase,process,step,unit,quantity,duration_minutes,crew,crew_role,tools,preconditions) values(qa_task,qa_stream,'qa_adjustment',0,'Survey','Inspect','node',2,60,1,'Technician','Tester','Access');

insert into public.crm_catalog(id,name,unit,tracking) values(qa_item,'QA tool tester','each','Returnable');
insert into public.sc_locations(id,name,kind) values(qa_location,'QA task tool store','Office');
insert into public.sc_stock_ledger(item_id,location_id,quantity,rate,document_id,kind,actor_id) values(qa_item,qa_location,5,10,gen_random_uuid(),'QA fixture',qa_admin);
qa_rows:=jsonb_build_array(jsonb_build_object('item_id',qa_item,'quantity',2));
execute 'set local role authenticated';
qa_request:=public.request_project_task_tools(qa_task,0,qa_batch,'QA site',current_date,'QA explicit tools',qa_rows);
if not exists(select 1 from public.sc_requests where id=qa_request and task_id=qa_task and project_id=qa_project and source='Project tool plan' and status='Requested') then raise exception 'Linked request mismatch';end if;qa_count:=qa_count+1;
if not exists(select 1 from public.crm_project_tool_requests where request_id=qa_request and plan_version=0 and author_id=qa_admin and plan_snapshot->>'tools'='Tester') then raise exception 'Plan evidence mismatch';end if;qa_count:=qa_count+1;
if public.request_project_task_tools(qa_task,0,qa_batch,'QA site',current_date,'QA explicit tools',qa_rows)<>qa_request then raise exception 'Retry mismatch';end if;qa_count:=qa_count+1;
qa_report:=public.project_task_tool_requests(qa_project)->0;
if (qa_report->'lines'->0->>'reserved')::numeric<>0 or qa_report->'lines'->0 ? 'unit_cost' then raise exception 'Unexpected hold or private rates';end if;qa_count:=qa_count+1;
perform public.check_supply_stock(qa_request,1,qa_location);
qa_report:=public.project_task_tool_requests(qa_project)->0;
if (qa_report->'lines'->0->>'reserved')::numeric<>2 or qa_report->>'status'<>'Reserved / Sourcing' then raise exception 'Stores reservation mismatch';end if;qa_count:=qa_count+1;
begin perform public.request_project_task_tools(qa_task,1,gen_random_uuid(),'QA site',current_date,'QA stale plan',qa_rows);raise exception 'Stale plan allowed';exception when others then if sqlerrm is distinct from 'Current generated task plan required' then raise;end if;end;qa_count:=qa_count+1;
begin perform public.request_project_task_tools(qa_task,0,qa_batch,'Changed site',current_date,'QA explicit tools',qa_rows);raise exception 'Changed batch allowed';exception when others then if sqlerrm is distinct from 'Tool request batch already used for different data' then raise;end if;end;qa_count:=qa_count+1;
begin update public.crm_project_tool_requests set plan_version=99 where request_id=qa_request;raise exception 'Direct evidence write allowed';exception when insufficient_privilege then null;end;qa_count:=qa_count+1;
perform set_config('request.jwt.claim.sub',qa_client::text,true);
if exists(select 1 from public.crm_project_tool_requests) then raise exception 'Client link visible';end if;qa_count:=qa_count+1;
begin perform public.project_task_tool_requests(qa_project);raise exception 'Client report allowed';exception when others then if sqlerrm is distinct from 'Assigned project manager access required' then raise;end if;end;qa_count:=qa_count+1;
execute 'reset role';
if has_function_privilege('anon','public.request_project_task_tools(uuid,integer,uuid,text,date,text,jsonb)','EXECUTE') then raise exception 'Anonymous RPC exposed';end if;qa_count:=qa_count+1;
perform set_config('qa.tool_result',jsonb_build_object('passed',true,'assertions',qa_count,'fixtures_rollback',true)::text,true);
end$$;
select current_setting('qa.tool_result')::jsonb as qa_result;
rollback;
