import {activityEvidenceCases} from './activity-evidence-cases.mjs';
import {hrCases} from './hr-cases.mjs';
export async function activityCases({pg,fs,q,one,user,eq,deny,ids,actors,accounts}){
 await pg.exec('reset role');await pg.exec(await fs.readFile(new URL('../../supabase/024_activity_labour.sql',import.meta.url),'utf8'));await user(ids.admin);
 await q("select save_crm_configuration('setting','delay_reasons',$2,'Delay reasons',$1)",[JSON.stringify(['Material not available','Other']),(await one("select version from crm_settings where id='delay_reasons'")).version]);
 const project=(await one("insert into projects(company_id,title) values($1,'Activity project') returning id",[ids.a])).id;
 await q('insert into project_assignments(project_id,technician_id) values($1,$2)',[project,actors.manager]);
 const task=(await one("insert into tasks(project_id,title,assignee) values($1,'Logged work',$2) returning id",[project,ids.team])).id;
 const day=(await one("select ((now() at time zone 'Asia/Karachi')::date-2)::text d")).d;
 const data={link_kind:'Project',project_id:project,task_id:task,location:'Model Town',activity_type:'Installation',description:'Installed assigned cable route',actual_start:day+'T23:00:00+05:00',actual_end:day+'T23:30:00+05:00',outcome:'Done',quantity:5,crew:3};
 const save=async(d=data,id=null,v=null)=>(await one('select save_work_activity($1,$2,$3) id',[id,v,JSON.stringify(d)])).id;
 await user(ids.team);await deny('select set_work_hourly_rate($1,$2,100,$3)',[ids.team,day,'Self rate'],'Staff cannot set own hourly cost');eq((await q('select * from work_hourly_rates')).length,0,'Technician hourly rates private');
 await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,task_id:null})],'Task-only technician cannot log unrestricted project hours');await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,project_id:ids.pb})],'Activity cannot point to wrong task project');
 await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,actual_end:'2099-01-01T01:00:00+05:00'})],'Future actual work denied');await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,actual_end:data.actual_start})],'Zero duration denied');
 await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,planned_start:day+'T22:00:00+05:00',planned_end:day+'T23:15:00+05:00'})],'Late work requires explained delay');
 const id=await save();eq((await q('select * from work_activities where id=$1',[id])).length,1,'Assigned worker sees own draft');await deny('select save_work_activity(null,null,$1)',[JSON.stringify(data)],'Overlapping activity rejected');
 await deny("select work_activity_action($1,1,'Approve','Self approval')",[id],'Worker cannot self-approve');await q("select work_activity_action($1,1,'Submit','')",[id]);await deny('select save_work_activity($1,2,$2)',[id,JSON.stringify({...data,crew:10})],'Submitted actuals immutable');
 await user(actors.manager);await deny("select work_activity_action($1,2,'Approve','Reviewed')",[id],'Missing effective rate cannot silently count zero cost');await user(ids.admin);
 const rate=(await one('select set_work_hourly_rate($1,$2,120,$3) id',[ids.team,day,'Salary / monthly work hours'])).id;
 await deny('select set_work_hourly_rate($1,$2,150,$3)',[ids.team,day,'Overwrite rate'],'Effective rate cannot overwrite original');await deny("select set_work_hourly_rate($1,$2,'NaN','Bad rate')",[ids.team,day],'Non-finite hourly rate denied');
 await user(actors.manager);await q("select work_activity_action($1,2,'Approve','Task and actual time reviewed')",[id]);let report=(await one('select project_financials($1) r',[project])).r;eq(Number(report.approved_labour_hours),0.5,'Labour hours derived from actual timestamps');eq(Number(report.approved_hourly_labour),60,'Half hour times saved rate becomes project cost');eq(Number(report.recorded_cost),60,'Approved hours contribute to recorded cost');eq(report.labour_hours_pending,false,'Recorded hourly cost now available');eq(report.cost_complete,false,'Unrecorded costs still explicitly provisional');eq(Number(report.categories.find(c=>c.category==='Labour').recorded_cost),60,'Labour category totals match approved cost');
 await user(ids.team);eq((await q('select * from work_labour_costs')).length,0,'Technician cannot read private labour cost records');let own=(await one('select work_activity_report() r')).r.find(x=>x.id===id);eq(own.labour_cost,null,'Technician report excludes own hourly cost');eq(own.working_date,day,'Midnight work belongs to original Pakistan working date');await deny('update work_activities set actual_end=now()',[],'Direct time changes denied');await deny('insert into work_labour_costs(activity_id,rate_id,hours,rate,cost,approved_by) values($1,$2,999,999,999,$3)',[id,rate,ids.team],'Direct cost injection denied');
 const midnight=await save({...data,actual_start:day+'T23:30:00+05:00',actual_end:(await one('select ($1::date+1)::text d',[day])).d+'T01:30:00+05:00',planned_start:day+'T23:30:00+05:00',planned_end:(await one('select ($1::date+1)::text d',[day])).d+'T01:00:00+05:00',delay_reason:'Material not available',delay_note:'Cable arrived late',lost_minutes:30});await q("select work_activity_action($1,1,'Submit','')",[midnight]);
 await user(actors.manager);await q("select work_activity_action($1,2,'Reject','Check crew details')",[midnight]);await user(ids.team);await save({...data,actual_start:day+'T23:30:00+05:00',actual_end:(await one('select ($1::date+1)::text d',[day])).d+'T01:30:00+05:00'},midnight,3);await q("select work_activity_action($1,4,'Submit','')",[midnight]);await user(actors.manager);await q("select work_activity_action($1,5,'Approve','Revised work reviewed')",[midnight]);report=(await one('select project_financials($1) r',[project])).r;eq(Number(report.approved_labour_hours),2.5,'Cross-midnight interval costs both hours once');eq(Number(report.approved_hourly_labour),300,'Crew size never multiplies each employee hours');
 await user(ids.admin);await q('select set_work_hourly_rate($1,$2,200,$3)',[ids.team,(await one('select ($1::date+1)::text d',[day])).d,'New effective salary']);report=(await one('select project_financials($1) r',[project])).r;eq(Number(report.approved_hourly_labour),300,'New rates leave prior approved snapshots unchanged');
 await user(actors.manager);await deny("select work_activity_action($1,6,'Void','Undo approval')",[midnight],'Approving manager cannot erase approved labour');await user(ids.admin);await q("select work_activity_action($1,6,'Void','Incorrect duplicate work report')",[midnight]);report=(await one('select project_financials($1) r',[project])).r;eq(Number(report.recorded_cost),60,'Voided labour excluded without deleting history');eq((await q('select * from work_labour_costs where activity_id=$1',[midnight])).length,1,'Voiding preserves original rate snapshot');
 await q('delete from project_assignments where project_id=$1 and technician_id=$2',[project,actors.manager]);await user(actors.manager);eq((await q('select * from work_activities where id=$1',[id])).length,0,'Manager assignment revocation removes team activity');await deny('select project_financials($1)',[project],'Revoked manager cannot read labour financials');
 await user(ids.admin);await q('update tasks set assignee=null where id=$1',[task]);await user(ids.team);eq((await q('select * from work_activities where id=$1',[id])).length,0,'Worker task revocation removes activity access');eq((await q('select * from work_activity_history where activity_id=$1',[id])).length,0,'Worker revocation removes audit access');
 const internal=await save({...data,link_kind:'Internal',project_id:null,task_id:null,actual_start:day+'T14:00:00+05:00',actual_end:day+'T15:00:00+05:00',activity_type:'Training'});await q("select work_activity_action($1,1,'Submit','')",[internal]);await user(ids.admin);await q("select work_activity_action($1,2,'Approve','Training reviewed')",[internal]);report=(await one('select project_financials($1) r',[project])).r;eq(Number(report.recorded_cost),60,'Internal training cost not allocated to unrelated project');
 await user(accounts);eq((await q('select * from work_activities where id=$1',[id])).length,1,'Accounts can inspect approved costing sources');await deny("select work_activity_action($1,3,'Void','Accounts reversal')",[id],'Accounts cannot void or approve activities');

 await user(ids.admin);await q('update tasks set assignee=$2 where id=$1',[task,ids.team]);await q('insert into project_assignments(project_id,technician_id) values($1,$2)',[project,actors.manager]);
 await user(ids.team);const revoked=await save({...data,actual_start:day+'T10:00:00+05:00',actual_end:day+'T11:00:00+05:00'});await q("select work_activity_action($1,1,'Submit','')",[revoked]);await user(ids.admin);await q('update tasks set assignee=null where id=$1',[task]);await user(actors.manager);await deny("select work_activity_action($1,2,'Approve','Access revoked')",[revoked],'Approval rechecks employee task assignment');await user(ids.admin);await q('update tasks set assignee=$2 where id=$1',[task,ids.team]);
 await user(ids.team);await deny('select save_work_activity($1,1,$2)',[revoked,JSON.stringify(data)],'Stale activity revision denied');await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,link_kind:'Internal',project_id:null,task_id:null,actual_start:day+'T00:00:00+05:00',actual_end:day+'T17:00:00+05:00'})],'More than 16 hours in one interval denied');
 await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,actual_start:day+'T08:00:00+05:00',actual_end:day+'T09:00:00+05:00',delay_reason:'Invented',delay_note:'Bad category'})],'Activity delay requires configured category');
 await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,actual_start:day+'T08:00:00+05:00',actual_end:day+'T09:00:00+05:00',lost_minutes:61,delay_reason:'Other',delay_note:'Excess delay'})],'Lost minutes cannot exceed actual duration');
 await user(ids.admin);const closed=(await one("select id from projects where status='Completed' limit 1")).id;await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,project_id:closed,task_id:null})],'Signed closed project cannot acquire new time costs');
 await user(accounts);await deny('delete from work_hourly_rates',[],'Rate history cannot be deleted directly');await deny('update work_labour_costs set cost=999',[],'Approved labour cost cannot be rewritten directly');

 await user(ids.admin);const ticketTask=(await one("insert into tasks(project_id,ticket_id,title,assignee) values($1,$2,'Ticket activity',$3) returning id",[ids.pb,ids.ticket,ids.team])).id;
 await user(ids.team);const ticketActivity=await save({...data,link_kind:'Ticket',project_id:ids.pb,task_id:ticketTask,ticket_id:ids.ticket,actual_start:day+'T08:00:00+05:00',actual_end:day+'T09:00:00+05:00'});await q("select work_activity_action($1,1,'Submit','')",[ticketActivity]);await user(ids.admin);await q("select work_activity_action($1,2,'Approve','Ticket work reviewed')",[ticketActivity]);eq(Number((await one('select project_financials($1) r',[ids.pb])).r.approved_hourly_labour),120,'Ticket hours flow once to linked project');
 await user(ids.team);const deal=(await one('select id from crm_deals limit 1')).id;const survey=await save({...data,link_kind:'Deal',project_id:null,task_id:null,deal_id:deal,actual_start:day+'T06:00:00+05:00',actual_end:day+'T07:00:00+05:00',activity_type:'Survey'});await q("select work_activity_action($1,1,'Submit','')",[survey]);await user(ids.admin);await q("select work_activity_action($1,2,'Approve','Sales survey reviewed')",[survey]);eq(Number((await one('select project_financials($1) r',[project])).r.recorded_cost),60,'Deal survey does not invent a project cost allocation');
 await user(ids.team);const longDay=(await one('select ($1::date-1)::text d',[day])).d;await save({...data,link_kind:'Internal',project_id:null,task_id:null,actual_start:longDay+'T00:00:00+05:00',actual_end:longDay+'T16:00:00+05:00'});await deny('select save_work_activity(null,null,$1)',[JSON.stringify({...data,link_kind:'Internal',project_id:null,task_id:null,actual_start:longDay+'T16:00:00+05:00',actual_end:longDay+'T17:00:00+05:00'})],'Combined working-day total cannot exceed sixteen hours');
 await user(ids.admin);eq((await q("select * from work_activity_history where activity_id=$1 and action='Approve'",[id]))[0].snapshot.status,'Approved','Audit retains immutable approved actuals snapshot');await q('update profiles set active=false where id=$1',[ids.team]);await user(ids.team);eq((await q('select * from work_activities')).length,0,'Disabled employee loses activity access');await deny('select work_activity_report()',[],'Disabled employee cannot query report');await user(ids.admin);await q('update profiles set active=true where id=$1',[ids.team]);
 await user(ids.clientA);eq((await q('select * from work_activities')).length,0,'Client cannot see internal activity logs');eq((await q('select * from work_labour_costs')).length,0,'Client cannot see labour rates');await deny('select work_activity_report()',[],'Client cannot call activity report');
 await pg.exec("reset role;select set_config('request.jwt.claim.sub','',false);set role anon");await deny('select * from work_activities',[],'Anonymous activity access denied');await deny('select work_activity_report()',[],'Anonymous activity RPC denied');await user(ids.admin);
 await hrCases({pg,fs,q,one,user,eq,deny,ids,actors,accounts});
 await activityEvidenceCases({pg,fs,q,one,user,eq,deny,ids,accounts});
}
