export async function bonusCases({pg,fs,q,one,user,eq,deny,ids}){
 await pg.exec('reset role');await pg.exec(await fs.readFile(new URL('../../supabase/035_hr_bonus_modes.sql',import.meta.url),'utf8'));
 const accounts=crypto.randomUUID(),employee=crypto.randomUUID(),lead=crypto.randomUUID(),manager=crypto.randomUUID(),role='bonus_'+employee.slice(0,8);
 await q('insert into auth.users values($1),($2),($3),($4)',[employee,lead,manager,accounts]);
 await q("insert into profiles(id,name,role) values($1,'Bonus worker','team'),($2,'Bonus lead','admin'),($3,'Bonus manager','admin'),($4,'Bonus accounts','admin')",[employee,lead,manager,accounts]);await q('insert into crm_roles(id,name) values($1,$2)',[role,'Bonus test role']);await user(ids.admin);
 const month=(await one("select (date_trunc('month',now() at time zone 'Asia/Karachi')-interval '1 month')::date::text d")).d;
 const policy={role_id:role,effective_on:month,shift_start:'09:00',shift_end:'17:00',grace_minutes:15,half_day_minutes:240,off_days:[],holidays:[],ot_mode:'Fixed rate',ot_rate:0,off_multiplier:1,holiday_multiplier:1,weights:{attendance:100},bonus_slabs:[{score:0,amount:10,mode:'Salary percent'}],reason:'Explicit percentage bonus policy'};
 await q('select save_hr_terms($1)',[JSON.stringify({user_id:employee,effective_on:month,role_id:role,salary:30000,monthly_hours:200,lead_id:lead,manager_id:manager,reason:'Percentage salary basis fixture'})]);
 for(const [bands,label] of [[[{score:0,amount:101,mode:'Salary percent'}],'Percentage above 100 denied'],[[{score:0,amount:-1,mode:'Salary percent'}],'Negative percentage denied'],[[{score:0,amount:1,mode:'Unknown'}],'Unknown bonus calculation denied'],[[{score:0,amount:1},{score:0.0,amount:2}],'Numerically duplicate thresholds denied'],[[{score:0,amount:1.001,mode:'Salary percent'}],'Percentage precision bounded']])await deny('select save_hr_policy($1)',[JSON.stringify({...policy,bonus_slabs:bands})],label);
 await q('select save_hr_policy($1)',[JSON.stringify(policy)]);
 await user(employee);let report=(await one('select hr_month_preview($1,$2) r',[employee,month])).r;eq(Number(report.bonus),3000,'Percentage bonus derives from basic salary');eq(Number(report.gross_salary_summary),33000,'Gross summary includes calculated percentage bonus');eq(report.bonus_basis.band.mode,'Salary percent','Bonus calculation saved explicitly');
 await deny('select save_hr_policy($1)',[JSON.stringify({...policy,effective_on:month+'x'})],'Employee cannot configure bonus bands');await user(ids.admin);
 const start=(await one('select ($1::date+14)::text d',[month])).d;await q('select save_hr_employment($1,$2,null,null,$3)',[employee,start,'Actual mid-month employment']);await q('select save_hr_payout_policy($1)',[JSON.stringify({role_id:role,effective_on:month,proration:'Calendar days',absence_fraction:0,late_free:0,late_mode:'None',late_rate:0,reason:'Prorated salary without deductions'})]);
 report=(await one('select hr_month_preview($1,$2) r',[employee,month])).r;eq(Number(report.bonus),Math.round(Number(report.salary)*10)/100,'Percentage uses prorated salary for a mid-month hire');eq(Number(report.bonus_basis.salary_base),Number(report.salary),'Snapshot exposes exact bonus salary base');
 const summary=(await one('select save_hr_month($1,$2,null,0,$3) id',[employee,month,'Bonus summary review fixture'])).id;const saved=await one('select * from hr_monthly where id=$1',[summary]);eq(Number(saved.snapshot.net_salary_summary),Number(report.salary)+Number(report.bonus),'Saved net includes percentage once');
 await q('select save_hr_policy($1)',[JSON.stringify({...policy,effective_on:start,bonus_slabs:[{score:0,amount:250},{score:90,amount:20,mode:'Salary percent'}]})]);
 // Month-start policy remains the effective scorecard basis, even when a new policy begins mid-month.
 // Mid-month hire anchors to its first employed day, so this fixture deliberately changes that basis.
 await user(lead);await deny("select hr_month_action($1,1,'Lead review','Old bonus basis')",[summary],'Changed bonus policy invalidates draft review');
 await user(ids.admin);report=(await one('select hr_month_preview($1,$2) r',[employee,month])).r;eq(Number(report.bonus),250,'Fixed bands remain compatible without mode');eq(report.bonus_basis.band.mode,undefined,'Legacy band remains fixed PKR');
 await q('select save_hr_month($1,$2,1,0,$3)',[employee,month,'Rebuild changed bonus basis']);await user(lead);await q("select hr_month_action($1,2,'Lead review','Bonus basis checked')",[summary]);await user(manager);await q("select hr_month_action($1,3,'Manager review','Percentage reviewed')",[summary]);await user(accounts);await q("select hr_month_action($1,4,'Lock','Accounts bonus review')",[summary]);
 await user(employee);eq(Number((await one('select hr_month_preview($1,$2) r',[employee,month])).r.bonus),250,'Locked bonus reads saved snapshot');await user(ids.clientA);await deny('select hr_month_preview($1,$2)',[employee,month],'Client cannot inspect bonus calculation');
 await user(ids.admin);
}
