export async function hrCases({pg,fs,q,one,user,eq,deny,ids,actors,accounts}){
 await pg.exec('reset role');await pg.exec(await fs.readFile(new URL('../../supabase/025_hr_performance.sql',import.meta.url),'utf8'));await user(ids.admin);
 const lead=crypto.randomUUID();await pg.exec('reset role');await q('insert into auth.users values($1)',[lead]);await q("insert into profiles(id,name,role) values($1,'Designated lead','team')",[lead]);await user(ids.admin);const dept=(await one("select save_crm_configuration('team',null,null,'HR test team') id")).id;await q("select set_crm_membership($1,'team_lead',$2,true)",[lead,dept]);
 const month=(await one("select (date_trunc('month',now() at time zone 'Asia/Karachi')-interval '2 months')::date::text d")).d;
 const day=(await one("select min(x)::date::text d from generate_series($1::date,$1::date+6,interval '1 day') x where extract(dow from x) not in (0,6)",[month])).d;
 const policy={role_id:'default',effective_on:month,shift_start:'09:00',shift_end:'17:00',grace_minutes:15,half_day_minutes:240,off_days:[0],holidays:[],ot_mode:'Fixed rate',ot_rate:150,off_multiplier:2,holiday_multiplier:3,weights:{attendance:100,punctuality:0,task_completion:0,billable_utilisation:0,report_discipline:0},bonus_slabs:[{score:0,amount:100}],reason:'Agreed shift and recorded attendance KPIs'};
 await deny('select save_hr_policy($1)',[JSON.stringify({...policy,weights:{}})],'Empty KPI weights denied');await deny('select save_hr_policy($1)',[JSON.stringify({...policy,weights:{csat:100}})],'Unsupported KPI cannot silently score missing evidence');await q('select save_hr_policy($1)',[JSON.stringify(policy)]);
 const terms={user_id:ids.team,effective_on:month,role_id:'technician',salary:30000,monthly_hours:200,lead_id:lead,manager_id:actors.manager,reason:'Monthly salary and separate supervisors'};await q('select save_hr_terms($1)',[JSON.stringify(terms)]);await deny('select save_hr_terms($1)',[JSON.stringify({...terms,effective_on:day,lead_id:actors.manager})],'Employee lead and manager must differ');
 const clock=(await one('select correct_attendance(null,null,$1,$2,$3,false,$4) id',[ids.team,day+'T09:00:00+05:00',day+'T19:00:00+05:00','Recorded old attendance fixture'])).id;eq(Number((await one('select rate from work_hourly_rates where user_id=$1 and effective_on=$2',[ids.team,month])).rate),150,'HR salary terms derive matching effective project hourly cost');
 await user(ids.team);const activity=(await one('select save_work_activity(null,null,$1) id',[JSON.stringify({link_kind:'Internal',location:'Office',activity_type:'Office work',description:'Monthly work fixture',actual_start:day+'T10:00:00+05:00',actual_end:day+'T18:00:00+05:00',outcome:'Done'})])).id;await q("select work_activity_action($1,1,'Submit','')",[activity]);await user(ids.admin);await q("select work_activity_action($1,2,'Approve','Recorded time verified')",[activity]);
 await user(ids.team);let daily=(await one('select hr_daily_preview($1,$2) r',[ids.team,day])).r;eq(Number(daily.minutes),600,'Attendance and activity interval union avoids double counting');eq(Number(daily.overtime_hours),2,'Overtime only counts work beyond shift end');eq(Number(daily.overtime_amount),300,'Fixed overtime amount is server-derived');const ot=(await one('select submit_hr_overtime($1) id',[day])).id;await deny('select submit_hr_overtime($1)',[day],'Same day cannot have two active overtime claims');await deny("select review_hr_overtime($1,1,'Approve','Self review')",[ot],'Own overtime approval denied');
 await user(accounts);await deny("select review_hr_overtime($1,1,'Approve','Finance approval')",[ot],'Accounts cannot impersonate designated overtime manager');await user(lead);await q("select review_hr_overtime($1,1,'Approve','Recorded overtime reviewed')",[ot]);
 await user(ids.team);let preview=(await one('select hr_month_preview($1,$2) r',[ids.team,month])).r;eq(Number(preview.overtime_pay),300,'Monthly summary uses approved overtime only');eq(Number(preview.salary),30000,'Employee sees own salary basis');eq(Number(preview.bonus),100,'Configured bonus slab applies to available score');eq(preview.metrics.task_completion,null,'No due tasks leaves task metric unknown');await deny('select hr_month_preview($1,$2)',[lead,month],'Worker cannot inspect another employee salary');await deny('select save_hr_terms($1)',[JSON.stringify({...terms,effective_on:day})],'Worker cannot set salary or supervisors');
 await user(ids.admin);const payout=(await one('select save_hr_month($1,$2,null,50,$3) id',[ids.team,month,'Documented test deduction'])).id;await deny("select hr_month_action($1,1,'Lock','Bypass stages')",[payout],'Monthly summary cannot skip lead and manager reviews');
 await user(ids.team);eq((await q('select * from hr_monthly where id=$1',[payout])).length,0,'Employee cannot see unpublished payout draft');await user(lead);await q("select hr_month_action($1,1,'Lead review','Lead checked hours')",[payout]);await deny("select hr_month_action($1,2,'Manager review','Same actor')",[payout],'Same actor cannot perform both review stages');
 await user(actors.manager);await q("select hr_month_action($1,2,'Manager review','Manager checked score and salary')",[payout]);await user(ids.team);await q("select hr_month_action($1,3,'Acknowledge','Seen')",[payout]);eq((await one('select acknowledged_at from hr_monthly where id=$1',[payout])).acknowledged_at!==null,true,'Employee acknowledges own reviewed scorecard');
 await user(accounts);await q("select hr_month_action($1,4,'Lock','Accounts checked summary')",[payout]);const locked=await one('select * from hr_monthly where id=$1',[payout]);eq(locked.status,'Locked','Accounts completes separate three-stage review');eq(Number(locked.snapshot.net_salary_summary),30350,'Net salary includes approved OT and bonus less explicit deductions');await deny("select hr_month_action($1,5,'Return','Reopen locked')",[payout],'Locked payout cannot reopen');await user(ids.admin);await deny('select correct_attendance($1,1,$2,$3,$4,false,$5)',[clock,ids.team,day+'T09:00:00+05:00',day+'T20:00:00+05:00','Change locked times'],'Locked month rejects attendance correction');
 await user(ids.team);await deny('select save_work_activity(null,null,$1)',[JSON.stringify({link_kind:'Internal',location:'Office',activity_type:'Training',description:'New past work',actual_start:day+'T20:00:00+05:00',actual_end:day+'T21:00:00+05:00',outcome:'Done'})],'Locked month rejects backdated activity insertion');await deny('update hr_monthly set deductions=0',[],'Direct payout amount edits denied');eq((await q('select * from hr_terms where user_id=$1',[lead])).length,0,'Own terms do not grant colleague salary access');

 await user(ids.admin);const next=(await one("select ($1::date+interval '1 month')::date::text d",[month])).d;
 const nextDay=(await one("select min(x)::date::text d from generate_series($1::date,$1::date+6,interval '1 day') x where extract(dow from x) not in (0,6)",[next])).d;
 const nextDayEnd=(await one('select ($1::date+1)::text d',[nextDay])).d;
 const specific={...policy,role_id:'technician',effective_on:next,ot_mode:'Hourly multiplier',ot_rate:1.5,weights:{task_completion:100},bonus_slabs:[{score:0,amount:200},{score:90,amount:100}]};await q('select save_hr_policy($1)',[JSON.stringify(specific)]);
 const lateClock=(await one('select correct_attendance(null,null,$1,$2,$3,false,$4) id',[ids.team,nextDay+'T22:00:00+05:00',nextDayEnd+'T02:00:00+05:00','Overnight completed shift'])).id;
 await user(ids.team);daily=(await one('select hr_daily_preview($1,$2) r',[ids.team,nextDay])).r;eq(Number(daily.overtime_hours),4,'Late-start midnight overtime counts worked interval, not idle gap');eq(Number(daily.overtime_rate),225,'Salary-hourly multiplier uses configured salary and hours');eq(daily.working_date,nextDay,'Overnight work retains original day');
 const stale=(await one('select submit_hr_overtime($1) id',[nextDay])).id;await user(ids.admin);await q('select correct_attendance($1,1,$2,$3,$4,false,$5)',[lateClock,ids.team,nextDay+'T22:00:00+05:00',nextDayEnd+'T03:00:00+05:00','Overtime source correction']);await user(lead);await deny("select review_hr_overtime($1,1,'Approve','Stale hours')",[stale],'Overtime approval rejects changed source');await q("select review_hr_overtime($1,1,'Reject','Recalculate actual times')",[stale]);
 await user(ids.team);const replacement=(await one('select submit_hr_overtime($1) id',[nextDay])).id;await user(actors.manager);await q("select review_hr_overtime($1,1,'Approve','Updated times reviewed')",[replacement]);await user(ids.admin);preview=(await one('select hr_month_preview($1,$2) r',[ids.team,next])).r;eq(preview.score,null,'Unavailable weighted task metric leaves score unknown');eq(preview.bonus,null,'Unknown score does not invent a bonus');
 const unknown=(await one('select save_hr_month($1,$2,null,0,$3) id',[ids.team,next,'Missing task evidence'])).id;await user(lead);await q("select hr_month_action($1,1,'Lead review','Reviewed missing task evidence')",[unknown]);await user(actors.manager);await q("select hr_month_action($1,2,'Manager review','Manager notes missing score')",[unknown]);await user(accounts);await deny("select hr_month_action($1,3,'Lock','Lock without evidence')",[unknown],'Accounts cannot lock payout with unknown weighted score');await q("select hr_month_action($1,3,'Return','Need complete KPI evidence')",[unknown]);
 await user(ids.admin);const holiday=(await one('select ($1::date+10)::text d',[next])).d;await q('select save_hr_policy($1)',[JSON.stringify({...specific,effective_on:holiday,holidays:[holiday]})]);await q('select correct_attendance(null,null,$1,$2,$3,false,$4)',[ids.team,holiday+'T10:00:00+05:00',holiday+'T12:00:00+05:00','Holiday work approved source']);await user(ids.team);daily=(await one('select hr_daily_preview($1,$2) r',[ids.team,holiday])).r;eq(daily.kind,'Holiday','Explicit holiday overrides weekly classification');eq(Number(daily.overtime_hours),2,'Holiday overtime counts whole recorded interval');eq(Number(daily.overtime_rate),675,'Holiday multiplier applies separately');

 await user(ids.admin);await q("insert into tasks(project_id,title,assignee,deadline,status) values($1,'KPI due task',$2,$3,'Done')",[ids.pa,ids.team,nextDay]);preview=(await one('select hr_month_preview($1,$2) r',[ids.team,next])).r;eq(Number(preview.score),100,'Recorded due-task cohort supplies measurable completion');eq(Number(preview.bonus),100,'Bonus selects highest applicable threshold, not largest lower-band amount');eq(Number(preview.pending_overtime_days),1,'Unclaimed recorded holiday overtime remains unresolved');
 await user(lead);await deny("select hr_month_action($1,4,'Lead review','Changed task basis')",[unknown],'Monthly review rejects changed KPI source');await user(ids.admin);await q('select save_hr_month($1,$2,4,0,$3)',[ids.team,next,'Rebuild after task evidence']);await user(lead);await q("select hr_month_action($1,5,'Lead review','Updated KPI evidence')",[unknown]);await user(actors.manager);await q("select hr_month_action($1,6,'Manager review','Updated summary reviewed')",[unknown]);await user(accounts);await deny("select hr_month_action($1,7,'Lock','Unreviewed overtime')",[unknown],'Accounts cannot lock while recorded overtime is unreviewed');await q("select hr_month_action($1,7,'Return','Resolve holiday overtime')",[unknown]);
 await user(ids.team);const holidayClaim=(await one('select submit_hr_overtime($1) id',[holiday])).id;await user(actors.manager);await q("select review_hr_overtime($1,1,'Reject','Holiday premium not authorized')",[holidayClaim]);await user(ids.admin);preview=(await one('select hr_month_preview($1,$2) r',[ids.team,next])).r;eq(Number(preview.pending_overtime_days),0,'Documented rejection resolves overtime without counting pay');eq(Number(preview.overtime_pay),1125,'Rejected holiday premium excluded from payout');
 await user(ids.admin);await q('select save_hr_terms($1)',[JSON.stringify({...terms,effective_on:(await one("select (now() at time zone 'Asia/Karachi')::date::text d")).d,manager_id:ids.admin,salary:50000,reason:'Supervisor transfer and new salary'})]);await user(actors.manager);await deny('select hr_month_preview($1,$2)',[ids.team,month],'Current supervisor reassignment immediately revokes old manager salary access');await user(ids.team);eq(Number((await one('select hr_month_preview($1,$2) r',[ids.team,month])).r.net_salary_summary),30350,'Locked month reads immutable snapshot after later salary changes');
 await user(ids.clientA);eq((await q('select * from hr_monthly')).length,0,'Clients cannot see payroll summaries');await deny('select hr_daily_preview($1,$2)',[ids.team,day],'Client cannot query staff overtime');await deny('select hr_people()',[],'Client cannot list HR staff');
 await pg.exec("reset role;select set_config('request.jwt.claim.sub','',false);set role anon");await deny('select * from hr_terms',[],'Anonymous salary access denied');await deny('select hr_month_preview($1,$2)',[ids.team,month],'Anonymous HR report denied');await user(ids.admin);
}
