export async function leaveCases({pg,fs,q,one,user,eq,deny,ids,actors,accounts}){
 await pg.exec('reset role');await pg.exec(await fs.readFile(new URL('../../supabase/029_hr_leave.sql',import.meta.url),'utf8'));
 // Isolate fixtures from previously reviewed and locked HR months.
 const employee=crypto.randomUUID();await q('insert into auth.users values($1)',[employee]);await q("insert into profiles(id,name,role) values($1,'Leave employee','team')",[employee]);
 const month=(await one("select (date_trunc('month',now() at time zone 'Asia/Karachi')-interval '1 month')::date::text d")).d;
 const year=Number(month.slice(0,4));await user(ids.admin);
 const lead=(await one('select lead_id from hr_terms where user_id=$1 order by effective_on desc limit 1',[ids.team])).lead_id;
 await q('select save_hr_terms($1)',[JSON.stringify({user_id:employee,effective_on:month,role_id:'technician',salary:30000,monthly_hours:200,lead_id:lead,manager_id:ids.admin,reason:'Leave fixture terms and distinct reviewers'})]);
 // Manager must carry its own scope; administrator is the designated manager here.
 const day=(await one("select min(x)::date::text d from generate_series($1::date,$1::date+6,interval '1 day') x where extract(dow from x) not in (0,6)",[month])).d;
 const next=(await one('select ($1::date+1)::text d',[day])).d;
 const weekend=(await one("select min(x)::date::text d from generate_series($1::date,$1::date+6,interval '1 day') x where extract(dow from x)=0",[month])).d;
 await q('select save_hr_leave_allowance($1,$2,$3,$4,null,$5)',[employee,year,'Annual',3,'Annual leave entitlement']);
 await deny('select save_hr_leave_allowance($1,$2,$3,$4,1,$5)',[employee,year,'Annual','NaN','Invalid entitlement'],'Nonfinite leave allowance rejected');
 await user(employee);let b=(await one('select hr_leave_balances($1,$2) r',[employee,year])).r;eq(Number(b[0].available),3,'Employee sees explicit leave allowance');
 await deny('select save_hr_leave_allowance($1,$2,$3,$4,1,$5)',[employee,year,'Annual',99,'Own entitlement edit'],'Employee cannot change allowance');
 await deny('select request_hr_leave($1,$2,$3,$4,false,$5)',[crypto.randomUUID(),'Annual',weekend,weekend,'Weekend leave'],'Weekly off-day consumes no leave and cannot form empty request');
 const request=crypto.randomUUID();await q('select request_hr_leave($1,$2,$3,$4,false,$5)',[request,'Annual',day,next,'Personal leave request']);
 eq((await one('select request_hr_leave($1,$2,$3,$4,false,$5) id',[request,'Annual',day,next,'Personal leave request'])).id,request,'Request retry does not duplicate leave consumption');
 b=(await one('select hr_leave_balances($1,$2) r',[employee,year])).r;eq(Number(b[0].pending),2,'Submitted leave reserves annual balance');eq(Number(b[0].available),1,'Available leave excludes pending requests');
 await deny('select request_hr_leave($1,$2,$3,$4,false,$5)',[crypto.randomUUID(),'Annual',day,next,'Overlapping leave'],'Overlapping active leave rejected');
 await deny("select hr_leave_action($1,1,'Approve','Own approval')",[request],'Self leave approval denied');
 await user(accounts);eq((await q('select * from hr_leave_requests where id=$1',[request])).length,0,'Accounts cannot inspect private leave request reason');await deny('select hr_leave_balances($1,$2)',[employee,year],'Accounts cannot inspect another employee leave balances');
 await user(actors.manager);await deny("select hr_leave_action($1,1,'Approve','Wrong manager')",[request],'Team lead cannot approve without designated manager scope');
 await user(ids.admin);await deny('select save_hr_leave_allowance($1,$2,$3,$4,1,$5)',[employee,year,'Annual',1,'Below pending requests'],'Allowance reduction cannot remove reserved leave');await q("select hr_leave_action($1,1,'Approve','Leave reviewed by designated manager')",[request]);
 await deny("select hr_leave_action($1,1,'Reject','Stale review')",[request],'Stale leave version rejected');
 await user(employee);let daily=(await one('select hr_daily_preview($1,$2) r',[employee,day])).r;eq(daily.attendance_status,'Approved leave','Approved leave is excused in recorded attendance');eq(daily.leave.paid,true,'Annual leave carries paid classification');eq('reason' in daily.leave,false,'Attendance and payroll basis excludes private leave reason');
 let report=(await one('select hr_month_preview($1,$2) r',[employee,month])).r;eq(Number(report.approved_leave_units),2,'Monthly scorecard includes approved leave units');eq(Number(report.unpaid_leave_units),0,'Paid leave is not classified as unpaid');
 await deny('select save_work_activity(null,null,$1)',[JSON.stringify({link_kind:'Internal',location:'Office',activity_type:'Office work',description:'Conflicting work',actual_start:day+'T09:00:00+05:00',actual_end:day+'T17:00:00+05:00',outcome:'Done'})],'Approved full-day leave blocks work recording');
 await q("select hr_leave_action($1,2,'Request cancellation','Plans changed')",[request]);b=(await one('select hr_leave_balances($1,$2) r',[employee,year])).r;eq(Number(b[0].used),2,'Cancellation request holds approved balance until manager decision');
 await user(ids.admin);await q("select hr_leave_action($1,3,'Cancel approved','Cancellation reviewed')",[request]);await user(employee);b=(await one('select hr_leave_balances($1,$2) r',[employee,year])).r;eq(Number(b[0].available),3,'Approved cancellation restores leave balance without deleting history');
 const half=crypto.randomUUID();await q('select request_hr_leave($1,$2,$3,$4,true,$5)',[half,'Annual',day,day,'Half day personal leave']);await user(ids.admin);await q("select hr_leave_action($1,1,'Approve','Half day reviewed')",[half]);
 await deny('select correct_attendance(null,null,$1,$2,$3,false,$4)',[employee,day+'T09:00:00+05:00',day+'T13:00:00+05:00','Work in leave slot'],'Attendance cannot overlap approved half-day leave');
 await q('select correct_attendance(null,null,$1,$2,$3,false,$4)',[employee,day+'T13:00:00+05:00',day+'T17:00:00+05:00','Worked remaining half day']);await user(employee);daily=(await one('select hr_daily_preview($1,$2) r',[employee,day])).r;eq(Number(daily.leave.units),0.5,'Half-day leave consumes exactly half a day');eq(daily.attendance_status,'Present','Recorded remaining half-day can satisfy attendance');report=(await one('select hr_month_preview($1,$2) r',[employee,month])).r;eq(Number(report.metrics.attendance)<=100,true,'Half-day attendance cannot exceed full KPI credit');
 await user(ids.admin);await q('select save_hr_leave_allowance($1,$2,$3,$4,null,$5)',[employee,year,'Unpaid',2,'Unpaid leave limit']);
 const third=(await one("select min(x)::date::text d from generate_series($1::date+2,$1::date+8,interval '1 day') x where extract(dow from x) not in (0,6)",[day])).d;
 await user(employee);const unpaid=crypto.randomUUID();await q('select request_hr_leave($1,$2,$3,$4,false,$5)',[unpaid,'Unpaid',next,next,'Unpaid personal leave']);await user(ids.admin);await q("select hr_leave_action($1,1,'Approve','Unpaid request reviewed')",[unpaid]);await user(employee);report=(await one('select hr_month_preview($1,$2) r',[employee,month])).r;eq(Number(report.unpaid_leave_units),1,'Monthly summary identifies approved unpaid leave units');eq(JSON.stringify(report).includes('Unpaid personal leave'),false,'Monthly payroll source excludes leave reasons');
 const pending=crypto.randomUUID();await q('select request_hr_leave($1,$2,$3,$4,false,$5)',[pending,'Annual',third,third,'Additional pending leave']);report=(await one('select hr_month_preview($1,$2) r',[employee,month])).r;eq(Number(report.pending_leave_requests),1,'Pending leave decisions are visible to salary review');
 await pg.exec('reset role');await q("insert into tasks(project_id,title,assignee,deadline,status) values($1,'Leave fixture KPI',$2,$3,'Done')",[ids.pa,employee,next]);
 const summary=(await one("insert into hr_monthly(user_id,month,snapshot,source_hash,deductions,status,created_by,lead_by,manager_by) select $1,$2,portal_private.hr_month($1,$2)||jsonb_build_object('net_salary_summary',(portal_private.hr_month($1,$2)->>'gross_salary_summary')::numeric),md5(portal_private.hr_month($1,$2)::text),0,'Manager reviewed',$3,$4,$3 returning id",[employee,month,ids.admin,lead])).id;
 await user(accounts);await deny("select hr_month_action($1,1,'Lock','Accounts reviewed pending leave')",[summary],'Monthly lock cannot bypass pending leave decisions');
 await user(ids.admin);await q("select hr_leave_action($1,1,'Reject','Pending leave not granted')",[pending]);await pg.exec('reset role');await q("update hr_monthly set snapshot=portal_private.hr_month($1,$2)||jsonb_build_object('net_salary_summary',(portal_private.hr_month($1,$2)->>'gross_salary_summary')::numeric),source_hash=md5(portal_private.hr_month($1,$2)::text) where id=$3",[employee,month,summary]);await user(accounts);await q("select hr_month_action($1,1,'Lock','Accounts reviewed resolved leave')",[summary]);eq((await one('select status from hr_monthly where id=$1',[summary])).status,'Locked','Resolved leave permits complete salary summary lock');
 await user(employee);await deny("select hr_leave_action($1,2,'Request cancellation','Change locked leave')",[half],'Locked month rejects approved leave cancellation');await deny('select request_hr_leave($1,$2,$3,$4,false,$5)',[crypto.randomUUID(),'Annual',third,third,'Leave after salary lock'],'Locked month rejects backdated leave request');
 await user(ids.clientA);eq((await q('select * from hr_leave_requests')).length,0,'Client cannot read staff leave');await deny('select hr_leave_people()',[],'Client cannot list leave employees');
 await pg.exec('reset role');await q('update profiles set active=false where id=$1',[employee]);await user(employee);await deny('select hr_leave_balances($1,$2)',[employee,year],'Disabled employee loses leave access');await user(ids.admin);
}
