import {financeCases} from './finance-cases.mjs';
export async function payablesCases({pg,fs,q,one,user,eq,deny,ids,actors,po,grn,location,department}){
 await pg.exec('reset role');await pg.exec(await fs.readFile(new URL('../../supabase/022_vendor_payables.sql',import.meta.url),'utf8'));
 const accounts=crypto.randomUUID();await q('insert into auth.users values($1)',[accounts]);await q("insert into profiles(id,name,role) values($1,'Accounts','team')",[accounts]);await user(ids.admin);await q('select set_crm_membership($1,$2,$3,true)',[accounts,'accounts',department]);
 const receipts=await q('select id,accepted from sc_receipts where order_id=$1 order by id',[po]);const allocations=receipts.map(r=>({receipt_id:r.id,quantity:Number(r.accepted)}));
 const today=(await one("select (now() at time zone 'Asia/Karachi')::date::text business_date" )).business_date;
 const details={vendor_invoice:'SUP-INV-1',invoice_date:today,due_date:today,quantity:3,rate:13,evidence:'Original vendor invoice reference DOC-001'};
 await user(actors.purchase);await deny('select save_vendor_bill(null,null,$1,$2,$3)',[po,JSON.stringify(details),JSON.stringify(allocations)],'Purchase cannot create Accounts bill');
 await user(ids.team);eq((await q('select * from sc_bills')).length,0,'Technician cannot read vendor bills');await deny('select vendor_payables_report()',[],'Technician cannot read payable balances');
 await user(accounts);await deny('select save_vendor_bill(null,null,$1,$2,$3)',[po,JSON.stringify(details),JSON.stringify([{receipt_id:grn,quantity:1}])],'Bill allocation must equal invoice quantity');eq((await q('select * from sc_bills')).length,0,'Invalid bill allocation rolls back header');
 const otherReceipt=(await one('select id from sc_receipts where order_id<>$1 and accepted>0 limit 1',[po])).id;
 await deny('select save_vendor_bill(null,null,$1,$2,$3)',[po,JSON.stringify({...details,quantity:1}),JSON.stringify([{receipt_id:otherReceipt,quantity:1}])],'Invoice cannot use another purchase order GRN');
 const excess=(await one('select save_vendor_bill(null,null,$1,$2,$3) id',[po,JSON.stringify({...details,vendor_invoice:'EXCESS-1',quantity:2,rate:12}),JSON.stringify([{receipt_id:grn,quantity:2}])])).id;
 await q("select vendor_bill_action($1,1,'Match','')",[excess]);eq((await one('select status,match_note from sc_bills where id=$1',[excess])).match_note.includes('accepted GRN'),true,'Rejected or excess GRN units are held instead of payable');await q("select vendor_bill_action($1,2,'Cancel','Excess GRN billed')",[excess]);
 const bill=(await one('select save_vendor_bill(null,null,$1,$2,$3) id',[po,JSON.stringify(details),JSON.stringify(allocations)])).id;
 await deny('select save_vendor_bill(null,null,$1,$2,$3)',[po,JSON.stringify({...details,vendor_invoice:' sup-inv-1 '}),JSON.stringify(allocations)],'Vendor invoice duplicates normalized case and spaces');
 await deny("select record_vendor_payment($1,1,10,$2,'Cash','cash-1','Cash voucher')",[bill,today],'Draft invoice cannot be paid');
 await q("select vendor_bill_action($1,1,'Match','')",[bill]);eq((await one('select status from sc_bills where id=$1',[bill])).status,'Held','Rate mismatch places vendor bill on hold');eq((await one('select * from vendor_payables_report() where id=$1',[bill])).aging,'Not payable','Held bills excluded from payable aging');
 await user(ids.admin);await deny("select vendor_bill_action($1,2,'Approve','Reviewed invoice')",[bill],'Administrator cannot bypass held match');
 await user(actors.purchase);eq((await q('select * from sc_bills where id=$1',[bill])).length,1,'Purchase can inspect held bill for resolution');eq((await q('select * from sc_vendor_payments')).length,0,'Purchase cannot read payment evidence');await deny("select vendor_bill_action($1,2,'Match','')",[bill],'Purchase cannot certify financial match');
 await user(accounts);await deny('select save_vendor_bill($1,1,$2,$3,$4)',[bill,po,JSON.stringify({...details,rate:12}),JSON.stringify(allocations)],'Stale bill revision rejected');
 await q('select save_vendor_bill($1,2,$2,$3,$4)',[bill,po,JSON.stringify({...details,rate:12}),JSON.stringify(allocations)]);await q("select vendor_bill_action($1,3,'Match','')",[bill]);eq((await one('select status from sc_bills where id=$1',[bill])).status,'Matched','Corrected rate and accepted GRNs produce matched bill');
 await deny("select vendor_bill_action($1,4,'Approve','Self approval')",[bill],'Bill creator cannot approve own match');
 await user(actors.store);await deny('select return_supply_material(null,$1,$2,1,$3,$4)',[grn,location,'Return billed material','{}'],'Vendor return cannot invalidate matched receipt allocation');
 await user(accounts);const duplicate=(await one('select save_vendor_bill(null,null,$1,$2,$3) id',[po,JSON.stringify({...details,vendor_invoice:'SUP-INV-2',rate:12}),JSON.stringify(allocations)])).id;await q("select vendor_bill_action($1,1,'Match','')",[duplicate]);eq((await one('select status from sc_bills where id=$1',[duplicate])).status,'Held','Same accepted GRNs cannot be invoiced twice');await q("select vendor_bill_action($1,2,'Cancel','Duplicate vendor billing')",[duplicate]);
 await user(ids.admin);await q("select vendor_bill_action($1,4,'Approve','Original invoice and GRNs reviewed')",[bill]);await deny("select record_vendor_payment($1,5,10,$2,'Cash','cash-1','Voucher 001')",[bill,today],'Approver cannot record own bill payment');
 await user(accounts);await deny('select save_vendor_bill($1,5,$2,$3,$4)',[bill,po,JSON.stringify({...details,rate:12}),JSON.stringify(allocations)],'Approved vendor bill content fixed');
 await deny("select record_vendor_payment($1,5,37,$2,'Bank transfer','BANK-1','Bank receipt DOC-B1')",[bill,today],'Payment cannot exceed outstanding balance');await deny("select record_vendor_payment($1,5,0,$2,'Cash','cash-1','Voucher 001')",[bill,today],'Zero payment rejected');await deny("select record_vendor_payment($1,5,1,$2::date+1,'Cash','cash-1','Voucher 001')",[bill,today],'Future cash-out cannot be recorded');
 const payment=(await one("select record_vendor_payment($1,5,10,$2,'Bank transfer','BANK-1','Bank receipt DOC-B1') id",[bill,today])).id;
 let report=await one('select * from vendor_payables_report() where id=$1',[bill]);eq(report.status,'Partially paid','Partial payment reflected in payable status');eq(Number(report.balance),26,'Outstanding balance derived from unreversed payments');eq(report.aging,'Current','Due today remains current aging');
 await deny("select record_vendor_payment($1,5,10,$2,'Bank transfer','BANK-2','Bank receipt DOC-B2')",[bill,today],'Stale payment retry rejected');await deny("select record_vendor_payment($1,6,10,$2,'Bank transfer',' bank-1 ','Duplicate evidence')",[bill,today],'Same payment reference cannot be recorded twice');
 await user(ids.admin);await deny("select vendor_bill_action($1,6,'Cancel','Cancel paid bill')",[bill],'Partially paid bill cannot be cancelled');await q("select reverse_vendor_payment($1,6,'Bank payment entered on wrong bill')",[payment]);report=await one('select * from vendor_payables_report() where id=$1',[bill]);eq(Number(report.balance),36,'Documented reversal restores outstanding amount');eq(report.status,'Unpaid','Reversal restores unpaid status');await deny("select reverse_vendor_payment($1,7,'Repeat reversal')",[payment],'Payment cannot be reversed twice');
 await user(accounts);const finalPayment=(await one("select record_vendor_payment($1,7,36,$2,'Cheque','CHQ-0003','Cheque clearance reference DOC-003') id",[bill,today])).id;report=await one('select * from vendor_payables_report() where id=$1',[bill]);eq(report.status,'Paid','Full payment settles payable');eq(report.aging,'Settled','Paid invoice excluded from overdue aging');eq(Number(report.balance),0,'Paid balance is zero');await deny("select record_vendor_payment($1,8,1,$2,'Cash','CASH-extra','Extra cash voucher')",[bill,today],'Settled bill cannot be overpaid');
 await deny('update sc_vendor_payments set amount=999',[],'Direct payment amount mutation denied');await deny('delete from sc_bill_history',[],'Bill audit history cannot be deleted');await deny("update sc_bills set status='Approved'",[],'Direct bill approval bypass denied');
 await user(ids.admin);await q("select reverse_vendor_payment($1,8,'Test aging with restored balance')",[finalPayment]);
 for(const [days,bucket] of [[0,'Current'],[1,'1–30'],[30,'1–30'],[31,'31–60'],[60,'31–60'],[61,'61–90'],[90,'61–90'],[91,'90+']]){
 await pg.exec('reset role');await q("update sc_bills set invoice_date=$2::date-100,due_date=$2::date-$3::integer where id=$1",[bill,today,days]);await user(accounts);const aged=await one('select * from vendor_payables_report() where id=$1',[bill]);eq(aged.aging,bucket,'Payable aging boundary '+days+' days');eq(aged.days_overdue,days,'Pakistan business-date overdue days '+days);
 }
 await pg.exec('reset role');await q('update sc_bills set invoice_date=$2,due_date=$2 where id=$1',[bill,today]);await pg.exec("select set_config('request.jwt.claim.sub','',false);set role anon");await deny('select * from sc_bills',[],'Anonymous cannot read vendor bills');await deny('select vendor_payables_report()',[],'Anonymous cannot call financial report');await deny("select vendor_bill_action($1,9,'Match','')",[bill],'Anonymous cannot invoke bill workflow');
 await user(ids.clientA);eq((await q('select * from sc_bills')).length,0,'Own company client cannot see internal vendor bills');eq((await q('select * from sc_vendor_payments')).length,0,'Client cannot see vendor bank evidence');await deny('select vendor_payables_report()',[],'Client cannot call payables report');
 await user(ids.admin);eq((await q('select * from sc_bill_history where bill_id=$1',[bill])).length>=7,true,'Invoice revisions matching approval and payment preserve audit');await financeCases({pg,fs,q,one,user,eq,deny,ids,actors,accounts,today,po});await q('update profiles set active=false where id=$1',[accounts]);await user(accounts);await deny('select vendor_payables_report()',[],'Disabled Accounts account loses finance access');await user(ids.admin);
}
