export async function scheduleCases({pg,fs,q,one,user,eq,deny,ids,accounts}){
 await pg.exec('reset role');await pg.exec(await fs.readFile(new URL('../../supabase/033_work_schedules.sql',import.meta.url),'utf8'));
 const worker='98000000-0000-0000-0000-000000000001';await q('insert into auth.users(id) values($1)',[worker]);await q("insert into profiles(id,name,role) values($1,'Schedule worker','team')",[worker]);await user(ids.admin);
 const project=(await one("insert into projects(company_id,title) values($1,'Scheduling acceptance') returning id",[ids.a])).id,task=(await one("insert into tasks(project_id,title,assignee) values($1,'Scheduled task',$2) returning id",[project,worker])).id;
 const day=(await one("select ((now() at time zone 'Asia/Karachi')::date-20)::text d")).d;
 const data={user_id:worker,link_kind:'Project',project_id:project,task_id:task,location:'QA site',activity_type:'Installation',description:'Assigned scheduled work',planned_start:day+'T23:00:00+05:00',planned_end:(await one('select ($1::date+1)::text d',[day])).d+'T01:00:00+05:00'};
 const save=async(d=data,id=null,v=null)=>(await one('select save_work_schedule($1,$2,$3,$4) id',[id,v,JSON.stringify(d),'Schedule acceptance'])).id;
 const id=await save();await deny('select save_work_schedule(null,null,$1,$2)',[JSON.stringify(data),'Duplicate interval'],'Overlapping employee plan rejected');
 await deny('select save_work_schedule($1,0,$2,$3)',[id,JSON.stringify(data),'Stale edit'],'Stale schedule edit rejected');
 await deny('select save_work_schedule($1,1,$2,$3)',[id,JSON.stringify({...data,user_id:ids.admin}),'Change worker'],'Schedule worker cannot change');
 await user(ids.clientA);eq((await q('select * from work_schedules')).length,0,'Clients cannot read staff work schedules');await deny('select save_scheduled_activity($1,1,$2)',[id,'{}'],'Client cannot record staff schedule');
 await user(accounts);eq((await q('select * from work_schedules where id=$1',[id])).length,0,'Unrelated Accounts cannot read schedule');
 await user(ids.team);eq((await q('select * from work_schedules where id=$1',[id])).length,0,'Unassigned technician cannot read another schedule');await deny('select save_scheduled_activity($1,1,$2)',[id,'{}'],'Unassigned technician cannot record schedule');
 await user(worker);eq((await q('select * from work_schedules where id=$1',[id])).length,1,'Assigned worker sees own plan');await deny('select save_work_schedule($1,1,$2,$3)',[id,JSON.stringify(data),'Worker edit'],'Worker cannot rewrite manager plan');await deny('update work_schedules set description=$1',['Direct edit'],'Direct schedule edits denied');
 const actual={...data,user_id:ids.admin,project_id:ids.pb,task_id:null,location:'Forged location',description:'Forged plan',planned_start:day+'T22:00:00+05:00',planned_end:day+'T23:00:00+05:00',actual_start:data.planned_start,actual_end:data.planned_end,outcome:'Done',quantity:1,crew:1};
 await deny('select save_scheduled_activity($1,0,$2)',[id,JSON.stringify(actual)],'Stale schedule cannot prefill activity');
 await user(ids.admin);await q('update tasks set assignee=null where id=$1',[task]);await user(worker);eq((await q('select * from work_schedules where id=$1',[id])).length,0,'Revoked assignment removes scheduled work');eq((await q('select * from work_schedule_history where schedule_id=$1',[id])).length,0,'Revoked assignment removes schedule audit');await deny('select save_scheduled_activity($1,1,$2)',[id,JSON.stringify(actual)],'Revoked worker cannot record plan');await user(ids.admin);await q('update tasks set assignee=$1 where id=$2',[worker,task]);await user(worker);
 const activity=(await one('select save_scheduled_activity($1,1,$2) id',[id,JSON.stringify(actual)])).id;
 let row=await one('select * from work_activities where id=$1',[activity]);eq(row.user_id,worker,'Scheduled actuals belong to authenticated worker');eq(row.project_id,project,'Server supplies original assigned project');eq(row.task_id,task,'Server supplies original task');eq(row.location,data.location,'Server supplies planned site');eq(row.description,data.description,'Server supplies planned work description');eq(row.schedule_snapshot.id,id,'Actual work keeps exact schedule snapshot');eq(row.planned_start.toISOString(),new Date(data.planned_start).toISOString(),'Cross-midnight planned start preserved');eq(row.planned_end.toISOString(),new Date(data.planned_end).toISOString(),'Cross-midnight planned end preserved');
 await deny('select save_scheduled_activity($1,1,$2)',[id,JSON.stringify(actual)],'Schedule cannot produce duplicate activity');
 await q('select save_work_activity($1,1,$2)',[activity,JSON.stringify({...actual,link_kind:'Project',project_id:project,task_id:task,given_by:worker})]);row=await one('select * from work_activities where id=$1',[activity]);eq(row.planned_start.toISOString(),new Date(data.planned_start).toISOString(),'Activity revision cannot replace original planned start');eq(row.given_by,ids.admin,'Activity revision retains assigning manager');
 await user(worker);await q("select work_activity_action($1,2,'Submit','')",[activity]);await user(ids.admin);await q('select set_work_hourly_rate($1,$2,100,$3)',[worker,day,'Schedule approval rate']);await q("select work_activity_action($1,3,'Approve','Scheduled actuals reviewed')",[activity]);eq((await one("select snapshot from work_activity_history where activity_id=$1 and action='Approve'",[activity])).snapshot.schedule_snapshot.id,id,'Approval retains source schedule snapshot');eq(Number((await one('select cost from work_labour_costs where activity_id=$1',[activity])).cost),200,'Scheduled work costs actual two hours once');await user(ids.admin);await deny('select save_work_schedule($1,1,$2,$3)',[id,JSON.stringify(data),'Rewrite used plan'],'Recorded schedule cannot be rewritten');await deny('select save_work_activity_recorded($1,2,$2)',[activity,JSON.stringify(actual)],'Authenticated users cannot bypass schedule wrapper');
 const cancelled=await save({...data,planned_start:day+'T10:00:00+05:00',planned_end:day+'T11:00:00+05:00',status:'Cancelled'});await user(worker);await deny('select save_scheduled_activity($1,1,$2)',[cancelled,JSON.stringify(actual)],'Cancelled schedule cannot record activity');
 await user(ids.admin);const abandoned=await save({...data,planned_start:day+'T12:00:00+05:00',planned_end:day+'T13:00:00+05:00'});await q('update profiles set active=false where id=$1',[worker]);await user(worker);eq((await q('select * from work_schedules')).length,0,'Inactive worker loses scheduled work');await user(ids.admin);await save({...data,planned_start:day+'T12:00:00+05:00',planned_end:day+'T13:00:00+05:00',status:'Cancelled'},abandoned,1);eq((await one('select status from work_schedules where id=$1',[abandoned])).status,'Cancelled','Administrator can cancel unused plan after worker deactivation');await q('update profiles set active=true where id=$1',[worker]);
 await pg.exec("reset role;select set_config('request.jwt.claim.sub','',false);set role anon");await deny('select * from work_schedules',[],'Anonymous schedule access denied');await deny('select save_work_schedule(null,null,$1,$2)',[JSON.stringify(data),'Anon plan'],'Anonymous scheduling denied');await user(ids.admin);
}
