import {payablesCases} from './payables-cases.mjs';
export async function supplyCases({pg,fs,q,one,user,eq,deny,ids}){
await pg.exec('reset role');await pg.exec(await fs.readFile(new URL('../../supabase/021_supply_chain.sql',import.meta.url),'utf8'));
const actors={store:crypto.randomUUID(),purchase:crypto.randomUUID(),logistics:crypto.randomUUID(),manager:crypto.randomUUID(),admin2:crypto.randomUUID()};
for(const [name,id] of Object.entries(actors)){await q('insert into auth.users values($1)',[id]);await q('insert into profiles(id,name,role) values($1,$2,$3)',[id,name,name==='admin2'?'admin':'team']);}
await user(ids.admin);const department=(await one('select id from crm_teams where active limit 1')).id;for(const [key,role] of [['store','store_keeper'],['purchase','purchase_officer'],['logistics','logistics'],['manager','project_manager']])await q('select set_crm_membership($1,$2,$3,true)',[actors[key],role,department]);
const location=(await one("select save_supply_master('Location',null,null,$1) id",[JSON.stringify({name:'Office rack',kind:'Office'})])).id;
const item=(await one("select save_supply_master('Item',null,null,$1) id",[JSON.stringify({name:'Cable spool',unit:'metre',tracking:'Quantity',category:'Network',reorder_level:5,safety_stock:2})])).id;
const serialItem=(await one("select save_supply_master('Item',null,null,$1) id",[JSON.stringify({name:'Camera',unit:'each',tracking:'Serial'})])).id;
const vendor=(await one("select save_supply_master('Vendor',null,null,$1) id",[JSON.stringify({name:'Assessed vendor',contact:'Office'})])).id;await q("select save_supply_master('Vendor',$1,1,$2)",[vendor,JSON.stringify({name:'Assessed vendor',contact:'Office',assessment:'Reference and warranty checked',rating:4,status:'Approved'})]);
const vendor2=(await one("select save_supply_master('Vendor',null,null,$1) id",[JSON.stringify({name:'Second vendor'})])).id;await q("select save_supply_master('Vendor',$1,1,$2)",[vendor2,JSON.stringify({name:'Second vendor',assessment:'Assessed warranty',rating:3,status:'Approved'})]);
await user(actors.store);const adj=(await one('select create_supply_adjustment($1,$2,5,10,$3) id',[item,location,'Opening physical stock count'])).id;await deny('select post_supply_adjustment($1)',[adj],'Store cannot approve its own stock variance');await user(ids.admin);await q('select post_supply_adjustment($1)',[adj]);eq(Number((await one('select * from supply_stock_report() where item_id=$1',[item])).on_hand),5,'On hand is derived from approved stock ledger');
const project=crypto.randomUUID();await q("insert into projects(id,company_id,title) values($1,$2,'Supply test project')",[project,ids.a]);await q('insert into project_assignments(project_id,technician_id) values($1,$2)',[project,actors.manager]);const task=(await one("insert into tasks(project_id,title,assignee) values($1,'Install cable',$2) returning id",[project,ids.team])).id;
await user(ids.team);const req=(await one('select create_supply_request($1,$2,$3,$4,current_date+2,$5) id',[project,task,'Cable for assigned installation','Site A',JSON.stringify([{item_id:item,quantity:8}])])).id;
await deny('select create_supply_request($1,null,$2,$3,current_date,$4)',[project,'Unscoped request','Site',JSON.stringify([{item_id:item,quantity:1}])],'Task-only technician must bind request to assigned task');await deny('select supply_stock_report()',[],'Technician cannot view global stock valuation');eq((await q('select * from sc_requests where id=$1',[req])).length,1,'Technician sees own assigned material request');
await user(actors.store);await q('select check_supply_stock($1,1,$2)',[req,location]);const line=(await one('select * from sc_request_lines where request_id=$1',[req]));const pr=(await one('select * from sc_requisitions where request_id=$1',[req]));eq(Number(line.reserved),5,'Stock check reserves available quantity first');eq(Number(pr.quantity),3,'Only shortfall becomes purchase requisition');eq(Number((await one('select * from supply_stock_report() where item_id=$1',[item])).available),0,'Reservations reduce availability');
await user(ids.team);eq((await q('select * from sc_orders')).length,0,'Technician cannot read purchase prices');eq((await q('select * from sc_requisitions')).length,0,'Technician cannot read private requisition costs');await deny('select approve_supply_request($1,2,$2)',[req,'Approve own'],'Requester cannot approve own requisition');
await user(actors.manager);await q('select approve_supply_request($1,2,$2)',[req,'Manual project needs material budget override']);await deny('select approve_supply_request($1,3,$2)',[req,'Second approval'],'Over-budget request requires separate administrator');await user(ids.admin);await q('select approve_supply_request($1,3,$2)',[req,'Administrator overrun approval']);eq((await one('select status from sc_requisitions where id=$1',[pr.id])).status,'Approved','PM and administrator approve missing-budget requisition');
await user(actors.purchase);const quote=(await one('select add_supply_quote($1,$2,12,current_date+1,$3,$4) id',[pr.id,vendor,'One year','Net 30'])).id;await deny('select create_supply_order($1,3,$2)',[quote,'Delivery reason'],'Minimum comparison vendors enforced');await q('select add_supply_quote($1,$2,14,current_date+2,$3,$4)',[pr.id,vendor2,'One year','Net 30']);await deny('select create_supply_order($1,4,$2)',[quote,'Delivery reason'],'Cannot purchase above shortfall');await deny('select create_supply_order($1,3,$2)',[quote,''],'Price jump requires documented reason');const po=(await one('select create_supply_order($1,3,$2) id',[quote,'Earlier delivery for site schedule'])).id;
await user(ids.admin);eq((await one('select vendor_snapshot from sc_orders where id=$1',[po])).vendor_snapshot.name,'Assessed vendor','Purchase order freezes assessed vendor identity');await deny("select save_supply_master('Vendor',$1,2,$2)",[vendor,JSON.stringify({name:'Renamed supplier',assessment:'Changed identity',rating:4,status:'Approved'})],'Used PO vendor cannot silently change identity');await user(actors.purchase);
await deny("select supply_order_action($1,1,'Approve','')",[po],'Purchase creator cannot approve own PO');await user(actors.manager);await q("select supply_order_action($1,1,'Approve','Actual price budget override')",[po]);await user(ids.admin);await q("select supply_order_action($1,2,'Approve','Administrator actual-rate override')",[po]);
await q('select set_crm_membership($1,$2,$3,true)',[actors.purchase,'store_keeper',department]);await user(actors.purchase);await deny('select receive_supply_order($1,3,$2,2,2,$3,$4)',[po,location,'Accepted inspection','{}'],'Even dual-role PO creator cannot post its GRN');
await user(actors.logistics);await q("select supply_order_action($1,3,'Dispatch','')",[po]);await user(actors.store);await deny('select receive_supply_order($1,4,$2,4,4,$3,$4)',[po,location,'Accepted inspection','{}'],'Over-receipt rejected');const grn=(await one('select receive_supply_order($1,4,$2,2,1,$3,$4) id',[po,location,'One accepted; one rejected','{}'])).id;eq((await one('select status,received,rejected from sc_orders where id=$1',[po])),{status:'Part received',received:'1.000',rejected:'1.000'},'Inspection records partial receipt and rejected quantity separately');await q('select receive_supply_order($1,5,$2,2,2,$3,$4)',[po,location,'Replacement accepted','{}']);eq(Number((await one('select * from supply_stock_report() where item_id=$1',[item])).on_hand),8,'Accepted receipts alone increase stock');eq(Number((await one('select * from supply_stock_report() where item_id=$1',[item])).average_rate),10.75,'Weighted average combines opening and purchased stock');
const issue=(await one('select create_supply_issue($1,$2,8,$3,null,$4) id',[line.id,location,ids.team,'{}'])).id;await deny('select create_supply_issue($1,$2,1,$3,null,$4)',[line.id,location,ids.team,'{}'],'Pending issues cannot double-book same reservation');await deny("select supply_issue_action($1,1,'Post','',false)",[issue],'Unapproved issue cannot leave store');await user(ids.admin);await q("select supply_issue_action($1,1,'Approve','',false)",[issue]);await user(actors.store);await q("select supply_issue_action($1,2,'Post','',false)",[issue]);eq(Number((await one('select * from supply_stock_report() where item_id=$1',[item])).on_hand),0,'Posted material issue reduces stock without negative balance');await user(actors.logistics);await q("select supply_issue_action($1,3,'Dispatch','',false)",[issue]);await deny("select supply_issue_action($1,4,'Confirm delivery','Dispatcher',true)",[issue],'Logistics role alone cannot sign site receiving');await user(ids.team);eq((await one('select supply_deliveries($1) d',[req])).d[0].rate,undefined,'Field delivery view excludes purchase and issue rates');await deny("select supply_issue_action($1,4,'Confirm delivery','Technician',false)",[issue],'Delivery signature requires consent');await q("select supply_issue_action($1,4,'Confirm delivery','Technician receiver',true)",[issue]);eq((await one('select status from sc_requests where id=$1',[req])).status,'Closed','All delivered request lines close MR');
await user(actors.store);await deny('select return_supply_material($1,null,$2,9,$3,$4)',[issue,location,'Unused cable returned','{}'],'Site return cannot exceed delivered quantity');await q('select return_supply_material($1,null,$2,2,$3,$4)',[issue,location,'Unused cable returned','{}']);eq(Number((await one('select * from supply_stock_report() where item_id=$1',[item])).on_hand),2,'Site return restores stock at original issue cost');eq(Number((await one('select sum(-quantity*rate) cost from sc_stock_ledger where project_id=$1',[project])).cost),64.5,'Site return credits project material cost');
await user(ids.clientA);eq((await q('select * from sc_requests')).length,0,'Client cannot see internal supply requests');eq((await q('select * from sc_stock_ledger')).length,0,'Client cannot see inventory costs');await deny('select supply_request_items()',[],'Client cannot access staff inventory master RPC');
await user(actors.purchase);const own=(await one('select create_supply_request(null,null,$1,$2,current_date,$3) id',['Office camera','Office',JSON.stringify([{item_id:serialItem,quantity:2}])])).id;await user(actors.store);await q('select check_supply_stock($1,1,$2)',[own,location]);await user(ids.admin);await q("select approve_supply_request($1,2,'Office stock approval')",[own]);const spr=(await one('select id from sc_requisitions where request_id=$1',[own])).id;await user(actors.purchase);const sq=(await one("select add_supply_quote($1,$2,20,current_date,'One year','Net 30') id",[spr,vendor])).id;await q("select add_supply_quote($1,$2,21,current_date,'One year','Net 30')",[spr,vendor2]);const spo=(await one("select create_supply_order($1,2,'Serial stock') id",[sq])).id;await user(ids.admin);await q("select supply_order_action($1,1,'Approve','')",[spo]);await user(actors.store);await deny('select receive_supply_order($1,2,$2,2,2,$3,$4)',[spo,location,'Inspected serial cameras',['CAM-S1']],'Serial quantity must match accepted units');await deny('select receive_supply_order($1,2,$2,2,2,$3,$4)',[spo,location,'Inspected serial cameras',['CAM-S1','CAM-S1']],'Duplicate serial receipt rejected atomically');await q('select receive_supply_order($1,2,$2,2,2,$3,$4)',[spo,location,'Inspected serial cameras',['CAM-S1','CAM-S2']]);eq((await q('select * from sc_serials where item_id=$1',[serialItem])).length,2,'Serialised receipts retain unit traceability');
const serialLine=(await one('select id from sc_request_lines where request_id=$1',[own])).id;const si=(await one('select create_supply_issue($1,$2,2,$3,null,$4) id',[serialLine,location,actors.store,['CAM-S1','CAM-S2']])).id;await user(ids.admin);await q("select supply_issue_action($1,1,'Approve','',false)",[si]);await user(actors.store);await q("select supply_issue_action($1,2,'Post','',false)",[si]);await user(actors.logistics);await q("select supply_issue_action($1,3,'Dispatch','',false)",[si]);await user(actors.store);await q("select supply_issue_action($1,4,'Confirm delivery','Store receiver',true)",[si]);
eq((await one("select status from sc_serials where serial='CAM-S1'")).status,'Issued','Serial issue tracks unit custody');await deny('select return_supply_material($1,null,$2,1,$3,$4)',[si,location,'Wrong serial return',['CAM-X']],'Return serial must belong to original issued unit');await q('select return_supply_material($1,null,$2,1,$3,$4)',[si,location,'Unused serial camera returned',['CAM-S1']]);eq((await one("select status from sc_serials where serial='CAM-S1'")).status,'In stock','Site return restores serial unit custody');const serialReceipt=(await one('select id from sc_receipts where order_id=$1',[spo])).id;await q('select return_supply_material(null,$1,$2,1,$3,$4)',[serialReceipt,location,'Defective serial to vendor',['CAM-S1']]);eq((await one("select status from sc_serials where serial='CAM-S1'")).status,'Returned to vendor','Vendor return records original serial traceability');
const cancel=(await one('select create_supply_request(null,null,$1,$2,current_date,$3) id',['Cancel office cable','Office',JSON.stringify([{item_id:item,quantity:1}])])).id;await q('select check_supply_stock($1,1,$2)',[cancel,location]);await q("select cancel_supply_request($1,2,'No longer required')",[cancel]);eq(Number((await one('select * from supply_stock_report() where item_id=$1',[item])).available),2,'Cancelled request releases its reservations');const vehicle=(await one("select save_supply_master('Location',null,null,$1) id",[JSON.stringify({name:'Vehicle stock',kind:'Vehicle'})])).id;
await q('select transfer_supply_stock($1,$2,$3,1,$4,$5)',[item,location,vehicle,'Move cable to van','{}']);eq(Number((await one('select sum(quantity*rate) value from sc_stock_ledger where item_id=$1',[item])).value),21.5,'Atomic transfer preserves total stock valuation');eq(Number((await one('select * from supply_stock_report() where item_id=$1 and location_id=$2',[item,vehicle])).on_hand),1,'Transfer credits destination location');
await deny('select transfer_supply_stock($1,$2,$3,2,$4,$5)',[item,location,vehicle,'Excess van transfer','{}'],'Transfer cannot consume unavailable stock');
await deny("select save_supply_master('Item',$1,1,$2)",[item,JSON.stringify({name:'Cable spool',unit:'box',tracking:'Quantity'})],'Used item unit cannot change through inventory master');
await user(ids.admin);await deny("select save_crm_catalog($1,1,$2)",[item,JSON.stringify({name:'Cable spool',unit:'box',last_rate:12,margin:20,active:true})],'Quotation catalogue cannot bypass inventory unit lock');await user(actors.store);
await user(ids.team);await q('select create_supply_request($1,$2,$3,$4,current_date,$5)',[project,task,'Another assigned cable request','Site A',JSON.stringify([{item_id:item,quantity:1}])]);await user(ids.admin);await q('update tasks set assignee=null where id=$1',[task]);await user(ids.team);eq((await q('select * from sc_requests where id=$1',[req])).length,0,'Revoked task assignment hides prior request and delivery data');await deny('select supply_deliveries($1)',[req],'Revoked technician cannot fetch sanitized delivery view');await user(ids.admin);await deny("update projects set status='Completed' where id=$1",[project],'Open material requests block project closure');await user(actors.store);
await payablesCases({pg,fs,q,one,user,eq,deny,ids,actors,po,grn,location,department});
await user(actors.store);await deny('update sc_stock_ledger set quantity=999',[],'Direct stock ledger mutations denied');await user(ids.admin);await q('update profiles set active=false where id=$1',[actors.store]);await user(actors.store);await deny('select supply_stock_report()',[],'Disabled store account loses inventory access');await user(ids.admin);eq((await q('select * from sc_history')).length>15,true,'Supply documents retain actor audit chain');
}
